<?xml version="1.0" encoding="UTF-8"?>
<CNameSets xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<CName Index="1" CID="997" Value="XXX CNameSet" StdVal="XXXNameSet" Lang="en" IsLead="1" IsStd="1" Ver="1">9997</CName>
<CName Index="1" CID="998" Value="YYY CNameSet" StdVal="YYYNameSet" Lang="es" IsLead="1" IsStd="1" Ver="1">9998</CName>
<CName Index="2" CID="999" Value="ZZZ CNameSet" StdVal="YYYNameSet" Lang="en" IsLead="1" IsStd="1" Ver="1">9999</CName>
</CNameSets>
