<?xml version="1.0" encoding="UTF-8"?>
<PNameSets xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<PName PID="9996" Value="XXX Province" StdVal="XX" CID="997" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">9997</PName>
<PName PID="9996" Value="YYY Province" StdVal="YY" CID="998" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">9998</PName>
<PName PID="9996" Value="ZZZ Province" StdVal="ZZ" CID="999" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">9999</PName>
</PNameSets>

