<?xml version="1.0" encoding="UTF-8"?>
<Entries xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<Entry Type="Country"  Action="ADD"    Version="1">InSituSCV__InSitu_CountryData_TEST</Entry> 
<Entry Type="Country"  Action="REMOVE" Version="1">InSituSCV__InSitu_CountryData_TEST</Entry>
<Entry Type="CNameSet" Action="ADD"    Version="1">InSituSCV__InSitu_CNameSetData_TEST</Entry> 
<Entry Type="CNameSet" Action="REMOVE" Version="1">InSituSCV__InSitu_CNameSetData_TEST</Entry>
<Entry Type="PNameSet" Action="ADD"    Version="1">InSituSCV__InSitu_PNameSetData_TEST</Entry> 
<Entry Type="PNameSet" Action="REMOVE" Version="1">InSituSCV__InSitu_PNameSetData_TEST</Entry>
</Entries>