<?xml version="1.0" encoding="UTF-8"?>
<CNameSets xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<CName Index="1" CID="004" Value="Afghanistan" StdVal="Afghanistan" Lang="en" IsLead="1" IsStd="1" Ver="1">1</CName>
<CName Index="1" CID="004" Value="Afganistán" StdVal="Afganistán" Lang="es" IsLead="1" IsStd="1" Ver="1">2</CName>
<CName Index="2" CID="008" Value="Albania" StdVal="Albania" Lang="en" IsLead="1" IsStd="1" Ver="1">5</CName>
<CName Index="3" CID="010" Value="Antarctica" StdVal="Antarctica" Lang="en" IsLead="1" IsStd="1" Ver="1">10</CName>
<CName Index="3" CID="010" Value="Antártida" StdVal="Antártida" Lang="es" IsLead="1" IsStd="1" Ver="1">11</CName>
<CName Index="4" CID="012" Value="Algeria" StdVal="Algeria" Lang="en" IsLead="1" IsStd="1" Ver="1">15</CName>
<CName Index="4" CID="012" Value="Argelia" StdVal="Argelia" Lang="es" IsLead="1" IsStd="1" Ver="1">16</CName>
<CName Index="5" CID="016" Value="American Samoa" StdVal="AmericanSamoa" Lang="en" IsLead="1" IsStd="1" Ver="1">19</CName>
<CName Index="5" CID="016" Value="Samoa Americana" StdVal="SamoaAmericana" Lang="es" IsLead="1" IsStd="1" Ver="1">20</CName>
<CName Index="6" CID="020" Value="Andorra" StdVal="Andorra" Lang="en" IsLead="1" IsStd="1" Ver="1">22</CName>
<CName Index="7" CID="024" Value="Angola" StdVal="Angola" Lang="en" IsLead="1" IsStd="1" Ver="1">24</CName>
<CName Index="8" CID="028" Value="Antigua and Barbuda" StdVal="AntiguaandBarbuda" Lang="en" IsLead="1" IsStd="1" Ver="1">26</CName>
<CName Index="8" CID="028" Value="Antigua Barbuda" StdVal="AntiguaBarbuda" Lang="en" IsLead="0" IsStd="1" Ver="1">27</CName>
<CName Index="8" CID="028" Value="Antigua y Barbuda" StdVal="AntiguayBarbuda" Lang="es" IsLead="1" IsStd="1" Ver="1">28</CName>
<CName Index="9" CID="031" Value="Azerbaijan" StdVal="Azerbaijan" Lang="en" IsLead="1" IsStd="1" Ver="1">32</CName>
<CName Index="9" CID="031" Value="Azerbaiyán" StdVal="Azerbaiyán" Lang="es" IsLead="1" IsStd="1" Ver="1">33</CName>
<CName Index="10" CID="032" Value="Argentina" StdVal="Argentina" Lang="en" IsLead="1" IsStd="1" Ver="1">36</CName>
<CName Index="11" CID="036" Value="Australia" StdVal="Australia" Lang="en" IsLead="1" IsStd="1" Ver="1">39</CName>
<CName Index="12" CID="040" Value="Austria" StdVal="Austria" Lang="en" IsLead="1" IsStd="1" Ver="1">42</CName>
<CName Index="13" CID="044" Value="The Bahamas" StdVal="TheBahamas" Lang="en" IsLead="0" IsStd="1" Ver="1">44</CName>
<CName Index="13" CID="044" Value="Bahamas" StdVal="Bahamas" Lang="en" IsLead="1" IsStd="1" Ver="1">45</CName>
<CName Index="14" CID="048" Value="Bahrain" StdVal="Bahrain" Lang="en" IsLead="1" IsStd="1" Ver="1">47</CName>
<CName Index="14" CID="048" Value="Bahráin" StdVal="Bahráin" Lang="es" IsLead="1" IsStd="1" Ver="1">48</CName>
<CName Index="15" CID="050" Value="Bangladesh" StdVal="Bangladesh" Lang="en" IsLead="1" IsStd="1" Ver="1">52</CName>
<CName Index="16" CID="051" Value="Armenia" StdVal="Armenia" Lang="en" IsLead="1" IsStd="1" Ver="1">54</CName>
<CName Index="17" CID="052" Value="Barbados" StdVal="Barbados" Lang="en" IsLead="1" IsStd="1" Ver="1">57</CName>
<CName Index="18" CID="056" Value="Belgium" StdVal="Belgium" Lang="en" IsLead="1" IsStd="1" Ver="1">60</CName>
<CName Index="18" CID="056" Value="Bélgica" StdVal="Bélgica" Lang="es" IsLead="1" IsStd="1" Ver="1">61</CName>
<CName Index="19" CID="060" Value="Bermuda" StdVal="Bermuda" Lang="en" IsLead="1" IsStd="1" Ver="1">63</CName>
<CName Index="19" CID="060" Value="Bermudas" StdVal="Bermudas" Lang="es" IsLead="1" IsStd="1" Ver="1">64</CName>
<CName Index="20" CID="064" Value="Bhutan" StdVal="Bhutan" Lang="en" IsLead="1" IsStd="1" Ver="1">67</CName>
<CName Index="20" CID="064" Value="Bután" StdVal="Bután" Lang="es" IsLead="1" IsStd="1" Ver="1">68</CName>
<CName Index="21" CID="068" Value="Bolivia" StdVal="Bolivia" Lang="en" IsLead="1" IsStd="1" Ver="1">71</CName>
<CName Index="22" CID="070" Value="Bosnia and Herzegovina" StdVal="BosniaandHerzegovina" Lang="en" IsLead="1" IsStd="1" Ver="1">75</CName>
<CName Index="22" CID="070" Value="Bosnia-Herzegovina" StdVal="BosniaHerzegovina" Lang="es" IsLead="1" IsStd="1" Ver="1">76</CName>
<CName Index="23" CID="072" Value="Botswana" StdVal="Botswana" Lang="en" IsLead="1" IsStd="1" Ver="1">78</CName>
<CName Index="23" CID="072" Value="Botsuana" StdVal="Botsuana" Lang="es" IsLead="1" IsStd="1" Ver="1">79</CName>
<CName Index="24" CID="074" Value="Bouvet Island" StdVal="BouvetIsland" Lang="en" IsLead="1" IsStd="1" Ver="1">80</CName>
<CName Index="25" CID="076" Value="Brazil" StdVal="Brazil" Lang="en" IsLead="1" IsStd="1" Ver="1">83</CName>
<CName Index="25" CID="076" Value="Brasil" StdVal="Brasil" Lang="es" IsLead="1" IsStd="1" Ver="1">84</CName>
<CName Index="26" CID="084" Value="Belize" StdVal="Belize" Lang="en" IsLead="1" IsStd="1" Ver="1">86</CName>
<CName Index="26" CID="084" Value="Belice" StdVal="Belice" Lang="es" IsLead="1" IsStd="1" Ver="1">87</CName>
<CName Index="27" CID="086" Value="British Indian Ocean Territory" StdVal="BritishIndianOceanTerritory" Lang="en" IsLead="1" IsStd="1" Ver="1">89</CName>
<CName Index="27" CID="086" Value="Territorios Británico del Océano Índico" StdVal="TerritoriosBritánicodelOcéanoÍndico" Lang="es" IsLead="1" IsStd="1" Ver="1">90</CName>
<CName Index="28" CID="090" Value="Solomon Islands" StdVal="SolomonIslands" Lang="en" IsLead="1" IsStd="1" Ver="1">93</CName>
<CName Index="28" CID="090" Value="Islas Salomón" StdVal="IslasSalomón" Lang="es" IsLead="1" IsStd="1" Ver="1">94</CName>
<CName Index="29" CID="092" Value="British Virgin Islands" StdVal="BritishVirginIslands" Lang="en" IsLead="0" IsStd="1" Ver="1">97</CName>
<CName Index="29" CID="092" Value="Virgin Islands (British)" StdVal="VirginIslandsBritish" Lang="en" IsLead="0" IsStd="1" Ver="1">98</CName>
<CName Index="29" CID="092" Value="Virgin Islands" StdVal="VirginIslands" Lang="en" IsLead="1" IsStd="1" Ver="1">99</CName>
<CName Index="29" CID="092" Value="Islas Vírgenes Británicas" StdVal="IslasVírgenesBritánicas" Lang="es" IsLead="1" IsStd="1" Ver="1">100</CName>
<CName Index="30" CID="096" Value="Brunei" StdVal="Brunei" Lang="en" IsLead="1" IsStd="1" Ver="1">103</CName>
<CName Index="30" CID="096" Value="Brunéi" StdVal="Brunéi" Lang="es" IsLead="1" IsStd="1" Ver="1">104</CName>
<CName Index="31" CID="100" Value="Bulgaria" StdVal="Bulgaria" Lang="en" IsLead="1" IsStd="1" Ver="1">108</CName>
<CName Index="32" CID="104" Value="Myanmar" StdVal="Myanmar" Lang="en" IsLead="1" IsStd="1" Ver="1">110</CName>
<CName Index="33" CID="108" Value="Burundi" StdVal="Burundi" Lang="en" IsLead="1" IsStd="1" Ver="1">112</CName>
<CName Index="34" CID="112" Value="Belarus" StdVal="Belarus" Lang="en" IsLead="1" IsStd="1" Ver="1">114</CName>
<CName Index="34" CID="112" Value="Bielorrusia" StdVal="Bielorrusia" Lang="es" IsLead="1" IsStd="1" Ver="1">115</CName>
<CName Index="35" CID="116" Value="Cambodia" StdVal="Cambodia" Lang="en" IsLead="1" IsStd="1" Ver="1">118</CName>
<CName Index="35" CID="116" Value="Camboya" StdVal="Camboya" Lang="es" IsLead="1" IsStd="1" Ver="1">119</CName>
<CName Index="36" CID="120" Value="Cameroon" StdVal="Cameroon" Lang="en" IsLead="1" IsStd="1" Ver="1">123</CName>
<CName Index="36" CID="120" Value="Camerún" StdVal="Camerún" Lang="es" IsLead="1" IsStd="1" Ver="1">124</CName>
<CName Index="37" CID="124" Value="Canada" StdVal="Canada" Lang="en" IsLead="1" IsStd="1" Ver="1">127</CName>
<CName Index="37" CID="124" Value="Canadá" StdVal="Canadá" Lang="es" IsLead="1" IsStd="1" Ver="1">128</CName>
<CName Index="38" CID="132" Value="Cape Verde" StdVal="CapeVerde" Lang="en" IsLead="1" IsStd="1" Ver="1">130</CName>
<CName Index="38" CID="132" Value="Cabo Verde" StdVal="CaboVerde" Lang="es" IsLead="1" IsStd="1" Ver="1">131</CName>
<CName Index="39" CID="136" Value="Cayman Islands" StdVal="CaymanIslands" Lang="en" IsLead="1" IsStd="1" Ver="1">134</CName>
<CName Index="39" CID="136" Value="Islas Caimán" StdVal="IslasCaimán" Lang="es" IsLead="1" IsStd="1" Ver="1">135</CName>
<CName Index="40" CID="140" Value="Central African Republic" StdVal="CentralAfricanRepublic" Lang="en" IsLead="1" IsStd="1" Ver="1">138</CName>
<CName Index="40" CID="140" Value="República Centroafricana" StdVal="RepúblicaCentroafricana" Lang="es" IsLead="1" IsStd="1" Ver="1">139</CName>
<CName Index="41" CID="144" Value="Sri Lanka" StdVal="SriLanka" Lang="en" IsLead="1" IsStd="1" Ver="1">141</CName>
<CName Index="42" CID="148" Value="Chad" StdVal="Chad" Lang="en" IsLead="1" IsStd="1" Ver="1">145</CName>
<CName Index="43" CID="152" Value="Chile" StdVal="Chile" Lang="en" IsLead="1" IsStd="1" Ver="1">147</CName>
<CName Index="44" CID="156" Value="People's Republic of China" StdVal="PeoplesRepublicofChina" Lang="en" IsLead="0" IsStd="1" Ver="1">149</CName>
<CName Index="44" CID="156" Value="China" StdVal="China" Lang="en" IsLead="1" IsStd="1" Ver="1">150</CName>
<CName Index="45" CID="158" Value="Taiwan" StdVal="Taiwan" Lang="en" IsLead="1" IsStd="1" Ver="1">153</CName>
<CName Index="45" CID="158" Value="Taiwán, República de China" StdVal="TaiwánRepúblicadeChina" Lang="es" IsLead="1" IsStd="1" Ver="1">154</CName>
<CName Index="46" CID="162" Value="Christmas Island" StdVal="ChristmasIsland" Lang="en" IsLead="1" IsStd="1" Ver="1">157</CName>
<CName Index="46" CID="162" Value="Isla Navidad" StdVal="IslaNavidad" Lang="es" IsLead="1" IsStd="1" Ver="1">158</CName>
<CName Index="47" CID="166" Value="Cocos (Keeling) Islands" StdVal="CocosKeelingIslands" Lang="en" IsLead="0" IsStd="1" Ver="1">161</CName>
<CName Index="47" CID="166" Value="Keeling Islands" StdVal="KeelingIslands" Lang="en" IsLead="0" IsStd="1" Ver="1">162</CName>
<CName Index="47" CID="166" Value="Cocos Islands" StdVal="CocosIslands" Lang="en" IsLead="1" IsStd="1" Ver="1">163</CName>
<CName Index="47" CID="166" Value="Islas Cocos (Keeling)" StdVal="IslasCocosKeeling" Lang="es" IsLead="1" IsStd="1" Ver="1">164</CName>
<CName Index="48" CID="170" Value="Colombia" StdVal="Colombia" Lang="en" IsLead="1" IsStd="1" Ver="1">167</CName>
<CName Index="49" CID="174" Value="Comoros" StdVal="Comoros" Lang="en" IsLead="1" IsStd="1" Ver="1">171</CName>
<CName Index="49" CID="174" Value="Comoras" StdVal="Comoras" Lang="es" IsLead="1" IsStd="1" Ver="1">172</CName>
<CName Index="50" CID="175" Value="Mayotte" StdVal="Mayotte" Lang="en" IsLead="1" IsStd="1" Ver="1">174</CName>
<CName Index="51" CID="178" Value="Congo" StdVal="Congo" Lang="en" IsLead="1" IsStd="1" Ver="1">176</CName>
<CName Index="52" CID="180" Value="Democratic Republic of Congo" StdVal="DemocraticRepublicofCongo" Lang="en" IsLead="1" IsStd="1" Ver="1">178</CName>
<CName Index="52" CID="180" Value="República Democrática del Congo" StdVal="RepúblicaDemocráticadelCongo" Lang="es" IsLead="1" IsStd="1" Ver="1">179</CName>
<CName Index="53" CID="184" Value="Cook Islands" StdVal="CookIslands" Lang="en" IsLead="1" IsStd="1" Ver="1">183</CName>
<CName Index="53" CID="184" Value="Islas Cook" StdVal="IslasCook" Lang="es" IsLead="1" IsStd="1" Ver="1">184</CName>
<CName Index="54" CID="188" Value="Costa Rica" StdVal="CostaRica" Lang="en" IsLead="1" IsStd="1" Ver="1">186</CName>
<CName Index="55" CID="191" Value="Croatia" StdVal="Croatia" Lang="en" IsLead="1" IsStd="1" Ver="1">188</CName>
<CName Index="55" CID="191" Value="Croacia" StdVal="Croacia" Lang="es" IsLead="1" IsStd="1" Ver="1">189</CName>
<CName Index="56" CID="192" Value="Cuba" StdVal="Cuba" Lang="en" IsLead="1" IsStd="1" Ver="1">193</CName>
<CName Index="57" CID="196" Value="Cyprus" StdVal="Cyprus" Lang="en" IsLead="1" IsStd="1" Ver="1">196</CName>
<CName Index="57" CID="196" Value="Chipre" StdVal="Chipre" Lang="es" IsLead="1" IsStd="1" Ver="1">197</CName>
<CName Index="58" CID="203" Value="Czech Republic" StdVal="CzechRepublic" Lang="en" IsLead="1" IsStd="1" Ver="1">201</CName>
<CName Index="58" CID="203" Value="República Checa" StdVal="RepúblicaCheca" Lang="es" IsLead="0" IsStd="1" Ver="1">202</CName>
<CName Index="58" CID="203" Value="Chequia" StdVal="Chequia" Lang="es" IsLead="1" IsStd="1" Ver="1">203</CName>
<CName Index="59" CID="204" Value="Benin" StdVal="Benin" Lang="en" IsLead="1" IsStd="1" Ver="1">205</CName>
<CName Index="59" CID="204" Value="Benín" StdVal="Benín" Lang="es" IsLead="1" IsStd="1" Ver="1">206</CName>
<CName Index="60" CID="208" Value="Denmark" StdVal="Denmark" Lang="en" IsLead="1" IsStd="1" Ver="1">210</CName>
<CName Index="60" CID="208" Value="Dinamarca" StdVal="Dinamarca" Lang="es" IsLead="1" IsStd="1" Ver="1">211</CName>
<CName Index="61" CID="212" Value="Dominica" StdVal="Dominica" Lang="en" IsLead="1" IsStd="1" Ver="1">213</CName>
<CName Index="62" CID="214" Value="Dominican Republic" StdVal="DominicanRepublic" Lang="en" IsLead="1" IsStd="1" Ver="1">216</CName>
<CName Index="62" CID="214" Value="República Dominicana" StdVal="RepúblicaDominicana" Lang="es" IsLead="1" IsStd="1" Ver="1">217</CName>
<CName Index="63" CID="218" Value="Ecuador" StdVal="Ecuador" Lang="en" IsLead="1" IsStd="1" Ver="1">219</CName>
<CName Index="64" CID="222" Value="El Salvador" StdVal="ElSalvador" Lang="en" IsLead="1" IsStd="1" Ver="1">221</CName>
<CName Index="65" CID="226" Value="Equatorial Guinea" StdVal="EquatorialGuinea" Lang="en" IsLead="1" IsStd="1" Ver="1">223</CName>
<CName Index="65" CID="226" Value="Guinea Ecuatorial" StdVal="GuineaEcuatorial" Lang="es" IsLead="1" IsStd="1" Ver="1">224</CName>
<CName Index="66" CID="231" Value="Ethiopia" StdVal="Ethiopia" Lang="en" IsLead="1" IsStd="1" Ver="1">228</CName>
<CName Index="66" CID="231" Value="Etiopía" StdVal="Etiopía" Lang="es" IsLead="1" IsStd="1" Ver="1">229</CName>
<CName Index="67" CID="232" Value="Eritrea" StdVal="Eritrea" Lang="en" IsLead="1" IsStd="1" Ver="1">232</CName>
<CName Index="68" CID="233" Value="Estonia" StdVal="Estonia" Lang="en" IsLead="1" IsStd="1" Ver="1">235</CName>
<CName Index="69" CID="234" Value="Faeroe Islands" StdVal="FaeroeIslands" Lang="en" IsLead="0" IsStd="1" Ver="1">240</CName>
<CName Index="69" CID="234" Value="Faroe Islands" StdVal="FaroeIslands" Lang="en" IsLead="1" IsStd="1" Ver="1">241</CName>
<CName Index="69" CID="234" Value="Islas Feroe" StdVal="IslasFeroe" Lang="es" IsLead="1" IsStd="1" Ver="1">242</CName>
<CName Index="70" CID="238" Value="Malvinas" StdVal="Malvinas" Lang="en" IsLead="0" IsStd="1" Ver="1">245</CName>
<CName Index="70" CID="238" Value="Falkland Islands" StdVal="FalklandIslands" Lang="en" IsLead="1" IsStd="1" Ver="1">246</CName>
<CName Index="70" CID="238" Value="Islas Falkland (Malvinas)" StdVal="IslasFalklandMalvinas" Lang="es" IsLead="1" IsStd="1" Ver="1">247</CName>
<CName Index="71" CID="239" Value="South Georgia and South Sandwich Islands" StdVal="SouthGeorgiaandSouthSandwichIslands" Lang="en" IsLead="1" IsStd="1" Ver="1">250</CName>
<CName Index="71" CID="239" Value="Islas Georgia del Sur y Sandwich del Sur" StdVal="IslasGeorgiadelSurySandwichdelSur" Lang="es" IsLead="1" IsStd="1" Ver="1">251</CName>
<CName Index="72" CID="242" Value="Fiji Islands" StdVal="FijiIslands" Lang="en" IsLead="0" IsStd="1" Ver="1">254</CName>
<CName Index="72" CID="242" Value="Fiji" StdVal="Fiji" Lang="en" IsLead="1" IsStd="1" Ver="1">255</CName>
<CName Index="72" CID="242" Value="Fiyi" StdVal="Fiyi" Lang="es" IsLead="1" IsStd="1" Ver="1">256</CName>
<CName Index="73" CID="246" Value="Finland" StdVal="Finland" Lang="en" IsLead="1" IsStd="1" Ver="1">259</CName>
<CName Index="73" CID="246" Value="Finlandia" StdVal="Finlandia" Lang="es" IsLead="1" IsStd="1" Ver="1">260</CName>
<CName Index="74" CID="248" Value="Åland Islands" StdVal="ÅlandIslands" Lang="en" IsLead="1" IsStd="1" Ver="1">263</CName>
<CName Index="75" CID="250" Value="France" StdVal="France" Lang="en" IsLead="1" IsStd="1" Ver="1">266</CName>
<CName Index="75" CID="250" Value="Francia" StdVal="Francia" Lang="es" IsLead="1" IsStd="1" Ver="1">267</CName>
<CName Index="76" CID="254" Value="French Guiana" StdVal="FrenchGuiana" Lang="en" IsLead="1" IsStd="1" Ver="1">269</CName>
<CName Index="76" CID="254" Value="Guayana Francesa" StdVal="GuayanaFrancesa" Lang="es" IsLead="1" IsStd="1" Ver="1">270</CName>
<CName Index="77" CID="258" Value="French Polynesia" StdVal="FrenchPolynesia" Lang="en" IsLead="1" IsStd="1" Ver="1">274</CName>
<CName Index="77" CID="258" Value="Polinesia Francesa" StdVal="PolinesiaFrancesa" Lang="es" IsLead="1" IsStd="1" Ver="1">275</CName>
<CName Index="78" CID="260" Value="French Southern and Antarctic Lands" StdVal="FrenchSouthernandAntarcticLands" Lang="en" IsLead="0" IsStd="1" Ver="1">278</CName>
<CName Index="78" CID="260" Value="French Southern Territories" StdVal="FrenchSouthernTerritories" Lang="en" IsLead="1" IsStd="1" Ver="1">279</CName>
<CName Index="78" CID="260" Value="Territorios Australes Franceses" StdVal="TerritoriosAustralesFranceses" Lang="es" IsLead="1" IsStd="1" Ver="1">280</CName>
<CName Index="79" CID="262" Value="Djibouti" StdVal="Djibouti" Lang="en" IsLead="1" IsStd="1" Ver="1">284</CName>
<CName Index="79" CID="262" Value="Yibuti" StdVal="Yibuti" Lang="es" IsLead="1" IsStd="1" Ver="1">285</CName>
<CName Index="80" CID="266" Value="Gabon" StdVal="Gabon" Lang="en" IsLead="1" IsStd="1" Ver="1">287</CName>
<CName Index="80" CID="266" Value="Gabón" StdVal="Gabón" Lang="es" IsLead="1" IsStd="1" Ver="1">288</CName>
<CName Index="81" CID="268" Value="Georgia" StdVal="Georgia" Lang="en" IsLead="1" IsStd="1" Ver="1">290</CName>
<CName Index="82" CID="270" Value="The Gambia" StdVal="TheGambia" Lang="en" IsLead="0" IsStd="1" Ver="1">293</CName>
<CName Index="82" CID="270" Value="Gambia" StdVal="Gambia" Lang="en" IsLead="1" IsStd="1" Ver="1">294</CName>
<CName Index="83" CID="275" Value="Palestinian Territory, Occupied" StdVal="PalestinianTerritoryOccupied" Lang="en" IsLead="1" IsStd="1" Ver="1">297</CName>
<CName Index="84" CID="276" Value="Germany" StdVal="Germany" Lang="en" IsLead="1" IsStd="1" Ver="1">299</CName>
<CName Index="84" CID="276" Value="Alemania" StdVal="Alemania" Lang="es" IsLead="1" IsStd="1" Ver="1">300</CName>
<CName Index="85" CID="288" Value="Ghana" StdVal="Ghana" Lang="en" IsLead="1" IsStd="1" Ver="1">302</CName>
<CName Index="86" CID="292" Value="Gibraltar" StdVal="Gibraltar" Lang="en" IsLead="1" IsStd="1" Ver="1">303</CName>
<CName Index="87" CID="296" Value="Kiribati" StdVal="Kiribati" Lang="en" IsLead="1" IsStd="1" Ver="1">304</CName>
<CName Index="88" CID="300" Value="Greece" StdVal="Greece" Lang="en" IsLead="1" IsStd="1" Ver="1">308</CName>
<CName Index="88" CID="300" Value="Grecia" StdVal="Grecia" Lang="es" IsLead="1" IsStd="1" Ver="1">309</CName>
<CName Index="89" CID="304" Value="Greenland" StdVal="Greenland" Lang="en" IsLead="1" IsStd="1" Ver="1">313</CName>
<CName Index="89" CID="304" Value="Groenlandia" StdVal="Groenlandia" Lang="es" IsLead="1" IsStd="1" Ver="1">314</CName>
<CName Index="90" CID="308" Value="Grenada" StdVal="Grenada" Lang="en" IsLead="1" IsStd="1" Ver="1">316</CName>
<CName Index="90" CID="308" Value="Granada" StdVal="Granada" Lang="es" IsLead="1" IsStd="1" Ver="1">317</CName>
<CName Index="91" CID="312" Value="Guadeloupe" StdVal="Guadeloupe" Lang="en" IsLead="1" IsStd="1" Ver="1">319</CName>
<CName Index="91" CID="312" Value="Guadalupe" StdVal="Guadalupe" Lang="es" IsLead="1" IsStd="1" Ver="1">320</CName>
<CName Index="92" CID="316" Value="Guam" StdVal="Guam" Lang="en" IsLead="1" IsStd="1" Ver="1">321</CName>
<CName Index="93" CID="320" Value="Guatemala" StdVal="Guatemala" Lang="en" IsLead="1" IsStd="1" Ver="1">322</CName>
<CName Index="94" CID="324" Value="Guinea" StdVal="Guinea" Lang="en" IsLead="1" IsStd="1" Ver="1">323</CName>
<CName Index="95" CID="328" Value="Guyana" StdVal="Guyana" Lang="en" IsLead="1" IsStd="1" Ver="1">325</CName>
<CName Index="96" CID="332" Value="Haiti" StdVal="Haiti" Lang="en" IsLead="1" IsStd="1" Ver="1">326</CName>
<CName Index="96" CID="332" Value="Haití" StdVal="Haití" Lang="es" IsLead="1" IsStd="1" Ver="1">327</CName>
<CName Index="97" CID="334" Value="Heard Island and McDonald Islands" StdVal="HeardIslandandMcDonaldIslands" Lang="en" IsLead="1" IsStd="1" Ver="1">329</CName>
<CName Index="98" CID="336" Value="Vatican City" StdVal="VaticanCity" Lang="en" IsLead="0" IsStd="1" Ver="1">331</CName>
<CName Index="98" CID="336" Value="Vatican" StdVal="Vatican" Lang="en" IsLead="1" IsStd="1" Ver="1">332</CName>
<CName Index="98" CID="336" Value="Santa Sede (Ciudad del Vaticano)" StdVal="SantaSedeCiudaddelVaticano" Lang="es" IsLead="0" IsStd="1" Ver="1">333</CName>
<CName Index="98" CID="336" Value="Ciudad del Vaticano" StdVal="CiudaddelVaticano" Lang="es" IsLead="1" IsStd="1" Ver="1">334</CName>
<CName Index="99" CID="340" Value="Honduras" StdVal="Honduras" Lang="en" IsLead="1" IsStd="1" Ver="1">337</CName>
<CName Index="100" CID="344" Value="Hong Kong S.A.R., China" StdVal="HongKongSARChina" Lang="en" IsLead="0" IsStd="1" Ver="1">338</CName>
<CName Index="100" CID="344" Value="Hong Kong" StdVal="HongKong" Lang="en" IsLead="1" IsStd="1" Ver="1">339</CName>
<CName Index="100" CID="344" Value="Hong-Kong, Región administrativa especial de China" StdVal="HongKongRegiónadministrativaespecialdeChina" Lang="es" IsLead="1" IsStd="1" Ver="1">340</CName>
<CName Index="101" CID="348" Value="Hungary" StdVal="Hungary" Lang="en" IsLead="1" IsStd="1" Ver="1">343</CName>
<CName Index="101" CID="348" Value="Hungría" StdVal="Hungría" Lang="es" IsLead="1" IsStd="1" Ver="1">344</CName>
<CName Index="102" CID="352" Value="Iceland" StdVal="Iceland" Lang="en" IsLead="1" IsStd="1" Ver="1">348</CName>
<CName Index="102" CID="352" Value="Islandia" StdVal="Islandia" Lang="es" IsLead="1" IsStd="1" Ver="1">349</CName>
<CName Index="103" CID="356" Value="India" StdVal="India" Lang="en" IsLead="1" IsStd="1" Ver="1">353</CName>
<CName Index="104" CID="360" Value="Indonesia" StdVal="Indonesia" Lang="en" IsLead="1" IsStd="1" Ver="1">356</CName>
<CName Index="105" CID="364" Value="Iran" StdVal="Iran" Lang="en" IsLead="1" IsStd="1" Ver="1">358</CName>
<CName Index="105" CID="364" Value="Irán" StdVal="Irán" Lang="es" IsLead="1" IsStd="1" Ver="1">359</CName>
<CName Index="106" CID="368" Value="Iraq" StdVal="Iraq" Lang="en" IsLead="1" IsStd="1" Ver="1">363</CName>
<CName Index="107" CID="372" Value="Ireland" StdVal="Ireland" Lang="en" IsLead="1" IsStd="1" Ver="1">365</CName>
<CName Index="107" CID="372" Value="IRE" StdVal="IRE" Lang="en" IsLead="0" IsStd="1" Ver="1">366</CName>
<CName Index="107" CID="372" Value="Irlanda" StdVal="Irlanda" Lang="es" IsLead="1" IsStd="1" Ver="1">367</CName>
<CName Index="108" CID="376" Value="Israel" StdVal="Israel" Lang="en" IsLead="1" IsStd="1" Ver="1">370</CName>
<CName Index="109" CID="380" Value="Italy" StdVal="Italy" Lang="en" IsLead="1" IsStd="1" Ver="1">373</CName>
<CName Index="109" CID="380" Value="Italia" StdVal="Italia" Lang="es" IsLead="1" IsStd="1" Ver="1">374</CName>
<CName Index="110" CID="384" Value="Côte d’Ivoire" StdVal="Côted’Ivoire" Lang="en" IsLead="1" IsStd="1" Ver="1">376</CName>
<CName Index="110" CID="384" Value="Costa de Marfil" StdVal="CostadeMarfil" Lang="es" IsLead="1" IsStd="1" Ver="1">377</CName>
<CName Index="111" CID="388" Value="Jamaica" StdVal="Jamaica" Lang="en" IsLead="1" IsStd="1" Ver="1">379</CName>
<CName Index="111" CID="388" Value="Jamaica W.I." StdVal="JamaicaWI" Lang="en" IsLead="0" IsStd="1" Ver="1">380</CName>
<CName Index="112" CID="392" Value="Japan" StdVal="Japan" Lang="en" IsLead="1" IsStd="1" Ver="1">382</CName>
<CName Index="112" CID="392" Value="Japón" StdVal="Japón" Lang="es" IsLead="1" IsStd="1" Ver="1">383</CName>
<CName Index="113" CID="398" Value="Kazakhstan" StdVal="Kazakhstan" Lang="en" IsLead="1" IsStd="1" Ver="1">388</CName>
<CName Index="113" CID="398" Value="Kazajstán" StdVal="Kazajstán" Lang="es" IsLead="1" IsStd="1" Ver="1">389</CName>
<CName Index="114" CID="400" Value="Jordan" StdVal="Jordan" Lang="en" IsLead="1" IsStd="1" Ver="1">394</CName>
<CName Index="114" CID="400" Value="Jordania" StdVal="Jordania" Lang="es" IsLead="1" IsStd="1" Ver="1">395</CName>
<CName Index="115" CID="404" Value="Kenya" StdVal="Kenya" Lang="en" IsLead="1" IsStd="1" Ver="1">397</CName>
<CName Index="115" CID="404" Value="Kenia" StdVal="Kenia" Lang="es" IsLead="1" IsStd="1" Ver="1">398</CName>
<CName Index="116" CID="408" Value="North Korea" StdVal="NorthKorea" Lang="en" IsLead="1" IsStd="1" Ver="1">400</CName>
<CName Index="116" CID="408" Value="Corea del Norte" StdVal="CoreadelNorte" Lang="es" IsLead="1" IsStd="1" Ver="1">401</CName>
<CName Index="117" CID="410" Value="Korea" StdVal="Korea" Lang="en" IsLead="0" IsStd="1" Ver="1">405</CName>
<CName Index="117" CID="410" Value="South Korea" StdVal="SouthKorea" Lang="en" IsLead="1" IsStd="1" Ver="1">406</CName>
<CName Index="117" CID="410" Value="Corea del Sur" StdVal="CoreadelSur" Lang="es" IsLead="1" IsStd="1" Ver="1">407</CName>
<CName Index="118" CID="414" Value="Kuwait" StdVal="Kuwait" Lang="en" IsLead="1" IsStd="1" Ver="1">411</CName>
<CName Index="119" CID="417" Value="Kyrgyzstan" StdVal="Kyrgyzstan" Lang="en" IsLead="1" IsStd="1" Ver="1">414</CName>
<CName Index="119" CID="417" Value="Kirguizistán" StdVal="Kirguizistán" Lang="es" IsLead="1" IsStd="1" Ver="1">415</CName>
<CName Index="120" CID="418" Value="Laos" StdVal="Laos" Lang="en" IsLead="1" IsStd="1" Ver="1">417</CName>
<CName Index="120" CID="418" Value="República Democrática Popular Lao" StdVal="RepúblicaDemocráticaPopularLao" Lang="es" IsLead="1" IsStd="1" Ver="1">418</CName>
<CName Index="121" CID="422" Value="Lebanon" StdVal="Lebanon" Lang="en" IsLead="1" IsStd="1" Ver="1">422</CName>
<CName Index="121" CID="422" Value="Líbano" StdVal="Líbano" Lang="es" IsLead="1" IsStd="1" Ver="1">423</CName>
<CName Index="122" CID="426" Value="Lesotho" StdVal="Lesotho" Lang="en" IsLead="1" IsStd="1" Ver="1">425</CName>
<CName Index="123" CID="428" Value="Latvia" StdVal="Latvia" Lang="en" IsLead="1" IsStd="1" Ver="1">427</CName>
<CName Index="123" CID="428" Value="Letonia" StdVal="Letonia" Lang="es" IsLead="1" IsStd="1" Ver="1">428</CName>
<CName Index="124" CID="430" Value="Liberia" StdVal="Liberia" Lang="en" IsLead="1" IsStd="1" Ver="1">431</CName>
<CName Index="125" CID="434" Value="Libya" StdVal="Libya" Lang="en" IsLead="1" IsStd="1" Ver="1">435</CName>
<CName Index="125" CID="434" Value="Libia" StdVal="Libia" Lang="es" IsLead="1" IsStd="1" Ver="1">436</CName>
<CName Index="126" CID="438" Value="Liechtenstein" StdVal="Liechtenstein" Lang="en" IsLead="1" IsStd="1" Ver="1">438</CName>
<CName Index="127" CID="440" Value="Lithuania" StdVal="Lithuania" Lang="en" IsLead="1" IsStd="1" Ver="1">440</CName>
<CName Index="127" CID="440" Value="Lituania" StdVal="Lituania" Lang="es" IsLead="1" IsStd="1" Ver="1">441</CName>
<CName Index="128" CID="442" Value="Luxembourg" StdVal="Luxembourg" Lang="en" IsLead="1" IsStd="1" Ver="1">445</CName>
<CName Index="128" CID="442" Value="Luxemburgo" StdVal="Luxemburgo" Lang="es" IsLead="1" IsStd="1" Ver="1">446</CName>
<CName Index="129" CID="446" Value="Macao S.A.R., China" StdVal="MacaoSARChina" Lang="en" IsLead="0" IsStd="1" Ver="1">448</CName>
<CName Index="129" CID="446" Value="Macau" StdVal="Macau" Lang="en" IsLead="0" IsStd="1" Ver="1">449</CName>
<CName Index="129" CID="446" Value="Macao" StdVal="Macao" Lang="en" IsLead="1" IsStd="1" Ver="1">450</CName>
<CName Index="129" CID="446" Value="Macao, Región administrativa especial de China" StdVal="MacaoRegiónadministrativaespecialdeChina" Lang="es" IsLead="1" IsStd="1" Ver="1">451</CName>
<CName Index="130" CID="450" Value="Madagascar" StdVal="Madagascar" Lang="en" IsLead="1" IsStd="1" Ver="1">454</CName>
<CName Index="131" CID="454" Value="Malawi" StdVal="Malawi" Lang="en" IsLead="1" IsStd="1" Ver="1">455</CName>
<CName Index="132" CID="458" Value="Malaysia" StdVal="Malaysia" Lang="en" IsLead="1" IsStd="1" Ver="1">456</CName>
<CName Index="132" CID="458" Value="Malasia" StdVal="Malasia" Lang="es" IsLead="1" IsStd="1" Ver="1">457</CName>
<CName Index="133" CID="462" Value="Maldives" StdVal="Maldives" Lang="en" IsLead="1" IsStd="1" Ver="1">461</CName>
<CName Index="133" CID="462" Value="Maldivas" StdVal="Maldivas" Lang="es" IsLead="1" IsStd="1" Ver="1">462</CName>
<CName Index="134" CID="466" Value="Mali" StdVal="Mali" Lang="en" IsLead="1" IsStd="1" Ver="1">463</CName>
<CName Index="134" CID="466" Value="Malí" StdVal="Malí" Lang="es" IsLead="1" IsStd="1" Ver="1">464</CName>
<CName Index="135" CID="470" Value="Malta" StdVal="Malta" Lang="en" IsLead="1" IsStd="1" Ver="1">465</CName>
<CName Index="136" CID="474" Value="Martinique" StdVal="Martinique" Lang="en" IsLead="1" IsStd="1" Ver="1">467</CName>
<CName Index="136" CID="474" Value="Martinica" StdVal="Martinica" Lang="es" IsLead="1" IsStd="1" Ver="1">468</CName>
<CName Index="137" CID="478" Value="Mauritania" StdVal="Mauritania" Lang="en" IsLead="1" IsStd="1" Ver="1">471</CName>
<CName Index="138" CID="480" Value="Mauritius" StdVal="Mauritius" Lang="en" IsLead="1" IsStd="1" Ver="1">473</CName>
<CName Index="138" CID="480" Value="Mauricio" StdVal="Mauricio" Lang="es" IsLead="1" IsStd="1" Ver="1">474</CName>
<CName Index="139" CID="484" Value="Mexico" StdVal="Mexico" Lang="en" IsLead="1" IsStd="1" Ver="1">477</CName>
<CName Index="139" CID="484" Value="Mex" StdVal="Mex" Lang="en" IsLead="0" IsStd="1" Ver="1">478</CName>
<CName Index="139" CID="484" Value="México" StdVal="México" Lang="es" IsLead="1" IsStd="1" Ver="1">479</CName>
<CName Index="140" CID="492" Value="Monaco" StdVal="Monaco" Lang="en" IsLead="1" IsStd="1" Ver="1">481</CName>
<CName Index="140" CID="492" Value="Mónaco" StdVal="Mónaco" Lang="es" IsLead="1" IsStd="1" Ver="1">482</CName>
<CName Index="141" CID="496" Value="Mongolia" StdVal="Mongolia" Lang="en" IsLead="1" IsStd="1" Ver="1">484</CName>
<CName Index="142" CID="498" Value="Moldova" StdVal="Moldova" Lang="en" IsLead="1" IsStd="1" Ver="1">488</CName>
<CName Index="142" CID="498" Value="Moldavia, República de" StdVal="MoldaviaRepúblicade" Lang="es" IsLead="1" IsStd="1" Ver="1">489</CName>
<CName Index="143" CID="499" Value="Montenegro" StdVal="Montenegro" Lang="en" IsLead="1" IsStd="1" Ver="1">492</CName>
<CName Index="144" CID="500" Value="Montserrat" StdVal="Montserrat" Lang="en" IsLead="1" IsStd="1" Ver="1">494</CName>
<CName Index="145" CID="504" Value="Morocco" StdVal="Morocco" Lang="en" IsLead="1" IsStd="1" Ver="1">497</CName>
<CName Index="145" CID="504" Value="Marruecos" StdVal="Marruecos" Lang="es" IsLead="1" IsStd="1" Ver="1">498</CName>
<CName Index="146" CID="508" Value="Mozambique" StdVal="Mozambique" Lang="en" IsLead="1" IsStd="1" Ver="1">501</CName>
<CName Index="147" CID="512" Value="Oman" StdVal="Oman" Lang="en" IsLead="1" IsStd="1" Ver="1">504</CName>
<CName Index="147" CID="512" Value="Omán" StdVal="Omán" Lang="es" IsLead="1" IsStd="1" Ver="1">505</CName>
<CName Index="148" CID="516" Value="Namibia" StdVal="Namibia" Lang="en" IsLead="1" IsStd="1" Ver="1">506</CName>
<CName Index="149" CID="520" Value="Nauru" StdVal="Nauru" Lang="en" IsLead="1" IsStd="1" Ver="1">508</CName>
<CName Index="150" CID="524" Value="Nepal" StdVal="Nepal" Lang="en" IsLead="1" IsStd="1" Ver="1">509</CName>
<CName Index="151" CID="528" Value="The Netherlands" StdVal="TheNetherlands" Lang="en" IsLead="0" IsStd="1" Ver="1">513</CName>
<CName Index="151" CID="528" Value="Netherlands" StdVal="Netherlands" Lang="en" IsLead="1" IsStd="1" Ver="1">514</CName>
<CName Index="151" CID="528" Value="Países Bajos" StdVal="PaísesBajos" Lang="es" IsLead="1" IsStd="1" Ver="1">515</CName>
<CName Index="152" CID="530" Value="Netherlands Antilles" StdVal="NetherlandsAntilles" Lang="en" IsLead="1" IsStd="1" Ver="1">519</CName>
<CName Index="152" CID="530" Value="Antillas Neerlandesas" StdVal="AntillasNeerlandesas" Lang="es" IsLead="1" IsStd="1" Ver="1">520</CName>
<CName Index="153" CID="533" Value="Aruba" StdVal="Aruba" Lang="en" IsLead="1" IsStd="1" Ver="1">523</CName>
<CName Index="154" CID="540" Value="New Caledonia" StdVal="NewCaledonia" Lang="en" IsLead="1" IsStd="1" Ver="1">525</CName>
<CName Index="154" CID="540" Value="Nueva Caledonia" StdVal="NuevaCaledonia" Lang="es" IsLead="1" IsStd="1" Ver="1">526</CName>
<CName Index="155" CID="548" Value="Vanuatu" StdVal="Vanuatu" Lang="en" IsLead="1" IsStd="1" Ver="1">528</CName>
<CName Index="156" CID="554" Value="New Zealand" StdVal="NewZealand" Lang="en" IsLead="1" IsStd="1" Ver="1">530</CName>
<CName Index="156" CID="554" Value="Nueva Zelanda" StdVal="NuevaZelanda" Lang="es" IsLead="1" IsStd="1" Ver="1">531</CName>
<CName Index="157" CID="558" Value="Nicaragua" StdVal="Nicaragua" Lang="en" IsLead="1" IsStd="1" Ver="1">533</CName>
<CName Index="158" CID="562" Value="Niger" StdVal="Niger" Lang="en" IsLead="1" IsStd="1" Ver="1">534</CName>
<CName Index="158" CID="562" Value="Níger" StdVal="Níger" Lang="es" IsLead="1" IsStd="1" Ver="1">535</CName>
<CName Index="159" CID="566" Value="Nigeria" StdVal="Nigeria" Lang="en" IsLead="1" IsStd="1" Ver="1">536</CName>
<CName Index="160" CID="570" Value="Niue" StdVal="Niue" Lang="en" IsLead="1" IsStd="1" Ver="1">538</CName>
<CName Index="160" CID="570" Value="Isla Niue" StdVal="IslaNiue" Lang="es" IsLead="1" IsStd="1" Ver="1">539</CName>
<CName Index="161" CID="574" Value="Norfolk Island" StdVal="NorfolkIsland" Lang="en" IsLead="1" IsStd="1" Ver="1">542</CName>
<CName Index="161" CID="574" Value="Isla Norfolk" StdVal="IslaNorfolk" Lang="es" IsLead="1" IsStd="1" Ver="1">543</CName>
<CName Index="162" CID="578" Value="Norway" StdVal="Norway" Lang="en" IsLead="1" IsStd="1" Ver="1">546</CName>
<CName Index="162" CID="578" Value="Noruega" StdVal="Noruega" Lang="es" IsLead="1" IsStd="1" Ver="1">547</CName>
<CName Index="163" CID="580" Value="Northern Mariana Islands" StdVal="NorthernMarianaIslands" Lang="en" IsLead="1" IsStd="1" Ver="1">551</CName>
<CName Index="163" CID="580" Value="Islas Marianas del Norte" StdVal="IslasMarianasdelNorte" Lang="es" IsLead="1" IsStd="1" Ver="1">552</CName>
<CName Index="164" CID="581" Value="United States Minor Outlying Islands" StdVal="UnitedStatesMinorOutlyingIslands" Lang="en" IsLead="1" IsStd="1" Ver="1">555</CName>
<CName Index="164" CID="581" Value="Islas menores alejadas de los Estados Unidos" StdVal="IslasmenoresalejadasdelosEstadosUnidos" Lang="es" IsLead="1" IsStd="1" Ver="1">556</CName>
<CName Index="165" CID="583" Value="Federated States of Micronesia" StdVal="FederatedStatesofMicronesia" Lang="en" IsLead="0" IsStd="1" Ver="1">559</CName>
<CName Index="165" CID="583" Value="Micronesia (Federated States of)" StdVal="MicronesiaFederatedStatesof" Lang="en" IsLead="0" IsStd="1" Ver="1">560</CName>
<CName Index="165" CID="583" Value="Micronesia" StdVal="Micronesia" Lang="en" IsLead="1" IsStd="1" Ver="1">561</CName>
<CName Index="165" CID="583" Value="Micronesia, Estados Federados de" StdVal="MicronesiaEstadosFederadosde" Lang="es" IsLead="1" IsStd="1" Ver="1">562</CName>
<CName Index="166" CID="584" Value="Marshall Islands" StdVal="MarshallIslands" Lang="en" IsLead="1" IsStd="1" Ver="1">565</CName>
<CName Index="166" CID="584" Value="Islas Marshall" StdVal="IslasMarshall" Lang="es" IsLead="1" IsStd="1" Ver="1">566</CName>
<CName Index="167" CID="585" Value="Palau" StdVal="Palau" Lang="en" IsLead="1" IsStd="1" Ver="1">568</CName>
<CName Index="168" CID="586" Value="Pakistan" StdVal="Pakistan" Lang="en" IsLead="1" IsStd="1" Ver="1">570</CName>
<CName Index="168" CID="586" Value="Pakistán" StdVal="Pakistán" Lang="es" IsLead="1" IsStd="1" Ver="1">571</CName>
<CName Index="169" CID="591" Value="Panama" StdVal="Panama" Lang="en" IsLead="1" IsStd="1" Ver="1">572</CName>
<CName Index="169" CID="591" Value="Panamá" StdVal="Panamá" Lang="es" IsLead="1" IsStd="1" Ver="1">573</CName>
<CName Index="170" CID="598" Value="Papua New Guinea" StdVal="PapuaNewGuinea" Lang="en" IsLead="1" IsStd="1" Ver="1">575</CName>
<CName Index="170" CID="598" Value="Papúa Nueva Guinea" StdVal="PapúaNuevaGuinea" Lang="es" IsLead="1" IsStd="1" Ver="1">576</CName>
<CName Index="171" CID="600" Value="Paraguay" StdVal="Paraguay" Lang="en" IsLead="1" IsStd="1" Ver="1">578</CName>
<CName Index="172" CID="604" Value="Peru" StdVal="Peru" Lang="en" IsLead="1" IsStd="1" Ver="1">579</CName>
<CName Index="172" CID="604" Value="Perú" StdVal="Perú" Lang="es" IsLead="1" IsStd="1" Ver="1">580</CName>
<CName Index="173" CID="608" Value="Philippines" StdVal="Philippines" Lang="en" IsLead="1" IsStd="1" Ver="1">583</CName>
<CName Index="173" CID="608" Value="Phillippines" StdVal="Phillippines" Lang="en" IsLead="0" IsStd="1" Ver="1">584</CName>
<CName Index="173" CID="608" Value="Islas Filipinas" StdVal="IslasFilipinas" Lang="es" IsLead="0" IsStd="1" Ver="1">585</CName>
<CName Index="173" CID="608" Value="Filipinas" StdVal="Filipinas" Lang="es" IsLead="1" IsStd="1" Ver="1">586</CName>
<CName Index="174" CID="612" Value="Pitcairn Islands" StdVal="PitcairnIslands" Lang="en" IsLead="0" IsStd="1" Ver="1">587</CName>
<CName Index="174" CID="612" Value="Pitcairn" StdVal="Pitcairn" Lang="en" IsLead="1" IsStd="1" Ver="1">588</CName>
<CName Index="175" CID="616" Value="Poland" StdVal="Poland" Lang="en" IsLead="1" IsStd="1" Ver="1">590</CName>
<CName Index="175" CID="616" Value="Polonia" StdVal="Polonia" Lang="es" IsLead="1" IsStd="1" Ver="1">591</CName>
<CName Index="176" CID="620" Value="Portugal" StdVal="Portugal" Lang="en" IsLead="1" IsStd="1" Ver="1">594</CName>
<CName Index="177" CID="624" Value="Guinea-Bissau" StdVal="GuineaBissau" Lang="en" IsLead="1" IsStd="1" Ver="1">595</CName>
<CName Index="178" CID="626" Value="Timor-Leste" StdVal="TimorLeste" Lang="en" IsLead="1" IsStd="1" Ver="1">599</CName>
<CName Index="178" CID="626" Value="Timor Oriental" StdVal="TimorOriental" Lang="es" IsLead="1" IsStd="1" Ver="1">600</CName>
<CName Index="179" CID="630" Value="Puerto Rico" StdVal="PuertoRico" Lang="en" IsLead="1" IsStd="1" Ver="1">602</CName>
<CName Index="180" CID="634" Value="Qatar" StdVal="Qatar" Lang="en" IsLead="1" IsStd="1" Ver="1">606</CName>
<CName Index="181" CID="638" Value="Réunion" StdVal="Réunion" Lang="en" IsLead="1" IsStd="1" Ver="1">607</CName>
<CName Index="181" CID="638" Value="Reunión" StdVal="Reunión" Lang="es" IsLead="1" IsStd="1" Ver="1">608</CName>
<CName Index="182" CID="642" Value="Romania" StdVal="Romania" Lang="en" IsLead="1" IsStd="1" Ver="1">611</CName>
<CName Index="182" CID="642" Value="Rumanía" StdVal="Rumanía" Lang="es" IsLead="1" IsStd="1" Ver="1">612</CName>
<CName Index="183" CID="643" Value="Russia" StdVal="Russia" Lang="en" IsLead="1" IsStd="1" Ver="1">616</CName>
<CName Index="183" CID="643" Value="Russian Federation" StdVal="RussianFederation" Lang="en" IsLead="0" IsStd="1" Ver="1">617</CName>
<CName Index="183" CID="643" Value="Federación Rusa" StdVal="FederaciónRusa" Lang="es" IsLead="0" IsStd="1" Ver="1">618</CName>
<CName Index="183" CID="643" Value="Rusia" StdVal="Rusia" Lang="es" IsLead="1" IsStd="1" Ver="1">619</CName>
<CName Index="184" CID="646" Value="Rwanda" StdVal="Rwanda" Lang="en" IsLead="1" IsStd="1" Ver="1">622</CName>
<CName Index="184" CID="646" Value="Ruanda" StdVal="Ruanda" Lang="es" IsLead="1" IsStd="1" Ver="1">623</CName>
<CName Index="185" CID="652" Value="Collectivity of Saint Barthélemy" StdVal="CollectivityofSaintBarthélemy" Lang="en" IsLead="0" IsStd="1" Ver="1">627</CName>
<CName Index="185" CID="652" Value="Saint Barth" StdVal="SaintBarth" Lang="en" IsLead="0" IsStd="1" Ver="1">628</CName>
<CName Index="185" CID="652" Value="Saint Barths" StdVal="SaintBarths" Lang="en" IsLead="0" IsStd="1" Ver="1">629</CName>
<CName Index="185" CID="652" Value="Saint Barts" StdVal="SaintBarts" Lang="en" IsLead="0" IsStd="1" Ver="1">630</CName>
<CName Index="185" CID="652" Value="St. Bart's" StdVal="StBarts" Lang="en" IsLead="0" IsStd="1" Ver="1">631</CName>
<CName Index="185" CID="652" Value="Saint Barthélemy" StdVal="SaintBarthélemy" Lang="en" IsLead="1" IsStd="1" Ver="1">632</CName>
<CName Index="185" CID="652" Value="Colectividad de San Bartolomé" StdVal="ColectividaddeSanBartolomé" Lang="es" IsLead="0" IsStd="1" Ver="1">633</CName>
<CName Index="185" CID="652" Value="San Bartolomé" StdVal="SanBartolomé" Lang="es" IsLead="1" IsStd="1" Ver="1">634</CName>
<CName Index="186" CID="654" Value="Saint Helena" StdVal="SaintHelena" Lang="en" IsLead="1" IsStd="1" Ver="1">638</CName>
<CName Index="186" CID="654" Value="Santa Elena" StdVal="SantaElena" Lang="es" IsLead="1" IsStd="1" Ver="1">639</CName>
<CName Index="187" CID="659" Value="St. Kitts and Nevis" StdVal="StKittsandNevis" Lang="en" IsLead="0" IsStd="1" Ver="1">642</CName>
<CName Index="187" CID="659" Value="Saint Kitts and Nevis" StdVal="SaintKittsandNevis" Lang="en" IsLead="1" IsStd="1" Ver="1">643</CName>
<CName Index="187" CID="659" Value="San Cristóbal y Nieves" StdVal="SanCristóbalyNieves" Lang="es" IsLead="1" IsStd="1" Ver="1">644</CName>
<CName Index="188" CID="660" Value="Anguilla" StdVal="Anguilla" Lang="en" IsLead="1" IsStd="1" Ver="1">646</CName>
<CName Index="189" CID="662" Value="Saint Lucia" StdVal="SaintLucia" Lang="en" IsLead="1" IsStd="1" Ver="1">649</CName>
<CName Index="189" CID="662" Value="Santa Lucia" StdVal="SantaLucia" Lang="es" IsLead="1" IsStd="1" Ver="1">650</CName>
<CName Index="190" CID="663" Value="Collectivity of Saint Martin" StdVal="CollectivityofSaintMartin" Lang="en" IsLead="0" IsStd="1" Ver="1">652</CName>
<CName Index="190" CID="663" Value="Saint Martin (French Part)" StdVal="SaintMartinFrenchPart" Lang="en" IsLead="0" IsStd="1" Ver="1">653</CName>
<CName Index="190" CID="663" Value="St. Martin" StdVal="StMartin" Lang="en" IsLead="0" IsStd="1" Ver="1">654</CName>
<CName Index="190" CID="663" Value="Saint Martin" StdVal="SaintMartin" Lang="en" IsLead="1" IsStd="1" Ver="1">655</CName>
<CName Index="190" CID="663" Value="Colectividad de San Martín" StdVal="ColectividaddeSanMartín" Lang="es" IsLead="0" IsStd="1" Ver="1">656</CName>
<CName Index="190" CID="663" Value="San Martín" StdVal="SanMartín" Lang="es" IsLead="1" IsStd="1" Ver="1">657</CName>
<CName Index="191" CID="666" Value="Saint Pierre and Miquelon" StdVal="SaintPierreandMiquelon" Lang="en" IsLead="1" IsStd="1" Ver="1">663</CName>
<CName Index="191" CID="666" Value="San Pedro y Miquelón" StdVal="SanPedroyMiquelón" Lang="es" IsLead="1" IsStd="1" Ver="1">664</CName>
<CName Index="192" CID="670" Value="St. Vincent and the Grenadines" StdVal="StVincentandtheGrenadines" Lang="en" IsLead="0" IsStd="1" Ver="1">667</CName>
<CName Index="192" CID="670" Value="Saint Vincent and the Grenadines" StdVal="SaintVincentandtheGrenadines" Lang="en" IsLead="1" IsStd="1" Ver="1">668</CName>
<CName Index="192" CID="670" Value="San Vicente y las Granadinas" StdVal="SanVicenteylasGranadinas" Lang="es" IsLead="1" IsStd="1" Ver="1">669</CName>
<CName Index="193" CID="674" Value="San Marino" StdVal="SanMarino" Lang="en" IsLead="1" IsStd="1" Ver="1">671</CName>
<CName Index="194" CID="678" Value="Sao Tome and Principe" StdVal="SaoTomeandPrincipe" Lang="en" IsLead="1" IsStd="1" Ver="1">674</CName>
<CName Index="194" CID="678" Value="Santo Tomé y Príncipe" StdVal="SantoToméyPríncipe" Lang="es" IsLead="1" IsStd="1" Ver="1">675</CName>
<CName Index="195" CID="682" Value="Saudi Arabia" StdVal="SaudiArabia" Lang="en" IsLead="1" IsStd="1" Ver="1">680</CName>
<CName Index="195" CID="682" Value="Arabia Saudí" StdVal="ArabiaSaudí" Lang="es" IsLead="1" IsStd="1" Ver="1">681</CName>
<CName Index="196" CID="686" Value="Senegal" StdVal="Senegal" Lang="en" IsLead="1" IsStd="1" Ver="1">683</CName>
<CName Index="197" CID="688" Value="Serbia" StdVal="Serbia" Lang="en" IsLead="1" IsStd="1" Ver="1">686</CName>
<CName Index="197" CID="688" Value="Serbia and Montenegro" StdVal="SerbiaandMontenegro" Lang="en" IsLead="0" IsStd="1" Ver="1">687</CName>
<CName Index="197" CID="688" Value="Serbia Montenegro" StdVal="SerbiaMontenegro" Lang="en" IsLead="0" IsStd="1" Ver="1">688</CName>
<CName Index="198" CID="690" Value="Seychelles" StdVal="Seychelles" Lang="en" IsLead="1" IsStd="1" Ver="1">692</CName>
<CName Index="199" CID="694" Value="Sierra Leone" StdVal="SierraLeone" Lang="en" IsLead="1" IsStd="1" Ver="1">693</CName>
<CName Index="200" CID="702" Value="Singapore" StdVal="Singapore" Lang="en" IsLead="1" IsStd="1" Ver="1">695</CName>
<CName Index="200" CID="702" Value="Singapur" StdVal="Singapur" Lang="es" IsLead="1" IsStd="1" Ver="1">696</CName>
<CName Index="201" CID="703" Value="Slovak Republic" StdVal="SlovakRepublic" Lang="en" IsLead="0" IsStd="1" Ver="1">699</CName>
<CName Index="201" CID="703" Value="Slovakia" StdVal="Slovakia" Lang="en" IsLead="1" IsStd="1" Ver="1">700</CName>
<CName Index="201" CID="703" Value="Eslovaquia" StdVal="Eslovaquia" Lang="es" IsLead="1" IsStd="1" Ver="1">701</CName>
<CName Index="202" CID="704" Value="Vietnam" StdVal="Vietnam" Lang="en" IsLead="1" IsStd="1" Ver="1">704</CName>
<CName Index="203" CID="705" Value="Slovenia" StdVal="Slovenia" Lang="en" IsLead="1" IsStd="1" Ver="1">708</CName>
<CName Index="203" CID="705" Value="Eslovenia" StdVal="Eslovenia" Lang="es" IsLead="1" IsStd="1" Ver="1">709</CName>
<CName Index="204" CID="706" Value="Somalia" StdVal="Somalia" Lang="en" IsLead="1" IsStd="1" Ver="1">713</CName>
<CName Index="205" CID="710" Value="South Africa" StdVal="SouthAfrica" Lang="en" IsLead="1" IsStd="1" Ver="1">717</CName>
<CName Index="205" CID="710" Value="Sudáfrica" StdVal="Sudáfrica" Lang="es" IsLead="1" IsStd="1" Ver="1">718</CName>
<CName Index="206" CID="716" Value="Zimbabwe" StdVal="Zimbabwe" Lang="en" IsLead="1" IsStd="1" Ver="1">721</CName>
<CName Index="206" CID="716" Value="Zimbabue" StdVal="Zimbabue" Lang="es" IsLead="1" IsStd="1" Ver="1">722</CName>
<CName Index="207" CID="724" Value="Spain" StdVal="Spain" Lang="en" IsLead="1" IsStd="1" Ver="1">724</CName>
<CName Index="207" CID="724" Value="España" StdVal="España" Lang="es" IsLead="1" IsStd="1" Ver="1">725</CName>
<CName Index="207" CID="724" Value="Espana" StdVal="Espana" Lang="es" IsLead="0" IsStd="1" Ver="1">726</CName>
<CName Index="208" CID="732" Value="Western Sahara" StdVal="WesternSahara" Lang="en" IsLead="1" IsStd="1" Ver="1">730</CName>
<CName Index="208" CID="732" Value="Sáhara Occidental" StdVal="SáharaOccidental" Lang="es" IsLead="1" IsStd="1" Ver="1">731</CName>
<CName Index="209" CID="736" Value="Sudan" StdVal="Sudan" Lang="en" IsLead="1" IsStd="1" Ver="1">734</CName>
<CName Index="209" CID="736" Value="Sudán" StdVal="Sudán" Lang="es" IsLead="1" IsStd="1" Ver="1">735</CName>
<CName Index="210" CID="740" Value="Suriname" StdVal="Suriname" Lang="en" IsLead="1" IsStd="1" Ver="1">737</CName>
<CName Index="210" CID="740" Value="Surinam" StdVal="Surinam" Lang="es" IsLead="1" IsStd="1" Ver="1">738</CName>
<CName Index="211" CID="744" Value="Svalbard" StdVal="Svalbard" Lang="en" IsLead="0" IsStd="1" Ver="1">740</CName>
<CName Index="211" CID="744" Value="Svalbard and Jan Mayen" StdVal="SvalbardandJanMayen" Lang="en" IsLead="1" IsStd="1" Ver="1">741</CName>
<CName Index="211" CID="744" Value="Svalbard y Jan Mayen" StdVal="SvalbardyJanMayen" Lang="es" IsLead="1" IsStd="1" Ver="1">742</CName>
<CName Index="212" CID="748" Value="Swaziland" StdVal="Swaziland" Lang="en" IsLead="1" IsStd="1" Ver="1">746</CName>
<CName Index="212" CID="748" Value="Suazilandia" StdVal="Suazilandia" Lang="es" IsLead="1" IsStd="1" Ver="1">747</CName>
<CName Index="213" CID="752" Value="Sweden" StdVal="Sweden" Lang="en" IsLead="1" IsStd="1" Ver="1">749</CName>
<CName Index="213" CID="752" Value="Suecia" StdVal="Suecia" Lang="es" IsLead="1" IsStd="1" Ver="1">750</CName>
<CName Index="214" CID="756" Value="Switzerland" StdVal="Switzerland" Lang="en" IsLead="1" IsStd="1" Ver="1">754</CName>
<CName Index="214" CID="756" Value="Suiza" StdVal="Suiza" Lang="es" IsLead="1" IsStd="1" Ver="1">755</CName>
<CName Index="215" CID="760" Value="Syria" StdVal="Syria" Lang="en" IsLead="1" IsStd="1" Ver="1">759</CName>
<CName Index="215" CID="760" Value="Siria" StdVal="Siria" Lang="es" IsLead="1" IsStd="1" Ver="1">760</CName>
<CName Index="216" CID="762" Value="Tajikistan" StdVal="Tajikistan" Lang="en" IsLead="1" IsStd="1" Ver="1">763</CName>
<CName Index="216" CID="762" Value="Tayikistán" StdVal="Tayikistán" Lang="es" IsLead="1" IsStd="1" Ver="1">764</CName>
<CName Index="217" CID="764" Value="Thailand" StdVal="Thailand" Lang="en" IsLead="1" IsStd="1" Ver="1">767</CName>
<CName Index="217" CID="764" Value="Tailandia" StdVal="Tailandia" Lang="es" IsLead="1" IsStd="1" Ver="1">768</CName>
<CName Index="218" CID="768" Value="Togo" StdVal="Togo" Lang="en" IsLead="1" IsStd="1" Ver="1">771</CName>
<CName Index="219" CID="772" Value="Tokelau" StdVal="Tokelau" Lang="en" IsLead="1" IsStd="1" Ver="1">772</CName>
<CName Index="219" CID="772" Value="Islas Tokelau" StdVal="IslasTokelau" Lang="es" IsLead="1" IsStd="1" Ver="1">773</CName>
<CName Index="220" CID="776" Value="Tonga" StdVal="Tonga" Lang="en" IsLead="1" IsStd="1" Ver="1">774</CName>
<CName Index="221" CID="780" Value="Trinidad and Tobago" StdVal="TrinidadandTobago" Lang="en" IsLead="1" IsStd="1" Ver="1">776</CName>
<CName Index="221" CID="780" Value="Trinidad Tobago" StdVal="TrinidadTobago" Lang="en" IsLead="0" IsStd="1" Ver="1">777</CName>
<CName Index="221" CID="780" Value="Trinidad y Tabago" StdVal="TrinidadyTabago" Lang="es" IsLead="1" IsStd="1" Ver="1">778</CName>
<CName Index="222" CID="784" Value="United Arab Emirates" StdVal="UnitedArabEmirates" Lang="en" IsLead="1" IsStd="1" Ver="1">782</CName>
<CName Index="222" CID="784" Value="Emiratos Árabes Unidos" StdVal="EmiratosÁrabesUnidos" Lang="es" IsLead="1" IsStd="1" Ver="1">783</CName>
<CName Index="223" CID="788" Value="Tunisia" StdVal="Tunisia" Lang="en" IsLead="1" IsStd="1" Ver="1">787</CName>
<CName Index="223" CID="788" Value="Túnez" StdVal="Túnez" Lang="es" IsLead="1" IsStd="1" Ver="1">788</CName>
<CName Index="224" CID="792" Value="Turkey" StdVal="Turkey" Lang="en" IsLead="1" IsStd="1" Ver="1">791</CName>
<CName Index="224" CID="792" Value="Turquía" StdVal="Turquía" Lang="es" IsLead="1" IsStd="1" Ver="1">792</CName>
<CName Index="225" CID="795" Value="Turkmenistan" StdVal="Turkmenistan" Lang="en" IsLead="1" IsStd="1" Ver="1">795</CName>
<CName Index="225" CID="795" Value="Turkmenistán" StdVal="Turkmenistán" Lang="es" IsLead="1" IsStd="1" Ver="1">796</CName>
<CName Index="226" CID="796" Value="Turks and Caicos Islands" StdVal="TurksandCaicosIslands" Lang="en" IsLead="1" IsStd="1" Ver="1">799</CName>
<CName Index="226" CID="796" Value="Islas Turcas y Caicos" StdVal="IslasTurcasyCaicos" Lang="es" IsLead="1" IsStd="1" Ver="1">800</CName>
<CName Index="227" CID="798" Value="Tuvalu" StdVal="Tuvalu" Lang="en" IsLead="1" IsStd="1" Ver="1">802</CName>
<CName Index="228" CID="800" Value="Uganda" StdVal="Uganda" Lang="en" IsLead="1" IsStd="1" Ver="1">803</CName>
<CName Index="229" CID="804" Value="Ukraine" StdVal="Ukraine" Lang="en" IsLead="1" IsStd="1" Ver="1">805</CName>
<CName Index="229" CID="804" Value="Ucrania" StdVal="Ucrania" Lang="es" IsLead="1" IsStd="1" Ver="1">806</CName>
<CName Index="230" CID="807" Value="F.Y.R.O. Macedonia" StdVal="FYROMacedonia" Lang="en" IsLead="0" IsStd="1" Ver="1">809</CName>
<CName Index="230" CID="807" Value="Macedonia" StdVal="Macedonia" Lang="en" IsLead="1" IsStd="1" Ver="1">810</CName>
<CName Index="230" CID="807" Value="Macedonia, Antigua República Yugoslava de" StdVal="MacedoniaAntiguaRepúblicaYugoslavade" Lang="es" IsLead="1" IsStd="1" Ver="1">811</CName>
<CName Index="231" CID="818" Value="Egypt" StdVal="Egypt" Lang="en" IsLead="1" IsStd="1" Ver="1">816</CName>
<CName Index="231" CID="818" Value="Egipto" StdVal="Egipto" Lang="es" IsLead="1" IsStd="1" Ver="1">817</CName>
<CName Index="232" CID="826" Value="Britain" StdVal="Britain" Lang="en" IsLead="0" IsStd="1" Ver="1">820</CName>
<CName Index="232" CID="826" Value="England" StdVal="England" Lang="en" IsLead="0" IsStd="1" Ver="1">821</CName>
<CName Index="232" CID="826" Value="Great Britain" StdVal="GreatBritain" Lang="en" IsLead="0" IsStd="1" Ver="1">822</CName>
<CName Index="232" CID="826" Value="Northern Ireland" StdVal="NorthernIreland" Lang="en" IsLead="0" IsStd="1" Ver="1">823</CName>
<CName Index="232" CID="826" Value="Scotland" StdVal="Scotland" Lang="en" IsLead="0" IsStd="1" Ver="1">824</CName>
<CName Index="232" CID="826" Value="UK" StdVal="UK" Lang="en" IsLead="0" IsStd="1" Ver="1">825</CName>
<CName Index="232" CID="826" Value="Wales" StdVal="Wales" Lang="en" IsLead="0" IsStd="1" Ver="1">826</CName>
<CName Index="232" CID="826" Value="United Kingdom" StdVal="UnitedKingdom" Lang="en" IsLead="1" IsStd="1" Ver="1">827</CName>
<CName Index="232" CID="826" Value="Reino Unido" StdVal="ReinoUnido" Lang="es" IsLead="1" IsStd="1" Ver="1">828</CName>
<CName Index="233" CID="831" Value="Guernsey" StdVal="Guernsey" Lang="en" IsLead="1" IsStd="1" Ver="1">830</CName>
<CName Index="234" CID="832" Value="Jersey" StdVal="Jersey" Lang="en" IsLead="1" IsStd="1" Ver="1">832</CName>
<CName Index="235" CID="833" Value="Isle of Man" StdVal="IsleofMan" Lang="en" IsLead="1" IsStd="1" Ver="1">833</CName>
<CName Index="235" CID="833" Value="Isla de Man" StdVal="IsladeMan" Lang="es" IsLead="1" IsStd="1" Ver="1">834</CName>
<CName Index="236" CID="834" Value="United Republic of Tanzania" StdVal="UnitedRepublicofTanzania" Lang="en" IsLead="0" IsStd="1" Ver="1">837</CName>
<CName Index="236" CID="834" Value="Tanzania" StdVal="Tanzania" Lang="en" IsLead="1" IsStd="1" Ver="1">838</CName>
<CName Index="237" CID="840" Value="United States" StdVal="UnitedStates" Lang="en" IsLead="0" IsStd="1" Ver="1">841</CName>
<CName Index="237" CID="840" Value="US" StdVal="US" Lang="en" IsLead="0" IsStd="1" Ver="1">842</CName>
<CName Index="237" CID="840" Value="USA" StdVal="USA" Lang="en" IsLead="0" IsStd="1" Ver="1">843</CName>
<CName Index="237" CID="840" Value="United States of America" StdVal="UnitedStatesofAmerica" Lang="en" IsLead="1" IsStd="1" Ver="1">844</CName>
<CName Index="237" CID="840" Value="Estados Unidos" StdVal="EstadosUnidos" Lang="es" IsLead="1" IsStd="1" Ver="1">845</CName>
<CName Index="238" CID="850" Value="U.S. Virgin Islands" StdVal="USVirginIslands" Lang="en" IsLead="0" IsStd="1" Ver="1">848</CName>
<CName Index="238" CID="850" Value="Virgin Islands (U.S.)" StdVal="VirginIslandsUS" Lang="en" IsLead="0" IsStd="1" Ver="1">849</CName>
<CName Index="238" CID="850" Value="Virgin Islands of the United States" StdVal="VirginIslandsoftheUnitedStates" Lang="en" IsLead="0" IsStd="1" Ver="1">850</CName>
<CName Index="238" CID="850" Value="Virgin Islands" StdVal="VirginIslands" Lang="en" IsLead="1" IsStd="1" Ver="1">851</CName>
<CName Index="238" CID="850" Value="Islas Vírgenes de los Estados Unidos" StdVal="IslasVírgenesdelosEstadosUnidos" Lang="es" IsLead="1" IsStd="1" Ver="1">852</CName>
<CName Index="239" CID="854" Value="Burkina Faso" StdVal="BurkinaFaso" Lang="en" IsLead="1" IsStd="1" Ver="1">854</CName>
<CName Index="240" CID="858" Value="Uruguay" StdVal="Uruguay" Lang="en" IsLead="1" IsStd="1" Ver="1">856</CName>
<CName Index="241" CID="860" Value="Uzbekistan" StdVal="Uzbekistan" Lang="en" IsLead="1" IsStd="1" Ver="1">858</CName>
<CName Index="241" CID="860" Value="Uzbekistán" StdVal="Uzbekistán" Lang="es" IsLead="1" IsStd="1" Ver="1">859</CName>
<CName Index="242" CID="862" Value="Venezuela" StdVal="Venezuela" Lang="en" IsLead="1" IsStd="1" Ver="1">862</CName>
<CName Index="243" CID="876" Value="Wallis and Futuna" StdVal="WallisandFutuna" Lang="en" IsLead="1" IsStd="1" Ver="1">865</CName>
<CName Index="243" CID="876" Value="Wallis y Futuna" StdVal="WallisyFutuna" Lang="es" IsLead="1" IsStd="1" Ver="1">866</CName>
<CName Index="244" CID="882" Value="Samoa" StdVal="Samoa" Lang="en" IsLead="1" IsStd="1" Ver="1">869</CName>
<CName Index="245" CID="887" Value="Yemen" StdVal="Yemen" Lang="en" IsLead="1" IsStd="1" Ver="1">872</CName>
<CName Index="246" CID="894" Value="Zambia" StdVal="Zambia" Lang="en" IsLead="1" IsStd="1" Ver="1">875</CName>
</CNameSets>
