<?xml version="1.0" encoding="UTF-8"?>
<CNameSets xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<CName Index="2" CID="008" Value="Albanien" StdVal="Albanien" Lang="de" IsLead="1" IsStd="1" Ver="1">4</CName>
<CName Index="2" CID="008" Value="Albanie" StdVal="Albanie" Lang="fr" IsLead="1" IsStd="1" Ver="1">6</CName>
<CName Index="3" CID="010" Value="Antarktis" StdVal="Antarktis" Lang="de" IsLead="1" IsStd="1" Ver="1">9</CName>
<CName Index="3" CID="010" Value="Antarctique" StdVal="Antarctique" Lang="fr" IsLead="1" IsStd="1" Ver="1">12</CName>
<CName Index="4" CID="012" Value="Algerien" StdVal="Algerien" Lang="de" IsLead="1" IsStd="1" Ver="1">14</CName>
<CName Index="4" CID="012" Value="Algérie" StdVal="Algérie" Lang="fr" IsLead="1" IsStd="1" Ver="1">17</CName>
<CName Index="5" CID="016" Value="Amerikanisch-Samoa" StdVal="AmerikanischSamoa" Lang="de" IsLead="1" IsStd="1" Ver="1">18</CName>
<CName Index="5" CID="016" Value="Samoa américaines" StdVal="Samoaaméricaines" Lang="fr" IsLead="1" IsStd="1" Ver="1">21</CName>
<CName Index="6" CID="020" Value="Andorre" StdVal="Andorre" Lang="fr" IsLead="1" IsStd="1" Ver="1">23</CName>
<CName Index="8" CID="028" Value="Antigua und Barbuda" StdVal="AntiguaundBarbuda" Lang="de" IsLead="1" IsStd="1" Ver="1">25</CName>
<CName Index="8" CID="028" Value="Antigua-et-Barbuda" StdVal="AntiguaetBarbuda" Lang="fr" IsLead="1" IsStd="1" Ver="1">29</CName>
<CName Index="9" CID="031" Value="Aserbaidschan" StdVal="Aserbaidschan" Lang="de" IsLead="1" IsStd="1" Ver="1">31</CName>
<CName Index="9" CID="031" Value="Azerbaïdjan" StdVal="Azerbaïdjan" Lang="fr" IsLead="1" IsStd="1" Ver="1">34</CName>
<CName Index="10" CID="032" Value="Argentinien" StdVal="Argentinien" Lang="de" IsLead="1" IsStd="1" Ver="1">35</CName>
<CName Index="10" CID="032" Value="Argentine" StdVal="Argentine" Lang="fr" IsLead="1" IsStd="1" Ver="1">37</CName>
<CName Index="11" CID="036" Value="Australien" StdVal="Australien" Lang="de" IsLead="1" IsStd="1" Ver="1">38</CName>
<CName Index="11" CID="036" Value="Australie" StdVal="Australie" Lang="fr" IsLead="1" IsStd="1" Ver="1">40</CName>
<CName Index="12" CID="040" Value="Österreich" StdVal="Österreich" Lang="de" IsLead="1" IsStd="1" Ver="1">41</CName>
<CName Index="12" CID="040" Value="Autriche" StdVal="Autriche" Lang="fr" IsLead="1" IsStd="1" Ver="1">43</CName>
<CName Index="14" CID="048" Value="Bahreïn" StdVal="Bahreïn" Lang="fr" IsLead="1" IsStd="1" Ver="1">49</CName>
<CName Index="15" CID="050" Value="Bangladesch" StdVal="Bangladesch" Lang="de" IsLead="1" IsStd="1" Ver="1">51</CName>
<CName Index="16" CID="051" Value="Armenien" StdVal="Armenien" Lang="de" IsLead="1" IsStd="1" Ver="1">53</CName>
<CName Index="16" CID="051" Value="Arménie" StdVal="Arménie" Lang="fr" IsLead="1" IsStd="1" Ver="1">55</CName>
<CName Index="17" CID="052" Value="Barbade" StdVal="Barbade" Lang="fr" IsLead="1" IsStd="1" Ver="1">58</CName>
<CName Index="18" CID="056" Value="Belgien" StdVal="Belgien" Lang="de" IsLead="1" IsStd="1" Ver="1">59</CName>
<CName Index="18" CID="056" Value="Belgique" StdVal="Belgique" Lang="fr" IsLead="1" IsStd="1" Ver="1">62</CName>
<CName Index="19" CID="060" Value="Bermudes" StdVal="Bermudes" Lang="fr" IsLead="1" IsStd="1" Ver="1">65</CName>
<CName Index="20" CID="064" Value="Bhoutan" StdVal="Bhoutan" Lang="fr" IsLead="1" IsStd="1" Ver="1">69</CName>
<CName Index="21" CID="068" Value="Bolivien" StdVal="Bolivien" Lang="de" IsLead="1" IsStd="1" Ver="1">70</CName>
<CName Index="21" CID="068" Value="Bolivie" StdVal="Bolivie" Lang="fr" IsLead="1" IsStd="1" Ver="1">72</CName>
<CName Index="22" CID="070" Value="Bosnien und Herzegowina" StdVal="BosnienundHerzegowina" Lang="de" IsLead="1" IsStd="1" Ver="1">74</CName>
<CName Index="22" CID="070" Value="Bosnie-Herzégovine" StdVal="BosnieHerzégovine" Lang="fr" IsLead="1" IsStd="1" Ver="1">77</CName>
<CName Index="25" CID="076" Value="Brasilien" StdVal="Brasilien" Lang="de" IsLead="1" IsStd="1" Ver="1">82</CName>
<CName Index="25" CID="076" Value="Brésil" StdVal="Brésil" Lang="fr" IsLead="1" IsStd="1" Ver="1">85</CName>
<CName Index="27" CID="086" Value="Britisches Territorium im Indischen Ozean" StdVal="BritischesTerritoriumimIndischenOzean" Lang="de" IsLead="1" IsStd="1" Ver="1">88</CName>
<CName Index="27" CID="086" Value="Territoire britannique de l’océan indien" StdVal="Territoirebritanniquedel’océanindien" Lang="fr" IsLead="1" IsStd="1" Ver="1">91</CName>
<CName Index="28" CID="090" Value="Salomonen" StdVal="Salomonen" Lang="de" IsLead="1" IsStd="1" Ver="1">92</CName>
<CName Index="28" CID="090" Value="Îles Salomon" StdVal="ÎlesSalomon" Lang="fr" IsLead="1" IsStd="1" Ver="1">95</CName>
<CName Index="29" CID="092" Value="Britische Jungferninseln" StdVal="BritischeJungferninseln" Lang="de" IsLead="1" IsStd="1" Ver="1">96</CName>
<CName Index="29" CID="092" Value="Îles Vierges Britanniques" StdVal="ÎlesViergesBritanniques" Lang="fr" IsLead="1" IsStd="1" Ver="1">101</CName>
<CName Index="30" CID="096" Value="Brunei Darussalam" StdVal="BruneiDarussalam" Lang="de" IsLead="1" IsStd="1" Ver="1">102</CName>
<CName Index="30" CID="096" Value="Brunéi Darussalam" StdVal="BrunéiDarussalam" Lang="fr" IsLead="1" IsStd="1" Ver="1">105</CName>
<CName Index="31" CID="100" Value="Bulgarien" StdVal="Bulgarien" Lang="de" IsLead="1" IsStd="1" Ver="1">107</CName>
<CName Index="31" CID="100" Value="Bulgarie" StdVal="Bulgarie" Lang="fr" IsLead="1" IsStd="1" Ver="1">109</CName>
<CName Index="34" CID="112" Value="Bélarus" StdVal="Bélarus" Lang="fr" IsLead="1" IsStd="1" Ver="1">116</CName>
<CName Index="35" CID="116" Value="Kambodscha" StdVal="Kambodscha" Lang="de" IsLead="1" IsStd="1" Ver="1">117</CName>
<CName Index="35" CID="116" Value="Cambodge" StdVal="Cambodge" Lang="fr" IsLead="1" IsStd="1" Ver="1">120</CName>
<CName Index="36" CID="120" Value="Kamerun" StdVal="Kamerun" Lang="de" IsLead="1" IsStd="1" Ver="1">122</CName>
<CName Index="36" CID="120" Value="Cameroun" StdVal="Cameroun" Lang="fr" IsLead="1" IsStd="1" Ver="1">125</CName>
<CName Index="37" CID="124" Value="Kanada" StdVal="Kanada" Lang="de" IsLead="1" IsStd="1" Ver="1">126</CName>
<CName Index="38" CID="132" Value="Kap Verde" StdVal="KapVerde" Lang="de" IsLead="1" IsStd="1" Ver="1">129</CName>
<CName Index="38" CID="132" Value="Cap Vert" StdVal="CapVert" Lang="fr" IsLead="1" IsStd="1" Ver="1">132</CName>
<CName Index="39" CID="136" Value="Kaimaninseln" StdVal="Kaimaninseln" Lang="de" IsLead="1" IsStd="1" Ver="1">133</CName>
<CName Index="39" CID="136" Value="Îles Caïmanes" StdVal="ÎlesCaïmanes" Lang="fr" IsLead="1" IsStd="1" Ver="1">136</CName>
<CName Index="40" CID="140" Value="Zentralafrikanische Republik" StdVal="ZentralafrikanischeRepublik" Lang="de" IsLead="1" IsStd="1" Ver="1">137</CName>
<CName Index="40" CID="140" Value="République centrafricaine" StdVal="Républiquecentrafricaine" Lang="fr" IsLead="1" IsStd="1" Ver="1">140</CName>
<CName Index="42" CID="148" Value="Tschad" StdVal="Tschad" Lang="de" IsLead="1" IsStd="1" Ver="1">144</CName>
<CName Index="42" CID="148" Value="Tchad" StdVal="Tchad" Lang="fr" IsLead="1" IsStd="1" Ver="1">146</CName>
<CName Index="43" CID="152" Value="Chili" StdVal="Chili" Lang="fr" IsLead="1" IsStd="1" Ver="1">148</CName>
<CName Index="44" CID="156" Value="Chine" StdVal="Chine" Lang="fr" IsLead="1" IsStd="1" Ver="1">151</CName>
<CName Index="45" CID="158" Value="Taïwan" StdVal="Taïwan" Lang="fr" IsLead="1" IsStd="1" Ver="1">155</CName>
<CName Index="46" CID="162" Value="Weihnachtsinsel" StdVal="Weihnachtsinsel" Lang="de" IsLead="1" IsStd="1" Ver="1">156</CName>
<CName Index="46" CID="162" Value="Île Christmas" StdVal="ÎleChristmas" Lang="fr" IsLead="1" IsStd="1" Ver="1">159</CName>
<CName Index="47" CID="166" Value="Kokosinseln (Keeling)" StdVal="KokosinselnKeeling" Lang="de" IsLead="1" IsStd="1" Ver="1">160</CName>
<CName Index="47" CID="166" Value="Îles Cocos" StdVal="ÎlesCocos" Lang="fr" IsLead="1" IsStd="1" Ver="1">165</CName>
<CName Index="48" CID="170" Value="Kolumbien" StdVal="Kolumbien" Lang="de" IsLead="1" IsStd="1" Ver="1">166</CName>
<CName Index="48" CID="170" Value="Colombie" StdVal="Colombie" Lang="fr" IsLead="1" IsStd="1" Ver="1">168</CName>
<CName Index="49" CID="174" Value="Komoren" StdVal="Komoren" Lang="de" IsLead="1" IsStd="1" Ver="1">170</CName>
<CName Index="49" CID="174" Value="Comores" StdVal="Comores" Lang="fr" IsLead="1" IsStd="1" Ver="1">173</CName>
<CName Index="51" CID="178" Value="Kongo" StdVal="Kongo" Lang="de" IsLead="1" IsStd="1" Ver="1">175</CName>
<CName Index="52" CID="180" Value="Demokratische Republik Kongo" StdVal="DemokratischeRepublikKongo" Lang="de" IsLead="1" IsStd="1" Ver="1">177</CName>
<CName Index="52" CID="180" Value="Congo, République démocratique du" StdVal="CongoRépubliquedémocratiquedu" Lang="fr" IsLead="0" IsStd="1" Ver="1">180</CName>
<CName Index="52" CID="180" Value="République démocratique du Congo" StdVal="RépubliquedémocratiqueduCongo" Lang="fr" IsLead="1" IsStd="1" Ver="1">181</CName>
<CName Index="53" CID="184" Value="Cookinseln" StdVal="Cookinseln" Lang="de" IsLead="1" IsStd="1" Ver="1">182</CName>
<CName Index="53" CID="184" Value="Îles Cook" StdVal="ÎlesCook" Lang="fr" IsLead="1" IsStd="1" Ver="1">185</CName>
<CName Index="55" CID="191" Value="Kroatien" StdVal="Kroatien" Lang="de" IsLead="1" IsStd="1" Ver="1">187</CName>
<CName Index="55" CID="191" Value="Croatie" StdVal="Croatie" Lang="fr" IsLead="1" IsStd="1" Ver="1">190</CName>
<CName Index="56" CID="192" Value="Kuba" StdVal="Kuba" Lang="de" IsLead="1" IsStd="1" Ver="1">192</CName>
<CName Index="57" CID="196" Value="Zypern" StdVal="Zypern" Lang="de" IsLead="1" IsStd="1" Ver="1">194</CName>
<CName Index="57" CID="196" Value="Chypre" StdVal="Chypre" Lang="fr" IsLead="1" IsStd="1" Ver="1">198</CName>
<CName Index="58" CID="203" Value="Česko" StdVal="Česko" Lang="cs" IsLead="1" IsStd="1" Ver="1">199</CName>
<CName Index="58" CID="203" Value="Tschechische Republik" StdVal="TschechischeRepublik" Lang="de" IsLead="1" IsStd="1" Ver="1">200</CName>
<CName Index="58" CID="203" Value="République tchèque" StdVal="Républiquetchèque" Lang="fr" IsLead="1" IsStd="1" Ver="1">204</CName>
<CName Index="59" CID="204" Value="Bénin" StdVal="Bénin" Lang="fr" IsLead="1" IsStd="1" Ver="1">207</CName>
<CName Index="60" CID="208" Value="Danmark" StdVal="Danmark" Lang="da" IsLead="1" IsStd="1" Ver="1">208</CName>
<CName Index="60" CID="208" Value="Dänemark" StdVal="Dänemark" Lang="de" IsLead="1" IsStd="1" Ver="1">209</CName>
<CName Index="60" CID="208" Value="Danemark" StdVal="Danemark" Lang="fr" IsLead="1" IsStd="1" Ver="1">212</CName>
<CName Index="61" CID="212" Value="Dominique" StdVal="Dominique" Lang="fr" IsLead="1" IsStd="1" Ver="1">214</CName>
<CName Index="62" CID="214" Value="Dominikanische Republik" StdVal="DominikanischeRepublik" Lang="de" IsLead="1" IsStd="1" Ver="1">215</CName>
<CName Index="62" CID="214" Value="République dominicaine" StdVal="Républiquedominicaine" Lang="fr" IsLead="1" IsStd="1" Ver="1">218</CName>
<CName Index="63" CID="218" Value="Équateur" StdVal="Équateur" Lang="fr" IsLead="1" IsStd="1" Ver="1">220</CName>
<CName Index="65" CID="226" Value="Äquatorialguinea" StdVal="Äquatorialguinea" Lang="de" IsLead="1" IsStd="1" Ver="1">222</CName>
<CName Index="65" CID="226" Value="Guinée équatoriale" StdVal="Guinéeéquatoriale" Lang="fr" IsLead="1" IsStd="1" Ver="1">225</CName>
<CName Index="66" CID="231" Value="Äthiopien" StdVal="Äthiopien" Lang="de" IsLead="1" IsStd="1" Ver="1">227</CName>
<CName Index="66" CID="231" Value="Éthiopie" StdVal="Éthiopie" Lang="fr" IsLead="1" IsStd="1" Ver="1">230</CName>
<CName Index="67" CID="232" Value="Érythrée" StdVal="Érythrée" Lang="fr" IsLead="1" IsStd="1" Ver="1">233</CName>
<CName Index="68" CID="233" Value="Estland" StdVal="Estland" Lang="de" IsLead="1" IsStd="1" Ver="1">234</CName>
<CName Index="68" CID="233" Value="Estonie" StdVal="Estonie" Lang="fr" IsLead="1" IsStd="1" Ver="1">237</CName>
<CName Index="69" CID="234" Value="Færøerne" StdVal="Færøerne" Lang="da" IsLead="1" IsStd="1" Ver="1">238</CName>
<CName Index="69" CID="234" Value="Färöer" StdVal="Färöer" Lang="de" IsLead="1" IsStd="1" Ver="1">239</CName>
<CName Index="69" CID="234" Value="Îles Féroé" StdVal="ÎlesFéroé" Lang="fr" IsLead="1" IsStd="1" Ver="1">243</CName>
<CName Index="70" CID="238" Value="Falklandinseln" StdVal="Falklandinseln" Lang="de" IsLead="1" IsStd="1" Ver="1">244</CName>
<CName Index="70" CID="238" Value="Îles Falkland (Malvinas)" StdVal="ÎlesFalklandMalvinas" Lang="fr" IsLead="1" IsStd="1" Ver="1">248</CName>
<CName Index="71" CID="239" Value="Südgeorgien und die Südlichen Sandwichinseln" StdVal="SüdgeorgienunddieSüdlichenSandwichinseln" Lang="de" IsLead="1" IsStd="1" Ver="1">249</CName>
<CName Index="71" CID="239" Value="Géorgie du Sud, Îles Sandwich du Sud" StdVal="GéorgieduSudÎlesSandwichduSud" Lang="fr" IsLead="1" IsStd="1" Ver="1">252</CName>
<CName Index="72" CID="242" Value="Fidschi" StdVal="Fidschi" Lang="de" IsLead="1" IsStd="1" Ver="1">253</CName>
<CName Index="72" CID="242" Value="Fidji" StdVal="Fidji" Lang="fr" IsLead="1" IsStd="1" Ver="1">257</CName>
<CName Index="73" CID="246" Value="Finnland" StdVal="Finnland" Lang="de" IsLead="1" IsStd="1" Ver="1">258</CName>
<CName Index="73" CID="246" Value="Suomi" StdVal="Suomi" Lang="fi" IsLead="1" IsStd="1" Ver="1">261</CName>
<CName Index="73" CID="246" Value="Finlande" StdVal="Finlande" Lang="fr" IsLead="1" IsStd="1" Ver="1">262</CName>
<CName Index="74" CID="248" Value="Ahvenanmaa" StdVal="Ahvenanmaa" Lang="fi" IsLead="1" IsStd="1" Ver="1">264</CName>
<CName Index="75" CID="250" Value="Frankreich" StdVal="Frankreich" Lang="de" IsLead="1" IsStd="1" Ver="1">265</CName>
<CName Index="76" CID="254" Value="Französisch-Guayana" StdVal="FranzösischGuayana" Lang="de" IsLead="1" IsStd="1" Ver="1">268</CName>
<CName Index="76" CID="254" Value="Guyane" StdVal="Guyane" Lang="fr" IsLead="0" IsStd="1" Ver="1">271</CName>
<CName Index="76" CID="254" Value="Guyane française" StdVal="Guyanefrançaise" Lang="fr" IsLead="1" IsStd="1" Ver="1">272</CName>
<CName Index="77" CID="258" Value="Französisch-Polynesien" StdVal="FranzösischPolynesien" Lang="de" IsLead="1" IsStd="1" Ver="1">273</CName>
<CName Index="77" CID="258" Value="Polynésie française" StdVal="Polynésiefrançaise" Lang="fr" IsLead="1" IsStd="1" Ver="1">276</CName>
<CName Index="78" CID="260" Value="Französische Süd- und Antarktisgebiete" StdVal="FranzösischeSüdundAntarktisgebiete" Lang="de" IsLead="1" IsStd="1" Ver="1">277</CName>
<CName Index="78" CID="260" Value="Terres australes françaises" StdVal="Terresaustralesfrançaises" Lang="fr" IsLead="1" IsStd="1" Ver="1">281</CName>
<CName Index="79" CID="262" Value="Dschibuti" StdVal="Dschibuti" Lang="de" IsLead="1" IsStd="1" Ver="1">283</CName>
<CName Index="80" CID="266" Value="Gabun" StdVal="Gabun" Lang="de" IsLead="1" IsStd="1" Ver="1">286</CName>
<CName Index="81" CID="268" Value="Georgien" StdVal="Georgien" Lang="de" IsLead="1" IsStd="1" Ver="1">289</CName>
<CName Index="81" CID="268" Value="Géorgie" StdVal="Géorgie" Lang="fr" IsLead="1" IsStd="1" Ver="1">291</CName>
<CName Index="82" CID="270" Value="Gambie" StdVal="Gambie" Lang="fr" IsLead="1" IsStd="1" Ver="1">295</CName>
<CName Index="84" CID="276" Value="Deutschland" StdVal="Deutschland" Lang="de" IsLead="1" IsStd="1" Ver="1">298</CName>
<CName Index="84" CID="276" Value="Allemagne" StdVal="Allemagne" Lang="fr" IsLead="1" IsStd="1" Ver="1">301</CName>
<CName Index="88" CID="300" Value="Griechenland" StdVal="Griechenland" Lang="de" IsLead="1" IsStd="1" Ver="1">305</CName>
<CName Index="88" CID="300" Value="Grèce" StdVal="Grèce" Lang="fr" IsLead="1" IsStd="1" Ver="1">310</CName>
<CName Index="89" CID="304" Value="Grønland" StdVal="Grønland" Lang="da" IsLead="1" IsStd="1" Ver="1">311</CName>
<CName Index="89" CID="304" Value="Grönland" StdVal="Grönland" Lang="de" IsLead="1" IsStd="1" Ver="1">312</CName>
<CName Index="89" CID="304" Value="Groenland" StdVal="Groenland" Lang="fr" IsLead="1" IsStd="1" Ver="1">315</CName>
<CName Index="90" CID="308" Value="Grenade" StdVal="Grenade" Lang="fr" IsLead="1" IsStd="1" Ver="1">318</CName>
<CName Index="94" CID="324" Value="Guinée" StdVal="Guinée" Lang="fr" IsLead="1" IsStd="1" Ver="1">324</CName>
<CName Index="96" CID="332" Value="Haïti" StdVal="Haïti" Lang="fr" IsLead="1" IsStd="1" Ver="1">328</CName>
<CName Index="98" CID="336" Value="Vatikanstadt" StdVal="Vatikanstadt" Lang="de" IsLead="1" IsStd="1" Ver="1">330</CName>
<CName Index="98" CID="336" Value="Saint-Siège (Etat de la Cité du Vatican)" StdVal="SaintSiègeEtatdelaCitéduVatican" Lang="fr" IsLead="1" IsStd="1" Ver="1">335</CName>
<CName Index="98" CID="336" Value="Santa Sede" StdVal="SantaSede" Lang="it" IsLead="1" IsStd="1" Ver="1">336</CName>
<CName Index="100" CID="344" Value="Hong-Kong R.A.S." StdVal="HongKongRAS" Lang="fr" IsLead="1" IsStd="1" Ver="1">341</CName>
<CName Index="101" CID="348" Value="Ungarn" StdVal="Ungarn" Lang="de" IsLead="1" IsStd="1" Ver="1">342</CName>
<CName Index="101" CID="348" Value="Hongrie" StdVal="Hongrie" Lang="fr" IsLead="1" IsStd="1" Ver="1">345</CName>
<CName Index="101" CID="348" Value="Magyarország" StdVal="Magyarország" Lang="hu" IsLead="1" IsStd="1" Ver="1">346</CName>
<CName Index="102" CID="352" Value="Island" StdVal="Island" Lang="de" IsLead="1" IsStd="1" Ver="1">347</CName>
<CName Index="102" CID="352" Value="Islande" StdVal="Islande" Lang="fr" IsLead="1" IsStd="1" Ver="1">350</CName>
<CName Index="103" CID="356" Value="Indien" StdVal="Indien" Lang="de" IsLead="1" IsStd="1" Ver="1">352</CName>
<CName Index="103" CID="356" Value="Inde" StdVal="Inde" Lang="fr" IsLead="1" IsStd="1" Ver="1">354</CName>
<CName Index="104" CID="360" Value="Indonesien" StdVal="Indonesien" Lang="de" IsLead="1" IsStd="1" Ver="1">355</CName>
<CName Index="104" CID="360" Value="Indonésie" StdVal="Indonésie" Lang="fr" IsLead="1" IsStd="1" Ver="1">357</CName>
<CName Index="106" CID="368" Value="Irak" StdVal="Irak" Lang="de" IsLead="1" IsStd="1" Ver="1">362</CName>
<CName Index="107" CID="372" Value="Irland" StdVal="Irland" Lang="de" IsLead="1" IsStd="1" Ver="1">364</CName>
<CName Index="107" CID="372" Value="Irlande" StdVal="Irlande" Lang="fr" IsLead="1" IsStd="1" Ver="1">368</CName>
<CName Index="108" CID="376" Value="Israël" StdVal="Israël" Lang="fr" IsLead="1" IsStd="1" Ver="1">371</CName>
<CName Index="109" CID="380" Value="Italien" StdVal="Italien" Lang="de" IsLead="1" IsStd="1" Ver="1">372</CName>
<CName Index="109" CID="380" Value="Italie" StdVal="Italie" Lang="fr" IsLead="1" IsStd="1" Ver="1">375</CName>
<CName Index="111" CID="388" Value="Jamaika" StdVal="Jamaika" Lang="de" IsLead="1" IsStd="1" Ver="1">378</CName>
<CName Index="111" CID="388" Value="Jamaïque" StdVal="Jamaïque" Lang="fr" IsLead="1" IsStd="1" Ver="1">381</CName>
<CName Index="112" CID="392" Value="Japon" StdVal="Japon" Lang="fr" IsLead="1" IsStd="1" Ver="1">384</CName>
<CName Index="112" CID="392" Value="Nihon" StdVal="Nihon" Lang="ja" IsLead="0" IsStd="1" Ver="1">385</CName>
<CName Index="112" CID="392" Value="Nippon" StdVal="Nippon" Lang="ja" IsLead="1" IsStd="1" Ver="1">386</CName>
<CName Index="113" CID="398" Value="Kasachstan" StdVal="Kasachstan" Lang="de" IsLead="1" IsStd="1" Ver="1">387</CName>
<CName Index="113" CID="398" Value="Kazakstan" StdVal="Kazakstan" Lang="fr" IsLead="1" IsStd="1" Ver="1">390</CName>
<CName Index="114" CID="400" Value="Jordanien" StdVal="Jordanien" Lang="de" IsLead="1" IsStd="1" Ver="1">393</CName>
<CName Index="114" CID="400" Value="Jordanie" StdVal="Jordanie" Lang="fr" IsLead="1" IsStd="1" Ver="1">396</CName>
<CName Index="116" CID="408" Value="Demokratische Volksrepublik Korea" StdVal="DemokratischeVolksrepublikKorea" Lang="de" IsLead="1" IsStd="1" Ver="1">399</CName>
<CName Index="116" CID="408" Value="Corée du Nord" StdVal="CoréeduNord" Lang="fr" IsLead="1" IsStd="1" Ver="1">402</CName>
<CName Index="116" CID="408" Value="Chosŏn" StdVal="Chosŏn" Lang="ko" IsLead="1" IsStd="1" Ver="1">403</CName>
<CName Index="117" CID="410" Value="Republik Korea" StdVal="RepublikKorea" Lang="de" IsLead="1" IsStd="1" Ver="1">404</CName>
<CName Index="117" CID="410" Value="Corée du Sud" StdVal="CoréeduSud" Lang="fr" IsLead="1" IsStd="1" Ver="1">408</CName>
<CName Index="117" CID="410" Value="Han'guk" StdVal="Hanguk" Lang="ko" IsLead="1" IsStd="1" Ver="1">409</CName>
<CName Index="118" CID="414" Value="Koweït" StdVal="Koweït" Lang="fr" IsLead="1" IsStd="1" Ver="1">412</CName>
<CName Index="119" CID="417" Value="Kirgisistan" StdVal="Kirgisistan" Lang="de" IsLead="1" IsStd="1" Ver="1">413</CName>
<CName Index="119" CID="417" Value="Kirghizistan" StdVal="Kirghizistan" Lang="fr" IsLead="1" IsStd="1" Ver="1">416</CName>
<CName Index="121" CID="422" Value="Libanon" StdVal="Libanon" Lang="de" IsLead="1" IsStd="1" Ver="1">421</CName>
<CName Index="121" CID="422" Value="Liban" StdVal="Liban" Lang="fr" IsLead="1" IsStd="1" Ver="1">424</CName>
<CName Index="123" CID="428" Value="Lettland" StdVal="Lettland" Lang="de" IsLead="1" IsStd="1" Ver="1">426</CName>
<CName Index="123" CID="428" Value="Lettonie" StdVal="Lettonie" Lang="fr" IsLead="1" IsStd="1" Ver="1">429</CName>
<CName Index="124" CID="430" Value="Libéria" StdVal="Libéria" Lang="fr" IsLead="1" IsStd="1" Ver="1">432</CName>
<CName Index="125" CID="434" Value="Libyen" StdVal="Libyen" Lang="de" IsLead="1" IsStd="1" Ver="1">434</CName>
<CName Index="125" CID="434" Value="Libye" StdVal="Libye" Lang="fr" IsLead="1" IsStd="1" Ver="1">437</CName>
<CName Index="127" CID="440" Value="Litauen" StdVal="Litauen" Lang="de" IsLead="1" IsStd="1" Ver="1">439</CName>
<CName Index="127" CID="440" Value="Lithuanie" StdVal="Lithuanie" Lang="fr" IsLead="1" IsStd="1" Ver="1">442</CName>
<CName Index="128" CID="442" Value="Luxemburg" StdVal="Luxemburg" Lang="de" IsLead="1" IsStd="1" Ver="1">444</CName>
<CName Index="129" CID="446" Value="Macau S.A.R., China" StdVal="MacauSARChina" Lang="de" IsLead="1" IsStd="1" Ver="1">447</CName>
<CName Index="129" CID="446" Value="Macao R.A.S. de Chine" StdVal="MacaoRASdeChine" Lang="fr" IsLead="1" IsStd="1" Ver="1">452</CName>
<CName Index="130" CID="450" Value="Madagaskar" StdVal="Madagaskar" Lang="de" IsLead="1" IsStd="1" Ver="1">453</CName>
<CName Index="132" CID="458" Value="Malaisie" StdVal="Malaisie" Lang="fr" IsLead="1" IsStd="1" Ver="1">458</CName>
<CName Index="133" CID="462" Value="Malediven" StdVal="Malediven" Lang="de" IsLead="1" IsStd="1" Ver="1">459</CName>
<CName Index="135" CID="470" Value="Malte" StdVal="Malte" Lang="fr" IsLead="1" IsStd="1" Ver="1">466</CName>
<CName Index="137" CID="478" Value="Mauretanien" StdVal="Mauretanien" Lang="de" IsLead="1" IsStd="1" Ver="1">470</CName>
<CName Index="137" CID="478" Value="Mauritanie" StdVal="Mauritanie" Lang="fr" IsLead="1" IsStd="1" Ver="1">472</CName>
<CName Index="138" CID="480" Value="Maurice" StdVal="Maurice" Lang="fr" IsLead="1" IsStd="1" Ver="1">475</CName>
<CName Index="139" CID="484" Value="Mexiko" StdVal="Mexiko" Lang="de" IsLead="1" IsStd="1" Ver="1">476</CName>
<CName Index="139" CID="484" Value="Mexique" StdVal="Mexique" Lang="fr" IsLead="1" IsStd="1" Ver="1">480</CName>
<CName Index="141" CID="496" Value="Mongolei" StdVal="Mongolei" Lang="de" IsLead="1" IsStd="1" Ver="1">483</CName>
<CName Index="141" CID="496" Value="Mongolie" StdVal="Mongolie" Lang="fr" IsLead="1" IsStd="1" Ver="1">485</CName>
<CName Index="142" CID="498" Value="Republik Moldau" StdVal="RepublikMoldau" Lang="de" IsLead="1" IsStd="1" Ver="1">487</CName>
<CName Index="142" CID="498" Value="Moldavie" StdVal="Moldavie" Lang="fr" IsLead="1" IsStd="1" Ver="1">490</CName>
<CName Index="143" CID="499" Value="Monténégro" StdVal="Monténégro" Lang="fr" IsLead="1" IsStd="1" Ver="1">493</CName>
<CName Index="145" CID="504" Value="Marokko" StdVal="Marokko" Lang="de" IsLead="1" IsStd="1" Ver="1">496</CName>
<CName Index="145" CID="504" Value="Maroc" StdVal="Maroc" Lang="fr" IsLead="1" IsStd="1" Ver="1">499</CName>
<CName Index="146" CID="508" Value="Mosambik" StdVal="Mosambik" Lang="de" IsLead="1" IsStd="1" Ver="1">500</CName>
<CName Index="148" CID="516" Value="Namibie" StdVal="Namibie" Lang="fr" IsLead="1" IsStd="1" Ver="1">507</CName>
<CName Index="150" CID="524" Value="Népal" StdVal="Népal" Lang="fr" IsLead="1" IsStd="1" Ver="1">510</CName>
<CName Index="151" CID="528" Value="Niederlande" StdVal="Niederlande" Lang="de" IsLead="1" IsStd="1" Ver="1">512</CName>
<CName Index="151" CID="528" Value="Pays-Bas" StdVal="PaysBas" Lang="fr" IsLead="1" IsStd="1" Ver="1">516</CName>
<CName Index="152" CID="530" Value="Niederländische Antillen" StdVal="NiederländischeAntillen" Lang="de" IsLead="1" IsStd="1" Ver="1">518</CName>
<CName Index="152" CID="530" Value="Antilles néerlandaises" StdVal="Antillesnéerlandaises" Lang="fr" IsLead="1" IsStd="1" Ver="1">521</CName>
<CName Index="154" CID="540" Value="Neukaledonien" StdVal="Neukaledonien" Lang="de" IsLead="1" IsStd="1" Ver="1">524</CName>
<CName Index="154" CID="540" Value="Nouvelle-Calédonie" StdVal="NouvelleCalédonie" Lang="fr" IsLead="1" IsStd="1" Ver="1">527</CName>
<CName Index="156" CID="554" Value="Neuseeland" StdVal="Neuseeland" Lang="de" IsLead="1" IsStd="1" Ver="1">529</CName>
<CName Index="156" CID="554" Value="Nouvelle-Zélande" StdVal="NouvelleZélande" Lang="fr" IsLead="1" IsStd="1" Ver="1">532</CName>
<CName Index="159" CID="566" Value="Nigéria" StdVal="Nigéria" Lang="fr" IsLead="1" IsStd="1" Ver="1">537</CName>
<CName Index="160" CID="570" Value="Niué" StdVal="Niué" Lang="fr" IsLead="1" IsStd="1" Ver="1">540</CName>
<CName Index="161" CID="574" Value="Norfolkinsel" StdVal="Norfolkinsel" Lang="de" IsLead="1" IsStd="1" Ver="1">541</CName>
<CName Index="161" CID="574" Value="Île Norfolk" StdVal="ÎleNorfolk" Lang="fr" IsLead="1" IsStd="1" Ver="1">544</CName>
<CName Index="162" CID="578" Value="Norwegen" StdVal="Norwegen" Lang="de" IsLead="1" IsStd="1" Ver="1">545</CName>
<CName Index="162" CID="578" Value="Norvège" StdVal="Norvège" Lang="fr" IsLead="1" IsStd="1" Ver="1">548</CName>
<CName Index="163" CID="580" Value="Nördliche Marianen" StdVal="NördlicheMarianen" Lang="de" IsLead="1" IsStd="1" Ver="1">550</CName>
<CName Index="163" CID="580" Value="Îles Mariannes du Nord" StdVal="ÎlesMariannesduNord" Lang="fr" IsLead="1" IsStd="1" Ver="1">553</CName>
<CName Index="164" CID="581" Value="Amerikanisch-Ozeanien" StdVal="AmerikanischOzeanien" Lang="de" IsLead="1" IsStd="1" Ver="1">554</CName>
<CName Index="164" CID="581" Value="Îles Mineures Éloignées des États-Unis" StdVal="ÎlesMineuresÉloignéesdesÉtatsUnis" Lang="fr" IsLead="1" IsStd="1" Ver="1">557</CName>
<CName Index="165" CID="583" Value="Mikronesien" StdVal="Mikronesien" Lang="de" IsLead="1" IsStd="1" Ver="1">558</CName>
<CName Index="165" CID="583" Value="Micronésie" StdVal="Micronésie" Lang="fr" IsLead="1" IsStd="1" Ver="1">563</CName>
<CName Index="166" CID="584" Value="Marshallinseln" StdVal="Marshallinseln" Lang="de" IsLead="1" IsStd="1" Ver="1">564</CName>
<CName Index="166" CID="584" Value="Îles Marshall" StdVal="ÎlesMarshall" Lang="fr" IsLead="1" IsStd="1" Ver="1">567</CName>
<CName Index="167" CID="585" Value="Palaos" StdVal="Palaos" Lang="fr" IsLead="1" IsStd="1" Ver="1">569</CName>
<CName Index="170" CID="598" Value="Papua-Neuguinea" StdVal="PapuaNeuguinea" Lang="de" IsLead="1" IsStd="1" Ver="1">574</CName>
<CName Index="170" CID="598" Value="Papouasie-Nouvelle-Guinée" StdVal="PapouasieNouvelleGuinée" Lang="fr" IsLead="1" IsStd="1" Ver="1">577</CName>
<CName Index="172" CID="604" Value="Pérou" StdVal="Pérou" Lang="fr" IsLead="1" IsStd="1" Ver="1">581</CName>
<CName Index="173" CID="608" Value="Philippinen" StdVal="Philippinen" Lang="de" IsLead="1" IsStd="1" Ver="1">582</CName>
<CName Index="175" CID="616" Value="Polen" StdVal="Polen" Lang="de" IsLead="1" IsStd="1" Ver="1">589</CName>
<CName Index="175" CID="616" Value="Pologne" StdVal="Pologne" Lang="fr" IsLead="1" IsStd="1" Ver="1">592</CName>
<CName Index="175" CID="616" Value="Polska" StdVal="Polska" Lang="pl" IsLead="1" IsStd="1" Ver="1">593</CName>
<CName Index="177" CID="624" Value="Guinée-Bissau" StdVal="GuinéeBissau" Lang="fr" IsLead="1" IsStd="1" Ver="1">596</CName>
<CName Index="178" CID="626" Value="Osttimor" StdVal="Osttimor" Lang="de" IsLead="1" IsStd="1" Ver="1">598</CName>
<CName Index="178" CID="626" Value="Timor" StdVal="Timor" Lang="fr" IsLead="1" IsStd="1" Ver="1">601</CName>
<CName Index="179" CID="630" Value="Porto Rico" StdVal="PortoRico" Lang="fr" IsLead="1" IsStd="1" Ver="1">603</CName>
<CName Index="180" CID="634" Value="Katar" StdVal="Katar" Lang="de" IsLead="1" IsStd="1" Ver="1">605</CName>
<CName Index="181" CID="638" Value="La Réunion" StdVal="LaRéunion" Lang="fr" IsLead="1" IsStd="1" Ver="1">609</CName>
<CName Index="182" CID="642" Value="Rumänien" StdVal="Rumänien" Lang="de" IsLead="1" IsStd="1" Ver="1">610</CName>
<CName Index="182" CID="642" Value="Roumanie" StdVal="Roumanie" Lang="fr" IsLead="1" IsStd="1" Ver="1">613</CName>
<CName Index="182" CID="642" Value="România" StdVal="România" Lang="ro" IsLead="1" IsStd="1" Ver="1">614</CName>
<CName Index="183" CID="643" Value="Russische Föderation" StdVal="RussischeFöderation" Lang="de" IsLead="1" IsStd="1" Ver="1">615</CName>
<CName Index="183" CID="643" Value="Russie" StdVal="Russie" Lang="fr" IsLead="1" IsStd="1" Ver="1">620</CName>
<CName Index="183" CID="643" Value="Rossija" StdVal="Rossija" Lang="ru" IsLead="1" IsStd="1" Ver="1">621</CName>
<CName Index="185" CID="652" Value="Sankt Bartholomäus" StdVal="SanktBartholomäus" Lang="de" IsLead="0" IsStd="1" Ver="1">624</CName>
<CName Index="185" CID="652" Value="St. Barths" StdVal="StBarths" Lang="de" IsLead="0" IsStd="1" Ver="1">625</CName>
<CName Index="185" CID="652" Value="St. Barts" StdVal="StBarts" Lang="de" IsLead="1" IsStd="1" Ver="1">626</CName>
<CName Index="185" CID="652" Value="Collectivité de Saint-Barthélemy" StdVal="CollectivitédeSaintBarthélemy" Lang="fr" IsLead="0" IsStd="1" Ver="1">635</CName>
<CName Index="185" CID="652" Value="Saint-Barthélemy" StdVal="SaintBarthélemy" Lang="fr" IsLead="1" IsStd="1" Ver="1">636</CName>
<CName Index="186" CID="654" Value="St. Helena" StdVal="StHelena" Lang="de" IsLead="1" IsStd="1" Ver="1">637</CName>
<CName Index="186" CID="654" Value="Sainte-Hélène" StdVal="SainteHélène" Lang="fr" IsLead="1" IsStd="1" Ver="1">640</CName>
<CName Index="187" CID="659" Value="St. Kitts und Nevis" StdVal="StKittsundNevis" Lang="de" IsLead="1" IsStd="1" Ver="1">641</CName>
<CName Index="187" CID="659" Value="Saint Kitts et Nevis" StdVal="SaintKittsetNevis" Lang="fr" IsLead="1" IsStd="1" Ver="1">645</CName>
<CName Index="188" CID="660" Value="Anguila" StdVal="Anguila" Lang="fr" IsLead="1" IsStd="1" Ver="1">647</CName>
<CName Index="189" CID="662" Value="St. Lucia" StdVal="StLucia" Lang="de" IsLead="1" IsStd="1" Ver="1">648</CName>
<CName Index="189" CID="662" Value="Sainte-Lucie" StdVal="SainteLucie" Lang="fr" IsLead="1" IsStd="1" Ver="1">651</CName>
<CName Index="190" CID="663" Value="Collectivité de Saint-Martin" StdVal="CollectivitédeSaintMartin" Lang="fr" IsLead="0" IsStd="1" Ver="1">658</CName>
<CName Index="190" CID="663" Value="Saint-Martin (Antilles Françaises)" StdVal="SaintMartinAntillesFrançaises" Lang="fr" IsLead="0" IsStd="1" Ver="1">659</CName>
<CName Index="190" CID="663" Value="Saint-Martin (Partie Française)" StdVal="SaintMartinPartieFrançaise" Lang="fr" IsLead="0" IsStd="1" Ver="1">660</CName>
<CName Index="190" CID="663" Value="Saint-Martin" StdVal="SaintMartin" Lang="fr" IsLead="1" IsStd="1" Ver="1">661</CName>
<CName Index="191" CID="666" Value="St. Pierre und Miquelon" StdVal="StPierreundMiquelon" Lang="de" IsLead="1" IsStd="1" Ver="1">662</CName>
<CName Index="191" CID="666" Value="Saint-Pierre-et-Miquelon" StdVal="SaintPierreetMiquelon" Lang="fr" IsLead="1" IsStd="1" Ver="1">665</CName>
<CName Index="192" CID="670" Value="St. Vincent und die Grenadinen" StdVal="StVincentunddieGrenadinen" Lang="de" IsLead="1" IsStd="1" Ver="1">666</CName>
<CName Index="192" CID="670" Value="Saint-Vincent-et-les Grenadines" StdVal="SaintVincentetlesGrenadines" Lang="fr" IsLead="1" IsStd="1" Ver="1">670</CName>
<CName Index="193" CID="674" Value="Saint-Marin" StdVal="SaintMarin" Lang="fr" IsLead="1" IsStd="1" Ver="1">672</CName>
<CName Index="194" CID="678" Value="São Tomé und Príncipe" StdVal="SãoToméundPríncipe" Lang="de" IsLead="1" IsStd="1" Ver="1">673</CName>
<CName Index="194" CID="678" Value="Sao Tomé-et-Principe" StdVal="SaoToméetPrincipe" Lang="fr" IsLead="1" IsStd="1" Ver="1">676</CName>
<CName Index="195" CID="682" Value="Saudi-Arabien" StdVal="SaudiArabien" Lang="de" IsLead="1" IsStd="1" Ver="1">679</CName>
<CName Index="195" CID="682" Value="Arabie saoudite" StdVal="Arabiesaoudite" Lang="fr" IsLead="1" IsStd="1" Ver="1">682</CName>
<CName Index="196" CID="686" Value="Sénégal" StdVal="Sénégal" Lang="fr" IsLead="1" IsStd="1" Ver="1">684</CName>
<CName Index="197" CID="688" Value="Serbien" StdVal="Serbien" Lang="de" IsLead="1" IsStd="1" Ver="1">685</CName>
<CName Index="197" CID="688" Value="Serbie" StdVal="Serbie" Lang="fr" IsLead="1" IsStd="1" Ver="1">689</CName>
<CName Index="198" CID="690" Value="Seychellen" StdVal="Seychellen" Lang="de" IsLead="1" IsStd="1" Ver="1">691</CName>
<CName Index="199" CID="694" Value="Sierra Leona" StdVal="SierraLeona" Lang="fr" IsLead="1" IsStd="1" Ver="1">694</CName>
<CName Index="200" CID="702" Value="Singapour" StdVal="Singapour" Lang="fr" IsLead="1" IsStd="1" Ver="1">697</CName>
<CName Index="201" CID="703" Value="Slowakei" StdVal="Slowakei" Lang="de" IsLead="1" IsStd="1" Ver="1">698</CName>
<CName Index="201" CID="703" Value="Slovaquie" StdVal="Slovaquie" Lang="fr" IsLead="1" IsStd="1" Ver="1">702</CName>
<CName Index="202" CID="704" Value="Viet Nam" StdVal="VietNam" Lang="fr" IsLead="1" IsStd="1" Ver="1">705</CName>
<CName Index="203" CID="705" Value="Slowenien" StdVal="Slowenien" Lang="de" IsLead="1" IsStd="1" Ver="1">707</CName>
<CName Index="203" CID="705" Value="Slovénie" StdVal="Slovénie" Lang="fr" IsLead="1" IsStd="1" Ver="1">710</CName>
<CName Index="204" CID="706" Value="Somalie" StdVal="Somalie" Lang="fr" IsLead="1" IsStd="1" Ver="1">714</CName>
<CName Index="205" CID="710" Value="Südafrika" StdVal="Südafrika" Lang="de" IsLead="1" IsStd="1" Ver="1">716</CName>
<CName Index="205" CID="710" Value="Afrique du Sud" StdVal="AfriqueduSud" Lang="fr" IsLead="1" IsStd="1" Ver="1">719</CName>
<CName Index="206" CID="716" Value="Simbabwe" StdVal="Simbabwe" Lang="de" IsLead="1" IsStd="1" Ver="1">720</CName>
<CName Index="207" CID="724" Value="Spanien" StdVal="Spanien" Lang="de" IsLead="1" IsStd="1" Ver="1">723</CName>
<CName Index="207" CID="724" Value="Espagne" StdVal="Espagne" Lang="fr" IsLead="1" IsStd="1" Ver="1">727</CName>
<CName Index="208" CID="732" Value="Westsahara" StdVal="Westsahara" Lang="de" IsLead="1" IsStd="1" Ver="1">729</CName>
<CName Index="208" CID="732" Value="Sahara occidental" StdVal="Saharaoccidental" Lang="fr" IsLead="1" IsStd="1" Ver="1">732</CName>
<CName Index="209" CID="736" Value="Soudan" StdVal="Soudan" Lang="fr" IsLead="1" IsStd="1" Ver="1">736</CName>
<CName Index="211" CID="744" Value="Svalbard und Jan Mayen" StdVal="SvalbardundJanMayen" Lang="de" IsLead="1" IsStd="1" Ver="1">739</CName>
<CName Index="211" CID="744" Value="Svalbard et Île Jan Mayen" StdVal="SvalbardetÎleJanMayen" Lang="fr" IsLead="1" IsStd="1" Ver="1">743</CName>
<CName Index="212" CID="748" Value="Swasiland" StdVal="Swasiland" Lang="de" IsLead="1" IsStd="1" Ver="1">745</CName>
<CName Index="213" CID="752" Value="Schweden" StdVal="Schweden" Lang="de" IsLead="1" IsStd="1" Ver="1">748</CName>
<CName Index="213" CID="752" Value="Suède" StdVal="Suède" Lang="fr" IsLead="1" IsStd="1" Ver="1">751</CName>
<CName Index="213" CID="752" Value="Sverige" StdVal="Sverige" Lang="sv" IsLead="1" IsStd="1" Ver="1">752</CName>
<CName Index="214" CID="756" Value="Schweiz" StdVal="Schweiz" Lang="de" IsLead="1" IsStd="1" Ver="1">753</CName>
<CName Index="214" CID="756" Value="Suisse" StdVal="Suisse" Lang="fr" IsLead="1" IsStd="1" Ver="1">756</CName>
<CName Index="215" CID="760" Value="Syrien" StdVal="Syrien" Lang="de" IsLead="1" IsStd="1" Ver="1">758</CName>
<CName Index="215" CID="760" Value="Syrie" StdVal="Syrie" Lang="fr" IsLead="1" IsStd="1" Ver="1">761</CName>
<CName Index="216" CID="762" Value="Tadschikistan" StdVal="Tadschikistan" Lang="de" IsLead="1" IsStd="1" Ver="1">762</CName>
<CName Index="216" CID="762" Value="Tadjikistan" StdVal="Tadjikistan" Lang="fr" IsLead="1" IsStd="1" Ver="1">765</CName>
<CName Index="217" CID="764" Value="Thaïlande" StdVal="Thaïlande" Lang="fr" IsLead="1" IsStd="1" Ver="1">769</CName>
<CName Index="217" CID="764" Value="Prathet Thai" StdVal="PrathetThai" Lang="th" IsLead="1" IsStd="1" Ver="1">770</CName>
<CName Index="221" CID="780" Value="Trinidad und Tobago" StdVal="TrinidadundTobago" Lang="de" IsLead="1" IsStd="1" Ver="1">775</CName>
<CName Index="221" CID="780" Value="Trinité-et-Tobago" StdVal="TrinitéetTobago" Lang="fr" IsLead="1" IsStd="1" Ver="1">779</CName>
<CName Index="222" CID="784" Value="Vereinigte Arabische Emirate" StdVal="VereinigteArabischeEmirate" Lang="de" IsLead="1" IsStd="1" Ver="1">781</CName>
<CName Index="222" CID="784" Value="Émirats arabes unis" StdVal="Émiratsarabesunis" Lang="fr" IsLead="1" IsStd="1" Ver="1">784</CName>
<CName Index="223" CID="788" Value="Tunesien" StdVal="Tunesien" Lang="de" IsLead="1" IsStd="1" Ver="1">786</CName>
<CName Index="223" CID="788" Value="Tunisie" StdVal="Tunisie" Lang="fr" IsLead="1" IsStd="1" Ver="1">789</CName>
<CName Index="224" CID="792" Value="Türkei" StdVal="Türkei" Lang="de" IsLead="1" IsStd="1" Ver="1">790</CName>
<CName Index="224" CID="792" Value="Turquie" StdVal="Turquie" Lang="fr" IsLead="1" IsStd="1" Ver="1">793</CName>
<CName Index="224" CID="792" Value="Türkiye" StdVal="Türkiye" Lang="tr" IsLead="1" IsStd="1" Ver="1">794</CName>
<CName Index="226" CID="796" Value="Turks- und Caicosinseln" StdVal="TurksundCaicosinseln" Lang="de" IsLead="1" IsStd="1" Ver="1">798</CName>
<CName Index="226" CID="796" Value="Îles Turks et Caïques" StdVal="ÎlesTurksetCaïques" Lang="fr" IsLead="1" IsStd="1" Ver="1">801</CName>
<CName Index="228" CID="800" Value="Ouganda" StdVal="Ouganda" Lang="fr" IsLead="1" IsStd="1" Ver="1">804</CName>
<CName Index="230" CID="807" Value="Mazedonien" StdVal="Mazedonien" Lang="de" IsLead="1" IsStd="1" Ver="1">808</CName>
<CName Index="230" CID="807" Value="Macédoine" StdVal="Macédoine" Lang="fr" IsLead="1" IsStd="1" Ver="1">812</CName>
<CName Index="231" CID="818" Value="Ägypten" StdVal="Ägypten" Lang="de" IsLead="1" IsStd="1" Ver="1">815</CName>
<CName Index="231" CID="818" Value="Égypte" StdVal="Égypte" Lang="fr" IsLead="1" IsStd="1" Ver="1">818</CName>
<CName Index="232" CID="826" Value="Vereinigtes Königreich" StdVal="VereinigtesKönigreich" Lang="de" IsLead="1" IsStd="1" Ver="1">819</CName>
<CName Index="232" CID="826" Value="Royaume-Uni" StdVal="RoyaumeUni" Lang="fr" IsLead="1" IsStd="1" Ver="1">829</CName>
<CName Index="233" CID="831" Value="Guernesey" StdVal="Guernesey" Lang="fr" IsLead="1" IsStd="1" Ver="1">831</CName>
<CName Index="235" CID="833" Value="Île de Man" StdVal="ÎledeMan" Lang="fr" IsLead="1" IsStd="1" Ver="1">835</CName>
<CName Index="236" CID="834" Value="Tansania" StdVal="Tansania" Lang="de" IsLead="1" IsStd="1" Ver="1">836</CName>
<CName Index="236" CID="834" Value="Tanzanie" StdVal="Tanzanie" Lang="fr" IsLead="1" IsStd="1" Ver="1">839</CName>
<CName Index="237" CID="840" Value="Vereinigte Staaten" StdVal="VereinigteStaaten" Lang="de" IsLead="1" IsStd="1" Ver="1">840</CName>
<CName Index="237" CID="840" Value="États-Unis" StdVal="ÉtatsUnis" Lang="fr" IsLead="1" IsStd="1" Ver="1">846</CName>
<CName Index="238" CID="850" Value="Amerikanische Jungferninseln" StdVal="AmerikanischeJungferninseln" Lang="de" IsLead="1" IsStd="1" Ver="1">847</CName>
<CName Index="238" CID="850" Value="Îles Vierges des États-Unis" StdVal="ÎlesViergesdesÉtatsUnis" Lang="fr" IsLead="1" IsStd="1" Ver="1">853</CName>
<CName Index="239" CID="854" Value="Burkina" StdVal="Burkina" Lang="fr" IsLead="1" IsStd="1" Ver="1">855</CName>
<CName Index="241" CID="860" Value="Usbekistan" StdVal="Usbekistan" Lang="de" IsLead="1" IsStd="1" Ver="1">857</CName>
<CName Index="241" CID="860" Value="Ouzbékistan" StdVal="Ouzbékistan" Lang="fr" IsLead="1" IsStd="1" Ver="1">860</CName>
<CName Index="242" CID="862" Value="Vénézuela" StdVal="Vénézuela" Lang="fr" IsLead="1" IsStd="1" Ver="1">863</CName>
<CName Index="243" CID="876" Value="Wallis und Futuna" StdVal="WallisundFutuna" Lang="de" IsLead="1" IsStd="1" Ver="1">864</CName>
<CName Index="243" CID="876" Value="Wallis-et-Futuna" StdVal="WallisetFutuna" Lang="fr" IsLead="0" IsStd="1" Ver="1">867</CName>
<CName Index="243" CID="876" Value="Wallis et Futuna" StdVal="WallisetFutuna" Lang="fr" IsLead="1" IsStd="1" Ver="1">868</CName>
<CName Index="245" CID="887" Value="Jemen" StdVal="Jemen" Lang="de" IsLead="1" IsStd="1" Ver="1">871</CName>
<CName Index="245" CID="887" Value="Yémen" StdVal="Yémen" Lang="fr" IsLead="1" IsStd="1" Ver="1">873</CName>
<CName Index="246" CID="894" Value="Sambia" StdVal="Sambia" Lang="de" IsLead="1" IsStd="1" Ver="1">874</CName>
<CName Index="246" CID="894" Value="Zambie" StdVal="Zambie" Lang="fr" IsLead="1" IsStd="1" Ver="1">876</CName>
</CNameSets>
