<?xml version="1.0" encoding="UTF-8"?>
<Countries xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<Country CName="ZZZ-Version" ISO2="ZZ" ISO3="ZZZ" Region="ZZ" Status="Version" PFormat="None" PUsage="Not Used" Ver="1">000</Country>
<Country CName="Afghanistan" ISO2="AF" ISO3="AFG" Region="AS" Status="Active" PFormat="Full" PUsage="Not Provided" Lang="" Ver="1">004</Country>
<Country CName="Albania" ISO2="AL" ISO3="ALB" Region="EU" Status="Active" PFormat="Full" PUsage="Required" Lang="sq" Ver="1">008</Country>
<Country CName="Antarctica" ISO2="AQ" ISO3="ATA" Region="AN" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">010</Country>
<Country CName="Algeria" ISO2="DZ" ISO3="DZA" Region="AF" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">012</Country>
<Country CName="American Samoa" ISO2="AS" ISO3="ASM" Region="OC" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">016</Country>
<Country CName="Andorra" ISO2="AD" ISO3="AND" Region="EU" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">020</Country>
<Country CName="Angola" ISO2="AO" ISO3="AGO" Region="AF" Status="Active" PFormat="Full" PUsage="Not Provided" Lang="" Ver="1">024</Country>
<Country CName="Antigua and Barbuda" ISO2="AG" ISO3="ATG" Region="CRB" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">028</Country>
<Country CName="Azerbaijan" ISO2="AZ" ISO3="AZE" Region="AS" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">031</Country>
<Country CName="Argentina" ISO2="AR" ISO3="ARG" Region="SA" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">032</Country>
<Country CName="Australia" ISO2="AU" ISO3="AUS" Region="AU" Status="Active" PFormat="Short" PUsage="Required" Lang="en" Ver="1">036</Country>
<Country CName="Austria" ISO2="AT" ISO3="AUT" Region="EU" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">040</Country>
<Country CName="Bahamas" ISO2="BS" ISO3="BHS" Region="CRB" Status="Active" PFormat="Full" PUsage="Not Provided" Lang="" Ver="1">044</Country>
<Country CName="Bahrain" ISO2="BH" ISO3="BHR" Region="AS" Status="Active" PFormat="Full" PUsage="Not Provided" Lang="" Ver="1">048</Country>
<Country CName="Bangladesh" ISO2="BD" ISO3="BGD" Region="AS" Status="Active" PFormat="Full" PUsage="Not Provided" Lang="" Ver="1">050</Country>
<Country CName="Armenia" ISO2="AM" ISO3="ARM" Region="AS" Status="Active" PFormat="Full" PUsage="Not Provided" Lang="" Ver="1">051</Country>
<Country CName="Barbados" ISO2="BB" ISO3="BRB" Region="CRB" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">052</Country>
<Country CName="Belgium" ISO2="BE" ISO3="BEL" Region="EU" Status="Active" PFormat="Full" PUsage="Optional" Lang="fr" Ver="1">056</Country>
<Country CName="Bermuda" ISO2="BM" ISO3="BMU" Region="CRB" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">060</Country>
<Country CName="Bhutan" ISO2="BT" ISO3="BTN" Region="AS" Status="Active" PFormat="Full" PUsage="Not Provided" Lang="" Ver="1">064</Country>
<Country CName="Bolivia" ISO2="BO" ISO3="BOL" Region="SA" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">068</Country>
<Country CName="Bosnia and Herzegovina" ISO2="BA" ISO3="BIH" Region="EU" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">070</Country>
<Country CName="Botswana" ISO2="BW" ISO3="BWA" Region="AF" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">072</Country>
<Country CName="Bouvet Island" ISO2="BV" ISO3="BVT" Region="AN" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">074</Country>
<Country CName="Brazil" ISO2="BR" ISO3="BRA" Region="SA" Status="Active" PFormat="Short" PUsage="Required" Lang="pt" Ver="1">076</Country>
<Country CName="Belize" ISO2="BZ" ISO3="BLZ" Region="CA" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">084</Country>
<Country CName="British Indian Ocean Territory" ISO2="IO" ISO3="IOT" Region="AS" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">086</Country>
<Country CName="Solomon Islands" ISO2="SB" ISO3="SLB" Region="OC" Status="Active" PFormat="Full" PUsage="Not Provided" Lang="" Ver="1">090</Country>
<Country CName="British Virgin Islands" ISO2="VG" ISO3="VGB" Region="CRB" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">092</Country>
<Country CName="Brunei Darussalam" ISO2="BN" ISO3="BRN" Region="AS" Status="Active" PFormat="Full" PUsage="Not Provided" Lang="" Ver="1">096</Country>
<Country CName="Bulgaria" ISO2="BG" ISO3="BGR" Region="EU" Status="Active" PFormat="Full" PUsage="Required" Lang="bg" Ver="1">100</Country>
<Country CName="Myanmar" ISO2="MM" ISO3="MMR" Region="AS" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">104</Country>
<Country CName="Burundi" ISO2="BI" ISO3="BDI" Region="AF" Status="Active" PFormat="Full" PUsage="Not Provided" Lang="" Ver="1">108</Country>
<Country CName="Belarus" ISO2="BY" ISO3="BLR" Region="EU" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">112</Country>
<Country CName="Cambodia" ISO2="KH" ISO3="KHM" Region="AS" Status="Active" PFormat="Full" PUsage="Not Provided" Lang="" Ver="1">116</Country>
<Country CName="Cameroon" ISO2="CM" ISO3="CMR" Region="AF" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">120</Country>
<Country CName="Canada" ISO2="CA" ISO3="CAN" Region="NA" Status="Active" PFormat="Short" PUsage="Required" Lang="en" Ver="1">124</Country>
<Country CName="Cape Verde" ISO2="CV" ISO3="CPV" Region="AF" Status="Active" PFormat="Full" PUsage="Not Provided" Lang="" Ver="1">132</Country>
<Country CName="Cayman Islands" ISO2="KY" ISO3="CYM" Region="CRB" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">136</Country>
<Country CName="Central African Republic" ISO2="CF" ISO3="CAF" Region="AF" Status="Active" PFormat="Full" PUsage="Not Provided" Lang="" Ver="1">140</Country>
<Country CName="Sri Lanka" ISO2="LK" ISO3="LKA" Region="AS" Status="Active" PFormat="Full" PUsage="Not Provided" Lang="" Ver="1">144</Country>
<Country CName="Chad" ISO2="TD" ISO3="TCD" Region="AF" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">148</Country>
<Country CName="Chile" ISO2="CL" ISO3="CHL" Region="SA" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">152</Country>
<Country CName="China" ISO2="CN" ISO3="CHN" Region="AS" Status="Active" PFormat="Full" PUsage="Required" Lang="zh" Ver="1">156</Country>
<Country CName="Taiwan" ISO2="TW" ISO3="TWN" Region="AS" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">158</Country>
<Country CName="Christmas Island" ISO2="CX" ISO3="CXR" Region="AS" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">162</Country>
<Country CName="Cocos (Keeling) Islands" ISO2="CC" ISO3="CCK" Region="AS" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">166</Country>
<Country CName="Colombia" ISO2="CO" ISO3="COL" Region="SA" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">170</Country>
<Country CName="Comoros" ISO2="KM" ISO3="COM" Region="AF" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">174</Country>
<Country CName="Mayotte" ISO2="YT" ISO3="MYT" Region="AF" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">175</Country>
<Country CName="Congo" ISO2="CG" ISO3="COG" Region="AF" Status="Active" PFormat="Full" PUsage="Not Provided" Lang="" Ver="1">178</Country>
<Country CName="Democratic Republic of Congo" ISO2="CD" ISO3="COD" Region="AF" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">180</Country>
<Country CName="Cook Islands" ISO2="CK" ISO3="COK" Region="OC" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">184</Country>
<Country CName="Costa Rica" ISO2="CR" ISO3="CRI" Region="CA" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">188</Country>
<Country CName="Croatia" ISO2="HR" ISO3="HRV" Region="EU" Status="Active" PFormat="Full" PUsage="Required" Lang="hr" Ver="1">191</Country>
<Country CName="Cuba" ISO2="CU" ISO3="CUB" Region="CRB" Status="Active" PFormat="Full" PUsage="Not Provided" Lang="" Ver="1">192</Country>
<Country CName="Cyprus" ISO2="CY" ISO3="CYP" Region="AS" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">196</Country>
<Country CName="Czech Republic" ISO2="CZ" ISO3="CZE" Region="EU" Status="Active" PFormat="Full" PUsage="Optional" Lang="cs" Ver="1">203</Country>
<Country CName="Benin" ISO2="BJ" ISO3="BEN" Region="AF" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">204</Country>
<Country CName="Denmark" ISO2="DK" ISO3="DNK" Region="EU" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">208</Country>
<Country CName="Dominica" ISO2="DM" ISO3="DMA" Region="CRB" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">212</Country>
<Country CName="Dominican Republic" ISO2="DO" ISO3="DOM" Region="CRB" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">214</Country>
<Country CName="Ecuador" ISO2="EC" ISO3="ECU" Region="SA" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">218</Country>
<Country CName="El Salvador" ISO2="SV" ISO3="SLV" Region="CA" Status="Active" PFormat="Full" PUsage="Not Provided" Lang="" Ver="1">222</Country>
<Country CName="Equatorial Guinea" ISO2="GQ" ISO3="GNQ" Region="AF" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">226</Country>
<Country CName="Ethiopia" ISO2="ET" ISO3="ETH" Region="AF" Status="Active" PFormat="Full" PUsage="Not Provided" Lang="" Ver="1">231</Country>
<Country CName="Eritrea" ISO2="ER" ISO3="ERI" Region="AF" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">232</Country>
<Country CName="Estonia" ISO2="EE" ISO3="EST" Region="EU" Status="Active" PFormat="Full" PUsage="Required" Lang="et" Ver="1">233</Country>
<Country CName="Faeroe Islands" ISO2="FO" ISO3="FRO" Region="EU" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">234</Country>
<Country CName="Falkland Islands" ISO2="FK" ISO3="FLK" Region="SA" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">238</Country>
<Country CName="South Georgia and South Sandwich Islands" ISO2="GS" ISO3="SGS" Region="AN" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">239</Country>
<Country CName="Fiji" ISO2="FJ" ISO3="FJI" Region="OC" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">242</Country>
<Country CName="Finland" ISO2="FI" ISO3="FIN" Region="EU" Status="Active" PFormat="Full" PUsage="Optional" Lang="fi" Ver="1">246</Country>
<Country CName="Åland Islands" ISO2="AX" ISO3="ALA" Region="EU" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">248</Country>
<Country CName="France" ISO2="FR" ISO3="FRA" Region="EU" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">250</Country>
<Country CName="French Guiana" ISO2="GF" ISO3="GUF" Region="SA" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">254</Country>
<Country CName="French Polynesia" ISO2="PF" ISO3="PYF" Region="OC" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">258</Country>
<Country CName="French Southern Territories" ISO2="TF" ISO3="ATF" Region="AN" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">260</Country>
<Country CName="Djibouti" ISO2="DJ" ISO3="DJI" Region="AF" Status="Active" PFormat="Full" PUsage="Not Provided" Lang="" Ver="1">262</Country>
<Country CName="Gabon" ISO2="GA" ISO3="GAB" Region="AF" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">266</Country>
<Country CName="Georgia" ISO2="GE" ISO3="GEO" Region="AS" Status="Active" PFormat="Full" PUsage="Not Used" Lang="" Ver="1">268</Country>
<Country CName="Gambia" ISO2="GM" ISO3="GMB" Region="AF" Status="Active" PFormat="Full" PUsage="Not Provided" Lang="" Ver="1">270</Country>
<Country CName="Palestinian Territory, Occupied" ISO2="PS" ISO3="PSE" Region="AS" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">275</Country>
<Country CName="Germany" ISO2="DE" ISO3="DEU" Region="EU" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">276</Country>
<Country CName="Ghana" ISO2="GH" ISO3="GHA" Region="AF" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">288</Country>
<Country CName="Gibraltar" ISO2="GI" ISO3="GIB" Region="EU" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">292</Country>
<Country CName="Kiribati" ISO2="KI" ISO3="KIR" Region="OC" Status="Active" PFormat="Full" PUsage="Not Provided" Lang="" Ver="1">296</Country>
<Country CName="Greece" ISO2="GR" ISO3="GRC" Region="EU" Status="Active" PFormat="Full" PUsage="Optional" Lang="el" Ver="1">300</Country>
<Country CName="Greenland" ISO2="GL" ISO3="GRL" Region="NA" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">304</Country>
<Country CName="Grenada" ISO2="GD" ISO3="GRD" Region="CRB" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">308</Country>
<Country CName="Guadeloupe" ISO2="GP" ISO3="GLP" Region="CRB" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">312</Country>
<Country CName="Guam" ISO2="GU" ISO3="GUM" Region="OC" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">316</Country>
<Country CName="Guatemala" ISO2="GT" ISO3="GTM" Region="CA" Status="Active" PFormat="Full" PUsage="Not Provided" Lang="" Ver="1">320</Country>
<Country CName="Guinea" ISO2="GN" ISO3="GIN" Region="AF" Status="Active" PFormat="Full" PUsage="Not Provided" Lang="" Ver="1">324</Country>
<Country CName="Guyana" ISO2="GY" ISO3="GUY" Region="SA" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">328</Country>
<Country CName="Haiti" ISO2="HT" ISO3="HTI" Region="CRB" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">332</Country>
<Country CName="Heard Island and McDonald Islands" ISO2="HM" ISO3="HMD" Region="AN" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">334</Country>
<Country CName="Vatican" ISO2="VA" ISO3="VAT" Region="EU" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">336</Country>
<Country CName="Honduras" ISO2="HN" ISO3="HND" Region="CA" Status="Active" PFormat="Full" PUsage="Not Provided" Lang="" Ver="1">340</Country>
<Country CName="Hong Kong" ISO2="HK" ISO3="HKG" Region="AS" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">344</Country>
<Country CName="Hungary" ISO2="HU" ISO3="HUN" Region="EU" Status="Active" PFormat="Full" PUsage="Required" Lang="hu" Ver="1">348</Country>
<Country CName="Iceland" ISO2="IS" ISO3="ISL" Region="EU" Status="Active" PFormat="Full" PUsage="Required" Lang="is" Ver="1">352</Country>
<Country CName="India" ISO2="IN" ISO3="IND" Region="AS" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">356</Country>
<Country CName="Indonesia" ISO2="ID" ISO3="IDN" Region="AS" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">360</Country>
<Country CName="Iran" ISO2="IR" ISO3="IRN" Region="AS" Status="Active" PFormat="Full" PUsage="Not Provided" Lang="" Ver="1">364</Country>
<Country CName="Iraq" ISO2="IQ" ISO3="IRQ" Region="AS" Status="Active" PFormat="Full" PUsage="Not Provided" Lang="" Ver="1">368</Country>
<Country CName="Ireland" ISO2="IE" ISO3="IRL" Region="EU" Status="Active" PFormat="Full" PUsage="Required" Lang="en" Ver="1">372</Country>
<Country CName="Israel" ISO2="IL" ISO3="ISR" Region="AS" Status="Active" PFormat="Full" PUsage="Optional" Lang="he" Ver="1">376</Country>
<Country CName="Italy" ISO2="IT" ISO3="ITA" Region="EU" Status="Active" PFormat="Short" PUsage="Required" Lang="it" Ver="1">380</Country>
<Country CName="Côte d'Ivoire" ISO2="CI" ISO3="CIV" Region="AF" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">384</Country>
<Country CName="Jamaica" ISO2="JM" ISO3="JAM" Region="CRB" Status="Active" PFormat="Full" PUsage="Not Provided" Lang="" Ver="1">388</Country>
<Country CName="Japan" ISO2="JP" ISO3="JPN" Region="AS" Status="Active" PFormat="Full" PUsage="Required" Lang="ja" Ver="1">392</Country>
<Country CName="Kazakhstan" ISO2="KZ" ISO3="KAZ" Region="AS" Status="Active" PFormat="Full" PUsage="Not Provided" Lang="" Ver="1">398</Country>
<Country CName="Jordan" ISO2="JO" ISO3="JOR" Region="AS" Status="Active" PFormat="Full" PUsage="Not Provided" Lang="" Ver="1">400</Country>
<Country CName="Kenya" ISO2="KE" ISO3="KEN" Region="AF" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">404</Country>
<Country CName="North Korea" ISO2="KP" ISO3="PRK" Region="AS" Status="Active" PFormat="Full" PUsage="Not Provided" Lang="" Ver="1">408</Country>
<Country CName="South Korea" ISO2="KR" ISO3="KOR" Region="AS" Status="Active" PFormat="Full" PUsage="Not Provided" Lang="" Ver="1">410</Country>
<Country CName="Kuwait" ISO2="KW" ISO3="KWT" Region="AS" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">414</Country>
<Country CName="Kyrgyzstan" ISO2="KG" ISO3="KGZ" Region="AS" Status="Active" PFormat="Full" PUsage="Not Provided" Lang="" Ver="1">417</Country>
<Country CName="Laos" ISO2="LA" ISO3="LAO" Region="AS" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">418</Country>
<Country CName="Lebanon" ISO2="LB" ISO3="LBN" Region="AS" Status="Active" PFormat="Full" PUsage="Not Used" Lang="" Ver="1">422</Country>
<Country CName="Lesotho" ISO2="LS" ISO3="LSO" Region="AF" Status="Active" PFormat="Full" PUsage="Not Provided" Lang="" Ver="1">426</Country>
<Country CName="Latvia" ISO2="LV" ISO3="LVA" Region="EU" Status="Active" PFormat="Full" PUsage="Required" Lang="lv" Ver="1">428</Country>
<Country CName="Liberia" ISO2="LR" ISO3="LBR" Region="AF" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">430</Country>
<Country CName="Libya" ISO2="LY" ISO3="LBY" Region="AF" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">434</Country>
<Country CName="Liechtenstein" ISO2="LI" ISO3="LIE" Region="EU" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">438</Country>
<Country CName="Lithuania" ISO2="LT" ISO3="LTU" Region="EU" Status="Active" PFormat="Full" PUsage="Required" Lang="lt" Ver="1">440</Country>
<Country CName="Luxembourg" ISO2="LU" ISO3="LUX" Region="EU" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">442</Country>
<Country CName="Macau" ISO2="MO" ISO3="MAC" Region="AS" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">446</Country>
<Country CName="Madagascar" ISO2="MG" ISO3="MDG" Region="AF" Status="Active" PFormat="Full" PUsage="Not Provided" Lang="" Ver="1">450</Country>
<Country CName="Malawi" ISO2="MW" ISO3="MWI" Region="AF" Status="Active" PFormat="Full" PUsage="Not Provided" Lang="" Ver="1">454</Country>
<Country CName="Malaysia" ISO2="MY" ISO3="MYS" Region="AS" Status="Active" PFormat="Full" PUsage="Not Provided" Lang="" Ver="1">458</Country>
<Country CName="Maldives" ISO2="MV" ISO3="MDV" Region="AS" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">462</Country>
<Country CName="Mali" ISO2="ML" ISO3="MLI" Region="AF" Status="Active" PFormat="Full" PUsage="Not Provided" Lang="" Ver="1">466</Country>
<Country CName="Malta" ISO2="MT" ISO3="MLT" Region="EU" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">470</Country>
<Country CName="Martinique" ISO2="MQ" ISO3="MTQ" Region="CRB" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">474</Country>
<Country CName="Mauritania" ISO2="MR" ISO3="MRT" Region="AF" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">478</Country>
<Country CName="Mauritius" ISO2="MU" ISO3="MUS" Region="AF" Status="Active" PFormat="Full" PUsage="Not Provided" Lang="" Ver="1">480</Country>
<Country CName="Mexico" ISO2="MX" ISO3="MEX" Region="NA" Status="Active" PFormat="Short" PUsage="Required" Lang="es" Ver="1">484</Country>
<Country CName="Monaco" ISO2="MC" ISO3="MCO" Region="EU" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">492</Country>
<Country CName="Mongolia" ISO2="MN" ISO3="MNG" Region="AS" Status="Active" PFormat="Full" PUsage="Not Provided" Lang="" Ver="1">496</Country>
<Country CName="Moldova" ISO2="MD" ISO3="MDA" Region="EU" Status="Active" PFormat="Full" PUsage="Required" Lang="ro" Ver="1">498</Country>
<Country CName="Montenegro" ISO2="ME" ISO3="MNE" Region="EU" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">499</Country>
<Country CName="Montserrat" ISO2="MS" ISO3="MSR" Region="CRB" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">500</Country>
<Country CName="Morocco" ISO2="MA" ISO3="MAR" Region="AF" Status="Active" PFormat="Full" PUsage="Not Provided" Lang="" Ver="1">504</Country>
<Country CName="Mozambique" ISO2="MZ" ISO3="MOZ" Region="AF" Status="Active" PFormat="Full" PUsage="Not Provided" Lang="" Ver="1">508</Country>
<Country CName="Oman" ISO2="OM" ISO3="OMN" Region="AS" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">512</Country>
<Country CName="Namibia" ISO2="NA" ISO3="NAM" Region="AF" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">516</Country>
<Country CName="Nauru" ISO2="NR" ISO3="NRU" Region="OC" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">520</Country>
<Country CName="Nepal" ISO2="NP" ISO3="NPL" Region="AS" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">524</Country>
<Country CName="Netherlands" ISO2="NL" ISO3="NLD" Region="EU" Status="Active" PFormat="Full" PUsage="Optional" Lang="nl" Ver="1">528</Country>
<Country CName="Netherlands Antilles" ISO2="AN" ISO3="ANT" Region="CRB" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">530</Country>
<Country CName="Aruba" ISO2="AW" ISO3="ABW" Region="CRB" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">533</Country>
<Country CName="New Caledonia" ISO2="NC" ISO3="NCL" Region="OC" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">540</Country>
<Country CName="Vanuatu" ISO2="VU" ISO3="VUT" Region="OC" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">548</Country>
<Country CName="New Zealand" ISO2="NZ" ISO3="NZL" Region="AU" Status="Active" PFormat="Full" PUsage="Required" Lang="en" Ver="1">554</Country>
<Country CName="Nicaragua" ISO2="NI" ISO3="NIC" Region="CA" Status="Active" PFormat="Full" PUsage="Not Provided" Lang="" Ver="1">558</Country>
<Country CName="Niger" ISO2="NE" ISO3="NER" Region="AF" Status="Active" PFormat="Full" PUsage="Not Provided" Lang="" Ver="1">562</Country>
<Country CName="Nigeria" ISO2="NG" ISO3="NGA" Region="AF" Status="Active" PFormat="Full" PUsage="Not Provided" Lang="" Ver="1">566</Country>
<Country CName="Niue" ISO2="NU" ISO3="NIU" Region="OC" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">570</Country>
<Country CName="Norfolk Island" ISO2="NF" ISO3="NFK" Region="OC" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">574</Country>
<Country CName="Norway" ISO2="NO" ISO3="NOR" Region="EU" Status="Active" PFormat="Full" PUsage="Optional" Lang="nb" Ver="1">578</Country>
<Country CName="Northern Mariana Islands" ISO2="MP" ISO3="MNP" Region="OC" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">580</Country>
<Country CName="United States Minor Outlying Islands" ISO2="UM" ISO3="UMI" Region="OC" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">581</Country>
<Country CName="Micronesia (Federated States of)" ISO2="FM" ISO3="FSM" Region="OC" Status="Active" PFormat="Full" PUsage="Not Provided" Lang="" Ver="1">583</Country>
<Country CName="Marshall Islands" ISO2="MH" ISO3="MHL" Region="OC" Status="Active" PFormat="Full" PUsage="Not Provided" Lang="" Ver="1">584</Country>
<Country CName="Palau" ISO2="PW" ISO3="PLW" Region="OC" Status="Active" PFormat="Short" PUsage="Not Used" Lang="" Ver="1">585</Country>
<Country CName="Pakistan" ISO2="PK" ISO3="PAK" Region="AS" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">586</Country>
<Country CName="Panama" ISO2="PA" ISO3="PAN" Region="CA" Status="Active" PFormat="Full" PUsage="Not Provided" Lang="" Ver="1">591</Country>
<Country CName="Papua New Guinea" ISO2="PG" ISO3="PNG" Region="OC" Status="Active" PFormat="Short" PUsage="Not Provided" Lang="" Ver="1">598</Country>
<Country CName="Paraguay" ISO2="PY" ISO3="PRY" Region="SA" Status="Active" PFormat="Full" PUsage="Optional" Lang="es" Ver="1">600</Country>
<Country CName="Peru" ISO2="PE" ISO3="PER" Region="SA" Status="Active" PFormat="Full" PUsage="Required" Lang="es" Ver="1">604</Country>
<Country CName="Philippines" ISO2="PH" ISO3="PHL" Region="AS" Status="Active" PFormat="Full" PUsage="Not Provided" Lang="" Ver="1">608</Country>
<Country CName="Pitcairn" ISO2="PN" ISO3="PCN" Region="OC" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">612</Country>
<Country CName="Poland" ISO2="PL" ISO3="POL" Region="EU" Status="Active" PFormat="Full" PUsage="Required" Lang="pl" Ver="1">616</Country>
<Country CName="Portugal" ISO2="PT" ISO3="PRT" Region="EU" Status="Active" PFormat="Full" PUsage="Required" Lang="pt" Ver="1">620</Country>
<Country CName="Guinea-Bissau" ISO2="GW" ISO3="GNB" Region="AF" Status="Active" PFormat="Full" PUsage="Not Provided" Lang="" Ver="1">624</Country>
<Country CName="Timor-Leste" ISO2="TL" ISO3="TLS" Region="AS" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">626</Country>
<Country CName="Puerto Rico" ISO2="PR" ISO3="PRI" Region="CRB" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">630</Country>
<Country CName="Qatar" ISO2="QA" ISO3="QAT" Region="AS" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">634</Country>
<Country CName="Réunion" ISO2="RE" ISO3="REU" Region="AF" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">638</Country>
<Country CName="Romania" ISO2="RO" ISO3="ROU" Region="EU" Status="Active" PFormat="Full" PUsage="Required" Lang="ro" Ver="1">642</Country>
<Country CName="Russia" ISO2="RU" ISO3="RUS" Region="EU" Status="Active" PFormat="Full" PUsage="Required" Lang="en" Ver="1">643</Country>
<Country CName="Rwanda" ISO2="RW" ISO3="RWA" Region="AF" Status="Active" PFormat="Full" PUsage="Not Provided" Lang="" Ver="1">646</Country>
<Country CName="Saint Barthélemy" ISO2="BL" ISO3="BLM" Region="CRB" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">652</Country>
<Country CName="Saint Helena" ISO2="SH" ISO3="SHN" Region="AF" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">654</Country>
<Country CName="Saint Kitts and Nevis" ISO2="KN" ISO3="KNA" Region="CRB" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">659</Country>
<Country CName="Anguilla" ISO2="AI" ISO3="AIA" Region="CRB" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">660</Country>
<Country CName="St. Lucia" ISO2="LC" ISO3="LCA" Region="CRB" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">662</Country>
<Country CName="Saint Martin (French Part)" ISO2="MF" ISO3="MAF" Region="CRB" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">663</Country>
<Country CName="Saint Pierre and Miquelon" ISO2="PM" ISO3="SPM" Region="CRB" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">666</Country>
<Country CName="Saint Vincent and the Grenadines" ISO2="VC" ISO3="VCT" Region="CRB" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">670</Country>
<Country CName="San Marino" ISO2="SM" ISO3="SMR" Region="EU" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">674</Country>
<Country CName="Sao Tome and Principe" ISO2="ST" ISO3="STP" Region="AF" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">678</Country>
<Country CName="Saudi Arabia" ISO2="SA" ISO3="SAU" Region="AS" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">682</Country>
<Country CName="Senegal" ISO2="SN" ISO3="SEN" Region="AF" Status="Active" PFormat="Full" PUsage="Not Provided" Lang="" Ver="1">686</Country>
<Country CName="Serbia" ISO2="RS" ISO3="SRB" Region="EU" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">688</Country>
<Country CName="Seychelles" ISO2="SC" ISO3="SYC" Region="AF" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">690</Country>
<Country CName="Sierra Leone" ISO2="SL" ISO3="SLE" Region="AF" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">694</Country>
<Country CName="Singapore" ISO2="SG" ISO3="SGP" Region="AS" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">702</Country>
<Country CName="Slovakia" ISO2="SK" ISO3="SVK" Region="EU" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">703</Country>
<Country CName="Vietnam" ISO2="VN" ISO3="VNM" Region="AS" Status="Active" PFormat="Full" PUsage="Not Provided" Lang="" Ver="1">704</Country>
<Country CName="Slovenia" ISO2="SI" ISO3="SVN" Region="EU" Status="Active" PFormat="Full" PUsage="Required" Lang="sl" Ver="1">705</Country>
<Country CName="Somalia" ISO2="SO" ISO3="SOM" Region="AF" Status="Active" PFormat="Short" PUsage="Not Provided" Lang="" Ver="1">706</Country>
<Country CName="South Africa" ISO2="ZA" ISO3="ZAF" Region="AF" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">710</Country>
<Country CName="Zimbabwe" ISO2="ZW" ISO3="ZWE" Region="AF" Status="Active" PFormat="Full" PUsage="Not Provided" Lang="" Ver="1">716</Country>
<Country CName="Spain" ISO2="ES" ISO3="ESP" Region="EU" Status="Active" PFormat="Full" PUsage="Required" Lang="es" Ver="1">724</Country>
<Country CName="Western Sahara" ISO2="EH" ISO3="ESH" Region="AF" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">732</Country>
<Country CName="Sudan" ISO2="SD" ISO3="SDN" Region="AF" Status="Active" PFormat="Full" PUsage="Not Used" Lang="" Ver="1">736</Country>
<Country CName="Suriname" ISO2="SR" ISO3="SUR" Region="SA" Status="Active" PFormat="Full" PUsage="Not Provided" Lang="" Ver="1">740</Country>
<Country CName="Svalbard and Jan Mayen" ISO2="SJ" ISO3="SJM" Region="EU" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">744</Country>
<Country CName="Swaziland" ISO2="SZ" ISO3="SWZ" Region="AF" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">748</Country>
<Country CName="Sweden" ISO2="SE" ISO3="SWE" Region="EU" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">752</Country>
<Country CName="Switzerland" ISO2="CH" ISO3="CHE" Region="EU" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">756</Country>
<Country CName="Syria" ISO2="SY" ISO3="SYR" Region="AS" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">760</Country>
<Country CName="Tajikistan" ISO2="TJ" ISO3="TJK" Region="AS" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">762</Country>
<Country CName="Thailand" ISO2="TH" ISO3="THA" Region="AS" Status="Active" PFormat="Full" PUsage="Not Provided" Lang="" Ver="1">764</Country>
<Country CName="Togo" ISO2="TG" ISO3="TGO" Region="AF" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">768</Country>
<Country CName="Tokelau" ISO2="TK" ISO3="TKL" Region="OC" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">772</Country>
<Country CName="Tonga" ISO2="TO" ISO3="TON" Region="OC" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">776</Country>
<Country CName="Trinidad and Tobago" ISO2="TT" ISO3="TTO" Region="CRB" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">780</Country>
<Country CName="United Arab Emirates" ISO2="AE" ISO3="ARE" Region="AS" Status="Active" PFormat="Full" PUsage="Required" Lang="en" Ver="1">784</Country>
<Country CName="Tunisia" ISO2="TN" ISO3="TUN" Region="AF" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">788</Country>
<Country CName="Turkey" ISO2="TR" ISO3="TUR" Region="AS" Status="Active" PFormat="Full" PUsage="Required" Lang="tr" Ver="1">792</Country>
<Country CName="Turkmenistan" ISO2="TM" ISO3="TKM" Region="AS" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">795</Country>
<Country CName="Turks and Caicos Islands" ISO2="TC" ISO3="TCA" Region="CRB" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">796</Country>
<Country CName="Tuvalu" ISO2="TV" ISO3="TUV" Region="OC" Status="Active" PFormat="Full" PUsage="Not Used" Lang="" Ver="1">798</Country>
<Country CName="Uganda" ISO2="UG" ISO3="UGA" Region="AF" Status="Active" PFormat="Full" PUsage="Not Used" Lang="" Ver="1">800</Country>
<Country CName="Ukraine" ISO2="UA" ISO3="UKR" Region="EU" Status="Active" PFormat="Full" PUsage="Required" Lang="en" Ver="1">804</Country>
<Country CName="Macedonia" ISO2="MK" ISO3="MKD" Region="EU" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">807</Country>
<Country CName="Egypt" ISO2="EG" ISO3="EGY" Region="AF" Status="Active" PFormat="Full" PUsage="Not Provided" Lang="" Ver="1">818</Country>
<Country CName="United Kingdom" ISO2="GB" ISO3="GBR" Region="EU" Status="Active" PFormat="Full" PUsage="Optional" Lang="en" Ver="1">826</Country>
<Country CName="Guernsey" ISO2="GG" ISO3="GGY" Region="EU" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">831</Country>
<Country CName="Jersey" ISO2="JE" ISO3="JEY" Region="EU" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">832</Country>
<Country CName="Isle of Man" ISO2="IM" ISO3="IMN" Region="EU" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">833</Country>
<Country CName="Tanzania" ISO2="TZ" ISO3="TZA" Region="AF" Status="Active" PFormat="Full" PUsage="Not Provided" Lang="" Ver="1">834</Country>
<Country CName="United States of America" ISO2="US" ISO3="USA" Region="NA" Status="Active" PFormat="Short" PUsage="Required" Lang="en" Ver="1">840</Country>
<Country CName="U.S. Virgin Islands" ISO2="VI" ISO3="VIR" Region="CRB" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">850</Country>
<Country CName="Burkina Faso" ISO2="BF" ISO3="BFA" Region="AF" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">854</Country>
<Country CName="Uruguay" ISO2="UY" ISO3="URY" Region="SA" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">858</Country>
<Country CName="Uzbekistan" ISO2="UZ" ISO3="UZB" Region="AS" Status="Active" PFormat="Full" PUsage="Not Provided" Lang="" Ver="1">860</Country>
<Country CName="Venezuela" ISO2="VE" ISO3="VEN" Region="SA" Status="Active" PFormat="Full" PUsage="Required" Lang="es" Ver="1">862</Country>
<Country CName="Wallis and Futuna" ISO2="WF" ISO3="WLF" Region="OC" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">876</Country>
<Country CName="Samoa" ISO2="WS" ISO3="WSM" Region="OC" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">882</Country>
<Country CName="Yemen" ISO2="YE" ISO3="YEM" Region="AS" Status="Active" PFormat="Full" PUsage="Not Provided" Lang="" Ver="1">887</Country>
<Country CName="Zambia" ISO2="ZM" ISO3="ZMB" Region="AF" Status="Active" PFormat="None" PUsage="Not Used" Lang="" Ver="1">894</Country>
</Countries>
