<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Provinces xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<PName PID="1240" CID="484" Value="DF" StdVal="DF" Lang="es" Type="Short" IsLead="1" IsStd="1" Ver="2">1830</PName>
<PName PID="1240" CID="484" Value="Distrito Federal" StdVal="DistritoFederal" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="2">1831</PName>
<PName PID="1240" CID="484" Value="Federal District" StdVal="FederalDistrict" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="2">1832</PName>
</Provinces>