<?xml version="1.0" encoding="UTF-8"?>
<Countries xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<Country CName="XXX Country" ISO2="Z1" ISO3="ZZ1" Region="ZZ" Status="Active" PFormat="Full" PUsage="Required" Ver="1">997</Country>
<Country CName="YYY Country" ISO2="Z2" ISO3="ZZ2" Region="ZZ" Status="Active" PFormat="Full" PUsage="Required" Ver="1">998</Country>
<Country CName="ZZZ Country" ISO2="Z3" ISO3="ZZ3" Region="ZZ" Status="Active" PFormat="Full" PUsage="Required" Ver="1">999</Country>
</Countries>
