<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<PNameSets xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<PName PID="37" CID="036" Value="New South Wales" StdVal="NewSouthWales" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">37</PName>
<PName PID="37" CID="036" Value="NSW" StdVal="NSW" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">38</PName>
<PName PID="38" CID="036" Value="QLD" StdVal="QLD" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">39</PName>
<PName PID="38" CID="036" Value="Queensland" StdVal="Queensland" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">40</PName>
<PName PID="39" CID="036" Value="SA" StdVal="SA" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">41</PName>
<PName PID="39" CID="036" Value="South Australia" StdVal="SouthAustralia" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">42</PName>
<PName PID="40" CID="036" Value="TAS" StdVal="TAS" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">43</PName>
<PName PID="40" CID="036" Value="Tasmania" StdVal="Tasmania" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">44</PName>
<PName PID="41" CID="036" Value="VIC" StdVal="VIC" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">45</PName>
<PName PID="41" CID="036" Value="Victoria" StdVal="Victoria" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">46</PName>
<PName PID="42" CID="036" Value="WA" StdVal="WA" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">47</PName>
<PName PID="42" CID="036" Value="Western Australia" StdVal="WesternAustralia" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">48</PName>
<PName PID="81" CID="124" Value="AB" StdVal="AB" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">97</PName>
<PName PID="81" CID="124" Value="Alberta" StdVal="Alberta" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">98</PName>
<PName PID="82" CID="124" Value="BC" StdVal="BC" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">99</PName>
<PName PID="82" CID="124" Value="British Columbia" StdVal="BritishColumbia" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">100</PName>
<PName PID="83" CID="124" Value="Manitoba" StdVal="Manitoba" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">102</PName>
<PName PID="83" CID="124" Value="MB" StdVal="MB" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">103</PName>
<PName PID="84" CID="124" Value="NB" StdVal="NB" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">104</PName>
<PName PID="84" CID="124" Value="New Brunswick" StdVal="NewBrunswick" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">105</PName>
<PName PID="85" CID="124" Value="Newfoundland" StdVal="Newfoundland" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">107</PName>
<PName PID="85" CID="124" Value="NL" StdVal="NL" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">108</PName>
<PName PID="85" CID="124" Value="Newfoundland and Lab" StdVal="NewfoundlandandLab" Lang="en" Type="Full" IsLead="0" IsStd="1" Ver="1">109</PName>
<PName PID="86" CID="124" Value="Nova Scotia" StdVal="NovaScotia" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">112</PName>
<PName PID="86" CID="124" Value="NS" StdVal="NS" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">113</PName>
<PName PID="87" CID="124" Value="ON" StdVal="ON" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">115</PName>
<PName PID="87" CID="124" Value="Ontario" StdVal="Ontario" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">116</PName>
<PName PID="87" CID="124" Value="ONT" StdVal="ONT" Lang="en" Type="Short" IsLead="0" IsStd="1" Ver="1">117</PName>
<PName PID="88" CID="124" Value="PE" StdVal="PE" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">118</PName>
<PName PID="88" CID="124" Value="Prince Edward Island" StdVal="PrinceEdwardIsland" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">119</PName>
<PName PID="88" CID="124" Value="PEI" StdVal="PEI" Lang="en" Type="Short" IsLead="0" IsStd="1" Ver="1">120</PName>
<PName PID="89" CID="124" Value="QC" StdVal="QC" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">123</PName>
<PName PID="89" CID="124" Value="Quebec" StdVal="Quebec" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">124</PName>
<PName PID="89" CID="124" Value="PQ" StdVal="PQ" Lang="en" Type="Short" IsLead="0" IsStd="1" Ver="1">125</PName>
<PName PID="89" CID="124" Value="QUE" StdVal="QUE" Lang="en" Type="Short" IsLead="0" IsStd="1" Ver="1">126</PName>
<PName PID="90" CID="124" Value="Saskatchewan" StdVal="Saskatchewan" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">128</PName>
<PName PID="90" CID="124" Value="SK" StdVal="SK" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">129</PName>
<PName PID="90" CID="124" Value="Saskachewan" StdVal="Saskachewan" Lang="en" Type="Full" IsLead="0" IsStd="1" Ver="1">130</PName>
<PName PID="226" CID="372" Value="Carlow" StdVal="Carlow" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">316</PName>
<PName PID="227" CID="372" Value="Cavan" StdVal="Cavan" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">318</PName>
<PName PID="228" CID="372" Value="Clare" StdVal="Clare" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">320</PName>
<PName PID="229" CID="372" Value="Cork" StdVal="Cork" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">322</PName>
<PName PID="230" CID="372" Value="Donegal" StdVal="Donegal" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">324</PName>
<PName PID="231" CID="372" Value="Dublin" StdVal="Dublin" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">326</PName>
<PName PID="232" CID="372" Value="Galway" StdVal="Galway" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">328</PName>
<PName PID="233" CID="372" Value="Kerry" StdVal="Kerry" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">330</PName>
<PName PID="234" CID="372" Value="Kildare" StdVal="Kildare" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">332</PName>
<PName PID="235" CID="372" Value="Kilkenny" StdVal="Kilkenny" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">334</PName>
<PName PID="236" CID="372" Value="Laois" StdVal="Laois" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">336</PName>
<PName PID="237" CID="372" Value="Leitrim" StdVal="Leitrim" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">337</PName>
<PName PID="238" CID="372" Value="Limerick" StdVal="Limerick" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">339</PName>
<PName PID="239" CID="372" Value="Longford" StdVal="Longford" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">341</PName>
<PName PID="240" CID="372" Value="Louth" StdVal="Louth" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">343</PName>
<PName PID="241" CID="372" Value="Mayo" StdVal="Mayo" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">345</PName>
<PName PID="242" CID="372" Value="Meath" StdVal="Meath" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">347</PName>
<PName PID="243" CID="372" Value="Monaghan" StdVal="Monaghan" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">349</PName>
<PName PID="244" CID="372" Value="Offaly" StdVal="Offaly" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">351</PName>
<PName PID="245" CID="372" Value="Roscommon" StdVal="Roscommon" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">353</PName>
<PName PID="246" CID="372" Value="Sligo" StdVal="Sligo" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">355</PName>
<PName PID="247" CID="372" Value="Tipperary" StdVal="Tipperary" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">357</PName>
<PName PID="248" CID="372" Value="Waterford" StdVal="Waterford" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">359</PName>
<PName PID="249" CID="372" Value="Westmeath" StdVal="Westmeath" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">361</PName>
<PName PID="250" CID="372" Value="Wexford" StdVal="Wexford" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">363</PName>
<PName PID="251" CID="372" Value="Wicklow" StdVal="Wicklow" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">365</PName>
<PName PID="396" CID="484" Value="AGU" StdVal="AGU" Lang="es" Type="Short" IsLead="1" IsStd="1" Ver="1">616</PName>
<PName PID="396" CID="484" Value="Aguascalientes" StdVal="Aguascalientes" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">617</PName>
<PName PID="397" CID="484" Value="Baja California" StdVal="BajaCalifornia" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">618</PName>
<PName PID="397" CID="484" Value="BCN" StdVal="BCN" Lang="es" Type="Short" IsLead="1" IsStd="1" Ver="1">619</PName>
<PName PID="398" CID="484" Value="Baja California Sur" StdVal="BajaCaliforniaSur" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">620</PName>
<PName PID="398" CID="484" Value="BCS" StdVal="BCS" Lang="es" Type="Short" IsLead="1" IsStd="1" Ver="1">621</PName>
<PName PID="399" CID="484" Value="CAM" StdVal="CAM" Lang="es" Type="Short" IsLead="1" IsStd="1" Ver="1">622</PName>
<PName PID="399" CID="484" Value="Campeche" StdVal="Campeche" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">623</PName>
<PName PID="400" CID="484" Value="Chiapas" StdVal="Chiapas" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">624</PName>
<PName PID="400" CID="484" Value="CHP" StdVal="CHP" Lang="es" Type="Short" IsLead="1" IsStd="1" Ver="1">625</PName>
<PName PID="401" CID="484" Value="CHH" StdVal="CHH" Lang="es" Type="Short" IsLead="1" IsStd="1" Ver="1">626</PName>
<PName PID="401" CID="484" Value="Chihuahua" StdVal="Chihuahua" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">627</PName>
<PName PID="402" CID="484" Value="COA" StdVal="COA" Lang="es" Type="Short" IsLead="1" IsStd="1" Ver="1">628</PName>
<PName PID="402" CID="484" Value="Coahuila" StdVal="Coahuila" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">629</PName>
<PName PID="403" CID="484" Value="COL" StdVal="COL" Lang="es" Type="Short" IsLead="1" IsStd="1" Ver="1">630</PName>
<PName PID="403" CID="484" Value="Colima" StdVal="Colima" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">631</PName>
<PName PID="404" CID="484" Value="DUR" StdVal="DUR" Lang="es" Type="Short" IsLead="1" IsStd="1" Ver="1">632</PName>
<PName PID="404" CID="484" Value="Durango" StdVal="Durango" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">633</PName>
<PName PID="405" CID="484" Value="GUA" StdVal="GUA" Lang="es" Type="Short" IsLead="1" IsStd="1" Ver="1">634</PName>
<PName PID="405" CID="484" Value="Guanajuato" StdVal="Guanajuato" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">635</PName>
<PName PID="406" CID="484" Value="GRO" StdVal="GRO" Lang="es" Type="Short" IsLead="1" IsStd="1" Ver="1">636</PName>
<PName PID="406" CID="484" Value="Guerrero" StdVal="Guerrero" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">637</PName>
<PName PID="407" CID="484" Value="HID" StdVal="HID" Lang="es" Type="Short" IsLead="1" IsStd="1" Ver="1">638</PName>
<PName PID="407" CID="484" Value="Hidalgo" StdVal="Hidalgo" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">639</PName>
<PName PID="408" CID="484" Value="JAL" StdVal="JAL" Lang="es" Type="Short" IsLead="1" IsStd="1" Ver="1">640</PName>
<PName PID="408" CID="484" Value="Jalisco" StdVal="Jalisco" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">641</PName>
<PName PID="409" CID="484" Value="MEX" StdVal="MEX" Lang="es" Type="Short" IsLead="1" IsStd="1" Ver="1">642</PName>
<PName PID="409" CID="484" Value="México" StdVal="México" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">643</PName>
<PName PID="410" CID="484" Value="MIC" StdVal="MIC" Lang="es" Type="Short" IsLead="1" IsStd="1" Ver="1">644</PName>
<PName PID="410" CID="484" Value="Michoacán" StdVal="Michoacán" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">645</PName>
<PName PID="411" CID="484" Value="MOR" StdVal="MOR" Lang="es" Type="Short" IsLead="1" IsStd="1" Ver="1">646</PName>
<PName PID="411" CID="484" Value="Morelos" StdVal="Morelos" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">647</PName>
<PName PID="412" CID="484" Value="NAY" StdVal="NAY" Lang="es" Type="Short" IsLead="1" IsStd="1" Ver="1">648</PName>
<PName PID="412" CID="484" Value="Nayarit" StdVal="Nayarit" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">649</PName>
<PName PID="413" CID="484" Value="NLE" StdVal="NLE" Lang="es" Type="Short" IsLead="1" IsStd="1" Ver="1">650</PName>
<PName PID="413" CID="484" Value="Nuevo León" StdVal="NuevoLeón" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">651</PName>
<PName PID="414" CID="484" Value="OAX" StdVal="OAX" Lang="es" Type="Short" IsLead="1" IsStd="1" Ver="1">652</PName>
<PName PID="414" CID="484" Value="Oaxaca" StdVal="Oaxaca" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">653</PName>
<PName PID="415" CID="484" Value="PUE" StdVal="PUE" Lang="es" Type="Short" IsLead="1" IsStd="1" Ver="1">654</PName>
<PName PID="415" CID="484" Value="Puebla" StdVal="Puebla" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">655</PName>
<PName PID="416" CID="484" Value="QUE" StdVal="QUE" Lang="es" Type="Short" IsLead="1" IsStd="1" Ver="1">656</PName>
<PName PID="416" CID="484" Value="Querétaro" StdVal="Querétaro" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">657</PName>
<PName PID="417" CID="484" Value="Quintana Roo" StdVal="QuintanaRoo" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">658</PName>
<PName PID="417" CID="484" Value="ROO" StdVal="ROO" Lang="es" Type="Short" IsLead="1" IsStd="1" Ver="1">659</PName>
<PName PID="418" CID="484" Value="San Luis Potosí" StdVal="SanLuisPotosí" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">660</PName>
<PName PID="418" CID="484" Value="SLP" StdVal="SLP" Lang="es" Type="Short" IsLead="1" IsStd="1" Ver="1">661</PName>
<PName PID="419" CID="484" Value="SIN" StdVal="SIN" Lang="es" Type="Short" IsLead="1" IsStd="1" Ver="1">662</PName>
<PName PID="419" CID="484" Value="Sinaloa" StdVal="Sinaloa" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">663</PName>
<PName PID="420" CID="484" Value="SON" StdVal="SON" Lang="es" Type="Short" IsLead="1" IsStd="1" Ver="1">664</PName>
<PName PID="420" CID="484" Value="Sonora" StdVal="Sonora" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">665</PName>
<PName PID="421" CID="484" Value="TAB" StdVal="TAB" Lang="es" Type="Short" IsLead="1" IsStd="1" Ver="1">666</PName>
<PName PID="421" CID="484" Value="Tabasco" StdVal="Tabasco" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">667</PName>
<PName PID="422" CID="484" Value="TAM" StdVal="TAM" Lang="es" Type="Short" IsLead="1" IsStd="1" Ver="1">668</PName>
<PName PID="422" CID="484" Value="Tamaulipas" StdVal="Tamaulipas" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">669</PName>
<PName PID="423" CID="484" Value="TLA" StdVal="TLA" Lang="es" Type="Short" IsLead="1" IsStd="1" Ver="1">670</PName>
<PName PID="423" CID="484" Value="Tlaxcala" StdVal="Tlaxcala" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">671</PName>
<PName PID="424" CID="484" Value="VER" StdVal="VER" Lang="es" Type="Short" IsLead="1" IsStd="1" Ver="1">672</PName>
<PName PID="424" CID="484" Value="Veracruz" StdVal="Veracruz" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">673</PName>
<PName PID="425" CID="484" Value="YUC" StdVal="YUC" Lang="es" Type="Short" IsLead="1" IsStd="1" Ver="1">674</PName>
<PName PID="425" CID="484" Value="Yucatán" StdVal="Yucatán" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">675</PName>
<PName PID="426" CID="484" Value="ZAC" StdVal="ZAC" Lang="es" Type="Short" IsLead="1" IsStd="1" Ver="1">676</PName>
<PName PID="426" CID="484" Value="Zacatecas" StdVal="Zacatecas" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">677</PName>
<PName PID="444" CID="528" Value="North Brabant" StdVal="NorthBrabant" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">701</PName>
<PName PID="445" CID="528" Value="North Holland" StdVal="NorthHolland" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">705</PName>
<PName PID="449" CID="528" Value="South Holland" StdVal="SouthHolland" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">713</PName>
<PName PID="450" CID="554" Value="Auckland" StdVal="Auckland" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">716</PName>
<PName PID="450" CID="554" Value="AUK" StdVal="AUK" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">717</PName>
<PName PID="451" CID="554" Value="Bay of Plenty" StdVal="BayofPlenty" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">718</PName>
<PName PID="451" CID="554" Value="BOP" StdVal="BOP" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">719</PName>
<PName PID="452" CID="554" Value="CAN" StdVal="CAN" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">720</PName>
<PName PID="452" CID="554" Value="Canterbury" StdVal="Canterbury" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">721</PName>
<PName PID="453" CID="554" Value="GIS" StdVal="GIS" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">722</PName>
<PName PID="453" CID="554" Value="Gisborne" StdVal="Gisborne" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">723</PName>
<PName PID="454" CID="554" Value="Hawkes's Bay" StdVal="HawkessBay" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">724</PName>
<PName PID="454" CID="554" Value="HKB" StdVal="HKB" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">725</PName>
<PName PID="455" CID="554" Value="Manawatu-Wanganui" StdVal="ManawatuWanganui" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">726</PName>
<PName PID="455" CID="554" Value="MWT" StdVal="MWT" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">727</PName>
<PName PID="456" CID="554" Value="Marlborough" StdVal="Marlborough" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">728</PName>
<PName PID="456" CID="554" Value="MBH" StdVal="MBH" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">729</PName>
<PName PID="457" CID="554" Value="Nelson" StdVal="Nelson" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">730</PName>
<PName PID="457" CID="554" Value="NSN" StdVal="NSN" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">731</PName>
<PName PID="458" CID="554" Value="Northland" StdVal="Northland" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">732</PName>
<PName PID="458" CID="554" Value="NTL" StdVal="NTL" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">733</PName>
<PName PID="459" CID="554" Value="OTA" StdVal="OTA" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">734</PName>
<PName PID="459" CID="554" Value="Otago" StdVal="Otago" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">735</PName>
<PName PID="460" CID="554" Value="Southland" StdVal="Southland" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">736</PName>
<PName PID="460" CID="554" Value="STL" StdVal="STL" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">737</PName>
<PName PID="461" CID="554" Value="Taranaki" StdVal="Taranaki" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">738</PName>
<PName PID="461" CID="554" Value="TKI" StdVal="TKI" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">739</PName>
<PName PID="462" CID="554" Value="TAS" StdVal="TAS" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">740</PName>
<PName PID="462" CID="554" Value="Tasman" StdVal="Tasman" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">741</PName>
<PName PID="463" CID="554" Value="Waikato" StdVal="Waikato" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">742</PName>
<PName PID="463" CID="554" Value="WKO" StdVal="WKO" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">743</PName>
<PName PID="464" CID="554" Value="Wellington" StdVal="Wellington" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">744</PName>
<PName PID="464" CID="554" Value="WGN" StdVal="WGN" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">745</PName>
<PName PID="465" CID="554" Value="West Coast" StdVal="WestCoast" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">746</PName>
<PName PID="465" CID="554" Value="WTC" StdVal="WTC" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">747</PName>
<PName PID="561" CID="643" Value="Amur" StdVal="Amur" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">902</PName>
<PName PID="562" CID="643" Value="Arkhangelsk" StdVal="Arkhangelsk" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">904</PName>
<PName PID="563" CID="643" Value="Astrakhan" StdVal="Astrakhan" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">906</PName>
<PName PID="563" CID="643" Value="Astrahan" StdVal="Astrahan" Lang="en" Type="Full" IsLead="0" IsStd="1" Ver="1">907</PName>
<PName PID="564" CID="643" Value="Belgorod" StdVal="Belgorod" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">909</PName>
<PName PID="565" CID="643" Value="Bryansk" StdVal="Bryansk" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">911</PName>
<PName PID="565" CID="643" Value="Brjansk" StdVal="Brjansk" Lang="en" Type="Full" IsLead="0" IsStd="1" Ver="1">912</PName>
<PName PID="566" CID="643" Value="Chelyabinsk" StdVal="Chelyabinsk" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">914</PName>
<PName PID="566" CID="643" Value="Cheliabinsk" StdVal="Cheliabinsk" Lang="en" Type="Full" IsLead="0" IsStd="1" Ver="1">915</PName>
<PName PID="567" CID="643" Value="Chita" StdVal="Chita" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">917</PName>
<PName PID="567" CID="643" Value="Chitin" StdVal="Chitin" Lang="en" Type="Full" IsLead="0" IsStd="1" Ver="1">918</PName>
<PName PID="568" CID="643" Value="Irkutsk" StdVal="Irkutsk" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">920</PName>
<PName PID="569" CID="643" Value="Ivanovo" StdVal="Ivanovo" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">922</PName>
<PName PID="570" CID="643" Value="Kalinigrad" StdVal="Kalinigrad" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">924</PName>
<PName PID="571" CID="643" Value="Kaluga" StdVal="Kaluga" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">926</PName>
<PName PID="571" CID="643" Value="Kaluž" StdVal="Kaluž" Lang="en" Type="Full" IsLead="0" IsStd="1" Ver="1">927</PName>
<PName PID="572" CID="643" Value="Kemerovo" StdVal="Kemerovo" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">929</PName>
<PName PID="573" CID="643" Value="Kirov" StdVal="Kirov" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">931</PName>
<PName PID="574" CID="643" Value="Kostroma" StdVal="Kostroma" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">933</PName>
<PName PID="575" CID="643" Value="Kurgan" StdVal="Kurgan" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">935</PName>
<PName PID="576" CID="643" Value="Kursk" StdVal="Kursk" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">937</PName>
<PName PID="577" CID="643" Value="Leningrad" StdVal="Leningrad" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">939</PName>
<PName PID="578" CID="643" Value="Lipetsk" StdVal="Lipetsk" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">941</PName>
<PName PID="579" CID="643" Value="Magadan" StdVal="Magadan" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">943</PName>
<PName PID="580" CID="643" Value="Moscow" StdVal="Moscow" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">945</PName>
<PName PID="580" CID="643" Value="Moskov" StdVal="Moskov" Lang="en" Type="Full" IsLead="0" IsStd="1" Ver="1">946</PName>
<PName PID="581" CID="643" Value="Murmansk" StdVal="Murmansk" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">948</PName>
<PName PID="582" CID="643" Value="Nizhny Novgorod" StdVal="NizhnyNovgorod" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">950</PName>
<PName PID="582" CID="643" Value="Nižegorod" StdVal="Nižegorod" Lang="en" Type="Full" IsLead="0" IsStd="1" Ver="1">951</PName>
<PName PID="582" CID="643" Value="Nizhegorod" StdVal="Nizhegorod" Lang="en" Type="Full" IsLead="0" IsStd="1" Ver="1">952</PName>
<PName PID="583" CID="643" Value="Novgorod" StdVal="Novgorod" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">954</PName>
<PName PID="584" CID="643" Value="Novosibirsk" StdVal="Novosibirsk" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">956</PName>
<PName PID="585" CID="643" Value="Omsk" StdVal="Omsk" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">958</PName>
<PName PID="586" CID="643" Value="Orel" StdVal="Orel" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">960</PName>
<PName PID="586" CID="643" Value="Oryol" StdVal="Oryol" Lang="en" Type="Full" IsLead="0" IsStd="1" Ver="1">961</PName>
<PName PID="587" CID="643" Value="Orenburg" StdVal="Orenburg" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">963</PName>
<PName PID="588" CID="643" Value="Penza" StdVal="Penza" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">965</PName>
<PName PID="588" CID="643" Value="Penzen" StdVal="Penzen" Lang="en" Type="Full" IsLead="0" IsStd="1" Ver="1">966</PName>
<PName PID="589" CID="643" Value="Pskov" StdVal="Pskov" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">968</PName>
<PName PID="590" CID="643" Value="Rostov" StdVal="Rostov" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">970</PName>
<PName PID="591" CID="643" Value="Ryazan" StdVal="Ryazan" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">972</PName>
<PName PID="591" CID="643" Value="Rjazan" StdVal="Rjazan" Lang="en" Type="Full" IsLead="0" IsStd="1" Ver="1">973</PName>
<PName PID="592" CID="643" Value="Sakhalin" StdVal="Sakhalin" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">975</PName>
<PName PID="592" CID="643" Value="Sahalin" StdVal="Sahalin" Lang="en" Type="Full" IsLead="0" IsStd="1" Ver="1">976</PName>
<PName PID="593" CID="643" Value="Samara" StdVal="Samara" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">978</PName>
<PName PID="594" CID="643" Value="Saratov" StdVal="Saratov" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">980</PName>
<PName PID="595" CID="643" Value="Smolensk" StdVal="Smolensk" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">982</PName>
<PName PID="596" CID="643" Value="Sverdlovsk" StdVal="Sverdlovsk" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">984</PName>
<PName PID="597" CID="643" Value="Tambov" StdVal="Tambov" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">986</PName>
<PName PID="598" CID="643" Value="Tomsk" StdVal="Tomsk" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">988</PName>
<PName PID="599" CID="643" Value="Tula" StdVal="Tula" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">990</PName>
<PName PID="600" CID="643" Value="Tyumen" StdVal="Tyumen" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">992</PName>
<PName PID="600" CID="643" Value="Tjumen" StdVal="Tjumen" Lang="en" Type="Full" IsLead="0" IsStd="1" Ver="1">993</PName>
<PName PID="601" CID="643" Value="Tver" StdVal="Tver" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">995</PName>
<PName PID="602" CID="643" Value="Ulyanovsk" StdVal="Ulyanovsk" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">997</PName>
<PName PID="602" CID="643" Value="Ul'janovsk" StdVal="Uljanovsk" Lang="en" Type="Full" IsLead="0" IsStd="1" Ver="1">998</PName>
<PName PID="603" CID="643" Value="Vladimir" StdVal="Vladimir" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1000</PName>
<PName PID="604" CID="643" Value="Volgograd" StdVal="Volgograd" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1002</PName>
<PName PID="605" CID="643" Value="Vologda" StdVal="Vologda" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1004</PName>
<PName PID="606" CID="643" Value="Voronezh" StdVal="Voronezh" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1006</PName>
<PName PID="606" CID="643" Value="Voronež" StdVal="Voronež" Lang="en" Type="Full" IsLead="0" IsStd="1" Ver="1">1007</PName>
<PName PID="607" CID="643" Value="Yaroslavl" StdVal="Yaroslavl" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1009</PName>
<PName PID="607" CID="643" Value="Jaroslav" StdVal="Jaroslav" Lang="en" Type="Full" IsLead="0" IsStd="1" Ver="1">1010</PName>
<PName PID="804" CID="724" Value="A Coruña" StdVal="ACoruña" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1211</PName>
<PName PID="805" CID="724" Value="Álava" StdVal="Álava" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1212</PName>
<PName PID="806" CID="724" Value="Albacete" StdVal="Albacete" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1213</PName>
<PName PID="807" CID="724" Value="Alicante" StdVal="Alicante" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1214</PName>
<PName PID="808" CID="724" Value="Almería" StdVal="Almería" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1215</PName>
<PName PID="810" CID="724" Value="Asturias" StdVal="Asturias" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1216</PName>
<PName PID="811" CID="724" Value="Ávila" StdVal="Ávila" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1217</PName>
<PName PID="812" CID="724" Value="Badajoz" StdVal="Badajoz" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1218</PName>
<PName PID="813" CID="724" Value="Baleares" StdVal="Baleares" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1219</PName>
<PName PID="814" CID="724" Value="Barcelona" StdVal="Barcelona" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1220</PName>
<PName PID="815" CID="724" Value="Burgos" StdVal="Burgos" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1221</PName>
<PName PID="816" CID="724" Value="Cáceres" StdVal="Cáceres" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1222</PName>
<PName PID="817" CID="724" Value="Cádiz" StdVal="Cádiz" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1223</PName>
<PName PID="818" CID="724" Value="Cantabria" StdVal="Cantabria" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1224</PName>
<PName PID="820" CID="724" Value="Castellón" StdVal="Castellón" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1225</PName>
<PName PID="821" CID="724" Value="Ciudad Real" StdVal="CiudadReal" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1226</PName>
<PName PID="822" CID="724" Value="Córdoba" StdVal="Córdoba" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1227</PName>
<PName PID="823" CID="724" Value="Cuenca" StdVal="Cuenca" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1228</PName>
<PName PID="824" CID="724" Value="Girona" StdVal="Girona" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1229</PName>
<PName PID="825" CID="724" Value="Granada" StdVal="Granada" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1230</PName>
<PName PID="826" CID="724" Value="Guadalajara" StdVal="Guadalajara" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1231</PName>
<PName PID="827" CID="724" Value="Guipúzcoa" StdVal="Guipúzcoa" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1232</PName>
<PName PID="828" CID="724" Value="Huelva" StdVal="Huelva" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1233</PName>
<PName PID="829" CID="724" Value="Huesca" StdVal="Huesca" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1234</PName>
<PName PID="830" CID="724" Value="Jaén" StdVal="Jaén" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1235</PName>
<PName PID="831" CID="724" Value="La Rioja" StdVal="LaRioja" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1236</PName>
<PName PID="833" CID="724" Value="Las Palmas" StdVal="LasPalmas" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1237</PName>
<PName PID="834" CID="724" Value="León" StdVal="León" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1238</PName>
<PName PID="835" CID="724" Value="Lleida" StdVal="Lleida" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1239</PName>
<PName PID="836" CID="724" Value="Lugo" StdVal="Lugo" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1240</PName>
<PName PID="837" CID="724" Value="Madrid" StdVal="Madrid" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1241</PName>
<PName PID="838" CID="724" Value="Comunidad de Madrid" StdVal="ComunidaddeMadrid" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1242</PName>
<PName PID="838" CID="724" Value="Madrid, Comunidad de" StdVal="MadridComunidadde" Lang="es" Type="Full" IsLead="0" IsStd="1" Ver="1">1243</PName>
<PName PID="839" CID="724" Value="Málaga" StdVal="Málaga" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1244</PName>
<PName PID="840" CID="724" Value="Murcia" StdVal="Murcia" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1245</PName>
<PName PID="841" CID="724" Value="Murcia, Región de" StdVal="MurciaRegiónde" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1246</PName>
<PName PID="841" CID="724" Value="Región de Murcia" StdVal="RegióndeMurcia" Lang="es" Type="Full" IsLead="0" IsStd="1" Ver="1">1247</PName>
<PName PID="842" CID="724" Value="Navarra" StdVal="Navarra" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1248</PName>
<PName PID="844" CID="724" Value="Ourense" StdVal="Ourense" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1249</PName>
<PName PID="845" CID="724" Value="Palencia" StdVal="Palencia" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1250</PName>
<PName PID="846" CID="724" Value="Pontevedra" StdVal="Pontevedra" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1251</PName>
<PName PID="847" CID="724" Value="Salamanca" StdVal="Salamanca" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1252</PName>
<PName PID="848" CID="724" Value="Santa Cruz" StdVal="SantaCruz" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1253</PName>
<PName PID="849" CID="724" Value="Segovia" StdVal="Segovia" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1254</PName>
<PName PID="850" CID="724" Value="Sevilla" StdVal="Sevilla" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1255</PName>
<PName PID="851" CID="724" Value="Soria" StdVal="Soria" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1256</PName>
<PName PID="852" CID="724" Value="Tarragona" StdVal="Tarragona" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1257</PName>
<PName PID="853" CID="724" Value="Teruel" StdVal="Teruel" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1258</PName>
<PName PID="854" CID="724" Value="Toledo" StdVal="Toledo" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1259</PName>
<PName PID="855" CID="724" Value="Valencia" StdVal="Valencia" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1260</PName>
<PName PID="856" CID="724" Value="Valladolid" StdVal="Valladolid" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1261</PName>
<PName PID="857" CID="724" Value="Vizcaya" StdVal="Vizcaya" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1262</PName>
<PName PID="858" CID="724" Value="Zamora" StdVal="Zamora" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1263</PName>
<PName PID="859" CID="724" Value="Zaragoza" StdVal="Zaragoza" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1264</PName>
<PName PID="860" CID="804" Value="Cherkasy" StdVal="Cherkasy" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1265</PName>
<PName PID="861" CID="804" Value="Chernihiv" StdVal="Chernihiv" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1267</PName>
<PName PID="862" CID="804" Value="Chernivtsi" StdVal="Chernivtsi" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1269</PName>
<PName PID="863" CID="804" Value="Dnipropetrovsk" StdVal="Dnipropetrovsk" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1271</PName>
<PName PID="864" CID="804" Value="Donetsk" StdVal="Donetsk" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1273</PName>
<PName PID="865" CID="804" Value="Ivano-Frankivsk" StdVal="IvanoFrankivsk" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1275</PName>
<PName PID="866" CID="804" Value="Kharkiv" StdVal="Kharkiv" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1277</PName>
<PName PID="867" CID="804" Value="Kherson" StdVal="Kherson" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1279</PName>
<PName PID="868" CID="804" Value="Khmelnytskyi" StdVal="Khmelnytskyi" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1281</PName>
<PName PID="869" CID="804" Value="Kirovohrad" StdVal="Kirovohrad" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1283</PName>
<PName PID="870" CID="804" Value="Kiev" StdVal="Kiev" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1285</PName>
<PName PID="871" CID="804" Value="Luhansk" StdVal="Luhansk" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1287</PName>
<PName PID="872" CID="804" Value="Lviv" StdVal="Lviv" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1289</PName>
<PName PID="873" CID="804" Value="Mykolaiv" StdVal="Mykolaiv" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1291</PName>
<PName PID="874" CID="804" Value="Odessa" StdVal="Odessa" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1293</PName>
<PName PID="875" CID="804" Value="Poltava" StdVal="Poltava" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1295</PName>
<PName PID="877" CID="804" Value="Rivne" StdVal="Rivne" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1298</PName>
<PName PID="878" CID="804" Value="Sumy" StdVal="Sumy" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1300</PName>
<PName PID="879" CID="804" Value="Ternopil" StdVal="Ternopil" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1302</PName>
<PName PID="880" CID="804" Value="Vinnytsia" StdVal="Vinnytsia" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1304</PName>
<PName PID="881" CID="804" Value="Volyn" StdVal="Volyn" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1306</PName>
<PName PID="881" CID="804" Value="Volhynia" StdVal="Volhynia" Lang="en" Type="Full" IsLead="0" IsStd="1" Ver="1">1307</PName>
<PName PID="882" CID="804" Value="Zakarpattia" StdVal="Zakarpattia" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1309</PName>
<PName PID="882" CID="804" Value="Transcarpathian" StdVal="Transcarpathian" Lang="en" Type="Full" IsLead="0" IsStd="1" Ver="1">1310</PName>
<PName PID="883" CID="804" Value="Zaporizhia" StdVal="Zaporizhia" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1312</PName>
<PName PID="884" CID="804" Value="Zhytomyr" StdVal="Zhytomyr" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1314</PName>
<PName PID="885" CID="826" Value="BDF" StdVal="BDF" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">1316</PName>
<PName PID="885" CID="826" Value="Bedfordshire" StdVal="Bedfordshire" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1317</PName>
<PName PID="886" CID="826" Value="BKM" StdVal="BKM" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">1318</PName>
<PName PID="886" CID="826" Value="Buckinghamshire" StdVal="Buckinghamshire" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1319</PName>
<PName PID="887" CID="826" Value="CAM" StdVal="CAM" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">1320</PName>
<PName PID="887" CID="826" Value="Cambridgeshire" StdVal="Cambridgeshire" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1321</PName>
<PName PID="888" CID="826" Value="Cheshire" StdVal="Cheshire" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1322</PName>
<PName PID="888" CID="826" Value="CHS" StdVal="CHS" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">1323</PName>
<PName PID="889" CID="826" Value="CON" StdVal="CON" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">1324</PName>
<PName PID="889" CID="826" Value="Cornwall" StdVal="Cornwall" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1325</PName>
<PName PID="890" CID="826" Value="CMA" StdVal="CMA" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">1326</PName>
<PName PID="890" CID="826" Value="Cumbria" StdVal="Cumbria" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1327</PName>
<PName PID="891" CID="826" Value="DBY" StdVal="DBY" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">1328</PName>
<PName PID="891" CID="826" Value="Derbyshire" StdVal="Derbyshire" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1329</PName>
<PName PID="892" CID="826" Value="DEV" StdVal="DEV" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">1330</PName>
<PName PID="892" CID="826" Value="Devon" StdVal="Devon" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1331</PName>
<PName PID="893" CID="826" Value="DOR" StdVal="DOR" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">1332</PName>
<PName PID="893" CID="826" Value="Dorset" StdVal="Dorset" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1333</PName>
<PName PID="894" CID="826" Value="DUR" StdVal="DUR" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">1334</PName>
<PName PID="894" CID="826" Value="Durham" StdVal="Durham" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1335</PName>
<PName PID="895" CID="826" Value="East Sussex" StdVal="EastSussex" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1336</PName>
<PName PID="895" CID="826" Value="ESX" StdVal="ESX" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">1337</PName>
<PName PID="896" CID="826" Value="ESS" StdVal="ESS" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">1338</PName>
<PName PID="896" CID="826" Value="Essex" StdVal="Essex" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1339</PName>
<PName PID="897" CID="826" Value="Gloucestershire" StdVal="Gloucestershire" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1340</PName>
<PName PID="897" CID="826" Value="GLS" StdVal="GLS" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">1341</PName>
<PName PID="897" CID="826" Value="Glouchester" StdVal="Glouchester" Lang="en" Type="Full" IsLead="0" IsStd="1" Ver="1">1342</PName>
<PName PID="898" CID="826" Value="HAM" StdVal="HAM" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">1343</PName>
<PName PID="898" CID="826" Value="Hampshire" StdVal="Hampshire" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1344</PName>
<PName PID="899" CID="826" Value="Hertfordshire" StdVal="Hertfordshire" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1345</PName>
<PName PID="899" CID="826" Value="HRT" StdVal="HRT" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">1346</PName>
<PName PID="900" CID="826" Value="KEN" StdVal="KEN" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">1347</PName>
<PName PID="900" CID="826" Value="Kent" StdVal="Kent" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1348</PName>
<PName PID="901" CID="826" Value="LAN" StdVal="LAN" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">1349</PName>
<PName PID="901" CID="826" Value="Lancashire" StdVal="Lancashire" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1350</PName>
<PName PID="902" CID="826" Value="LEC" StdVal="LEC" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">1351</PName>
<PName PID="902" CID="826" Value="Leicestershire" StdVal="Leicestershire" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1352</PName>
<PName PID="903" CID="826" Value="LIN" StdVal="LIN" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">1353</PName>
<PName PID="903" CID="826" Value="Lincolnshire" StdVal="Lincolnshire" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1354</PName>
<PName PID="904" CID="826" Value="NFK" StdVal="NFK" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">1355</PName>
<PName PID="904" CID="826" Value="Norfolk" StdVal="Norfolk" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1356</PName>
<PName PID="905" CID="826" Value="North Yorkshire" StdVal="NorthYorkshire" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1357</PName>
<PName PID="905" CID="826" Value="NYK" StdVal="NYK" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">1358</PName>
<PName PID="906" CID="826" Value="Northamptonshire" StdVal="Northamptonshire" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1359</PName>
<PName PID="906" CID="826" Value="NTH" StdVal="NTH" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">1360</PName>
<PName PID="907" CID="826" Value="NBL" StdVal="NBL" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">1361</PName>
<PName PID="907" CID="826" Value="Northumberland" StdVal="Northumberland" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1362</PName>
<PName PID="908" CID="826" Value="Nottinghamshire" StdVal="Nottinghamshire" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1363</PName>
<PName PID="908" CID="826" Value="NTT" StdVal="NTT" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">1364</PName>
<PName PID="909" CID="826" Value="OXF" StdVal="OXF" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">1365</PName>
<PName PID="909" CID="826" Value="Oxfordshire" StdVal="Oxfordshire" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1366</PName>
<PName PID="910" CID="826" Value="SHR" StdVal="SHR" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">1367</PName>
<PName PID="910" CID="826" Value="Shropshire" StdVal="Shropshire" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1368</PName>
<PName PID="911" CID="826" Value="SOM" StdVal="SOM" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">1369</PName>
<PName PID="911" CID="826" Value="Somerset" StdVal="Somerset" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1370</PName>
<PName PID="912" CID="826" Value="Staffordshire" StdVal="Staffordshire" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1371</PName>
<PName PID="912" CID="826" Value="STS" StdVal="STS" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">1372</PName>
<PName PID="913" CID="826" Value="SFK" StdVal="SFK" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">1373</PName>
<PName PID="913" CID="826" Value="Suffolk" StdVal="Suffolk" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1374</PName>
<PName PID="914" CID="826" Value="SRY" StdVal="SRY" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">1375</PName>
<PName PID="914" CID="826" Value="Surrey" StdVal="Surrey" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1376</PName>
<PName PID="915" CID="826" Value="WAR" StdVal="WAR" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">1377</PName>
<PName PID="915" CID="826" Value="Warwickshire" StdVal="Warwickshire" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1378</PName>
<PName PID="916" CID="826" Value="West Sussex" StdVal="WestSussex" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1379</PName>
<PName PID="916" CID="826" Value="WSX" StdVal="WSX" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">1380</PName>
<PName PID="917" CID="826" Value="WIL" StdVal="WIL" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">1381</PName>
<PName PID="917" CID="826" Value="Wiltshire" StdVal="Wiltshire" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1382</PName>
<PName PID="918" CID="826" Value="WOR" StdVal="WOR" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">1383</PName>
<PName PID="918" CID="826" Value="Worcestershire" StdVal="Worcestershire" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1384</PName>
<PName PID="919" CID="840" Value="AL" StdVal="AL" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">1385</PName>
<PName PID="919" CID="840" Value="Alabama" StdVal="Alabama" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1386</PName>
<PName PID="920" CID="840" Value="AK" StdVal="AK" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">1387</PName>
<PName PID="920" CID="840" Value="Alaska" StdVal="Alaska" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1388</PName>
<PName PID="921" CID="840" Value="Arizona" StdVal="Arizona" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1389</PName>
<PName PID="921" CID="840" Value="AZ" StdVal="AZ" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">1390</PName>
<PName PID="922" CID="840" Value="AR" StdVal="AR" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">1391</PName>
<PName PID="922" CID="840" Value="Arkansas" StdVal="Arkansas" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1392</PName>
<PName PID="923" CID="840" Value="CA" StdVal="CA" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">1393</PName>
<PName PID="923" CID="840" Value="California" StdVal="California" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1394</PName>
<PName PID="924" CID="840" Value="CO" StdVal="CO" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">1395</PName>
<PName PID="924" CID="840" Value="Colorado" StdVal="Colorado" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1396</PName>
<PName PID="925" CID="840" Value="Connecticut" StdVal="Connecticut" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1397</PName>
<PName PID="925" CID="840" Value="CT" StdVal="CT" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">1398</PName>
<PName PID="926" CID="840" Value="DE" StdVal="DE" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">1399</PName>
<PName PID="926" CID="840" Value="Delaware" StdVal="Delaware" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1400</PName>
<PName PID="927" CID="840" Value="DC" StdVal="DC" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">1401</PName>
<PName PID="927" CID="840" Value="District of Columbia" StdVal="DistrictofColumbia" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1402</PName>
<PName PID="928" CID="840" Value="FL" StdVal="FL" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">1403</PName>
<PName PID="928" CID="840" Value="Florida" StdVal="Florida" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1404</PName>
<PName PID="929" CID="840" Value="GA" StdVal="GA" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">1405</PName>
<PName PID="929" CID="840" Value="Georgia" StdVal="Georgia" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1406</PName>
<PName PID="930" CID="840" Value="Hawaii" StdVal="Hawaii" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1407</PName>
<PName PID="930" CID="840" Value="HI" StdVal="HI" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">1408</PName>
<PName PID="931" CID="840" Value="ID" StdVal="ID" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">1409</PName>
<PName PID="931" CID="840" Value="Idaho" StdVal="Idaho" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1410</PName>
<PName PID="932" CID="840" Value="IL" StdVal="IL" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">1411</PName>
<PName PID="932" CID="840" Value="Illinois" StdVal="Illinois" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1412</PName>
<PName PID="933" CID="840" Value="IN" StdVal="IN" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">1413</PName>
<PName PID="933" CID="840" Value="Indiana" StdVal="Indiana" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1414</PName>
<PName PID="934" CID="840" Value="IA" StdVal="IA" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">1415</PName>
<PName PID="934" CID="840" Value="Iowa" StdVal="Iowa" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1416</PName>
<PName PID="935" CID="840" Value="Kansas" StdVal="Kansas" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1417</PName>
<PName PID="935" CID="840" Value="KS" StdVal="KS" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">1418</PName>
<PName PID="936" CID="840" Value="Kentucky" StdVal="Kentucky" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1419</PName>
<PName PID="936" CID="840" Value="KY" StdVal="KY" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">1420</PName>
<PName PID="937" CID="840" Value="LA" StdVal="LA" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">1421</PName>
<PName PID="937" CID="840" Value="Louisiana" StdVal="Louisiana" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1422</PName>
<PName PID="938" CID="840" Value="Maine" StdVal="Maine" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1423</PName>
<PName PID="938" CID="840" Value="ME" StdVal="ME" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">1424</PName>
<PName PID="939" CID="840" Value="Maryland" StdVal="Maryland" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1425</PName>
<PName PID="939" CID="840" Value="MD" StdVal="MD" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">1426</PName>
<PName PID="940" CID="840" Value="MA" StdVal="MA" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">1427</PName>
<PName PID="940" CID="840" Value="Massachusetts" StdVal="Massachusetts" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1428</PName>
<PName PID="941" CID="840" Value="MI" StdVal="MI" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">1429</PName>
<PName PID="941" CID="840" Value="Michigan" StdVal="Michigan" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1430</PName>
<PName PID="942" CID="840" Value="Minnesota" StdVal="Minnesota" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1431</PName>
<PName PID="942" CID="840" Value="MN" StdVal="MN" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">1432</PName>
<PName PID="943" CID="840" Value="Mississippi" StdVal="Mississippi" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1433</PName>
<PName PID="943" CID="840" Value="MS" StdVal="MS" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">1434</PName>
<PName PID="944" CID="840" Value="Missouri" StdVal="Missouri" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1435</PName>
<PName PID="944" CID="840" Value="MO" StdVal="MO" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">1436</PName>
<PName PID="945" CID="840" Value="Montana" StdVal="Montana" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1437</PName>
<PName PID="945" CID="840" Value="MT" StdVal="MT" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">1438</PName>
<PName PID="946" CID="840" Value="NE" StdVal="NE" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">1439</PName>
<PName PID="946" CID="840" Value="Nebraska" StdVal="Nebraska" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1440</PName>
<PName PID="947" CID="840" Value="Nevada" StdVal="Nevada" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1441</PName>
<PName PID="947" CID="840" Value="NV" StdVal="NV" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">1442</PName>
<PName PID="948" CID="840" Value="New Hampshire" StdVal="NewHampshire" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1443</PName>
<PName PID="948" CID="840" Value="NH" StdVal="NH" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">1444</PName>
<PName PID="949" CID="840" Value="New Jersey" StdVal="NewJersey" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1445</PName>
<PName PID="949" CID="840" Value="NJ" StdVal="NJ" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">1446</PName>
<PName PID="950" CID="840" Value="New Mexico" StdVal="NewMexico" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1447</PName>
<PName PID="950" CID="840" Value="NM" StdVal="NM" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">1448</PName>
<PName PID="951" CID="840" Value="New York" StdVal="NewYork" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1449</PName>
<PName PID="951" CID="840" Value="NY" StdVal="NY" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">1450</PName>
<PName PID="952" CID="840" Value="NC" StdVal="NC" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">1451</PName>
<PName PID="952" CID="840" Value="North Carolina" StdVal="NorthCarolina" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1452</PName>
<PName PID="952" CID="840" Value="N Carolina" StdVal="NCarolina" Lang="en" Type="Full" IsLead="0" IsStd="1" Ver="1">1453</PName>
<PName PID="953" CID="840" Value="ND" StdVal="ND" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">1454</PName>
<PName PID="953" CID="840" Value="North Dakota" StdVal="NorthDakota" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1455</PName>
<PName PID="953" CID="840" Value="N Dakota" StdVal="NDakota" Lang="en" Type="Full" IsLead="0" IsStd="1" Ver="1">1456</PName>
<PName PID="954" CID="840" Value="OH" StdVal="OH" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">1457</PName>
<PName PID="954" CID="840" Value="Ohio" StdVal="Ohio" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1458</PName>
<PName PID="955" CID="840" Value="OK" StdVal="OK" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">1459</PName>
<PName PID="955" CID="840" Value="Oklahoma" StdVal="Oklahoma" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1460</PName>
<PName PID="956" CID="840" Value="OR" StdVal="OR" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">1461</PName>
<PName PID="956" CID="840" Value="Oregon" StdVal="Oregon" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1462</PName>
<PName PID="957" CID="840" Value="PA" StdVal="PA" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">1463</PName>
<PName PID="957" CID="840" Value="Pennsylvania" StdVal="Pennsylvania" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1464</PName>
<PName PID="958" CID="840" Value="Rhode Island" StdVal="RhodeIsland" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1465</PName>
<PName PID="958" CID="840" Value="RI" StdVal="RI" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">1466</PName>
<PName PID="959" CID="840" Value="SC" StdVal="SC" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">1467</PName>
<PName PID="959" CID="840" Value="South Carolina" StdVal="SouthCarolina" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1468</PName>
<PName PID="959" CID="840" Value="S Carolina" StdVal="SCarolina" Lang="en" Type="Full" IsLead="0" IsStd="1" Ver="1">1469</PName>
<PName PID="960" CID="840" Value="SD" StdVal="SD" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">1470</PName>
<PName PID="960" CID="840" Value="South Dakota" StdVal="SouthDakota" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1471</PName>
<PName PID="960" CID="840" Value="S Dakota" StdVal="SDakota" Lang="en" Type="Full" IsLead="0" IsStd="1" Ver="1">1472</PName>
<PName PID="961" CID="840" Value="Tennessee" StdVal="Tennessee" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1473</PName>
<PName PID="961" CID="840" Value="TN" StdVal="TN" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">1474</PName>
<PName PID="961" CID="840" Value="Tennesee" StdVal="Tennesee" Lang="en" Type="Full" IsLead="0" IsStd="1" Ver="1">1475</PName>
<PName PID="962" CID="840" Value="Texas" StdVal="Texas" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1476</PName>
<PName PID="962" CID="840" Value="TX" StdVal="TX" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">1477</PName>
<PName PID="963" CID="840" Value="UT" StdVal="UT" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">1478</PName>
<PName PID="963" CID="840" Value="Utah" StdVal="Utah" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1479</PName>
<PName PID="964" CID="840" Value="Vermont" StdVal="Vermont" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1480</PName>
<PName PID="964" CID="840" Value="VT" StdVal="VT" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">1481</PName>
<PName PID="965" CID="840" Value="VA" StdVal="VA" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">1482</PName>
<PName PID="965" CID="840" Value="Virginia" StdVal="Virginia" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1483</PName>
<PName PID="966" CID="840" Value="WA" StdVal="WA" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">1484</PName>
<PName PID="966" CID="840" Value="Washington" StdVal="Washington" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1485</PName>
<PName PID="967" CID="840" Value="West Virginia" StdVal="WestVirginia" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1486</PName>
<PName PID="967" CID="840" Value="WV" StdVal="WV" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">1487</PName>
<PName PID="967" CID="840" Value="W Virginia" StdVal="WVirginia" Lang="en" Type="Full" IsLead="0" IsStd="1" Ver="1">1488</PName>
<PName PID="968" CID="840" Value="WI" StdVal="WI" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">1489</PName>
<PName PID="968" CID="840" Value="Wisconsin" StdVal="Wisconsin" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1490</PName>
<PName PID="969" CID="840" Value="WY" StdVal="WY" Lang="en" Type="Short" IsLead="1" IsStd="1" Ver="1">1491</PName>
<PName PID="969" CID="840" Value="Wyoming" StdVal="Wyoming" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1492</PName>
<PName PID="970" CID="784" Value="Abu Dhabi" StdVal="AbuDhabi" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1494</PName>
<PName PID="971" CID="784" Value="Ajman" StdVal="Ajman" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1497</PName>
<PName PID="972" CID="784" Value="Fujayrah" StdVal="AlFujayrah" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1499</PName>
<PName PID="973" CID="784" Value="Sharjah" StdVal="Sharjah" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1501</PName>
<PName PID="974" CID="784" Value="Dubai" StdVal="Dubai" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1503</PName>
<PName PID="974" CID="784" Value="Dubay" StdVal="Dubay" Lang="en" Type="Full" IsLead="0" IsStd="1" Ver="1">1504</PName>
<PName PID="975" CID="784" Value="Ras al Khaymah" StdVal="Ras al Khaymah" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1506</PName>
<PName PID="976" CID="784" Value="Umm al Qaywayn" StdVal="UmmalQaywayn" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1507</PName>
<PName PID="1005" CID="156" Value="Macao" StdVal="Macao" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1564</PName>
<PName PID="1033" CID="156" Value="Hong Kong" StdVal="HongKong" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1593</PName>
<PName PID="1044" CID="392" Value="Aichi" StdVal="Aichi" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1611</PName>
<PName PID="1048" CID="392" Value="Gifu" StdVal="Gifu" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1616</PName>
<PName PID="1050" CID="392" Value="Hiroshima" StdVal="Hiroshima" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1619</PName>
<PName PID="1051" CID="392" Value="Hokkaido" StdVal="Hokkaido" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1621</PName>
<PName PID="1052" CID="392" Value="Fukui" StdVal="Fukui" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1623</PName>
<PName PID="1053" CID="392" Value="Fukuoka" StdVal="Fukuoka" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1625</PName>
<PName PID="1054" CID="392" Value="Fukushima" StdVal="Fukushima" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1627</PName>
<PName PID="1055" CID="392" Value="Hyogo" StdVal="Hyogo" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1629</PName>
<PName PID="1057" CID="392" Value="Ishikawa" StdVal="Ishikawa" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1632</PName>
<PName PID="1060" CID="392" Value="Kagoshima" StdVal="Kagoshima" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1636</PName>
<PName PID="1062" CID="392" Value="Kochi" StdVal="Kochi" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1639</PName>
<PName PID="1064" CID="392" Value="Kyoto" StdVal="Kyoto" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1642</PName>
<PName PID="1072" CID="392" Value="Oita" StdVal="Oita" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1651</PName>
<PName PID="1075" CID="392" Value="Osaka" StdVal="Osaka" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1655</PName>
<PName PID="1078" CID="392" Value="Shiga" StdVal="Shiga" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1659</PName>
<PName PID="1079" CID="392" Value="Shimane" StdVal="Shimane" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1661</PName>
<PName PID="1080" CID="392" Value="Shizuoka" StdVal="Shizuoka" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1663</PName>
<PName PID="1081" CID="392" Value="Chiba" StdVal="Chiba" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1665</PName>
<PName PID="1082" CID="392" Value="Tokushima" StdVal="Tokushima" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1667</PName>
<PName PID="1083" CID="392" Value="Tokyo" StdVal="Tokyo" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1669</PName>
<PName PID="1084" CID="392" Value="Tochigi" StdVal="Tochigi" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1671</PName>
<PName PID="1089" CID="392" Value="Yamaguchi" StdVal="Yamaguchi" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1677</PName>
<PName PID="1090" CID="392" Value="Yamanashi" StdVal="Yamanashi" Lang="en" Type="Full" IsLead="1" IsStd="1" Ver="1">1679</PName>
<PName PID="1091" CID="600" Value="Alto Paraguay" StdVal="AltoParaguay" Lang="es" Type="Full" IsLead="2" IsStd="1" Ver="1">1680</PName>
<PName PID="1092" CID="600" Value="Alto Paraná" StdVal="AltoParaná" Lang="es" Type="Full" IsLead="3" IsStd="1" Ver="1">1681</PName>
<PName PID="1093" CID="600" Value="Amambay" StdVal="Amambay" Lang="es" Type="Full" IsLead="4" IsStd="1" Ver="1">1682</PName>
<PName PID="1094" CID="600" Value="Asunción" StdVal="Asunción" Lang="es" Type="Full" IsLead="5" IsStd="1" Ver="1">1683</PName>
<PName PID="1095" CID="600" Value="Boquerón" StdVal="Boquerón" Lang="es" Type="Full" IsLead="6" IsStd="1" Ver="1">1684</PName>
<PName PID="1096" CID="600" Value="Caaguazú" StdVal="Caaguazú" Lang="es" Type="Full" IsLead="7" IsStd="1" Ver="1">1685</PName>
<PName PID="1097" CID="600" Value="Caazapá" StdVal="Caazapá" Lang="es" Type="Full" IsLead="8" IsStd="1" Ver="1">1686</PName>
<PName PID="1098" CID="600" Value="Canindeyú" StdVal="Canindeyú" Lang="es" Type="Full" IsLead="9" IsStd="1" Ver="1">1687</PName>
<PName PID="1099" CID="600" Value="Central" StdVal="Central" Lang="es" Type="Full" IsLead="10" IsStd="1" Ver="1">1688</PName>
<PName PID="1100" CID="600" Value="Concepción" StdVal="Concepción" Lang="es" Type="Full" IsLead="11" IsStd="1" Ver="1">1689</PName>
<PName PID="1101" CID="600" Value="Cordillera" StdVal="Cordillera" Lang="es" Type="Full" IsLead="12" IsStd="1" Ver="1">1690</PName>
<PName PID="1102" CID="600" Value="Guairá" StdVal="Guairá" Lang="es" Type="Full" IsLead="13" IsStd="1" Ver="1">1691</PName>
<PName PID="1103" CID="600" Value="Itapúa" StdVal="Itapúa" Lang="es" Type="Full" IsLead="14" IsStd="1" Ver="1">1692</PName>
<PName PID="1104" CID="600" Value="Misiones" StdVal="Misiones" Lang="es" Type="Full" IsLead="15" IsStd="1" Ver="1">1693</PName>
<PName PID="1105" CID="600" Value="Ñeembucú" StdVal="Ñeembucú" Lang="es" Type="Full" IsLead="16" IsStd="1" Ver="1">1694</PName>
<PName PID="1106" CID="600" Value="Paraguarí" StdVal="Paraguarí" Lang="es" Type="Full" IsLead="17" IsStd="1" Ver="1">1695</PName>
<PName PID="1107" CID="600" Value="Presidente Hayes" StdVal="PresidenteHayes" Lang="es" Type="Full" IsLead="18" IsStd="1" Ver="1">1696</PName>
<PName PID="1108" CID="600" Value="San Pedro" StdVal="SanPedro" Lang="es" Type="Full" IsLead="19" IsStd="1" Ver="1">1697</PName>
<PName PID="1109" CID="604" Value="Amazonas" StdVal="Amazonas" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1698</PName>
<PName PID="1110" CID="604" Value="Ancash" StdVal="Ancash" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1699</PName>
<PName PID="1111" CID="604" Value="Apurímac" StdVal="Apurímac" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1700</PName>
<PName PID="1112" CID="604" Value="Arequipa" StdVal="Arequipa" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1701</PName>
<PName PID="1113" CID="604" Value="Ayacucho" StdVal="Ayacucho" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1702</PName>
<PName PID="1114" CID="604" Value="Cajamarca" StdVal="Cajamarca" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1703</PName>
<PName PID="1115" CID="604" Value="Cusco" StdVal="Cusco" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1704</PName>
<PName PID="1115" CID="604" Value="Cuzco" StdVal="Cuzco" Lang="es" Type="Full" IsLead="0" IsStd="1" Ver="1">1705</PName>
<PName PID="1116" CID="604" Value="El Callao" StdVal="ElCallao" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1706</PName>
<PName PID="1117" CID="604" Value="Huancavelica" StdVal="Huancavelica" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1707</PName>
<PName PID="1118" CID="604" Value="Huánuco" StdVal="Huánuco" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1708</PName>
<PName PID="1119" CID="604" Value="Ica" StdVal="Ica" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1709</PName>
<PName PID="1120" CID="604" Value="Junín" StdVal="Junín" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1710</PName>
<PName PID="1121" CID="604" Value="La Libertad" StdVal="LaLibertad" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1711</PName>
<PName PID="1122" CID="604" Value="Lambayeque" StdVal="Lambayeque" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1712</PName>
<PName PID="1123" CID="604" Value="Lima" StdVal="Lima" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1713</PName>
<PName PID="1124" CID="604" Value="Loreto" StdVal="Loreto" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1714</PName>
<PName PID="1125" CID="604" Value="Madre de Dios" StdVal="MadredeDios" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1715</PName>
<PName PID="1126" CID="604" Value="Moquegua" StdVal="Moquegua" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1716</PName>
<PName PID="1127" CID="604" Value="Pasco" StdVal="Pasco" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1717</PName>
<PName PID="1128" CID="604" Value="Piura" StdVal="Piura" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1718</PName>
<PName PID="1129" CID="604" Value="Puno" StdVal="Puno" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1719</PName>
<PName PID="1130" CID="604" Value="San Martín" StdVal="SanMartín" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1720</PName>
<PName PID="1131" CID="604" Value="Tacna" StdVal="Tacna" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1721</PName>
<PName PID="1132" CID="604" Value="Tumbes" StdVal="Tumbes" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1722</PName>
<PName PID="1133" CID="604" Value="Ucayali" StdVal="Ucayali" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1723</PName>
<PName PID="1215" CID="862" Value="Amazonas" StdVal="Amazonas" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1805</PName>
<PName PID="1216" CID="862" Value="Anzoátegui" StdVal="Anzoátegui" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1806</PName>
<PName PID="1217" CID="862" Value="Apure" StdVal="Apure" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1807</PName>
<PName PID="1218" CID="862" Value="Aragua" StdVal="Aragua" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1808</PName>
<PName PID="1219" CID="862" Value="Barinas" StdVal="Barinas" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1809</PName>
<PName PID="1220" CID="862" Value="Bolívar" StdVal="Bolívar" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1810</PName>
<PName PID="1221" CID="862" Value="Carabobo" StdVal="Carabobo" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1811</PName>
<PName PID="1222" CID="862" Value="Cojedes" StdVal="Cojedes" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1812</PName>
<PName PID="1223" CID="862" Value="Delta Amacuro" StdVal="DeltaAmacuro" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1813</PName>
<PName PID="1224" CID="862" Value="Dependencias Federal" StdVal="DependenciasFederal" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1814</PName>
<PName PID="1225" CID="862" Value="Distrito Capital" StdVal="DistritoCapital" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1815</PName>
<PName PID="1226" CID="862" Value="Falcón" StdVal="Falcón" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1816</PName>
<PName PID="1227" CID="862" Value="Guárico" StdVal="Guárico" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1817</PName>
<PName PID="1228" CID="862" Value="Lara" StdVal="Lara" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1818</PName>
<PName PID="1229" CID="862" Value="Mérida" StdVal="Mérida" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1819</PName>
<PName PID="1230" CID="862" Value="Miranda" StdVal="Miranda" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1820</PName>
<PName PID="1231" CID="862" Value="Monagas" StdVal="Monagas" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1821</PName>
<PName PID="1232" CID="862" Value="Nueva Esparta" StdVal="NuevaEsparta" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1822</PName>
<PName PID="1233" CID="862" Value="Portuguesa" StdVal="Portuguesa" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1823</PName>
<PName PID="1234" CID="862" Value="Sucre" StdVal="Sucre" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1824</PName>
<PName PID="1235" CID="862" Value="Táchira" StdVal="Táchira" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1825</PName>
<PName PID="1236" CID="862" Value="Trujillo" StdVal="Trujillo" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1826</PName>
<PName PID="1237" CID="862" Value="Vargas" StdVal="Vargas" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1827</PName>
<PName PID="1238" CID="862" Value="Yaracuy" StdVal="Yaracuy" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1828</PName>
<PName PID="1239" CID="862" Value="Zulia" StdVal="Zulia" Lang="es" Type="Full" IsLead="1" IsStd="1" Ver="1">1829</PName>
</PNameSets>
