<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<PNameSets xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<PName PID="1" CID="008" Value="Berat" StdVal="Berat" Lang="sq" Type="Full" IsLead="1" IsStd="1" Ver="1">1</PName>
<PName PID="2" CID="008" Value="Bulqizë" StdVal="Bulqizë" Lang="sq" Type="Full" IsLead="1" IsStd="1" Ver="1">2</PName>
<PName PID="3" CID="008" Value="Delvinë" StdVal="Delvinë" Lang="sq" Type="Full" IsLead="1" IsStd="1" Ver="1">3</PName>
<PName PID="4" CID="008" Value="Devoll" StdVal="Devoll" Lang="sq" Type="Full" IsLead="1" IsStd="1" Ver="1">4</PName>
<PName PID="5" CID="008" Value="Dibër" StdVal="Dibër" Lang="sq" Type="Full" IsLead="1" IsStd="1" Ver="1">5</PName>
<PName PID="6" CID="008" Value="Durrës" StdVal="Durrës" Lang="sq" Type="Full" IsLead="1" IsStd="1" Ver="1">6</PName>
<PName PID="7" CID="008" Value="Elbasan" StdVal="Elbasan" Lang="sq" Type="Full" IsLead="1" IsStd="1" Ver="1">7</PName>
<PName PID="8" CID="008" Value="Fier" StdVal="Fier" Lang="sq" Type="Full" IsLead="1" IsStd="1" Ver="1">8</PName>
<PName PID="9" CID="008" Value="Gjirokastër" StdVal="Gjirokastër" Lang="sq" Type="Full" IsLead="1" IsStd="1" Ver="1">9</PName>
<PName PID="10" CID="008" Value="Gramsh" StdVal="Gramsh" Lang="sq" Type="Full" IsLead="1" IsStd="1" Ver="1">10</PName>
<PName PID="11" CID="008" Value="Has" StdVal="Has" Lang="sq" Type="Full" IsLead="1" IsStd="1" Ver="1">11</PName>
<PName PID="12" CID="008" Value="Kavajë" StdVal="Kavajë" Lang="sq" Type="Full" IsLead="1" IsStd="1" Ver="1">12</PName>
<PName PID="13" CID="008" Value="Kolonjë" StdVal="Kolonjë" Lang="sq" Type="Full" IsLead="1" IsStd="1" Ver="1">13</PName>
<PName PID="14" CID="008" Value="Korçë" StdVal="Korçë" Lang="sq" Type="Full" IsLead="1" IsStd="1" Ver="1">14</PName>
<PName PID="15" CID="008" Value="Krujë" StdVal="Krujë" Lang="sq" Type="Full" IsLead="1" IsStd="1" Ver="1">15</PName>
<PName PID="16" CID="008" Value="Kuçovë" StdVal="Kuçovë" Lang="sq" Type="Full" IsLead="1" IsStd="1" Ver="1">16</PName>
<PName PID="17" CID="008" Value="Kukës" StdVal="Kukës" Lang="sq" Type="Full" IsLead="1" IsStd="1" Ver="1">17</PName>
<PName PID="18" CID="008" Value="Kurbin" StdVal="Kurbin" Lang="sq" Type="Full" IsLead="1" IsStd="1" Ver="1">18</PName>
<PName PID="19" CID="008" Value="Lezhë" StdVal="Lezhë" Lang="sq" Type="Full" IsLead="1" IsStd="1" Ver="1">19</PName>
<PName PID="20" CID="008" Value="Librazhd" StdVal="Librazhd" Lang="sq" Type="Full" IsLead="1" IsStd="1" Ver="1">20</PName>
<PName PID="21" CID="008" Value="Lushnjë" StdVal="Lushnjë" Lang="sq" Type="Full" IsLead="1" IsStd="1" Ver="1">21</PName>
<PName PID="22" CID="008" Value="Malësi e Madhe" StdVal="MalësieMadhe" Lang="sq" Type="Full" IsLead="1" IsStd="1" Ver="1">22</PName>
<PName PID="23" CID="008" Value="Mallakastër" StdVal="Mallakastër" Lang="sq" Type="Full" IsLead="1" IsStd="1" Ver="1">23</PName>
<PName PID="24" CID="008" Value="Mat" StdVal="Mat" Lang="sq" Type="Full" IsLead="1" IsStd="1" Ver="1">24</PName>
<PName PID="25" CID="008" Value="Mirditë" StdVal="Mirditë" Lang="sq" Type="Full" IsLead="1" IsStd="1" Ver="1">25</PName>
<PName PID="26" CID="008" Value="Peqin" StdVal="Peqin" Lang="sq" Type="Full" IsLead="1" IsStd="1" Ver="1">26</PName>
<PName PID="27" CID="008" Value="Përmet" StdVal="Përmet" Lang="sq" Type="Full" IsLead="1" IsStd="1" Ver="1">27</PName>
<PName PID="28" CID="008" Value="Pogradec" StdVal="Pogradec" Lang="sq" Type="Full" IsLead="1" IsStd="1" Ver="1">28</PName>
<PName PID="29" CID="008" Value="Pukë" StdVal="Pukë" Lang="sq" Type="Full" IsLead="1" IsStd="1" Ver="1">29</PName>
<PName PID="30" CID="008" Value="Sarandë" StdVal="Sarandë" Lang="sq" Type="Full" IsLead="1" IsStd="1" Ver="1">30</PName>
<PName PID="31" CID="008" Value="Shkodër" StdVal="Shkodër" Lang="sq" Type="Full" IsLead="1" IsStd="1" Ver="1">31</PName>
<PName PID="32" CID="008" Value="Skrapar" StdVal="Skrapar" Lang="sq" Type="Full" IsLead="1" IsStd="1" Ver="1">32</PName>
<PName PID="33" CID="008" Value="Tepelenë" StdVal="Tepelenë" Lang="sq" Type="Full" IsLead="1" IsStd="1" Ver="1">33</PName>
<PName PID="34" CID="008" Value="Tiranë" StdVal="Tiranë" Lang="sq" Type="Full" IsLead="1" IsStd="1" Ver="1">34</PName>
<PName PID="35" CID="008" Value="Tropojë" StdVal="Tropojë" Lang="sq" Type="Full" IsLead="1" IsStd="1" Ver="1">35</PName>
<PName PID="36" CID="008" Value="Vlorë" StdVal="Vlorë" Lang="sq" Type="Full" IsLead="1" IsStd="1" Ver="1">36</PName>
<PName PID="48" CID="056" Value="Antwerpen" StdVal="Antwerpen" Lang="nl" Type="Full" IsLead="1" IsStd="1" Ver="1">59</PName>
<PName PID="48" CID="056" Value="VAN" StdVal="VAN" Lang="nl" Type="Short" IsLead="1" IsStd="1" Ver="1">60</PName>
<PName PID="49" CID="056" Value="Limburg" StdVal="Limburg" Lang="nl" Type="Full" IsLead="1" IsStd="1" Ver="1">61</PName>
<PName PID="49" CID="056" Value="VLI" StdVal="VLI" Lang="nl" Type="Short" IsLead="1" IsStd="1" Ver="1">62</PName>
<PName PID="50" CID="056" Value="Oost-Vlaanderen" StdVal="OostVlaanderen" Lang="nl" Type="Full" IsLead="1" IsStd="1" Ver="1">63</PName>
<PName PID="50" CID="056" Value="VOV" StdVal="VOV" Lang="nl" Type="Short" IsLead="1" IsStd="1" Ver="1">64</PName>
<PName PID="51" CID="056" Value="VBR" StdVal="VBR" Lang="nl" Type="Short" IsLead="1" IsStd="1" Ver="1">65</PName>
<PName PID="51" CID="056" Value="Vlaams Brabant" StdVal="VlaamsBrabant" Lang="nl" Type="Full" IsLead="1" IsStd="1" Ver="1">66</PName>
<PName PID="52" CID="056" Value="VWV" StdVal="VWV" Lang="nl" Type="Short" IsLead="1" IsStd="1" Ver="1">67</PName>
<PName PID="52" CID="056" Value="West-Vlaanderen" StdVal="WestVlaanderen" Lang="nl" Type="Full" IsLead="1" IsStd="1" Ver="1">68</PName>
<PName PID="53" CID="100" Value="Blagoevgrad" StdVal="Blagoevgrad" Lang="bg" Type="Full" IsLead="1" IsStd="1" Ver="1">69</PName>
<PName PID="54" CID="100" Value="Burgas" StdVal="Burgas" Lang="bg" Type="Full" IsLead="1" IsStd="1" Ver="1">70</PName>
<PName PID="55" CID="100" Value="Dobrich" StdVal="Dobrich" Lang="bg" Type="Full" IsLead="1" IsStd="1" Ver="1">71</PName>
<PName PID="56" CID="100" Value="Gabrovo" StdVal="Gabrovo" Lang="bg" Type="Full" IsLead="1" IsStd="1" Ver="1">72</PName>
<PName PID="57" CID="100" Value="Haskovo" StdVal="Haskovo" Lang="bg" Type="Full" IsLead="1" IsStd="1" Ver="1">73</PName>
<PName PID="58" CID="100" Value="Kardzhali" StdVal="Kardzhali" Lang="bg" Type="Full" IsLead="1" IsStd="1" Ver="1">74</PName>
<PName PID="59" CID="100" Value="Kyustendil" StdVal="Kyustendil" Lang="bg" Type="Full" IsLead="1" IsStd="1" Ver="1">75</PName>
<PName PID="60" CID="100" Value="Lovech" StdVal="Lovech" Lang="bg" Type="Full" IsLead="1" IsStd="1" Ver="1">76</PName>
<PName PID="61" CID="100" Value="Montana" StdVal="Montana" Lang="bg" Type="Full" IsLead="1" IsStd="1" Ver="1">77</PName>
<PName PID="62" CID="100" Value="Pazardzhik" StdVal="Pazardzhik" Lang="bg" Type="Full" IsLead="1" IsStd="1" Ver="1">78</PName>
<PName PID="63" CID="100" Value="Pernik" StdVal="Pernik" Lang="bg" Type="Full" IsLead="1" IsStd="1" Ver="1">79</PName>
<PName PID="64" CID="100" Value="Pleven" StdVal="Pleven" Lang="bg" Type="Full" IsLead="1" IsStd="1" Ver="1">80</PName>
<PName PID="65" CID="100" Value="Plovdiv" StdVal="Plovdiv" Lang="bg" Type="Full" IsLead="1" IsStd="1" Ver="1">81</PName>
<PName PID="66" CID="100" Value="Razgrad" StdVal="Razgrad" Lang="bg" Type="Full" IsLead="1" IsStd="1" Ver="1">82</PName>
<PName PID="67" CID="100" Value="Ruse" StdVal="Ruse" Lang="bg" Type="Full" IsLead="1" IsStd="1" Ver="1">83</PName>
<PName PID="68" CID="100" Value="Shumen" StdVal="Shumen" Lang="bg" Type="Full" IsLead="1" IsStd="1" Ver="1">84</PName>
<PName PID="69" CID="100" Value="Silistra" StdVal="Silistra" Lang="bg" Type="Full" IsLead="1" IsStd="1" Ver="1">85</PName>
<PName PID="70" CID="100" Value="Sliven" StdVal="Sliven" Lang="bg" Type="Full" IsLead="1" IsStd="1" Ver="1">86</PName>
<PName PID="71" CID="100" Value="Smolyan" StdVal="Smolyan" Lang="bg" Type="Full" IsLead="1" IsStd="1" Ver="1">87</PName>
<PName PID="72" CID="100" Value="Sofia" StdVal="Sofia" Lang="bg" Type="Full" IsLead="1" IsStd="1" Ver="1">88</PName>
<PName PID="73" CID="100" Value="Sofia-Grad" StdVal="SofiaGrad" Lang="bg" Type="Full" IsLead="1" IsStd="1" Ver="1">89</PName>
<PName PID="74" CID="100" Value="Stara Zagora" StdVal="StaraZagora" Lang="bg" Type="Full" IsLead="1" IsStd="1" Ver="1">90</PName>
<PName PID="75" CID="100" Value="Targovishte" StdVal="Targovishte" Lang="bg" Type="Full" IsLead="1" IsStd="1" Ver="1">91</PName>
<PName PID="76" CID="100" Value="Varna" StdVal="Varna" Lang="bg" Type="Full" IsLead="1" IsStd="1" Ver="1">92</PName>
<PName PID="77" CID="100" Value="Veliko Tarnovo" StdVal="VelikoTarnovo" Lang="bg" Type="Full" IsLead="1" IsStd="1" Ver="1">93</PName>
<PName PID="78" CID="100" Value="Vidin" StdVal="Vidin" Lang="bg" Type="Full" IsLead="1" IsStd="1" Ver="1">94</PName>
<PName PID="79" CID="100" Value="Vratsa" StdVal="Vratsa" Lang="bg" Type="Full" IsLead="1" IsStd="1" Ver="1">95</PName>
<PName PID="80" CID="100" Value="Yambol" StdVal="Yambol" Lang="bg" Type="Full" IsLead="1" IsStd="1" Ver="1">96</PName>
<PName PID="91" CID="191" Value="Bjelovarsko-bilogors" StdVal="Bjelovarskobilogors" Lang="hr" Type="Full" IsLead="1" IsStd="1" Ver="1">131</PName>
<PName PID="92" CID="191" Value="Brodsko-posavska" StdVal="Brodskoposavska" Lang="hr" Type="Full" IsLead="1" IsStd="1" Ver="1">132</PName>
<PName PID="92" CID="191" Value="Brodsko-posavska žup" StdVal="Brodskoposavskažup" Lang="hr" Type="Full" IsLead="0" IsStd="1" Ver="1">133</PName>
<PName PID="93" CID="191" Value="Dubrovačko-neretvans" StdVal="Dubrovačkoneretvans" Lang="hr" Type="Full" IsLead="1" IsStd="1" Ver="1">134</PName>
<PName PID="93" CID="191" Value="Dubrovačko-neretvans" StdVal="Dubrovačkoneretvans" Lang="hr" Type="Full" IsLead="0" IsStd="1" Ver="1">135</PName>
<PName PID="94" CID="191" Value="Grad Zagreb" StdVal="GradZagreb" Lang="hr" Type="Full" IsLead="1" IsStd="1" Ver="1">136</PName>
<PName PID="95" CID="191" Value="Istarska" StdVal="Istarska" Lang="hr" Type="Full" IsLead="1" IsStd="1" Ver="1">137</PName>
<PName PID="95" CID="191" Value="Istarska županija" StdVal="Istarskažupanija" Lang="hr" Type="Full" IsLead="0" IsStd="1" Ver="1">138</PName>
<PName PID="96" CID="191" Value="Karlovačka" StdVal="Karlovačka" Lang="hr" Type="Full" IsLead="1" IsStd="1" Ver="1">139</PName>
<PName PID="96" CID="191" Value="Karlovačka županija" StdVal="Karlovačkažupanija" Lang="hr" Type="Full" IsLead="0" IsStd="1" Ver="1">140</PName>
<PName PID="97" CID="191" Value="Koprivničko-križevač" StdVal="Koprivničkokriževač" Lang="hr" Type="Full" IsLead="1" IsStd="1" Ver="1">141</PName>
<PName PID="98" CID="191" Value="Krapinsko-zagorska" StdVal="Krapinskozagorska" Lang="hr" Type="Full" IsLead="1" IsStd="1" Ver="1">142</PName>
<PName PID="98" CID="191" Value="Krapinsko-zagorska ž" StdVal="Krapinskozagorskaž" Lang="hr" Type="Full" IsLead="0" IsStd="1" Ver="1">143</PName>
<PName PID="99" CID="191" Value="Ličko-senjska" StdVal="Ličkosenjska" Lang="hr" Type="Full" IsLead="1" IsStd="1" Ver="1">144</PName>
<PName PID="99" CID="191" Value="Ličko-senjska župani" StdVal="Ličkosenjskažupani" Lang="hr" Type="Full" IsLead="0" IsStd="1" Ver="1">145</PName>
<PName PID="100" CID="191" Value="Međimurska" StdVal="Međimurska" Lang="hr" Type="Full" IsLead="1" IsStd="1" Ver="1">146</PName>
<PName PID="100" CID="191" Value="Međimurska županija" StdVal="Međimurskažupanija" Lang="hr" Type="Full" IsLead="0" IsStd="1" Ver="1">147</PName>
<PName PID="101" CID="191" Value="Osječko-baranjska" StdVal="Osječkobaranjska" Lang="hr" Type="Full" IsLead="1" IsStd="1" Ver="1">148</PName>
<PName PID="101" CID="191" Value="Osječko-baranjska žu" StdVal="Osječkobaranjskažu" Lang="hr" Type="Full" IsLead="0" IsStd="1" Ver="1">149</PName>
<PName PID="102" CID="191" Value="Požeško-slavonska" StdVal="Požeškoslavonska" Lang="hr" Type="Full" IsLead="1" IsStd="1" Ver="1">150</PName>
<PName PID="102" CID="191" Value="Požeško-slavonska žu" StdVal="Požeškoslavonskažu" Lang="hr" Type="Full" IsLead="0" IsStd="1" Ver="1">151</PName>
<PName PID="103" CID="191" Value="Primorsko-goranska" StdVal="Primorskogoranska" Lang="hr" Type="Full" IsLead="1" IsStd="1" Ver="1">152</PName>
<PName PID="103" CID="191" Value="Primorsko-goranska ž" StdVal="Primorskogoranskaž" Lang="hr" Type="Full" IsLead="0" IsStd="1" Ver="1">153</PName>
<PName PID="104" CID="191" Value="Šibensko-kninska" StdVal="Šibenskokninska" Lang="hr" Type="Full" IsLead="1" IsStd="1" Ver="1">154</PName>
<PName PID="104" CID="191" Value="Šibensko-kninska žup" StdVal="Šibenskokninskažup" Lang="hr" Type="Full" IsLead="0" IsStd="1" Ver="1">155</PName>
<PName PID="105" CID="191" Value="Sisačko-moslavačka" StdVal="Sisačkomoslavačka" Lang="hr" Type="Full" IsLead="1" IsStd="1" Ver="1">156</PName>
<PName PID="105" CID="191" Value="Sisačko-moslavačka ž" StdVal="Sisačkomoslavačkaž" Lang="hr" Type="Full" IsLead="0" IsStd="1" Ver="1">157</PName>
<PName PID="106" CID="191" Value="Splitsko-dalmatinska" StdVal="Splitskodalmatinska" Lang="hr" Type="Full" IsLead="1" IsStd="1" Ver="1">158</PName>
<PName PID="107" CID="191" Value="Varaždinska" StdVal="Varaždinska" Lang="hr" Type="Full" IsLead="1" IsStd="1" Ver="1">159</PName>
<PName PID="107" CID="191" Value="Varaždinska županija" StdVal="Varaždinskažupanija" Lang="hr" Type="Full" IsLead="0" IsStd="1" Ver="1">160</PName>
<PName PID="108" CID="191" Value="Virovitičko-podravsk" StdVal="Virovitičkopodravsk" Lang="hr" Type="Full" IsLead="1" IsStd="1" Ver="1">161</PName>
<PName PID="109" CID="191" Value="Vukovarsko-srijemska" StdVal="Vukovarskosrijemska" Lang="hr" Type="Full" IsLead="1" IsStd="1" Ver="1">162</PName>
<PName PID="110" CID="191" Value="Zadarska" StdVal="Zadarska" Lang="hr" Type="Full" IsLead="1" IsStd="1" Ver="1">163</PName>
<PName PID="110" CID="191" Value="Zadarska županija" StdVal="Zadarskažupanija" Lang="hr" Type="Full" IsLead="0" IsStd="1" Ver="1">164</PName>
<PName PID="111" CID="191" Value="Zagrebačka" StdVal="Zagrebačka" Lang="hr" Type="Full" IsLead="1" IsStd="1" Ver="1">165</PName>
<PName PID="111" CID="191" Value="Zagrebačka županija" StdVal="Zagrebačkažupanija" Lang="hr" Type="Full" IsLead="0" IsStd="1" Ver="1">166</PName>
<PName PID="126" CID="233" Value="Harjumaa" StdVal="Harjumaa" Lang="et" Type="Full" IsLead="1" IsStd="1" Ver="1">183</PName>
<PName PID="127" CID="233" Value="Hiiumaa" StdVal="Hiiumaa" Lang="et" Type="Full" IsLead="1" IsStd="1" Ver="1">184</PName>
<PName PID="128" CID="233" Value="Ida-Virumaa" StdVal="IdaVirumaa" Lang="et" Type="Full" IsLead="1" IsStd="1" Ver="1">185</PName>
<PName PID="129" CID="233" Value="Järvamaa" StdVal="Järvamaa" Lang="et" Type="Full" IsLead="1" IsStd="1" Ver="1">186</PName>
<PName PID="130" CID="233" Value="Jõgevamaa" StdVal="Jõgevamaa" Lang="et" Type="Full" IsLead="1" IsStd="1" Ver="1">187</PName>
<PName PID="131" CID="233" Value="Läänemaa" StdVal="Läänemaa" Lang="et" Type="Full" IsLead="1" IsStd="1" Ver="1">188</PName>
<PName PID="132" CID="233" Value="Lääne-Virumaa" StdVal="LääneVirumaa" Lang="et" Type="Full" IsLead="1" IsStd="1" Ver="1">189</PName>
<PName PID="133" CID="233" Value="Pärnumaa" StdVal="Pärnumaa" Lang="et" Type="Full" IsLead="1" IsStd="1" Ver="1">190</PName>
<PName PID="134" CID="233" Value="Põlvamaa" StdVal="Põlvamaa" Lang="et" Type="Full" IsLead="1" IsStd="1" Ver="1">191</PName>
<PName PID="135" CID="233" Value="Raplamaa" StdVal="Raplamaa" Lang="et" Type="Full" IsLead="1" IsStd="1" Ver="1">192</PName>
<PName PID="136" CID="233" Value="Saaremaa" StdVal="Saaremaa" Lang="et" Type="Full" IsLead="1" IsStd="1" Ver="1">193</PName>
<PName PID="137" CID="233" Value="Tartumaa" StdVal="Tartumaa" Lang="et" Type="Full" IsLead="1" IsStd="1" Ver="1">194</PName>
<PName PID="138" CID="233" Value="Valgamaa" StdVal="Valgamaa" Lang="et" Type="Full" IsLead="1" IsStd="1" Ver="1">195</PName>
<PName PID="139" CID="233" Value="Viljandimaa" StdVal="Viljandimaa" Lang="et" Type="Full" IsLead="1" IsStd="1" Ver="1">196</PName>
<PName PID="140" CID="233" Value="Võrumaa" StdVal="Võrumaa" Lang="et" Type="Full" IsLead="1" IsStd="1" Ver="1">197</PName>
<PName PID="147" CID="300" Value="Achaïa" StdVal="Achaïa" Lang="el" Type="Full" IsLead="1" IsStd="1" Ver="1">216</PName>
<PName PID="148" CID="300" Value="Aitolia-Akarnania" StdVal="AitoliaAkarnania" Lang="el" Type="Full" IsLead="1" IsStd="1" Ver="1">217</PName>
<PName PID="149" CID="300" Value="Argolis" StdVal="Argolis" Lang="el" Type="Full" IsLead="1" IsStd="1" Ver="1">218</PName>
<PName PID="150" CID="300" Value="Arkadia" StdVal="Arkadia" Lang="el" Type="Full" IsLead="1" IsStd="1" Ver="1">219</PName>
<PName PID="151" CID="300" Value="Arta" StdVal="Arta" Lang="el" Type="Full" IsLead="1" IsStd="1" Ver="1">220</PName>
<PName PID="152" CID="300" Value="Attiki" StdVal="Attiki" Lang="el" Type="Full" IsLead="1" IsStd="1" Ver="1">221</PName>
<PName PID="153" CID="300" Value="Chalkidiki" StdVal="Chalkidiki" Lang="el" Type="Full" IsLead="1" IsStd="1" Ver="1">222</PName>
<PName PID="154" CID="300" Value="Chania" StdVal="Chania" Lang="el" Type="Full" IsLead="1" IsStd="1" Ver="1">223</PName>
<PName PID="155" CID="300" Value="Chios" StdVal="Chios" Lang="el" Type="Full" IsLead="1" IsStd="1" Ver="1">224</PName>
<PName PID="156" CID="300" Value="Dodekanisos" StdVal="Dodekanisos" Lang="el" Type="Full" IsLead="1" IsStd="1" Ver="1">225</PName>
<PName PID="157" CID="300" Value="Drama" StdVal="Drama" Lang="el" Type="Full" IsLead="1" IsStd="1" Ver="1">226</PName>
<PName PID="158" CID="300" Value="Evros" StdVal="Evros" Lang="el" Type="Full" IsLead="1" IsStd="1" Ver="1">227</PName>
<PName PID="159" CID="300" Value="Evrytania" StdVal="Evrytania" Lang="el" Type="Full" IsLead="1" IsStd="1" Ver="1">228</PName>
<PName PID="160" CID="300" Value="Evvoia" StdVal="Evvoia" Lang="el" Type="Full" IsLead="1" IsStd="1" Ver="1">229</PName>
<PName PID="161" CID="300" Value="Florina" StdVal="Florina" Lang="el" Type="Full" IsLead="1" IsStd="1" Ver="1">230</PName>
<PName PID="162" CID="300" Value="Fokis" StdVal="Fokis" Lang="el" Type="Full" IsLead="1" IsStd="1" Ver="1">231</PName>
<PName PID="163" CID="300" Value="Fthiotis" StdVal="Fthiotis" Lang="el" Type="Full" IsLead="1" IsStd="1" Ver="1">232</PName>
<PName PID="164" CID="300" Value="Grevena" StdVal="Grevena" Lang="el" Type="Full" IsLead="1" IsStd="1" Ver="1">233</PName>
<PName PID="165" CID="300" Value="Ileia" StdVal="Ileia" Lang="el" Type="Full" IsLead="1" IsStd="1" Ver="1">234</PName>
<PName PID="166" CID="300" Value="Imathia" StdVal="Imathia" Lang="el" Type="Full" IsLead="1" IsStd="1" Ver="1">235</PName>
<PName PID="167" CID="300" Value="Ioannina" StdVal="Ioannina" Lang="el" Type="Full" IsLead="1" IsStd="1" Ver="1">236</PName>
<PName PID="168" CID="300" Value="Irakleion" StdVal="Irakleion" Lang="el" Type="Full" IsLead="1" IsStd="1" Ver="1">237</PName>
<PName PID="169" CID="300" Value="Karditsa" StdVal="Karditsa" Lang="el" Type="Full" IsLead="1" IsStd="1" Ver="1">238</PName>
<PName PID="170" CID="300" Value="Kastoria" StdVal="Kastoria" Lang="el" Type="Full" IsLead="1" IsStd="1" Ver="1">239</PName>
<PName PID="171" CID="300" Value="Kavalla" StdVal="Kavalla" Lang="el" Type="Full" IsLead="1" IsStd="1" Ver="1">240</PName>
<PName PID="172" CID="300" Value="Kefallinia" StdVal="Kefallinia" Lang="el" Type="Full" IsLead="1" IsStd="1" Ver="1">241</PName>
<PName PID="173" CID="300" Value="Kerkyra" StdVal="Kerkyra" Lang="el" Type="Full" IsLead="1" IsStd="1" Ver="1">242</PName>
<PName PID="174" CID="300" Value="Kilkis" StdVal="Kilkis" Lang="el" Type="Full" IsLead="1" IsStd="1" Ver="1">243</PName>
<PName PID="175" CID="300" Value="Korinthia" StdVal="Korinthia" Lang="el" Type="Full" IsLead="1" IsStd="1" Ver="1">244</PName>
<PName PID="176" CID="300" Value="Kozani" StdVal="Kozani" Lang="el" Type="Full" IsLead="1" IsStd="1" Ver="1">245</PName>
<PName PID="177" CID="300" Value="Kyklades" StdVal="Kyklades" Lang="el" Type="Full" IsLead="1" IsStd="1" Ver="1">246</PName>
<PName PID="178" CID="300" Value="Lakonia" StdVal="Lakonia" Lang="el" Type="Full" IsLead="1" IsStd="1" Ver="1">247</PName>
<PName PID="179" CID="300" Value="Larisa" StdVal="Larisa" Lang="el" Type="Full" IsLead="1" IsStd="1" Ver="1">248</PName>
<PName PID="180" CID="300" Value="Lasithion" StdVal="Lasithion" Lang="el" Type="Full" IsLead="1" IsStd="1" Ver="1">249</PName>
<PName PID="181" CID="300" Value="Lefkas" StdVal="Lefkas" Lang="el" Type="Full" IsLead="1" IsStd="1" Ver="1">250</PName>
<PName PID="182" CID="300" Value="Lesvos" StdVal="Lesvos" Lang="el" Type="Full" IsLead="1" IsStd="1" Ver="1">251</PName>
<PName PID="183" CID="300" Value="Magnisia" StdVal="Magnisia" Lang="el" Type="Full" IsLead="1" IsStd="1" Ver="1">252</PName>
<PName PID="184" CID="300" Value="Messinia" StdVal="Messinia" Lang="el" Type="Full" IsLead="1" IsStd="1" Ver="1">253</PName>
<PName PID="185" CID="300" Value="Pella" StdVal="Pella" Lang="el" Type="Full" IsLead="1" IsStd="1" Ver="1">254</PName>
<PName PID="186" CID="300" Value="Pieria" StdVal="Pieria" Lang="el" Type="Full" IsLead="1" IsStd="1" Ver="1">255</PName>
<PName PID="187" CID="300" Value="Preveza" StdVal="Preveza" Lang="el" Type="Full" IsLead="1" IsStd="1" Ver="1">256</PName>
<PName PID="188" CID="300" Value="Rethymnon" StdVal="Rethymnon" Lang="el" Type="Full" IsLead="1" IsStd="1" Ver="1">257</PName>
<PName PID="189" CID="300" Value="Rodopi" StdVal="Rodopi" Lang="el" Type="Full" IsLead="1" IsStd="1" Ver="1">258</PName>
<PName PID="190" CID="300" Value="Samos" StdVal="Samos" Lang="el" Type="Full" IsLead="1" IsStd="1" Ver="1">259</PName>
<PName PID="191" CID="300" Value="Serrai" StdVal="Serrai" Lang="el" Type="Full" IsLead="1" IsStd="1" Ver="1">260</PName>
<PName PID="192" CID="300" Value="Thesprotia" StdVal="Thesprotia" Lang="el" Type="Full" IsLead="1" IsStd="1" Ver="1">261</PName>
<PName PID="193" CID="300" Value="Thessaloniki" StdVal="Thessaloniki" Lang="el" Type="Full" IsLead="1" IsStd="1" Ver="1">262</PName>
<PName PID="194" CID="300" Value="Trikala" StdVal="Trikala" Lang="el" Type="Full" IsLead="1" IsStd="1" Ver="1">263</PName>
<PName PID="195" CID="300" Value="Voiotia" StdVal="Voiotia" Lang="el" Type="Full" IsLead="1" IsStd="1" Ver="1">264</PName>
<PName PID="196" CID="300" Value="Xanthi" StdVal="Xanthi" Lang="el" Type="Full" IsLead="1" IsStd="1" Ver="1">265</PName>
<PName PID="197" CID="300" Value="Zakynthos" StdVal="Zakynthos" Lang="el" Type="Full" IsLead="1" IsStd="1" Ver="1">266</PName>
<PName PID="217" CID="352" Value="Austurland" StdVal="Austurland" Lang="is" Type="Full" IsLead="1" IsStd="1" Ver="1">306</PName>
<PName PID="218" CID="352" Value="Höfuðborgarsvæði" StdVal="Höfuðborgarsvæði" Lang="is" Type="Full" IsLead="1" IsStd="1" Ver="1">307</PName>
<PName PID="218" CID="352" Value="Höfuðborgarsvæði uta" StdVal="Höfuðborgarsvæðiuta" Lang="is" Type="Full" IsLead="0" IsStd="1" Ver="1">308</PName>
<PName PID="219" CID="352" Value="Norðurland eystra" StdVal="Norðurlandeystra" Lang="is" Type="Full" IsLead="1" IsStd="1" Ver="1">309</PName>
<PName PID="220" CID="352" Value="Norðurland vestra" StdVal="Norðurlandvestra" Lang="is" Type="Full" IsLead="1" IsStd="1" Ver="1">310</PName>
<PName PID="221" CID="352" Value="Reykjavík" StdVal="Reykjavík" Lang="is" Type="Full" IsLead="1" IsStd="1" Ver="1">311</PName>
<PName PID="222" CID="352" Value="Suðurland" StdVal="Suðurland" Lang="is" Type="Full" IsLead="1" IsStd="1" Ver="1">312</PName>
<PName PID="223" CID="352" Value="Suðurnes" StdVal="Suðurnes" Lang="is" Type="Full" IsLead="1" IsStd="1" Ver="1">313</PName>
<PName PID="224" CID="352" Value="Vestfirðir" StdVal="Vestfirðir" Lang="is" Type="Full" IsLead="1" IsStd="1" Ver="1">314</PName>
<PName PID="225" CID="352" Value="Vesturland" StdVal="Vesturland" Lang="is" Type="Full" IsLead="1" IsStd="1" Ver="1">315</PName>
<PName PID="226" CID="372" Value="Ceatharlach" StdVal="Ceatharlach" Lang="ga" Type="Full" IsLead="1" IsStd="1" Ver="1">317</PName>
<PName PID="227" CID="372" Value="An Cabhán" StdVal="AnCabhán" Lang="ga" Type="Full" IsLead="1" IsStd="1" Ver="1">319</PName>
<PName PID="228" CID="372" Value="An Clár" StdVal="AnClár" Lang="ga" Type="Full" IsLead="1" IsStd="1" Ver="1">321</PName>
<PName PID="229" CID="372" Value="Corcaigh" StdVal="Corcaigh" Lang="ga" Type="Full" IsLead="1" IsStd="1" Ver="1">323</PName>
<PName PID="230" CID="372" Value="Dún na nGall" StdVal="DúnnanGall" Lang="ga" Type="Full" IsLead="1" IsStd="1" Ver="1">325</PName>
<PName PID="231" CID="372" Value="Baile Átha Cliath" StdVal="BaileÁthaCliath" Lang="ga" Type="Full" IsLead="1" IsStd="1" Ver="1">327</PName>
<PName PID="232" CID="372" Value="Gaillimh" StdVal="Gaillimh" Lang="ga" Type="Full" IsLead="1" IsStd="1" Ver="1">329</PName>
<PName PID="233" CID="372" Value="Ciarraí" StdVal="Ciarraí" Lang="ga" Type="Full" IsLead="1" IsStd="1" Ver="1">331</PName>
<PName PID="234" CID="372" Value="Cill Dara" StdVal="CillDara" Lang="ga" Type="Full" IsLead="1" IsStd="1" Ver="1">333</PName>
<PName PID="235" CID="372" Value="Cill Chainnigh" StdVal="CillChainnigh" Lang="ga" Type="Full" IsLead="1" IsStd="1" Ver="1">335</PName>
<PName PID="237" CID="372" Value="Liatroim" StdVal="Liatroim" Lang="ga" Type="Full" IsLead="1" IsStd="1" Ver="1">338</PName>
<PName PID="238" CID="372" Value="Luimneach" StdVal="Luimneach" Lang="ga" Type="Full" IsLead="1" IsStd="1" Ver="1">340</PName>
<PName PID="239" CID="372" Value="An Longfort" StdVal="AnLongfort" Lang="ga" Type="Full" IsLead="1" IsStd="1" Ver="1">342</PName>
<PName PID="240" CID="372" Value="Lú" StdVal="Lú" Lang="ga" Type="Full" IsLead="1" IsStd="1" Ver="1">344</PName>
<PName PID="241" CID="372" Value="Maigh Eo" StdVal="MaighEo" Lang="ga" Type="Full" IsLead="1" IsStd="1" Ver="1">346</PName>
<PName PID="242" CID="372" Value="An Mhí" StdVal="AnMhí" Lang="ga" Type="Full" IsLead="1" IsStd="1" Ver="1">348</PName>
<PName PID="243" CID="372" Value="Muineachán" StdVal="Muineachán" Lang="ga" Type="Full" IsLead="1" IsStd="1" Ver="1">350</PName>
<PName PID="244" CID="372" Value="Uíbh Fhailí" StdVal="UíbhFhailí" Lang="ga" Type="Full" IsLead="1" IsStd="1" Ver="1">352</PName>
<PName PID="245" CID="372" Value="Ros Comáin" StdVal="RosComáin" Lang="ga" Type="Full" IsLead="1" IsStd="1" Ver="1">354</PName>
<PName PID="246" CID="372" Value="Sligeach" StdVal="Sligeach" Lang="ga" Type="Full" IsLead="1" IsStd="1" Ver="1">356</PName>
<PName PID="247" CID="372" Value="Tiobraid Árann" StdVal="TiobraidÁrann" Lang="ga" Type="Full" IsLead="1" IsStd="1" Ver="1">358</PName>
<PName PID="248" CID="372" Value="Port Láirge" StdVal="PortLáirge" Lang="ga" Type="Full" IsLead="1" IsStd="1" Ver="1">360</PName>
<PName PID="249" CID="372" Value="An Iarmhí" StdVal="AnIarmhí" Lang="ga" Type="Full" IsLead="1" IsStd="1" Ver="1">362</PName>
<PName PID="250" CID="372" Value="Loch Garman" StdVal="LochGarman" Lang="ga" Type="Full" IsLead="1" IsStd="1" Ver="1">364</PName>
<PName PID="251" CID="372" Value="Cill Mhantáin" StdVal="CillMhantáin" Lang="ga" Type="Full" IsLead="1" IsStd="1" Ver="1">366</PName>
<PName PID="360" CID="428" Value="Aizkraukles Apriņķis" StdVal="AizkrauklesApriņķis" Lang="lv" Type="Full" IsLead="1" IsStd="1" Ver="1">579</PName>
<PName PID="361" CID="428" Value="Alūksnes Apriņķis" StdVal="AlūksnesApriņķis" Lang="lv" Type="Full" IsLead="1" IsStd="1" Ver="1">580</PName>
<PName PID="362" CID="428" Value="Balvu Apriņķis" StdVal="BalvuApriņķis" Lang="lv" Type="Full" IsLead="1" IsStd="1" Ver="1">581</PName>
<PName PID="363" CID="428" Value="Bauskas Apriņķis" StdVal="BauskasApriņķis" Lang="lv" Type="Full" IsLead="1" IsStd="1" Ver="1">582</PName>
<PName PID="364" CID="428" Value="Cēsu Apriņķis" StdVal="CēsuApriņķis" Lang="lv" Type="Full" IsLead="1" IsStd="1" Ver="1">583</PName>
<PName PID="365" CID="428" Value="Daugavpils Apriņķis" StdVal="DaugavpilsApriņķis" Lang="lv" Type="Full" IsLead="1" IsStd="1" Ver="1">584</PName>
<PName PID="366" CID="428" Value="Dobeles Apriņķis" StdVal="DobelesApriņķis" Lang="lv" Type="Full" IsLead="1" IsStd="1" Ver="1">585</PName>
<PName PID="367" CID="428" Value="Gulbenes Apriņķis" StdVal="GulbenesApriņķis" Lang="lv" Type="Full" IsLead="1" IsStd="1" Ver="1">586</PName>
<PName PID="368" CID="428" Value="Jēkabpils Apriņķis" StdVal="JēkabpilsApriņķis" Lang="lv" Type="Full" IsLead="1" IsStd="1" Ver="1">587</PName>
<PName PID="369" CID="428" Value="Jelgavas Apriņķis" StdVal="JelgavasApriņķis" Lang="lv" Type="Full" IsLead="1" IsStd="1" Ver="1">588</PName>
<PName PID="370" CID="428" Value="Krāslavas Apriņķis" StdVal="KrāslavasApriņķis" Lang="lv" Type="Full" IsLead="1" IsStd="1" Ver="1">589</PName>
<PName PID="371" CID="428" Value="Kuldīgas Apriņķis" StdVal="KuldīgasApriņķis" Lang="lv" Type="Full" IsLead="1" IsStd="1" Ver="1">590</PName>
<PName PID="372" CID="428" Value="Liepājas Apriņķis" StdVal="LiepājasApriņķis" Lang="lv" Type="Full" IsLead="1" IsStd="1" Ver="1">591</PName>
<PName PID="373" CID="428" Value="Limbažu Apriņķis" StdVal="LimbažuApriņķis" Lang="lv" Type="Full" IsLead="1" IsStd="1" Ver="1">592</PName>
<PName PID="374" CID="428" Value="Ludzas Apriņķis" StdVal="LudzasApriņķis" Lang="lv" Type="Full" IsLead="1" IsStd="1" Ver="1">593</PName>
<PName PID="375" CID="428" Value="Madonas Apriņķis" StdVal="MadonasApriņķis" Lang="lv" Type="Full" IsLead="1" IsStd="1" Ver="1">594</PName>
<PName PID="376" CID="428" Value="Ogres Apriņķis" StdVal="OgresApriņķis" Lang="lv" Type="Full" IsLead="1" IsStd="1" Ver="1">595</PName>
<PName PID="377" CID="428" Value="Preiļu Apriņķis" StdVal="PreiļuApriņķis" Lang="lv" Type="Full" IsLead="1" IsStd="1" Ver="1">596</PName>
<PName PID="378" CID="428" Value="Rēzeknes Apriņķis" StdVal="RēzeknesApriņķis" Lang="lv" Type="Full" IsLead="1" IsStd="1" Ver="1">597</PName>
<PName PID="379" CID="428" Value="Rīgas Apriņķis" StdVal="RīgasApriņķis" Lang="lv" Type="Full" IsLead="1" IsStd="1" Ver="1">598</PName>
<PName PID="380" CID="428" Value="Saldus Apriņķis" StdVal="SaldusApriņķis" Lang="lv" Type="Full" IsLead="1" IsStd="1" Ver="1">599</PName>
<PName PID="381" CID="428" Value="Talsu Apriņķis" StdVal="TalsuApriņķis" Lang="lv" Type="Full" IsLead="1" IsStd="1" Ver="1">600</PName>
<PName PID="382" CID="428" Value="Tukuma Apriņķis" StdVal="TukumaApriņķis" Lang="lv" Type="Full" IsLead="1" IsStd="1" Ver="1">601</PName>
<PName PID="383" CID="428" Value="Valkas Apriņķis" StdVal="ValkasApriņķis" Lang="lv" Type="Full" IsLead="1" IsStd="1" Ver="1">602</PName>
<PName PID="384" CID="428" Value="Valmieras Apriņķis" StdVal="ValmierasApriņķis" Lang="lv" Type="Full" IsLead="1" IsStd="1" Ver="1">603</PName>
<PName PID="385" CID="428" Value="Ventpils Apriņķis" StdVal="VentpilsApriņķis" Lang="lv" Type="Full" IsLead="1" IsStd="1" Ver="1">604</PName>
<PName PID="386" CID="440" Value="Alytaus Apskritis" StdVal="AlytausApskritis" Lang="lt" Type="Full" IsLead="1" IsStd="1" Ver="1">605</PName>
<PName PID="387" CID="440" Value="Kauno Apskritis" StdVal="KaunoApskritis" Lang="lt" Type="Full" IsLead="1" IsStd="1" Ver="1">606</PName>
<PName PID="388" CID="440" Value="Klaipėdos Apskritis" StdVal="KlaipėdosApskritis" Lang="lt" Type="Full" IsLead="1" IsStd="1" Ver="1">607</PName>
<PName PID="389" CID="440" Value="Marijampolės" StdVal="Marijampolės" Lang="lt" Type="Full" IsLead="1" IsStd="1" Ver="1">608</PName>
<PName PID="389" CID="440" Value="Marijampolės Apskrit" StdVal="MarijampolėsApskrit" Lang="lt" Type="Full" IsLead="0" IsStd="1" Ver="1">609</PName>
<PName PID="390" CID="440" Value="Panevėžio Apskritis" StdVal="PanevėžioApskritis" Lang="lt" Type="Full" IsLead="1" IsStd="1" Ver="1">610</PName>
<PName PID="391" CID="440" Value="Šiaulių Apskritis" StdVal="ŠiauliųApskritis" Lang="lt" Type="Full" IsLead="1" IsStd="1" Ver="1">611</PName>
<PName PID="392" CID="440" Value="Tauragės Apskritis" StdVal="TauragėsApskritis" Lang="lt" Type="Full" IsLead="1" IsStd="1" Ver="1">612</PName>
<PName PID="393" CID="440" Value="Telšių Apskritis" StdVal="TelšiųApskritis" Lang="lt" Type="Full" IsLead="1" IsStd="1" Ver="1">613</PName>
<PName PID="394" CID="440" Value="Utenos Apskritis" StdVal="UtenosApskritis" Lang="lt" Type="Full" IsLead="1" IsStd="1" Ver="1">614</PName>
<PName PID="395" CID="440" Value="Vilniaus Apskritis" StdVal="VilniausApskritis" Lang="lt" Type="Full" IsLead="1" IsStd="1" Ver="1">615</PName>
<PName PID="438" CID="528" Value="LI" StdVal="LI" Lang="nl" Type="Short" IsLead="1" IsStd="1" Ver="1">689</PName>
<PName PID="438" CID="528" Value="Limburg" StdVal="Limburg" Lang="nl" Type="Full" IsLead="1" IsStd="1" Ver="1">690</PName>
<PName PID="439" CID="528" Value="DR" StdVal="DR" Lang="nl" Type="Short" IsLead="1" IsStd="1" Ver="1">691</PName>
<PName PID="439" CID="528" Value="Drenthe" StdVal="Drenthe" Lang="nl" Type="Full" IsLead="1" IsStd="1" Ver="1">692</PName>
<PName PID="440" CID="528" Value="Flevoland" StdVal="Flevoland" Lang="nl" Type="Full" IsLead="1" IsStd="1" Ver="1">693</PName>
<PName PID="441" CID="528" Value="FR" StdVal="FR" Lang="nl" Type="Short" IsLead="1" IsStd="1" Ver="1">694</PName>
<PName PID="441" CID="528" Value="Fryslân" StdVal="Fryslân" Lang="nl" Type="Full" IsLead="1" IsStd="1" Ver="1">695</PName>
<PName PID="441" CID="528" Value="Friesland" StdVal="Friesland" Lang="nl" Type="Full" IsLead="0" IsStd="1" Ver="1">696</PName>
<PName PID="442" CID="528" Value="GE" StdVal="GE" Lang="nl" Type="Short" IsLead="1" IsStd="1" Ver="1">697</PName>
<PName PID="442" CID="528" Value="Gelderland" StdVal="Gelderland" Lang="nl" Type="Full" IsLead="1" IsStd="1" Ver="1">698</PName>
<PName PID="443" CID="528" Value="GR" StdVal="GR" Lang="nl" Type="Short" IsLead="1" IsStd="1" Ver="1">699</PName>
<PName PID="443" CID="528" Value="Groningen" StdVal="Groningen" Lang="nl" Type="Full" IsLead="1" IsStd="1" Ver="1">700</PName>
<PName PID="444" CID="528" Value="NB" StdVal="NB" Lang="nl" Type="Short" IsLead="1" IsStd="1" Ver="1">702</PName>
<PName PID="444" CID="528" Value="Noord-Brabant" StdVal="NoordBrabant" Lang="nl" Type="Full" IsLead="1" IsStd="1" Ver="1">703</PName>
<PName PID="445" CID="528" Value="NH" StdVal="NH" Lang="nl" Type="Short" IsLead="1" IsStd="1" Ver="1">704</PName>
<PName PID="445" CID="528" Value="Noord-Holland" StdVal="NoordHolland" Lang="nl" Type="Full" IsLead="1" IsStd="1" Ver="1">706</PName>
<PName PID="446" CID="528" Value="OV" StdVal="OV" Lang="nl" Type="Short" IsLead="1" IsStd="1" Ver="1">707</PName>
<PName PID="446" CID="528" Value="Overijssel" StdVal="Overijssel" Lang="nl" Type="Full" IsLead="1" IsStd="1" Ver="1">708</PName>
<PName PID="447" CID="528" Value="UT" StdVal="UT" Lang="nl" Type="Short" IsLead="1" IsStd="1" Ver="1">709</PName>
<PName PID="447" CID="528" Value="Utrecht" StdVal="Utrecht" Lang="nl" Type="Full" IsLead="1" IsStd="1" Ver="1">710</PName>
<PName PID="448" CID="528" Value="ZE" StdVal="ZE" Lang="nl" Type="Short" IsLead="1" IsStd="1" Ver="1">711</PName>
<PName PID="448" CID="528" Value="Zeeland" StdVal="Zeeland" Lang="nl" Type="Full" IsLead="1" IsStd="1" Ver="1">712</PName>
<PName PID="449" CID="528" Value="ZH" StdVal="ZH" Lang="nl" Type="Short" IsLead="1" IsStd="1" Ver="1">714</PName>
<PName PID="449" CID="528" Value="Zuid-Holland" StdVal="ZuidHolland" Lang="nl" Type="Full" IsLead="1" IsStd="1" Ver="1">715</PName>
<PName PID="466" CID="578" Value="Akershus" StdVal="Akershus" Lang="nb" Type="Full" IsLead="1" IsStd="1" Ver="1">748</PName>
<PName PID="467" CID="578" Value="Aust-Agder" StdVal="AustAgder" Lang="nb" Type="Full" IsLead="1" IsStd="1" Ver="1">749</PName>
<PName PID="468" CID="578" Value="Buskerud" StdVal="Buskerud" Lang="nb" Type="Full" IsLead="1" IsStd="1" Ver="1">750</PName>
<PName PID="469" CID="578" Value="Finnmark" StdVal="Finnmark" Lang="nb" Type="Full" IsLead="1" IsStd="1" Ver="1">751</PName>
<PName PID="469" CID="578" Value="Finnmárku" StdVal="Finnmárku" Lang="se" Type="Full" IsLead="1" IsStd="1" Ver="1">752</PName>
<PName PID="470" CID="578" Value="Hedmark" StdVal="Hedmark" Lang="nb" Type="Full" IsLead="1" IsStd="1" Ver="1">753</PName>
<PName PID="471" CID="578" Value="Hordaland" StdVal="Hordaland" Lang="nb" Type="Full" IsLead="1" IsStd="1" Ver="1">754</PName>
<PName PID="472" CID="578" Value="Møre og Romsdal" StdVal="MøreogRomsdal" Lang="nb" Type="Full" IsLead="1" IsStd="1" Ver="1">755</PName>
<PName PID="473" CID="578" Value="Nordland" StdVal="Nordland" Lang="nb" Type="Full" IsLead="1" IsStd="1" Ver="1">756</PName>
<PName PID="474" CID="578" Value="Nord-Trøndelag" StdVal="NordTrøndelag" Lang="nb" Type="Full" IsLead="1" IsStd="1" Ver="1">757</PName>
<PName PID="475" CID="578" Value="Oppland" StdVal="Oppland" Lang="nb" Type="Full" IsLead="1" IsStd="1" Ver="1">758</PName>
<PName PID="476" CID="578" Value="Oslo" StdVal="Oslo" Lang="nb" Type="Full" IsLead="1" IsStd="1" Ver="1">759</PName>
<PName PID="477" CID="578" Value="Østfold" StdVal="Østfold" Lang="nb" Type="Full" IsLead="1" IsStd="1" Ver="1">760</PName>
<PName PID="478" CID="578" Value="Rogaland" StdVal="Rogaland" Lang="nb" Type="Full" IsLead="1" IsStd="1" Ver="1">761</PName>
<PName PID="479" CID="578" Value="Sogn og Fjordane" StdVal="SognogFjordane" Lang="nb" Type="Full" IsLead="1" IsStd="1" Ver="1">762</PName>
<PName PID="480" CID="578" Value="Sør-Trøndelag" StdVal="SørTrøndelag" Lang="nb" Type="Full" IsLead="1" IsStd="1" Ver="1">763</PName>
<PName PID="481" CID="578" Value="Telemark" StdVal="Telemark" Lang="nb" Type="Full" IsLead="1" IsStd="1" Ver="1">764</PName>
<PName PID="482" CID="578" Value="Troms" StdVal="Troms" Lang="nb" Type="Full" IsLead="1" IsStd="1" Ver="1">765</PName>
<PName PID="482" CID="578" Value="Romsa" StdVal="Romsa" Lang="se" Type="Full" IsLead="1" IsStd="1" Ver="1">766</PName>
<PName PID="483" CID="578" Value="Vest-Agder" StdVal="VestAgder" Lang="nb" Type="Full" IsLead="1" IsStd="1" Ver="1">767</PName>
<PName PID="484" CID="578" Value="Vestfold" StdVal="Vestfold" Lang="nb" Type="Full" IsLead="1" IsStd="1" Ver="1">768</PName>
<PName PID="501" CID="620" Value="Aveiro" StdVal="Aveiro" Lang="pt" Type="Full" IsLead="1" IsStd="1" Ver="1">801</PName>
<PName PID="502" CID="620" Value="Beja" StdVal="Beja" Lang="pt" Type="Full" IsLead="1" IsStd="1" Ver="1">802</PName>
<PName PID="503" CID="620" Value="Braga" StdVal="Braga" Lang="pt" Type="Full" IsLead="1" IsStd="1" Ver="1">803</PName>
<PName PID="504" CID="620" Value="Bragança" StdVal="Bragança" Lang="pt" Type="Full" IsLead="1" IsStd="1" Ver="1">804</PName>
<PName PID="505" CID="620" Value="Castelo Branco" StdVal="CasteloBranco" Lang="pt" Type="Full" IsLead="1" IsStd="1" Ver="1">805</PName>
<PName PID="506" CID="620" Value="Coimbra" StdVal="Coimbra" Lang="pt" Type="Full" IsLead="1" IsStd="1" Ver="1">806</PName>
<PName PID="507" CID="620" Value="Évora" StdVal="Évora" Lang="pt" Type="Full" IsLead="1" IsStd="1" Ver="1">807</PName>
<PName PID="508" CID="620" Value="Faro" StdVal="Faro" Lang="pt" Type="Full" IsLead="1" IsStd="1" Ver="1">808</PName>
<PName PID="509" CID="620" Value="Guarda" StdVal="Guarda" Lang="pt" Type="Full" IsLead="1" IsStd="1" Ver="1">809</PName>
<PName PID="510" CID="620" Value="Leiria" StdVal="Leiria" Lang="pt" Type="Full" IsLead="1" IsStd="1" Ver="1">810</PName>
<PName PID="511" CID="620" Value="Lisboa" StdVal="Lisboa" Lang="pt" Type="Full" IsLead="1" IsStd="1" Ver="1">811</PName>
<PName PID="512" CID="620" Value="Portalegre" StdVal="Portalegre" Lang="pt" Type="Full" IsLead="1" IsStd="1" Ver="1">812</PName>
<PName PID="513" CID="620" Value="Porto" StdVal="Porto" Lang="pt" Type="Full" IsLead="1" IsStd="1" Ver="1">813</PName>
<PName PID="514" CID="620" Value="Santarém" StdVal="Santarém" Lang="pt" Type="Full" IsLead="1" IsStd="1" Ver="1">814</PName>
<PName PID="515" CID="620" Value="Setúbal" StdVal="Setúbal" Lang="pt" Type="Full" IsLead="1" IsStd="1" Ver="1">815</PName>
<PName PID="516" CID="620" Value="Viana do Castelo" StdVal="VianadoCastelo" Lang="pt" Type="Full" IsLead="1" IsStd="1" Ver="1">816</PName>
<PName PID="517" CID="620" Value="Vila Real" StdVal="VilaReal" Lang="pt" Type="Full" IsLead="1" IsStd="1" Ver="1">817</PName>
<PName PID="518" CID="620" Value="Viseu" StdVal="Viseu" Lang="pt" Type="Full" IsLead="1" IsStd="1" Ver="1">818</PName>
<PName PID="608" CID="705" Value="Ajdovščina" StdVal="Ajdovščina" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1012</PName>
<PName PID="609" CID="705" Value="Beltinci" StdVal="Beltinci" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1013</PName>
<PName PID="610" CID="705" Value="Benedikt" StdVal="Benedikt" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1014</PName>
<PName PID="611" CID="705" Value="Bistrica ob Sotli" StdVal="BistricaobSotli" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1015</PName>
<PName PID="612" CID="705" Value="Bled" StdVal="Bled" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1016</PName>
<PName PID="613" CID="705" Value="Bloke" StdVal="Bloke" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1017</PName>
<PName PID="614" CID="705" Value="Bohinj" StdVal="Bohinj" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1018</PName>
<PName PID="615" CID="705" Value="Borovnica" StdVal="Borovnica" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1019</PName>
<PName PID="616" CID="705" Value="Bovec" StdVal="Bovec" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1020</PName>
<PName PID="617" CID="705" Value="Braslovče" StdVal="Braslovče" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1021</PName>
<PName PID="618" CID="705" Value="Brda" StdVal="Brda" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1022</PName>
<PName PID="619" CID="705" Value="Brežice" StdVal="Brežice" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1023</PName>
<PName PID="620" CID="705" Value="Brezovica" StdVal="Brezovica" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1024</PName>
<PName PID="621" CID="705" Value="Cankova" StdVal="Cankova" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1025</PName>
<PName PID="622" CID="705" Value="Celje" StdVal="Celje" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1026</PName>
<PName PID="623" CID="705" Value="Cerklje na Gorenjske" StdVal="CerkljenaGorenjske" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1027</PName>
<PName PID="624" CID="705" Value="Cerknica" StdVal="Cerknica" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1028</PName>
<PName PID="625" CID="705" Value="Cerkno" StdVal="Cerkno" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1029</PName>
<PName PID="626" CID="705" Value="Cerkvenjak" StdVal="Cerkvenjak" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1030</PName>
<PName PID="627" CID="705" Value="Črenšovci" StdVal="Črenšovci" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1031</PName>
<PName PID="628" CID="705" Value="Črna na Koroškem" StdVal="ČrnanaKoroškem" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1032</PName>
<PName PID="629" CID="705" Value="Črnomelj" StdVal="Črnomelj" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1033</PName>
<PName PID="630" CID="705" Value="Destrnik" StdVal="Destrnik" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1034</PName>
<PName PID="631" CID="705" Value="Divača" StdVal="Divača" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1035</PName>
<PName PID="632" CID="705" Value="Dobje" StdVal="Dobje" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1036</PName>
<PName PID="633" CID="705" Value="Dobrepolje" StdVal="Dobrepolje" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1037</PName>
<PName PID="634" CID="705" Value="Dobrna" StdVal="Dobrna" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1038</PName>
<PName PID="635" CID="705" Value="Dobrova-Horjul-Polho" StdVal="DobrovaHorjulPolho" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1039</PName>
<PName PID="636" CID="705" Value="Dobrovnik" StdVal="Dobrovnik" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1040</PName>
<PName PID="637" CID="705" Value="Dol pri Ljubljani" StdVal="DolpriLjubljani" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1041</PName>
<PName PID="638" CID="705" Value="Dolenjske Toplice" StdVal="DolenjskeToplice" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1042</PName>
<PName PID="639" CID="705" Value="Domžale" StdVal="Domžale" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1043</PName>
<PName PID="640" CID="705" Value="Dornava" StdVal="Dornava" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1044</PName>
<PName PID="641" CID="705" Value="Dravograd" StdVal="Dravograd" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1045</PName>
<PName PID="642" CID="705" Value="Duplek" StdVal="Duplek" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1046</PName>
<PName PID="643" CID="705" Value="Gorenja vas-Poljane" StdVal="GorenjavasPoljane" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1047</PName>
<PName PID="644" CID="705" Value="Gorišnica" StdVal="Gorišnica" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1048</PName>
<PName PID="645" CID="705" Value="Gornja Radgona" StdVal="GornjaRadgona" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1049</PName>
<PName PID="646" CID="705" Value="Gornji Grad" StdVal="GornjiGrad" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1050</PName>
<PName PID="647" CID="705" Value="Gornji Petrovci" StdVal="GornjiPetrovci" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1051</PName>
<PName PID="648" CID="705" Value="Grad" StdVal="Grad" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1052</PName>
<PName PID="649" CID="705" Value="Grosuplje" StdVal="Grosuplje" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1053</PName>
<PName PID="650" CID="705" Value="Hajdina" StdVal="Hajdina" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1054</PName>
<PName PID="651" CID="705" Value="Hoče-Slivnica" StdVal="HočeSlivnica" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1055</PName>
<PName PID="652" CID="705" Value="Hodos" StdVal="Hodos" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1056</PName>
<PName PID="653" CID="705" Value="Hodoš" StdVal="Hodoš" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1057</PName>
<PName PID="654" CID="705" Value="Horjul" StdVal="Horjul" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1058</PName>
<PName PID="655" CID="705" Value="Hrastnik" StdVal="Hrastnik" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1059</PName>
<PName PID="656" CID="705" Value="Hrpelje-Kozina" StdVal="HrpeljeKozina" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1060</PName>
<PName PID="657" CID="705" Value="Idrija" StdVal="Idrija" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1061</PName>
<PName PID="658" CID="705" Value="Ig" StdVal="Ig" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1062</PName>
<PName PID="659" CID="705" Value="Ilirska Bistrica" StdVal="IlirskaBistrica" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1063</PName>
<PName PID="660" CID="705" Value="Ivančna Gorica" StdVal="IvančnaGorica" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1064</PName>
<PName PID="661" CID="705" Value="Isola" StdVal="Isola" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1065</PName>
<PName PID="661" CID="705" Value="Izola" StdVal="Izola" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1066</PName>
<PName PID="661" CID="705" Value="Izola/Isola" StdVal="IzolaIsola" Lang="sl" Type="Full" IsLead="0" IsStd="1" Ver="1">1067</PName>
<PName PID="662" CID="705" Value="Jesenice" StdVal="Jesenice" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1068</PName>
<PName PID="663" CID="705" Value="Jezersko" StdVal="Jezersko" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1069</PName>
<PName PID="664" CID="705" Value="Juršinci" StdVal="Juršinci" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1070</PName>
<PName PID="665" CID="705" Value="Kamnik" StdVal="Kamnik" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1071</PName>
<PName PID="666" CID="705" Value="Kanal" StdVal="Kanal" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1072</PName>
<PName PID="667" CID="705" Value="Kidričevo" StdVal="Kidričevo" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1073</PName>
<PName PID="668" CID="705" Value="Kobarid" StdVal="Kobarid" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1074</PName>
<PName PID="669" CID="705" Value="Kobilje" StdVal="Kobilje" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1075</PName>
<PName PID="670" CID="705" Value="Kočevje" StdVal="Kočevje" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1076</PName>
<PName PID="671" CID="705" Value="Komen" StdVal="Komen" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1077</PName>
<PName PID="672" CID="705" Value="Komenda" StdVal="Komenda" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1078</PName>
<PName PID="673" CID="705" Value="Koper" StdVal="Koper" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1080</PName>
<PName PID="674" CID="705" Value="Kostel" StdVal="Kostel" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1081</PName>
<PName PID="675" CID="705" Value="Kozje" StdVal="Kozje" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1082</PName>
<PName PID="676" CID="705" Value="Kranj" StdVal="Kranj" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1083</PName>
<PName PID="677" CID="705" Value="Kranjska Gora" StdVal="KranjskaGora" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1084</PName>
<PName PID="678" CID="705" Value="Križevci" StdVal="Križevci" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1085</PName>
<PName PID="679" CID="705" Value="Krško" StdVal="Krško" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1086</PName>
<PName PID="680" CID="705" Value="Kungota" StdVal="Kungota" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1087</PName>
<PName PID="681" CID="705" Value="Kuzma" StdVal="Kuzma" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1088</PName>
<PName PID="682" CID="705" Value="Laško" StdVal="Laško" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1089</PName>
<PName PID="683" CID="705" Value="Lenart" StdVal="Lenart" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1090</PName>
<PName PID="684" CID="705" Value="Lendava" StdVal="Lendava" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1091</PName>
<PName PID="685" CID="705" Value="Lendva" StdVal="Lendva" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1092</PName>
<PName PID="686" CID="705" Value="Litija" StdVal="Litija" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1093</PName>
<PName PID="687" CID="705" Value="Ljubljana" StdVal="Ljubljana" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1094</PName>
<PName PID="688" CID="705" Value="Ljubno" StdVal="Ljubno" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1095</PName>
<PName PID="689" CID="705" Value="Ljutomer" StdVal="Ljutomer" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1096</PName>
<PName PID="690" CID="705" Value="Logatec" StdVal="Logatec" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1097</PName>
<PName PID="691" CID="705" Value="Loška Dolina" StdVal="LoškaDolina" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1098</PName>
<PName PID="692" CID="705" Value="Loški Potok" StdVal="LoškiPotok" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1099</PName>
<PName PID="693" CID="705" Value="Lovrenc na Pohorju" StdVal="LovrencnaPohorju" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1100</PName>
<PName PID="694" CID="705" Value="Luče" StdVal="Luče" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1101</PName>
<PName PID="695" CID="705" Value="Lukovica" StdVal="Lukovica" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1102</PName>
<PName PID="696" CID="705" Value="Majšperk" StdVal="Majšperk" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1103</PName>
<PName PID="697" CID="705" Value="Maribor" StdVal="Maribor" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1104</PName>
<PName PID="698" CID="705" Value="Markovci" StdVal="Markovci" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1105</PName>
<PName PID="699" CID="705" Value="Medvode" StdVal="Medvode" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1106</PName>
<PName PID="700" CID="705" Value="Mengeš" StdVal="Mengeš" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1107</PName>
<PName PID="701" CID="705" Value="Metlika" StdVal="Metlika" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1108</PName>
<PName PID="702" CID="705" Value="Mežica" StdVal="Mežica" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1109</PName>
<PName PID="703" CID="705" Value="Miklavž na Dravskem" StdVal="MiklavžnaDravskem" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1110</PName>
<PName PID="704" CID="705" Value="Miren-Kostanjevica" StdVal="MirenKostanjevica" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1111</PName>
<PName PID="705" CID="705" Value="Mirna Peč" StdVal="MirnaPeč" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1112</PName>
<PName PID="706" CID="705" Value="Mislinja" StdVal="Mislinja" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1113</PName>
<PName PID="707" CID="705" Value="Moravče" StdVal="Moravče" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1114</PName>
<PName PID="708" CID="705" Value="Moravske Toplice" StdVal="MoravskeToplice" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1115</PName>
<PName PID="709" CID="705" Value="Mozirje" StdVal="Mozirje" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1116</PName>
<PName PID="710" CID="705" Value="Murska Sobota" StdVal="MurskaSobota" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1117</PName>
<PName PID="711" CID="705" Value="Muta" StdVal="Muta" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1118</PName>
<PName PID="712" CID="705" Value="Naklo" StdVal="Naklo" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1119</PName>
<PName PID="713" CID="705" Value="Nazarje" StdVal="Nazarje" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1120</PName>
<PName PID="714" CID="705" Value="Nova Gorica" StdVal="NovaGorica" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1121</PName>
<PName PID="715" CID="705" Value="Novo Mesto" StdVal="NovoMesto" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1122</PName>
<PName PID="716" CID="705" Value="Odranci" StdVal="Odranci" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1123</PName>
<PName PID="717" CID="705" Value="Oplotnica" StdVal="Oplotnica" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1124</PName>
<PName PID="718" CID="705" Value="Ormož" StdVal="Ormož" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1125</PName>
<PName PID="719" CID="705" Value="Osilnica" StdVal="Osilnica" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1126</PName>
<PName PID="720" CID="705" Value="Pesnica" StdVal="Pesnica" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1127</PName>
<PName PID="721" CID="705" Value="Piran" StdVal="Piran" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1128</PName>
<PName PID="722" CID="705" Value="Pirano" StdVal="Pirano" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1129</PName>
<PName PID="723" CID="705" Value="Pivka" StdVal="Pivka" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1130</PName>
<PName PID="724" CID="705" Value="Podčetrtek" StdVal="Podčetrtek" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1131</PName>
<PName PID="725" CID="705" Value="Podlehnik" StdVal="Podlehnik" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1132</PName>
<PName PID="726" CID="705" Value="Podvelka" StdVal="Podvelka" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1133</PName>
<PName PID="727" CID="705" Value="Polzela" StdVal="Polzela" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1134</PName>
<PName PID="728" CID="705" Value="Postojna" StdVal="Postojna" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1135</PName>
<PName PID="729" CID="705" Value="Prebold" StdVal="Prebold" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1136</PName>
<PName PID="730" CID="705" Value="Preddvor" StdVal="Preddvor" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1137</PName>
<PName PID="731" CID="705" Value="Prevalje" StdVal="Prevalje" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1138</PName>
<PName PID="732" CID="705" Value="Ptuj" StdVal="Ptuj" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1139</PName>
<PName PID="733" CID="705" Value="Puconci" StdVal="Puconci" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1140</PName>
<PName PID="734" CID="705" Value="Rače-Fram" StdVal="RačeFram" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1141</PName>
<PName PID="735" CID="705" Value="Radeče" StdVal="Radeče" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1142</PName>
<PName PID="736" CID="705" Value="Radenci" StdVal="Radenci" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1143</PName>
<PName PID="737" CID="705" Value="Radlje ob Dravi" StdVal="RadljeobDravi" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1144</PName>
<PName PID="738" CID="705" Value="Radovljica" StdVal="Radovljica" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1145</PName>
<PName PID="739" CID="705" Value="Ravne na Koroškem" StdVal="RavnenaKoroškem" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1146</PName>
<PName PID="740" CID="705" Value="Razkrižje" StdVal="Razkrižje" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1147</PName>
<PName PID="741" CID="705" Value="Ribnica" StdVal="Ribnica" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1148</PName>
<PName PID="742" CID="705" Value="Ribnica na Pohorju" StdVal="RibnicanaPohorju" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1149</PName>
<PName PID="743" CID="705" Value="Rogaška Slatina" StdVal="RogaškaSlatina" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1150</PName>
<PName PID="744" CID="705" Value="Rogašovci" StdVal="Rogašovci" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1151</PName>
<PName PID="745" CID="705" Value="Rogatec" StdVal="Rogatec" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1152</PName>
<PName PID="746" CID="705" Value="Ruše" StdVal="Ruše" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1153</PName>
<PName PID="747" CID="705" Value="Šalovci" StdVal="Šalovci" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1154</PName>
<PName PID="748" CID="705" Value="Selnica ob Dravi" StdVal="SelnicaobDravi" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1155</PName>
<PName PID="749" CID="705" Value="Semič" StdVal="Semič" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1156</PName>
<PName PID="750" CID="705" Value="Šempeter-Vrtojba" StdVal="ŠempeterVrtojba" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1157</PName>
<PName PID="751" CID="705" Value="Šenčur" StdVal="Šenčur" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1158</PName>
<PName PID="752" CID="705" Value="Šentilj" StdVal="Šentilj" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1159</PName>
<PName PID="753" CID="705" Value="Šentjernej" StdVal="Šentjernej" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1160</PName>
<PName PID="754" CID="705" Value="Šentjur pri Celju" StdVal="ŠentjurpriCelju" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1161</PName>
<PName PID="755" CID="705" Value="Sevnica" StdVal="Sevnica" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1162</PName>
<PName PID="756" CID="705" Value="Sežana" StdVal="Sežana" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1163</PName>
<PName PID="757" CID="705" Value="Škocjan" StdVal="Škocjan" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1164</PName>
<PName PID="758" CID="705" Value="Škofja Loka" StdVal="ŠkofjaLoka" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1165</PName>
<PName PID="759" CID="705" Value="Škofljica" StdVal="Škofljica" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1166</PName>
<PName PID="760" CID="705" Value="Slovenj Gradec" StdVal="SlovenjGradec" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1167</PName>
<PName PID="761" CID="705" Value="Slovenska Bistrica" StdVal="SlovenskaBistrica" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1168</PName>
<PName PID="762" CID="705" Value="Slovenske Konjice" StdVal="SlovenskeKonjice" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1169</PName>
<PName PID="763" CID="705" Value="Šmarje pri Jelšah" StdVal="ŠmarjepriJelšah" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1170</PName>
<PName PID="764" CID="705" Value="Šmartno ob Paki" StdVal="ŠmartnoobPaki" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1171</PName>
<PName PID="765" CID="705" Value="Šmartno pri Litiji" StdVal="ŠmartnopriLitiji" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1172</PName>
<PName PID="766" CID="705" Value="Sodražica" StdVal="Sodražica" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1173</PName>
<PName PID="767" CID="705" Value="Solčava" StdVal="Solčava" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1174</PName>
<PName PID="768" CID="705" Value="Šoštanj" StdVal="Šoštanj" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1175</PName>
<PName PID="769" CID="705" Value="Starše" StdVal="Starše" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1176</PName>
<PName PID="770" CID="705" Value="Štore" StdVal="Štore" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1177</PName>
<PName PID="771" CID="705" Value="Sveta Ana" StdVal="SvetaAna" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1178</PName>
<PName PID="772" CID="705" Value="Sveti Andraž v Slove" StdVal="SvetiAndražvSlove" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1179</PName>
<PName PID="773" CID="705" Value="Sveti Jurij" StdVal="SvetiJurij" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1180</PName>
<PName PID="774" CID="705" Value="Tabor" StdVal="Tabor" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1181</PName>
<PName PID="775" CID="705" Value="Tišina" StdVal="Tišina" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1182</PName>
<PName PID="776" CID="705" Value="Tolmin" StdVal="Tolmin" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1183</PName>
<PName PID="777" CID="705" Value="Trbovlje" StdVal="Trbovlje" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1184</PName>
<PName PID="778" CID="705" Value="Trebnje" StdVal="Trebnje" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1185</PName>
<PName PID="779" CID="705" Value="Trnovska Vas" StdVal="TrnovskaVas" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1186</PName>
<PName PID="780" CID="705" Value="Tržič" StdVal="Tržič" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1187</PName>
<PName PID="781" CID="705" Value="Trzin" StdVal="Trzin" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1188</PName>
<PName PID="782" CID="705" Value="Turnišče" StdVal="Turnišče" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1189</PName>
<PName PID="783" CID="705" Value="Velenje" StdVal="Velenje" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1190</PName>
<PName PID="784" CID="705" Value="Velika Polana" StdVal="VelikaPolana" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1191</PName>
<PName PID="785" CID="705" Value="Velike Lašče" StdVal="VelikeLašče" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1192</PName>
<PName PID="786" CID="705" Value="Veržej" StdVal="Veržej" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1193</PName>
<PName PID="787" CID="705" Value="Videm" StdVal="Videm" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1194</PName>
<PName PID="788" CID="705" Value="Vipava" StdVal="Vipava" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1195</PName>
<PName PID="789" CID="705" Value="Vitanje" StdVal="Vitanje" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1196</PName>
<PName PID="790" CID="705" Value="Vodice" StdVal="Vodice" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1197</PName>
<PName PID="791" CID="705" Value="Vojnik" StdVal="Vojnik" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1198</PName>
<PName PID="792" CID="705" Value="Vransko" StdVal="Vransko" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1199</PName>
<PName PID="793" CID="705" Value="Vrhnika" StdVal="Vrhnika" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1200</PName>
<PName PID="794" CID="705" Value="Vuzenica" StdVal="Vuzenica" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1201</PName>
<PName PID="795" CID="705" Value="Zagorje ob Savi" StdVal="ZagorjeobSavi" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1202</PName>
<PName PID="796" CID="705" Value="Žalec" StdVal="Žalec" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1203</PName>
<PName PID="797" CID="705" Value="Zavrč" StdVal="Zavrč" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1204</PName>
<PName PID="798" CID="705" Value="Železniki" StdVal="Železniki" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1205</PName>
<PName PID="799" CID="705" Value="Žetale" StdVal="Žetale" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1206</PName>
<PName PID="800" CID="705" Value="Žiri" StdVal="Žiri" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1207</PName>
<PName PID="801" CID="705" Value="Žirovnica" StdVal="Žirovnica" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1208</PName>
<PName PID="802" CID="705" Value="Zreče" StdVal="Zreče" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1209</PName>
<PName PID="803" CID="705" Value="Žužemberk" StdVal="Žužemberk" Lang="sl" Type="Full" IsLead="1" IsStd="1" Ver="1">1210</PName>
<PName PID="860" CID="804" Value="Cherkas'ka Oblast'" StdVal="CherkaskaOblast" Lang="uk" Type="Full" IsLead="1" IsStd="1" Ver="1">1266</PName>
<PName PID="861" CID="804" Value="Chernihivs'ka Oblast" StdVal="ChernihivskaOblast" Lang="uk" Type="Full" IsLead="1" IsStd="1" Ver="1">1268</PName>
<PName PID="862" CID="804" Value="Chernivets'ka Oblast" StdVal="ChernivetskaOblast" Lang="uk" Type="Full" IsLead="1" IsStd="1" Ver="1">1270</PName>
<PName PID="863" CID="804" Value="Dnipropetrovs'ka Obl" StdVal="DnipropetrovskaObl" Lang="uk" Type="Full" IsLead="1" IsStd="1" Ver="1">1272</PName>
<PName PID="864" CID="804" Value="Donets'ka Oblast'" StdVal="DonetskaOblast" Lang="uk" Type="Full" IsLead="1" IsStd="1" Ver="1">1274</PName>
<PName PID="865" CID="804" Value="Ivano-Frankivs'ka Ob" StdVal="IvanoFrankivskaOb" Lang="uk" Type="Full" IsLead="1" IsStd="1" Ver="1">1276</PName>
<PName PID="866" CID="804" Value="Kharkivs'ka Oblast'" StdVal="KharkivskaOblast" Lang="uk" Type="Full" IsLead="1" IsStd="1" Ver="1">1278</PName>
<PName PID="867" CID="804" Value="Khersons'ka Oblast'" StdVal="KhersonskaOblast" Lang="uk" Type="Full" IsLead="1" IsStd="1" Ver="1">1280</PName>
<PName PID="868" CID="804" Value="Khmel'nyts'ka Oblast" StdVal="KhmelnytskaOblast" Lang="uk" Type="Full" IsLead="1" IsStd="1" Ver="1">1282</PName>
<PName PID="869" CID="804" Value="Kirovohrads'ka Oblas" StdVal="KirovohradskaOblas" Lang="uk" Type="Full" IsLead="1" IsStd="1" Ver="1">1284</PName>
<PName PID="870" CID="804" Value="Kyïvs'ka Oblast'" StdVal="KyïvskaOblast" Lang="uk" Type="Full" IsLead="1" IsStd="1" Ver="1">1286</PName>
<PName PID="871" CID="804" Value="Luhans'ka Oblast'" StdVal="LuhanskaOblast" Lang="uk" Type="Full" IsLead="1" IsStd="1" Ver="1">1288</PName>
<PName PID="872" CID="804" Value="L'vivs'ka Oblast'" StdVal="LvivskaOblast" Lang="uk" Type="Full" IsLead="1" IsStd="1" Ver="1">1290</PName>
<PName PID="873" CID="804" Value="Mykolaïvs'ka Oblast'" StdVal="MykolaïvskaOblast" Lang="uk" Type="Full" IsLead="1" IsStd="1" Ver="1">1292</PName>
<PName PID="874" CID="804" Value="Odes'ka Oblast'" StdVal="OdeskaOblast" Lang="uk" Type="Full" IsLead="1" IsStd="1" Ver="1">1294</PName>
<PName PID="875" CID="804" Value="Poltavs'ka Oblast'" StdVal="PoltavskaOblast" Lang="uk" Type="Full" IsLead="1" IsStd="1" Ver="1">1296</PName>
<PName PID="876" CID="804" Value="Respublika Krym" StdVal="RespublikaKrym" Lang="uk" Type="Full" IsLead="1" IsStd="1" Ver="1">1297</PName>
<PName PID="877" CID="804" Value="Rivnens'ka Oblast'" StdVal="RivnenskaOblast" Lang="uk" Type="Full" IsLead="1" IsStd="1" Ver="1">1299</PName>
<PName PID="878" CID="804" Value="Sums'ka Oblast'" StdVal="SumskaOblast" Lang="uk" Type="Full" IsLead="1" IsStd="1" Ver="1">1301</PName>
<PName PID="879" CID="804" Value="Ternopil's'ka Oblast" StdVal="TernopilskaOblast" Lang="uk" Type="Full" IsLead="1" IsStd="1" Ver="1">1303</PName>
<PName PID="880" CID="804" Value="Vinnyts'ka Oblast'" StdVal="VinnytskaOblast" Lang="uk" Type="Full" IsLead="1" IsStd="1" Ver="1">1305</PName>
<PName PID="881" CID="804" Value="Volyns'ka Oblast'" StdVal="VolynskaOblast" Lang="uk" Type="Full" IsLead="1" IsStd="1" Ver="1">1308</PName>
<PName PID="882" CID="804" Value="Zakarpats'ka Oblast'" StdVal="ZakarpatskaOblast" Lang="uk" Type="Full" IsLead="1" IsStd="1" Ver="1">1311</PName>
<PName PID="883" CID="804" Value="Zaporiz'ka Oblast'" StdVal="ZaporizkaOblast" Lang="uk" Type="Full" IsLead="1" IsStd="1" Ver="1">1313</PName>
<PName PID="884" CID="804" Value="Zhytomyrs'ka Oblast'" StdVal="ZhytomyrskaOblast" Lang="uk" Type="Full" IsLead="1" IsStd="1" Ver="1">1315</PName>
<PName PID="970" CID="784" Value="Abū Z̧aby" StdVal="AbūZ̧aby" Lang="ar" Type="Full" IsLead="1" IsStd="1" Ver="1">1493</PName>
<PName PID="971" CID="784" Value="Ajmān" StdVal="Ajmān" Lang="ar" Type="Full" IsLead="1" IsStd="1" Ver="1">1496</PName>
<PName PID="971" CID="784" Value="'Ajmān" StdVal="Ajmān" Lang="ar" Type="Full" IsLead="0" IsStd="1" Ver="1">1495</PName>
<PName PID="972" CID="784" Value="Al Fujayrah" StdVal="AlFujayrah" Lang="ar" Type="Full" IsLead="1" IsStd="1" Ver="1">1498</PName>
<PName PID="973" CID="784" Value="Ash Shāriqah" StdVal="AshShāriqah" Lang="ar" Type="Full" IsLead="1" IsStd="1" Ver="1">1500</PName>
<PName PID="974" CID="784" Value="Dubayy" StdVal="Dubayy" Lang="ar" Type="Full" IsLead="1" IsStd="1" Ver="1">1502</PName>
<PName PID="975" CID="784" Value="Ra’s al Khaymah" StdVal="RasalKhaymah" Lang="ar" Type="Full" IsLead="1" IsStd="1" Ver="1">1505</PName>
<PName PID="977" CID="076" Value="AC" StdVal="AC" Lang="pt" Type="Short" IsLead="1" IsStd="1" Ver="1">1509</PName>
<PName PID="977" CID="076" Value="Acre" StdVal="Acre" Lang="pt" Type="Full" IsLead="1" IsStd="1" Ver="1">1508</PName>
<PName PID="978" CID="076" Value="AL" StdVal="AL" Lang="pt" Type="Short" IsLead="1" IsStd="1" Ver="1">1511</PName>
<PName PID="978" CID="076" Value="Alagoas" StdVal="Alagoas" Lang="pt" Type="Full" IsLead="1" IsStd="1" Ver="1">1510</PName>
<PName PID="979" CID="076" Value="Amapá" StdVal="Amapá" Lang="pt" Type="Full" IsLead="1" IsStd="1" Ver="1">1512</PName>
<PName PID="979" CID="076" Value="AP" StdVal="AP" Lang="pt" Type="Short" IsLead="1" IsStd="1" Ver="1">1513</PName>
<PName PID="980" CID="076" Value="AM" StdVal="AM" Lang="pt" Type="Short" IsLead="1" IsStd="1" Ver="1">1515</PName>
<PName PID="980" CID="076" Value="Amazonas" StdVal="Amazonas" Lang="pt" Type="Full" IsLead="1" IsStd="1" Ver="1">1514</PName>
<PName PID="981" CID="076" Value="BA" StdVal="BA" Lang="pt" Type="Short" IsLead="1" IsStd="1" Ver="1">1517</PName>
<PName PID="981" CID="076" Value="Bahia" StdVal="Bahia" Lang="pt" Type="Full" IsLead="1" IsStd="1" Ver="1">1516</PName>
<PName PID="982" CID="076" Value="CE" StdVal="CE" Lang="pt" Type="Short" IsLead="1" IsStd="1" Ver="1">1519</PName>
<PName PID="982" CID="076" Value="Ceará" StdVal="Ceará" Lang="pt" Type="Full" IsLead="1" IsStd="1" Ver="1">1518</PName>
<PName PID="983" CID="076" Value="DF" StdVal="DF" Lang="pt" Type="Short" IsLead="1" IsStd="1" Ver="1">1521</PName>
<PName PID="983" CID="076" Value="Distrito Federal" StdVal="DistritoFederal" Lang="pt" Type="Full" IsLead="1" IsStd="1" Ver="1">1520</PName>
<PName PID="984" CID="076" Value="ES" StdVal="ES" Lang="pt" Type="Short" IsLead="1" IsStd="1" Ver="1">1523</PName>
<PName PID="984" CID="076" Value="Espírito Santo" StdVal="EspíritoSanto" Lang="pt" Type="Full" IsLead="1" IsStd="1" Ver="1">1522</PName>
<PName PID="985" CID="076" Value="GO" StdVal="GO" Lang="pt" Type="Short" IsLead="1" IsStd="1" Ver="1">1525</PName>
<PName PID="985" CID="076" Value="Goiás" StdVal="Goiás" Lang="pt" Type="Full" IsLead="1" IsStd="1" Ver="1">1524</PName>
<PName PID="986" CID="076" Value="MA" StdVal="MA" Lang="pt" Type="Short" IsLead="1" IsStd="1" Ver="1">1527</PName>
<PName PID="986" CID="076" Value="Maranhão" StdVal="Maranhão" Lang="pt" Type="Full" IsLead="1" IsStd="1" Ver="1">1526</PName>
<PName PID="987" CID="076" Value="Mato Grosso" StdVal="MatoGrosso" Lang="pt" Type="Full" IsLead="1" IsStd="1" Ver="1">1528</PName>
<PName PID="987" CID="076" Value="MT" StdVal="MT" Lang="pt" Type="Short" IsLead="1" IsStd="1" Ver="1">1529</PName>
<PName PID="988" CID="076" Value="Mato Grosso do Sul" StdVal="MatoGrossodoSul" Lang="pt" Type="Full" IsLead="1" IsStd="1" Ver="1">1530</PName>
<PName PID="988" CID="076" Value="MS" StdVal="MS" Lang="pt" Type="Short" IsLead="1" IsStd="1" Ver="1">1531</PName>
<PName PID="989" CID="076" Value="MG" StdVal="MG" Lang="pt" Type="Short" IsLead="1" IsStd="1" Ver="1">1533</PName>
<PName PID="989" CID="076" Value="Minas Gerais" StdVal="MinasGerais" Lang="pt" Type="Full" IsLead="1" IsStd="1" Ver="1">1532</PName>
<PName PID="990" CID="076" Value="PA" StdVal="PA" Lang="pt" Type="Short" IsLead="1" IsStd="1" Ver="1">1535</PName>
<PName PID="990" CID="076" Value="Pará" StdVal="Pará" Lang="pt" Type="Full" IsLead="1" IsStd="1" Ver="1">1534</PName>
<PName PID="991" CID="076" Value="Paraíba" StdVal="Paraíba" Lang="pt" Type="Full" IsLead="1" IsStd="1" Ver="1">1536</PName>
<PName PID="991" CID="076" Value="PB" StdVal="PB" Lang="pt" Type="Short" IsLead="1" IsStd="1" Ver="1">1537</PName>
<PName PID="992" CID="076" Value="Paraná" StdVal="Paraná" Lang="pt" Type="Full" IsLead="1" IsStd="1" Ver="1">1538</PName>
<PName PID="992" CID="076" Value="PR" StdVal="PR" Lang="pt" Type="Short" IsLead="1" IsStd="1" Ver="1">1539</PName>
<PName PID="993" CID="076" Value="PE" StdVal="PE" Lang="pt" Type="Short" IsLead="1" IsStd="1" Ver="1">1541</PName>
<PName PID="993" CID="076" Value="Pernambuco" StdVal="Pernambuco" Lang="pt" Type="Full" IsLead="1" IsStd="1" Ver="1">1540</PName>
<PName PID="994" CID="076" Value="PI" StdVal="PI" Lang="pt" Type="Short" IsLead="1" IsStd="1" Ver="1">1543</PName>
<PName PID="994" CID="076" Value="Piauí" StdVal="Piauí" Lang="pt" Type="Full" IsLead="1" IsStd="1" Ver="1">1542</PName>
<PName PID="995" CID="076" Value="Rio de Janeiro" StdVal="RiodeJaneiro" Lang="pt" Type="Full" IsLead="1" IsStd="1" Ver="1">1544</PName>
<PName PID="995" CID="076" Value="RJ" StdVal="RJ" Lang="pt" Type="Short" IsLead="1" IsStd="1" Ver="1">1545</PName>
<PName PID="996" CID="076" Value="Rio Grande do Norte" StdVal="RioGrandedoNorte" Lang="pt" Type="Full" IsLead="1" IsStd="1" Ver="1">1546</PName>
<PName PID="996" CID="076" Value="RN" StdVal="RN" Lang="pt" Type="Short" IsLead="1" IsStd="1" Ver="1">1547</PName>
<PName PID="997" CID="076" Value="Rio Grande do Sul" StdVal="RioGrandedoSul" Lang="pt" Type="Full" IsLead="1" IsStd="1" Ver="1">1548</PName>
<PName PID="997" CID="076" Value="RS" StdVal="RS" Lang="pt" Type="Short" IsLead="1" IsStd="1" Ver="1">1549</PName>
<PName PID="998" CID="076" Value="RO" StdVal="RO" Lang="pt" Type="Short" IsLead="1" IsStd="1" Ver="1">1551</PName>
<PName PID="998" CID="076" Value="Rondônia" StdVal="Rondônia" Lang="pt" Type="Full" IsLead="1" IsStd="1" Ver="1">1550</PName>
<PName PID="999" CID="076" Value="Roraima" StdVal="Roraima" Lang="pt" Type="Full" IsLead="1" IsStd="1" Ver="1">1552</PName>
<PName PID="999" CID="076" Value="RR" StdVal="RR" Lang="pt" Type="Short" IsLead="1" IsStd="1" Ver="1">1553</PName>
<PName PID="1000" CID="076" Value="Santa Catarina" StdVal="SantaCatarina" Lang="pt" Type="Full" IsLead="1" IsStd="1" Ver="1">1554</PName>
<PName PID="1000" CID="076" Value="SC" StdVal="SC" Lang="pt" Type="Short" IsLead="1" IsStd="1" Ver="1">1555</PName>
<PName PID="1001" CID="076" Value="São Paulo" StdVal="SãoPaulo" Lang="pt" Type="Full" IsLead="1" IsStd="1" Ver="1">1556</PName>
<PName PID="1001" CID="076" Value="SP" StdVal="SP" Lang="pt" Type="Short" IsLead="1" IsStd="1" Ver="1">1557</PName>
<PName PID="1002" CID="076" Value="SE" StdVal="SE" Lang="pt" Type="Short" IsLead="1" IsStd="1" Ver="1">1559</PName>
<PName PID="1002" CID="076" Value="Sergipe" StdVal="Sergipe" Lang="pt" Type="Full" IsLead="1" IsStd="1" Ver="1">1558</PName>
<PName PID="1003" CID="076" Value="TO" StdVal="TO" Lang="pt" Type="Short" IsLead="1" IsStd="1" Ver="1">1561</PName>
<PName PID="1003" CID="076" Value="Tocantins" StdVal="Tocantins" Lang="pt" Type="Full" IsLead="1" IsStd="1" Ver="1">1560</PName>
<PName PID="1004" CID="156" Value="Anhui" StdVal="Anhui" Lang="zh" Type="Full" IsLead="1" IsStd="1" Ver="1">1562</PName>
<PName PID="1005" CID="156" Value="Aomen" StdVal="Aomen" Lang="zh" Type="Full" IsLead="1" IsStd="1" Ver="1">1563</PName>
<PName PID="1006" CID="156" Value="Beijing" StdVal="Beijing" Lang="zh" Type="Full" IsLead="1" IsStd="1" Ver="1">1565</PName>
<PName PID="1007" CID="156" Value="Chongqing" StdVal="Chongqing" Lang="zh" Type="Full" IsLead="1" IsStd="1" Ver="1">1566</PName>
<PName PID="1008" CID="156" Value="Fujian" StdVal="Fujian" Lang="zh" Type="Full" IsLead="1" IsStd="1" Ver="1">1567</PName>
<PName PID="1009" CID="156" Value="Gansu" StdVal="Gansu" Lang="zh" Type="Full" IsLead="1" IsStd="1" Ver="1">1568</PName>
<PName PID="1010" CID="156" Value="Guangdong" StdVal="Guangdong" Lang="zh" Type="Full" IsLead="1" IsStd="1" Ver="1">1569</PName>
<PName PID="1011" CID="156" Value="Guangxi" StdVal="Guangxi" Lang="zh" Type="Full" IsLead="1" IsStd="1" Ver="1">1570</PName>
<PName PID="1012" CID="156" Value="Guizhou" StdVal="Guizhou" Lang="zh" Type="Full" IsLead="1" IsStd="1" Ver="1">1571</PName>
<PName PID="1013" CID="156" Value="Hainan" StdVal="Hainan" Lang="zh" Type="Full" IsLead="1" IsStd="1" Ver="1">1572</PName>
<PName PID="1014" CID="156" Value="Hebei" StdVal="Hebei" Lang="zh" Type="Full" IsLead="1" IsStd="1" Ver="1">1573</PName>
<PName PID="1015" CID="156" Value="Heilongjiang" StdVal="Heilongjiang" Lang="zh" Type="Full" IsLead="1" IsStd="1" Ver="1">1574</PName>
<PName PID="1016" CID="156" Value="Henan" StdVal="Henan" Lang="zh" Type="Full" IsLead="1" IsStd="1" Ver="1">1575</PName>
<PName PID="1017" CID="156" Value="Hubei" StdVal="Hubei" Lang="zh" Type="Full" IsLead="1" IsStd="1" Ver="1">1576</PName>
<PName PID="1018" CID="156" Value="Hunan" StdVal="Hunan" Lang="zh" Type="Full" IsLead="1" IsStd="1" Ver="1">1577</PName>
<PName PID="1019" CID="156" Value="Jiangsu" StdVal="Jiangsu" Lang="zh" Type="Full" IsLead="1" IsStd="1" Ver="1">1578</PName>
<PName PID="1020" CID="156" Value="Jiangxi" StdVal="Jiangxi" Lang="zh" Type="Full" IsLead="1" IsStd="1" Ver="1">1579</PName>
<PName PID="1021" CID="156" Value="Jilin" StdVal="Jilin" Lang="zh" Type="Full" IsLead="1" IsStd="1" Ver="1">1580</PName>
<PName PID="1022" CID="156" Value="Liaoning" StdVal="Liaoning" Lang="zh" Type="Full" IsLead="1" IsStd="1" Ver="1">1581</PName>
<PName PID="1023" CID="156" Value="Nei Mongol" StdVal="NeiMongol" Lang="zh" Type="Full" IsLead="1" IsStd="1" Ver="1">1582</PName>
<PName PID="1024" CID="156" Value="Ningxia" StdVal="Ningxia" Lang="zh" Type="Full" IsLead="1" IsStd="1" Ver="1">1583</PName>
<PName PID="1025" CID="156" Value="Qinghai" StdVal="Qinghai" Lang="zh" Type="Full" IsLead="1" IsStd="1" Ver="1">1584</PName>
<PName PID="1026" CID="156" Value="Shaanxi" StdVal="Shaanxi" Lang="zh" Type="Full" IsLead="1" IsStd="1" Ver="1">1585</PName>
<PName PID="1027" CID="156" Value="Shandong" StdVal="Shandong" Lang="zh" Type="Full" IsLead="1" IsStd="1" Ver="1">1586</PName>
<PName PID="1028" CID="156" Value="Shanghai" StdVal="Shanghai" Lang="zh" Type="Full" IsLead="1" IsStd="1" Ver="1">1587</PName>
<PName PID="1029" CID="156" Value="Shanxi" StdVal="Shanxi" Lang="zh" Type="Full" IsLead="1" IsStd="1" Ver="1">1588</PName>
<PName PID="1030" CID="156" Value="Sichuan" StdVal="Sichuan" Lang="zh" Type="Full" IsLead="1" IsStd="1" Ver="1">1589</PName>
<PName PID="1031" CID="156" Value="Taiwan" StdVal="Taiwan" Lang="zh" Type="Full" IsLead="1" IsStd="1" Ver="1">1590</PName>
<PName PID="1032" CID="156" Value="Tianjin" StdVal="Tianjin" Lang="zh" Type="Full" IsLead="1" IsStd="1" Ver="1">1591</PName>
<PName PID="1033" CID="156" Value="Xianggang" StdVal="Xianggang" Lang="zh" Type="Full" IsLead="1" IsStd="1" Ver="1">1592</PName>
<PName PID="1034" CID="156" Value="Xinjiang" StdVal="Xinjiang" Lang="zh" Type="Full" IsLead="1" IsStd="1" Ver="1">1594</PName>
<PName PID="1035" CID="156" Value="Xizang" StdVal="Xizang" Lang="zh" Type="Full" IsLead="1" IsStd="1" Ver="1">1595</PName>
<PName PID="1036" CID="156" Value="Yunnan" StdVal="Yunnan" Lang="zh" Type="Full" IsLead="1" IsStd="1" Ver="1">1596</PName>
<PName PID="1037" CID="156" Value="Zhejiang" StdVal="Zhejiang" Lang="zh" Type="Full" IsLead="1" IsStd="1" Ver="1">1597</PName>
<PName PID="1038" CID="376" Value="El Janūbī" StdVal="ElJanūbī" Lang="ar" Type="Full" IsLead="1" IsStd="1" Ver="1">1598</PName>
<PName PID="1038" CID="376" Value="HaDarom" StdVal="HaDarom" Lang="he" Type="Full" IsLead="1" IsStd="1" Ver="1">1599</PName>
<PName PID="1039" CID="376" Value="Ḥeifā" StdVal="Ḥeifā" Lang="ar" Type="Full" IsLead="1" IsStd="1" Ver="1">1600</PName>
<PName PID="1039" CID="376" Value="H̱efa" StdVal="H̱efa" Lang="he" Type="Full" IsLead="1" IsStd="1" Ver="1">1601</PName>
<PName PID="1040" CID="376" Value="Al Quds" StdVal="AlQuds" Lang="ar" Type="Full" IsLead="1" IsStd="1" Ver="1">1602</PName>
<PName PID="1040" CID="376" Value="Yerushalayim" StdVal="Yerushalayim" Lang="he" Type="Full" IsLead="1" IsStd="1" Ver="1">1603</PName>
<PName PID="1041" CID="376" Value="El Awsaṭ" StdVal="ElAwsaṭ" Lang="ar" Type="Full" IsLead="1" IsStd="1" Ver="1">1604</PName>
<PName PID="1041" CID="376" Value="HaMerkaz" StdVal="HaMerkaz" Lang="he" Type="Full" IsLead="1" IsStd="1" Ver="1">1605</PName>
<PName PID="1042" CID="376" Value="Tell Abīb" StdVal="TellAbīb" Lang="ar" Type="Full" IsLead="1" IsStd="1" Ver="1">1606</PName>
<PName PID="1042" CID="376" Value="Tel-Aviv" StdVal="TelAviv" Lang="he" Type="Full" IsLead="1" IsStd="1" Ver="1">1607</PName>
<PName PID="1043" CID="376" Value="Esh Shamālī" StdVal="EshShamālī" Lang="ar" Type="Full" IsLead="1" IsStd="1" Ver="1">1608</PName>
<PName PID="1043" CID="376" Value="Ha Ẕafon" StdVal="HaẔafon" Lang="he" Type="Full" IsLead="1" IsStd="1" Ver="1">1609</PName>
</PNameSets>
