<?xml version="1.0" encoding="UTF-8"?>
<Entries xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<Entry Type="Country"  Action="ADD" Version="1">InSituSCV__InSitu_CountryData_1_1</Entry> 
<Entry Type="CNameSet" Action="ADD" Version="1">InSituSCV__InSitu_CNameSetData_1_1</Entry> 
<Entry Type="CNameSet" Action="ADD" Version="1">InSituSCV__InSitu_CNameSetData_1_2</Entry> 
<Entry Type="CNameSet" Action="ADD" Version="1">InSituSCV__InSitu_CNameSetData_1_3</Entry> 
<Entry Type="PNameSet" Action="ADD" Version="1">InSituSCV__InSitu_PNameSetData_1_1</Entry> 
<Entry Type="PNameSet" Action="ADD" Version="1">InSituSCV__InSitu_PNameSetData_1_2</Entry> 
<Entry Type="PNameSet" Action="ADD" Version="1">InSituSCV__InSitu_PNameSetData_1_3</Entry> 
</Entries>
