<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<PNameSets xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<PName PID="43" CID="056" Value="Brabant Wallon" StdVal="BrabantWallon" Lang="fr" Type="Full" IsLead="1" IsStd="1" Ver="1">49</PName>
<PName PID="43" CID="056" Value="WBR" StdVal="WBR" Lang="fr" Type="Short" IsLead="1" IsStd="1" Ver="1">50</PName>
<PName PID="44" CID="056" Value="Hainaut" StdVal="Hainaut" Lang="fr" Type="Full" IsLead="1" IsStd="1" Ver="1">51</PName>
<PName PID="44" CID="056" Value="WHT" StdVal="WHT" Lang="fr" Type="Short" IsLead="1" IsStd="1" Ver="1">52</PName>
<PName PID="45" CID="056" Value="Liège" StdVal="Liège" Lang="fr" Type="Full" IsLead="1" IsStd="1" Ver="1">53</PName>
<PName PID="45" CID="056" Value="WLG" StdVal="WLG" Lang="fr" Type="Short" IsLead="1" IsStd="1" Ver="1">54</PName>
<PName PID="46" CID="056" Value="Luxembourg" StdVal="Luxembourg" Lang="fr" Type="Full" IsLead="1" IsStd="1" Ver="1">55</PName>
<PName PID="46" CID="056" Value="WLX" StdVal="WLX" Lang="fr" Type="Short" IsLead="1" IsStd="1" Ver="1">56</PName>
<PName PID="47" CID="056" Value="Namur" StdVal="Namur" Lang="fr" Type="Full" IsLead="1" IsStd="1" Ver="1">57</PName>
<PName PID="47" CID="056" Value="WNA" StdVal="WNA" Lang="fr" Type="Short" IsLead="1" IsStd="1" Ver="1">58</PName>
<PName PID="82" CID="124" Value="Colombie-Britannique" StdVal="ColombieBritannique" Lang="fr" Type="Full" IsLead="1" IsStd="1" Ver="1">101</PName>
<PName PID="84" CID="124" Value="Nouveau-Brunswick" StdVal="NouveauBrunswick" Lang="fr" Type="Full" IsLead="1" IsStd="1" Ver="1">106</PName>
<PName PID="85" CID="124" Value="Terre-Neuve" StdVal="TerreNeuve" Lang="fr" Type="Full" IsLead="1" IsStd="1" Ver="1">110</PName>
<PName PID="85" CID="124" Value="Terre-Neuve-et-Labra" StdVal="TerreNeuveetLabra" Lang="fr" Type="Full" IsLead="0" IsStd="1" Ver="1">111</PName>
<PName PID="86" CID="124" Value="Nouvelle-Écosse" StdVal="NouvelleÉcosse" Lang="fr" Type="Full" IsLead="1" IsStd="1" Ver="1">114</PName>
<PName PID="88" CID="124" Value="Prince-Édouard" StdVal="PrinceÉdouard" Lang="fr" Type="Full" IsLead="1" IsStd="1" Ver="1">121</PName>
<PName PID="88" CID="124" Value="Île-du-Prince-Édouar" StdVal="ÎleduPrinceÉdouar" Lang="fr" Type="Full" IsLead="0" IsStd="1" Ver="1">122</PName>
<PName PID="89" CID="124" Value="Québec" StdVal="Québec" Lang="fr" Type="Full" IsLead="1" IsStd="1" Ver="1">127</PName>
<PName PID="112" CID="203" Value="Jihočeský kraj" StdVal="Jihočeskýkraj" Lang="cs" Type="Full" IsLead="1" IsStd="1" Ver="1">167</PName>
<PName PID="113" CID="203" Value="Jihomoravský kraj" StdVal="Jihomoravskýkraj" Lang="cs" Type="Full" IsLead="1" IsStd="1" Ver="1">168</PName>
<PName PID="114" CID="203" Value="Karlovarský kraj" StdVal="Karlovarskýkraj" Lang="cs" Type="Full" IsLead="1" IsStd="1" Ver="1">169</PName>
<PName PID="115" CID="203" Value="Královéhradecký kraj" StdVal="Královéhradeckýkraj" Lang="cs" Type="Full" IsLead="1" IsStd="1" Ver="1">170</PName>
<PName PID="116" CID="203" Value="Liberecký kraj" StdVal="Libereckýkraj" Lang="cs" Type="Full" IsLead="1" IsStd="1" Ver="1">171</PName>
<PName PID="117" CID="203" Value="Moravskoslezský kraj" StdVal="Moravskoslezskýkraj" Lang="cs" Type="Full" IsLead="1" IsStd="1" Ver="1">172</PName>
<PName PID="118" CID="203" Value="Olomoucký kraj" StdVal="Olomouckýkraj" Lang="cs" Type="Full" IsLead="1" IsStd="1" Ver="1">173</PName>
<PName PID="119" CID="203" Value="Pardubický kraj" StdVal="Pardubickýkraj" Lang="cs" Type="Full" IsLead="1" IsStd="1" Ver="1">174</PName>
<PName PID="120" CID="203" Value="Plzeňský kraj" StdVal="Plzeňskýkraj" Lang="cs" Type="Full" IsLead="1" IsStd="1" Ver="1">175</PName>
<PName PID="121" CID="203" Value="Praha" StdVal="HlavníměstoPraha" Lang="cs" Type="Full" IsLead="1" IsStd="1" Ver="1">176</PName>
<PName PID="121" CID="203" Value="Praha, hlavní město" StdVal="Prahahlavníměsto" Lang="cs" Type="Full" IsLead="1" IsStd="1" Ver="1">177</PName>
<PName PID="121" CID="203" Value="Hlavní město Praha" StdVal="HlavníměstoPraha" Lang="cs" Type="Full" IsLead="0" IsStd="1" Ver="1">178</PName>
<PName PID="122" CID="203" Value="Středočeský kraj" StdVal="Středočeskýkraj" Lang="cs" Type="Full" IsLead="1" IsStd="1" Ver="1">179</PName>
<PName PID="123" CID="203" Value="Ústecký kraj" StdVal="Ústeckýkraj" Lang="cs" Type="Full" IsLead="1" IsStd="1" Ver="1">180</PName>
<PName PID="124" CID="203" Value="Vysočina" StdVal="Vysočina" Lang="cs" Type="Full" IsLead="1" IsStd="1" Ver="1">181</PName>
<PName PID="125" CID="203" Value="Zlínský kraj" StdVal="Zlínskýkraj" Lang="cs" Type="Full" IsLead="1" IsStd="1" Ver="1">182</PName>
<PName PID="141" CID="246" Value="Ahvenanmaan lääni" StdVal="Ahvenanmaanlääni" Lang="fi" Type="Full" IsLead="1" IsStd="1" Ver="1">198</PName>
<PName PID="141" CID="246" Value="AL" StdVal="AL" Lang="fi" Type="Short" IsLead="1" IsStd="1" Ver="1">199</PName>
<PName PID="141" CID="246" Value="Ålands län" StdVal="Ålandslän" Lang="sv" Type="Full" IsLead="1" IsStd="1" Ver="1">200</PName>
<PName PID="142" CID="246" Value="ES" StdVal="ES" Lang="fi" Type="Short" IsLead="1" IsStd="1" Ver="1">201</PName>
<PName PID="142" CID="246" Value="Etelä-Suomen lääni" StdVal="EteläSuomenlääni" Lang="fi" Type="Full" IsLead="1" IsStd="1" Ver="1">202</PName>
<PName PID="142" CID="246" Value="Södra Finlands län" StdVal="SödraFinlandslän" Lang="sv" Type="Full" IsLead="1" IsStd="1" Ver="1">203</PName>
<PName PID="143" CID="246" Value="IS" StdVal="IS" Lang="fi" Type="Short" IsLead="1" IsStd="1" Ver="1">204</PName>
<PName PID="143" CID="246" Value="Itä-Suomen lääni" StdVal="ItäSuomenlääni" Lang="fi" Type="Full" IsLead="1" IsStd="1" Ver="1">205</PName>
<PName PID="143" CID="246" Value="Östra Finlands län" StdVal="ÖstraFinlandslän" Lang="sv" Type="Full" IsLead="1" IsStd="1" Ver="1">206</PName>
<PName PID="144" CID="246" Value="Länsi-Suomen lääni" StdVal="LänsiSuomenlääni" Lang="fi" Type="Full" IsLead="1" IsStd="1" Ver="1">207</PName>
<PName PID="144" CID="246" Value="LS" StdVal="LS" Lang="fi" Type="Short" IsLead="1" IsStd="1" Ver="1">208</PName>
<PName PID="144" CID="246" Value="Västra Finlands län" StdVal="VästraFinlandslän" Lang="sv" Type="Full" IsLead="1" IsStd="1" Ver="1">209</PName>
<PName PID="145" CID="246" Value="Lapin lääni" StdVal="Lapinlääni" Lang="fi" Type="Full" IsLead="1" IsStd="1" Ver="1">210</PName>
<PName PID="145" CID="246" Value="LL" StdVal="LL" Lang="fi" Type="Short" IsLead="1" IsStd="1" Ver="1">211</PName>
<PName PID="145" CID="246" Value="Lapplands län" StdVal="Lapplandslän" Lang="sv" Type="Full" IsLead="1" IsStd="1" Ver="1">212</PName>
<PName PID="146" CID="246" Value="OL" StdVal="OL" Lang="fi" Type="Short" IsLead="1" IsStd="1" Ver="1">213</PName>
<PName PID="146" CID="246" Value="Oulun lääni" StdVal="Oulunlääni" Lang="fi" Type="Full" IsLead="1" IsStd="1" Ver="1">214</PName>
<PName PID="146" CID="246" Value="Uleåborgs län" StdVal="Uleåborgslän" Lang="sv" Type="Full" IsLead="1" IsStd="1" Ver="1">215</PName>
<PName PID="198" CID="348" Value="Bács-Kiskun" StdVal="BácsKiskun" Lang="hu" Type="Full" IsLead="1" IsStd="1" Ver="1">267</PName>
<PName PID="198" CID="348" Value="BK" StdVal="BK" Lang="hu" Type="Short" IsLead="1" IsStd="1" Ver="1">268</PName>
<PName PID="199" CID="348" Value="BA" StdVal="BA" Lang="hu" Type="Short" IsLead="1" IsStd="1" Ver="1">269</PName>
<PName PID="199" CID="348" Value="Baranya" StdVal="Baranya" Lang="hu" Type="Full" IsLead="1" IsStd="1" Ver="1">270</PName>
<PName PID="200" CID="348" Value="BE" StdVal="BE" Lang="hu" Type="Short" IsLead="1" IsStd="1" Ver="1">271</PName>
<PName PID="200" CID="348" Value="Békés" StdVal="Békés" Lang="hu" Type="Full" IsLead="1" IsStd="1" Ver="1">272</PName>
<PName PID="201" CID="348" Value="Borsod-Abaúj-Zemplén" StdVal="BorsodAbaújZemplén" Lang="hu" Type="Full" IsLead="1" IsStd="1" Ver="1">273</PName>
<PName PID="201" CID="348" Value="BZ" StdVal="BZ" Lang="hu" Type="Short" IsLead="1" IsStd="1" Ver="1">274</PName>
<PName PID="202" CID="348" Value="CS" StdVal="CS" Lang="hu" Type="Short" IsLead="1" IsStd="1" Ver="1">275</PName>
<PName PID="202" CID="348" Value="Csongrád" StdVal="Csongrád" Lang="hu" Type="Full" IsLead="1" IsStd="1" Ver="1">276</PName>
<PName PID="203" CID="348" Value="FE" StdVal="FE" Lang="hu" Type="Short" IsLead="1" IsStd="1" Ver="1">277</PName>
<PName PID="203" CID="348" Value="Fejér" StdVal="Fejér" Lang="hu" Type="Full" IsLead="1" IsStd="1" Ver="1">278</PName>
<PName PID="204" CID="348" Value="GS" StdVal="GS" Lang="hu" Type="Short" IsLead="1" IsStd="1" Ver="1">279</PName>
<PName PID="204" CID="348" Value="Győr-Moson-Sopron" StdVal="GyőrMosonSopron" Lang="hu" Type="Full" IsLead="1" IsStd="1" Ver="1">280</PName>
<PName PID="205" CID="348" Value="Hajdú-Bihar" StdVal="HajdúBihar" Lang="hu" Type="Full" IsLead="1" IsStd="1" Ver="1">281</PName>
<PName PID="205" CID="348" Value="HB" StdVal="HB" Lang="hu" Type="Short" IsLead="1" IsStd="1" Ver="1">282</PName>
<PName PID="206" CID="348" Value="HE" StdVal="HE" Lang="hu" Type="Short" IsLead="1" IsStd="1" Ver="1">283</PName>
<PName PID="206" CID="348" Value="Heves" StdVal="Heves" Lang="hu" Type="Full" IsLead="1" IsStd="1" Ver="1">284</PName>
<PName PID="207" CID="348" Value="Jász-Nagykun-Szolnok" StdVal="JászNagykunSzolnok" Lang="hu" Type="Full" IsLead="1" IsStd="1" Ver="1">285</PName>
<PName PID="207" CID="348" Value="JN" StdVal="JN" Lang="hu" Type="Short" IsLead="1" IsStd="1" Ver="1">286</PName>
<PName PID="208" CID="348" Value="KE" StdVal="KE" Lang="hu" Type="Short" IsLead="1" IsStd="1" Ver="1">287</PName>
<PName PID="208" CID="348" Value="Komárom-Esztergom" StdVal="KomáromEsztergom" Lang="hu" Type="Full" IsLead="1" IsStd="1" Ver="1">288</PName>
<PName PID="209" CID="348" Value="NO" StdVal="NO" Lang="hu" Type="Short" IsLead="1" IsStd="1" Ver="1">289</PName>
<PName PID="209" CID="348" Value="Nógrád" StdVal="Nógrád" Lang="hu" Type="Full" IsLead="1" IsStd="1" Ver="1">290</PName>
<PName PID="210" CID="348" Value="PE" StdVal="PE" Lang="hu" Type="Short" IsLead="1" IsStd="1" Ver="1">291</PName>
<PName PID="210" CID="348" Value="Pest" StdVal="Pest" Lang="hu" Type="Full" IsLead="1" IsStd="1" Ver="1">292</PName>
<PName PID="211" CID="348" Value="SO" StdVal="SO" Lang="hu" Type="Short" IsLead="1" IsStd="1" Ver="1">293</PName>
<PName PID="211" CID="348" Value="Somogy" StdVal="Somogy" Lang="hu" Type="Full" IsLead="1" IsStd="1" Ver="1">294</PName>
<PName PID="212" CID="348" Value="SZ" StdVal="SZ" Lang="hu" Type="Short" IsLead="1" IsStd="1" Ver="1">295</PName>
<PName PID="212" CID="348" Value="Szabolcs-Szatmár" StdVal="SzabolcsSzatmár" Lang="hu" Type="Full" IsLead="1" IsStd="1" Ver="1">296</PName>
<PName PID="212" CID="348" Value="Szabolcs-Szatmár-Ber" StdVal="SzabolcsSzatmárBer" Lang="hu" Type="Full" IsLead="0" IsStd="1" Ver="1">297</PName>
<PName PID="213" CID="348" Value="TO" StdVal="TO" Lang="hu" Type="Short" IsLead="1" IsStd="1" Ver="1">298</PName>
<PName PID="213" CID="348" Value="Tolna" StdVal="Tolna" Lang="hu" Type="Full" IsLead="1" IsStd="1" Ver="1">299</PName>
<PName PID="214" CID="348" Value="VA" StdVal="VA" Lang="hu" Type="Short" IsLead="1" IsStd="1" Ver="1">300</PName>
<PName PID="214" CID="348" Value="Vas" StdVal="Vas" Lang="hu" Type="Full" IsLead="1" IsStd="1" Ver="1">301</PName>
<PName PID="215" CID="348" Value="VE" StdVal="VE" Lang="hu" Type="Short" IsLead="1" IsStd="1" Ver="1">302</PName>
<PName PID="215" CID="348" Value="Veszprém" StdVal="Veszprém" Lang="hu" Type="Full" IsLead="1" IsStd="1" Ver="1">303</PName>
<PName PID="216" CID="348" Value="ZA" StdVal="ZA" Lang="hu" Type="Short" IsLead="1" IsStd="1" Ver="1">304</PName>
<PName PID="216" CID="348" Value="Zala" StdVal="Zala" Lang="hu" Type="Full" IsLead="1" IsStd="1" Ver="1">305</PName>
<PName PID="252" CID="380" Value="Aoste" StdVal="Aoste" Lang="fr" Type="Full" IsLead="1" IsStd="1" Ver="1">369</PName>
<PName PID="252" CID="380" Value="AO" StdVal="AO" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">367</PName>
<PName PID="252" CID="380" Value="Aosta" StdVal="Aosta" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">368</PName>
<PName PID="253" CID="380" Value="AG" StdVal="AG" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">370</PName>
<PName PID="253" CID="380" Value="Agrigento" StdVal="Agrigento" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">371</PName>
<PName PID="254" CID="380" Value="AL" StdVal="AL" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">372</PName>
<PName PID="254" CID="380" Value="Alessandria" StdVal="Alessandria" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">373</PName>
<PName PID="255" CID="380" Value="AN" StdVal="AN" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">374</PName>
<PName PID="255" CID="380" Value="Ancona" StdVal="Ancona" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">375</PName>
<PName PID="257" CID="380" Value="AR" StdVal="AR" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">376</PName>
<PName PID="257" CID="380" Value="Arezzo" StdVal="Arezzo" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">377</PName>
<PName PID="258" CID="380" Value="AP" StdVal="AP" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">378</PName>
<PName PID="258" CID="380" Value="Ascoli Piceno" StdVal="AscoliPiceno" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">379</PName>
<PName PID="259" CID="380" Value="Asti" StdVal="Asti" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">380</PName>
<PName PID="259" CID="380" Value="AT" StdVal="AT" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">381</PName>
<PName PID="260" CID="380" Value="AV" StdVal="AV" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">382</PName>
<PName PID="260" CID="380" Value="Avellino" StdVal="Avellino" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">383</PName>
<PName PID="261" CID="380" Value="BA" StdVal="BA" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">384</PName>
<PName PID="261" CID="380" Value="Bari" StdVal="Bari" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">385</PName>
<PName PID="262" CID="380" Value="Belluno" StdVal="Belluno" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">386</PName>
<PName PID="262" CID="380" Value="BL" StdVal="BL" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">387</PName>
<PName PID="263" CID="380" Value="Benevento" StdVal="Benevento" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">388</PName>
<PName PID="263" CID="380" Value="BN" StdVal="BN" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">389</PName>
<PName PID="264" CID="380" Value="Bergamo" StdVal="Bergamo" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">390</PName>
<PName PID="264" CID="380" Value="BG" StdVal="BG" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">391</PName>
<PName PID="265" CID="380" Value="BI" StdVal="BI" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">392</PName>
<PName PID="265" CID="380" Value="Biella" StdVal="Biella" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">393</PName>
<PName PID="266" CID="380" Value="BO" StdVal="BO" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">394</PName>
<PName PID="266" CID="380" Value="Bologna" StdVal="Bologna" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">395</PName>
<PName PID="267" CID="380" Value="Bozen" StdVal="Bozen" Lang="de" Type="Full" IsLead="1" IsStd="1" Ver="1">396</PName>
<PName PID="267" CID="380" Value="Bolzano" StdVal="Bolzano" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">397</PName>
<PName PID="267" CID="380" Value="BZ" StdVal="BZ" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">398</PName>
<PName PID="268" CID="380" Value="Brescia" StdVal="Brescia" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">399</PName>
<PName PID="268" CID="380" Value="BS" StdVal="BS" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">400</PName>
<PName PID="269" CID="380" Value="BR" StdVal="BR" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">401</PName>
<PName PID="269" CID="380" Value="Brindisi" StdVal="Brindisi" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">402</PName>
<PName PID="270" CID="380" Value="CA" StdVal="CA" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">403</PName>
<PName PID="270" CID="380" Value="Cagliari" StdVal="Cagliari" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">404</PName>
<PName PID="271" CID="380" Value="Caltanissetta" StdVal="Caltanissetta" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">405</PName>
<PName PID="271" CID="380" Value="CL" StdVal="CL" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">406</PName>
<PName PID="272" CID="380" Value="Campobasso" StdVal="Campobasso" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">407</PName>
<PName PID="272" CID="380" Value="CB" StdVal="CB" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">408</PName>
<PName PID="273" CID="380" Value="Carbonia-Iglesias" StdVal="CarboniaIglesias" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">409</PName>
<PName PID="274" CID="380" Value="Caserta" StdVal="Caserta" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">410</PName>
<PName PID="274" CID="380" Value="CE" StdVal="CE" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">411</PName>
<PName PID="275" CID="380" Value="Catania" StdVal="Catania" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">412</PName>
<PName PID="275" CID="380" Value="CT" StdVal="CT" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">413</PName>
<PName PID="276" CID="380" Value="Catanzaro" StdVal="Catanzaro" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">414</PName>
<PName PID="276" CID="380" Value="CZ" StdVal="CZ" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">415</PName>
<PName PID="277" CID="380" Value="CH" StdVal="CH" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">416</PName>
<PName PID="277" CID="380" Value="Chieti" StdVal="Chieti" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">417</PName>
<PName PID="278" CID="380" Value="CO" StdVal="CO" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">418</PName>
<PName PID="278" CID="380" Value="Como" StdVal="Como" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">419</PName>
<PName PID="279" CID="380" Value="Cosenza" StdVal="Cosenza" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">420</PName>
<PName PID="279" CID="380" Value="CS" StdVal="CS" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">421</PName>
<PName PID="280" CID="380" Value="CR" StdVal="CR" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">422</PName>
<PName PID="280" CID="380" Value="Cremona" StdVal="Cremona" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">423</PName>
<PName PID="281" CID="380" Value="Crotone" StdVal="Crotone" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">424</PName>
<PName PID="281" CID="380" Value="KR" StdVal="KR" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">425</PName>
<PName PID="282" CID="380" Value="CN" StdVal="CN" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">426</PName>
<PName PID="282" CID="380" Value="Cuneo" StdVal="Cuneo" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">427</PName>
<PName PID="283" CID="380" Value="EN" StdVal="EN" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">428</PName>
<PName PID="283" CID="380" Value="Enna" StdVal="Enna" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">429</PName>
<PName PID="284" CID="380" Value="FE" StdVal="FE" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">430</PName>
<PName PID="284" CID="380" Value="Ferrara" StdVal="Ferrara" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">431</PName>
<PName PID="285" CID="380" Value="FI" StdVal="FI" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">432</PName>
<PName PID="285" CID="380" Value="Firenze" StdVal="Firenze" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">433</PName>
<PName PID="286" CID="380" Value="FG" StdVal="FG" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">434</PName>
<PName PID="286" CID="380" Value="Foggia" StdVal="Foggia" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">435</PName>
<PName PID="287" CID="380" Value="FO" StdVal="FO" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">436</PName>
<PName PID="287" CID="380" Value="Forlì" StdVal="Forlì" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">437</PName>
<PName PID="288" CID="380" Value="FR" StdVal="FR" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">438</PName>
<PName PID="288" CID="380" Value="Frosinone" StdVal="Frosinone" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">439</PName>
<PName PID="289" CID="380" Value="GE" StdVal="GE" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">440</PName>
<PName PID="289" CID="380" Value="Genova" StdVal="Genova" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">441</PName>
<PName PID="290" CID="380" Value="GO" StdVal="GO" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">442</PName>
<PName PID="290" CID="380" Value="Gorizia" StdVal="Gorizia" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">443</PName>
<PName PID="291" CID="380" Value="GR" StdVal="GR" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">444</PName>
<PName PID="291" CID="380" Value="Grosseto" StdVal="Grosseto" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">445</PName>
<PName PID="292" CID="380" Value="IM" StdVal="IM" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">446</PName>
<PName PID="292" CID="380" Value="Imperia" StdVal="Imperia" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">447</PName>
<PName PID="293" CID="380" Value="IS" StdVal="IS" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">448</PName>
<PName PID="293" CID="380" Value="Isernia" StdVal="Isernia" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">449</PName>
<PName PID="294" CID="380" Value="La Spezia" StdVal="LaSpezia" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">450</PName>
<PName PID="294" CID="380" Value="SP" StdVal="SP" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">451</PName>
<PName PID="295" CID="380" Value="AQ" StdVal="AQ" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">452</PName>
<PName PID="295" CID="380" Value="L'Aquila" StdVal="LAquila" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">453</PName>
<PName PID="296" CID="380" Value="Latina" StdVal="Latina" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">454</PName>
<PName PID="296" CID="380" Value="LT" StdVal="LT" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">455</PName>
<PName PID="297" CID="380" Value="LE" StdVal="LE" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">456</PName>
<PName PID="297" CID="380" Value="Lecce" StdVal="Lecce" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">457</PName>
<PName PID="298" CID="380" Value="LC" StdVal="LC" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">458</PName>
<PName PID="298" CID="380" Value="Lecco" StdVal="Lecco" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">459</PName>
<PName PID="299" CID="380" Value="LI" StdVal="LI" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">460</PName>
<PName PID="299" CID="380" Value="Livorno" StdVal="Livorno" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">461</PName>
<PName PID="300" CID="380" Value="LO" StdVal="LO" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">462</PName>
<PName PID="300" CID="380" Value="Lodi" StdVal="Lodi" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">463</PName>
<PName PID="301" CID="380" Value="LU" StdVal="LU" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">464</PName>
<PName PID="301" CID="380" Value="Lucca" StdVal="Lucca" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">465</PName>
<PName PID="302" CID="380" Value="Macerata" StdVal="Macerata" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">466</PName>
<PName PID="302" CID="380" Value="MC" StdVal="MC" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">467</PName>
<PName PID="303" CID="380" Value="Mantova" StdVal="Mantova" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">468</PName>
<PName PID="303" CID="380" Value="MN" StdVal="MN" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">469</PName>
<PName PID="304" CID="380" Value="Massa-Carrara" StdVal="MassaCarrara" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">470</PName>
<PName PID="304" CID="380" Value="MS" StdVal="MS" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">471</PName>
<PName PID="305" CID="380" Value="Matera" StdVal="Matera" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">472</PName>
<PName PID="305" CID="380" Value="MT" StdVal="MT" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">473</PName>
<PName PID="306" CID="380" Value="Medio Campidano" StdVal="MedioCampidano" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">474</PName>
<PName PID="307" CID="380" Value="ME" StdVal="ME" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">475</PName>
<PName PID="307" CID="380" Value="Messina" StdVal="Messina" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">476</PName>
<PName PID="308" CID="380" Value="MI" StdVal="MI" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">477</PName>
<PName PID="308" CID="380" Value="Milano" StdVal="Milano" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">478</PName>
<PName PID="309" CID="380" Value="MO" StdVal="MO" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">479</PName>
<PName PID="309" CID="380" Value="Modena" StdVal="Modena" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">480</PName>
<PName PID="310" CID="380" Value="NA" StdVal="NA" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">481</PName>
<PName PID="310" CID="380" Value="Napoli" StdVal="Napoli" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">482</PName>
<PName PID="311" CID="380" Value="NO" StdVal="NO" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">483</PName>
<PName PID="311" CID="380" Value="Novara" StdVal="Novara" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">484</PName>
<PName PID="312" CID="380" Value="NU" StdVal="NU" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">485</PName>
<PName PID="312" CID="380" Value="Nuoro" StdVal="Nuoro" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">486</PName>
<PName PID="313" CID="380" Value="Ogliastra" StdVal="Ogliastra" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">487</PName>
<PName PID="314" CID="380" Value="Olbia-Tempio" StdVal="OlbiaTempio" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">488</PName>
<PName PID="315" CID="380" Value="OR" StdVal="OR" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">489</PName>
<PName PID="315" CID="380" Value="Oristano" StdVal="Oristano" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">490</PName>
<PName PID="316" CID="380" Value="Padova" StdVal="Padova" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">491</PName>
<PName PID="316" CID="380" Value="PD" StdVal="PD" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">492</PName>
<PName PID="317" CID="380" Value="PA" StdVal="PA" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">493</PName>
<PName PID="317" CID="380" Value="Palermo" StdVal="Palermo" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">494</PName>
<PName PID="318" CID="380" Value="Parma" StdVal="Parma" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">495</PName>
<PName PID="318" CID="380" Value="PR" StdVal="PR" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">496</PName>
<PName PID="319" CID="380" Value="Pavia" StdVal="Pavia" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">497</PName>
<PName PID="319" CID="380" Value="PV" StdVal="PV" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">498</PName>
<PName PID="320" CID="380" Value="Perugia" StdVal="Perugia" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">499</PName>
<PName PID="320" CID="380" Value="PG" StdVal="PG" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">500</PName>
<PName PID="321" CID="380" Value="Pesaro e Urbino" StdVal="PesaroeUrbino" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">501</PName>
<PName PID="321" CID="380" Value="PS" StdVal="PS" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">502</PName>
<PName PID="322" CID="380" Value="PE" StdVal="PE" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">503</PName>
<PName PID="322" CID="380" Value="Pescara" StdVal="Pescara" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">504</PName>
<PName PID="323" CID="380" Value="PC" StdVal="PC" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">505</PName>
<PName PID="323" CID="380" Value="Piacenza" StdVal="Piacenza" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">506</PName>
<PName PID="324" CID="380" Value="PI" StdVal="PI" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">507</PName>
<PName PID="324" CID="380" Value="Pisa" StdVal="Pisa" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">508</PName>
<PName PID="325" CID="380" Value="Pistoia" StdVal="Pistoia" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">509</PName>
<PName PID="325" CID="380" Value="PT" StdVal="PT" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">510</PName>
<PName PID="326" CID="380" Value="PN" StdVal="PN" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">511</PName>
<PName PID="326" CID="380" Value="Pordenone" StdVal="Pordenone" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">512</PName>
<PName PID="327" CID="380" Value="Potenza" StdVal="Potenza" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">513</PName>
<PName PID="327" CID="380" Value="PZ" StdVal="PZ" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">514</PName>
<PName PID="328" CID="380" Value="PO" StdVal="PO" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">515</PName>
<PName PID="328" CID="380" Value="Prato" StdVal="Prato" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">516</PName>
<PName PID="329" CID="380" Value="Ragusa" StdVal="Ragusa" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">517</PName>
<PName PID="329" CID="380" Value="RG" StdVal="RG" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">518</PName>
<PName PID="330" CID="380" Value="RA" StdVal="RA" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">519</PName>
<PName PID="330" CID="380" Value="Ravenna" StdVal="Ravenna" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">520</PName>
<PName PID="331" CID="380" Value="RC" StdVal="RC" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">521</PName>
<PName PID="331" CID="380" Value="Reggio Calabria" StdVal="ReggioCalabria" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">522</PName>
<PName PID="332" CID="380" Value="RE" StdVal="RE" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">523</PName>
<PName PID="332" CID="380" Value="Reggio Emilia" StdVal="ReggioEmilia" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">524</PName>
<PName PID="333" CID="380" Value="RI" StdVal="RI" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">525</PName>
<PName PID="333" CID="380" Value="Rieti" StdVal="Rieti" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">526</PName>
<PName PID="334" CID="380" Value="Rimini" StdVal="Rimini" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">527</PName>
<PName PID="334" CID="380" Value="RN" StdVal="RN" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">528</PName>
<PName PID="335" CID="380" Value="RM" StdVal="RM" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">529</PName>
<PName PID="335" CID="380" Value="Roma" StdVal="Roma" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">530</PName>
<PName PID="336" CID="380" Value="RO" StdVal="RO" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">531</PName>
<PName PID="336" CID="380" Value="Rovigo" StdVal="Rovigo" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">532</PName>
<PName PID="337" CID="380" Value="SA" StdVal="SA" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">533</PName>
<PName PID="337" CID="380" Value="Salerno" StdVal="Salerno" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">534</PName>
<PName PID="338" CID="380" Value="Sassari" StdVal="Sassari" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">535</PName>
<PName PID="338" CID="380" Value="SS" StdVal="SS" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">536</PName>
<PName PID="339" CID="380" Value="Savona" StdVal="Savona" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">537</PName>
<PName PID="339" CID="380" Value="SV" StdVal="SV" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">538</PName>
<PName PID="340" CID="380" Value="SI" StdVal="SI" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">539</PName>
<PName PID="340" CID="380" Value="Siena" StdVal="Siena" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">540</PName>
<PName PID="341" CID="380" Value="Siracusa" StdVal="Siracusa" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">541</PName>
<PName PID="341" CID="380" Value="SR" StdVal="SR" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">542</PName>
<PName PID="342" CID="380" Value="SO" StdVal="SO" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">543</PName>
<PName PID="342" CID="380" Value="Sondrio" StdVal="Sondrio" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">544</PName>
<PName PID="343" CID="380" Value="TA" StdVal="TA" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">545</PName>
<PName PID="343" CID="380" Value="Taranto" StdVal="Taranto" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">546</PName>
<PName PID="344" CID="380" Value="TE" StdVal="TE" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">547</PName>
<PName PID="344" CID="380" Value="Teramo" StdVal="Teramo" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">548</PName>
<PName PID="345" CID="380" Value="Terni" StdVal="Terni" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">549</PName>
<PName PID="345" CID="380" Value="TR" StdVal="TR" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">550</PName>
<PName PID="346" CID="380" Value="TO" StdVal="TO" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">551</PName>
<PName PID="346" CID="380" Value="Torino" StdVal="Torino" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">552</PName>
<PName PID="347" CID="380" Value="TP" StdVal="TP" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">553</PName>
<PName PID="347" CID="380" Value="Trapani" StdVal="Trapani" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">554</PName>
<PName PID="348" CID="380" Value="TN" StdVal="TN" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">555</PName>
<PName PID="348" CID="380" Value="Trento" StdVal="Trento" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">556</PName>
<PName PID="349" CID="380" Value="Treviso" StdVal="Treviso" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">557</PName>
<PName PID="349" CID="380" Value="TV" StdVal="TV" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">558</PName>
<PName PID="350" CID="380" Value="Trieste" StdVal="Trieste" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">559</PName>
<PName PID="350" CID="380" Value="TS" StdVal="TS" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">560</PName>
<PName PID="351" CID="380" Value="UD" StdVal="UD" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">561</PName>
<PName PID="351" CID="380" Value="Udine" StdVal="Udine" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">562</PName>
<PName PID="352" CID="380" Value="VA" StdVal="VA" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">563</PName>
<PName PID="352" CID="380" Value="Varese" StdVal="Varese" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">564</PName>
<PName PID="353" CID="380" Value="VE" StdVal="VE" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">565</PName>
<PName PID="353" CID="380" Value="Venezia" StdVal="Venezia" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">566</PName>
<PName PID="354" CID="380" Value="VB" StdVal="VB" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">567</PName>
<PName PID="354" CID="380" Value="Verbano-Cusio-Ossola" StdVal="VerbanoCusioOssola" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">568</PName>
<PName PID="355" CID="380" Value="VC" StdVal="VC" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">569</PName>
<PName PID="355" CID="380" Value="Vercelli" StdVal="Vercelli" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">570</PName>
<PName PID="356" CID="380" Value="Verona" StdVal="Verona" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">571</PName>
<PName PID="356" CID="380" Value="VR" StdVal="VR" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">572</PName>
<PName PID="357" CID="380" Value="Vibo Valentia" StdVal="ViboValentia" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">573</PName>
<PName PID="357" CID="380" Value="VV" StdVal="VV" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">574</PName>
<PName PID="358" CID="380" Value="VI" StdVal="VI" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">575</PName>
<PName PID="358" CID="380" Value="Vicenza" StdVal="Vicenza" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">576</PName>
<PName PID="359" CID="380" Value="Viterbo" StdVal="Viterbo" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">577</PName>
<PName PID="359" CID="380" Value="VT" StdVal="VT" Lang="it" Type="Short" IsLead="1" IsStd="1" Ver="1">578</PName>
<PName PID="427" CID="498" Value="Bălţi" StdVal="Bălţi" Lang="ro" Type="Full" IsLead="1" IsStd="1" Ver="1">678</PName>
<PName PID="428" CID="498" Value="Bender" StdVal="Bender" Lang="ro" Type="Full" IsLead="1" IsStd="1" Ver="1">679</PName>
<PName PID="428" CID="498" Value="Tighina" StdVal="Tighina" Lang="ro" Type="Full" IsLead="0" IsStd="1" Ver="1">680</PName>
<PName PID="429" CID="498" Value="Cahul" StdVal="Cahul" Lang="ro" Type="Full" IsLead="1" IsStd="1" Ver="1">681</PName>
<PName PID="430" CID="498" Value="Chişinău" StdVal="Chişinău" Lang="ro" Type="Full" IsLead="1" IsStd="1" Ver="1">682</PName>
<PName PID="431" CID="498" Value="Edineţ" StdVal="Edineţ" Lang="ro" Type="Full" IsLead="1" IsStd="1" Ver="1">683</PName>
<PName PID="432" CID="498" Value="Lăpuşna" StdVal="Lăpuşna" Lang="ro" Type="Full" IsLead="1" IsStd="1" Ver="1">684</PName>
<PName PID="433" CID="498" Value="Orhei" StdVal="Orhei" Lang="ro" Type="Full" IsLead="1" IsStd="1" Ver="1">685</PName>
<PName PID="434" CID="498" Value="Soroca" StdVal="Soroca" Lang="ro" Type="Full" IsLead="1" IsStd="1" Ver="1">686</PName>
<PName PID="435" CID="498" Value="Taraclia" StdVal="Taraclia" Lang="ro" Type="Full" IsLead="1" IsStd="1" Ver="1">687</PName>
<PName PID="437" CID="498" Value="Ungheni" StdVal="Ungheni" Lang="ro" Type="Full" IsLead="1" IsStd="1" Ver="1">688</PName>
<PName PID="485" CID="616" Value="Dolnośląskie" StdVal="Dolnośląskie" Lang="pl" Type="Full" IsLead="1" IsStd="1" Ver="1">769</PName>
<PName PID="485" CID="616" Value="DS" StdVal="DS" Lang="pl" Type="Short" IsLead="1" IsStd="1" Ver="1">770</PName>
<PName PID="486" CID="616" Value="KP" StdVal="KP" Lang="pl" Type="Short" IsLead="1" IsStd="1" Ver="1">771</PName>
<PName PID="486" CID="616" Value="Kujawsko-pomorskie" StdVal="Kujawskopomorskie" Lang="pl" Type="Full" IsLead="1" IsStd="1" Ver="1">772</PName>
<PName PID="487" CID="616" Value="LD" StdVal="LD" Lang="pl" Type="Short" IsLead="1" IsStd="1" Ver="1">773</PName>
<PName PID="487" CID="616" Value="Łódzkie" StdVal="Łódzkie" Lang="pl" Type="Full" IsLead="1" IsStd="1" Ver="1">774</PName>
<PName PID="488" CID="616" Value="LU" StdVal="LU" Lang="pl" Type="Short" IsLead="1" IsStd="1" Ver="1">775</PName>
<PName PID="488" CID="616" Value="Lubelskie" StdVal="Lubelskie" Lang="pl" Type="Full" IsLead="1" IsStd="1" Ver="1">776</PName>
<PName PID="489" CID="616" Value="LB" StdVal="LB" Lang="pl" Type="Short" IsLead="1" IsStd="1" Ver="1">777</PName>
<PName PID="489" CID="616" Value="Lubuskie" StdVal="Lubuskie" Lang="pl" Type="Full" IsLead="1" IsStd="1" Ver="1">778</PName>
<PName PID="490" CID="616" Value="MA" StdVal="MA" Lang="pl" Type="Short" IsLead="1" IsStd="1" Ver="1">779</PName>
<PName PID="490" CID="616" Value="Małopolskie" StdVal="Małopolskie" Lang="pl" Type="Full" IsLead="1" IsStd="1" Ver="1">780</PName>
<PName PID="491" CID="616" Value="Mazowieckie" StdVal="Mazowieckie" Lang="pl" Type="Full" IsLead="1" IsStd="1" Ver="1">781</PName>
<PName PID="491" CID="616" Value="MZ" StdVal="MZ" Lang="pl" Type="Short" IsLead="1" IsStd="1" Ver="1">782</PName>
<PName PID="492" CID="616" Value="OP" StdVal="OP" Lang="pl" Type="Short" IsLead="1" IsStd="1" Ver="1">783</PName>
<PName PID="492" CID="616" Value="Opolskie" StdVal="Opolskie" Lang="pl" Type="Full" IsLead="1" IsStd="1" Ver="1">784</PName>
<PName PID="493" CID="616" Value="PK" StdVal="PK" Lang="pl" Type="Short" IsLead="1" IsStd="1" Ver="1">785</PName>
<PName PID="493" CID="616" Value="Podkarpackie" StdVal="Podkarpackie" Lang="pl" Type="Full" IsLead="1" IsStd="1" Ver="1">786</PName>
<PName PID="494" CID="616" Value="PD" StdVal="PD" Lang="pl" Type="Short" IsLead="1" IsStd="1" Ver="1">787</PName>
<PName PID="494" CID="616" Value="Podlaskie" StdVal="Podlaskie" Lang="pl" Type="Full" IsLead="1" IsStd="1" Ver="1">788</PName>
<PName PID="495" CID="616" Value="PM" StdVal="PM" Lang="pl" Type="Short" IsLead="1" IsStd="1" Ver="1">789</PName>
<PName PID="495" CID="616" Value="Pomorskie" StdVal="Pomorskie" Lang="pl" Type="Full" IsLead="1" IsStd="1" Ver="1">790</PName>
<PName PID="496" CID="616" Value="SL" StdVal="SL" Lang="pl" Type="Short" IsLead="1" IsStd="1" Ver="1">791</PName>
<PName PID="496" CID="616" Value="Śląskie" StdVal="Śląskie" Lang="pl" Type="Full" IsLead="1" IsStd="1" Ver="1">792</PName>
<PName PID="497" CID="616" Value="SK" StdVal="SK" Lang="pl" Type="Short" IsLead="1" IsStd="1" Ver="1">793</PName>
<PName PID="497" CID="616" Value="Świętokrzyskie" StdVal="Świętokrzyskie" Lang="pl" Type="Full" IsLead="1" IsStd="1" Ver="1">794</PName>
<PName PID="498" CID="616" Value="Warmińsko-mazurskie" StdVal="Warmińskomazurskie" Lang="pl" Type="Full" IsLead="1" IsStd="1" Ver="1">795</PName>
<PName PID="498" CID="616" Value="WN" StdVal="WN" Lang="pl" Type="Short" IsLead="1" IsStd="1" Ver="1">796</PName>
<PName PID="499" CID="616" Value="Wielkopolskie" StdVal="Wielkopolskie" Lang="pl" Type="Full" IsLead="1" IsStd="1" Ver="1">797</PName>
<PName PID="499" CID="616" Value="WP" StdVal="WP" Lang="pl" Type="Short" IsLead="1" IsStd="1" Ver="1">798</PName>
<PName PID="500" CID="616" Value="Zachodniopomorskie" StdVal="Zachodniopomorskie" Lang="pl" Type="Full" IsLead="1" IsStd="1" Ver="1">799</PName>
<PName PID="500" CID="616" Value="ZP" StdVal="ZP" Lang="pl" Type="Short" IsLead="1" IsStd="1" Ver="1">800</PName>
<PName PID="519" CID="642" Value="AB" StdVal="AB" Lang="ro" Type="Short" IsLead="1" IsStd="1" Ver="1">819</PName>
<PName PID="519" CID="642" Value="Alba" StdVal="Alba" Lang="ro" Type="Full" IsLead="1" IsStd="1" Ver="1">820</PName>
<PName PID="520" CID="642" Value="AR" StdVal="AR" Lang="ro" Type="Short" IsLead="1" IsStd="1" Ver="1">821</PName>
<PName PID="520" CID="642" Value="Arad" StdVal="Arad" Lang="ro" Type="Full" IsLead="1" IsStd="1" Ver="1">822</PName>
<PName PID="521" CID="642" Value="AG" StdVal="AG" Lang="ro" Type="Short" IsLead="1" IsStd="1" Ver="1">823</PName>
<PName PID="521" CID="642" Value="Argeş" StdVal="Argeş" Lang="ro" Type="Full" IsLead="1" IsStd="1" Ver="1">824</PName>
<PName PID="522" CID="642" Value="Bacău" StdVal="Bacău" Lang="ro" Type="Full" IsLead="1" IsStd="1" Ver="1">825</PName>
<PName PID="522" CID="642" Value="BC" StdVal="BC" Lang="ro" Type="Short" IsLead="1" IsStd="1" Ver="1">826</PName>
<PName PID="523" CID="642" Value="BH" StdVal="BH" Lang="ro" Type="Short" IsLead="1" IsStd="1" Ver="1">827</PName>
<PName PID="523" CID="642" Value="Bihor" StdVal="Bihor" Lang="ro" Type="Full" IsLead="1" IsStd="1" Ver="1">828</PName>
<PName PID="524" CID="642" Value="Bistriţa-Năsăud" StdVal="BistriţaNăsăud" Lang="ro" Type="Full" IsLead="1" IsStd="1" Ver="1">829</PName>
<PName PID="524" CID="642" Value="BN" StdVal="BN" Lang="ro" Type="Short" IsLead="1" IsStd="1" Ver="1">830</PName>
<PName PID="525" CID="642" Value="Botoşani" StdVal="Botoşani" Lang="ro" Type="Full" IsLead="1" IsStd="1" Ver="1">831</PName>
<PName PID="525" CID="642" Value="BT" StdVal="BT" Lang="ro" Type="Short" IsLead="1" IsStd="1" Ver="1">832</PName>
<PName PID="526" CID="642" Value="BR" StdVal="BR" Lang="ro" Type="Short" IsLead="1" IsStd="1" Ver="1">833</PName>
<PName PID="526" CID="642" Value="Brăila" StdVal="Brăila" Lang="ro" Type="Full" IsLead="1" IsStd="1" Ver="1">834</PName>
<PName PID="527" CID="642" Value="Braşov" StdVal="Braşov" Lang="ro" Type="Full" IsLead="1" IsStd="1" Ver="1">835</PName>
<PName PID="527" CID="642" Value="BV" StdVal="BV" Lang="ro" Type="Short" IsLead="1" IsStd="1" Ver="1">836</PName>
<PName PID="528" CID="642" Value="B" StdVal="B" Lang="ro" Type="Short" IsLead="1" IsStd="1" Ver="1">837</PName>
<PName PID="528" CID="642" Value="Bucureşti" StdVal="Bucureşti" Lang="ro" Type="Full" IsLead="1" IsStd="1" Ver="1">838</PName>
<PName PID="529" CID="642" Value="Buzău" StdVal="Buzău" Lang="ro" Type="Full" IsLead="1" IsStd="1" Ver="1">839</PName>
<PName PID="529" CID="642" Value="BZ" StdVal="BZ" Lang="ro" Type="Short" IsLead="1" IsStd="1" Ver="1">840</PName>
<PName PID="530" CID="642" Value="Călăraşi" StdVal="Călăraşi" Lang="ro" Type="Full" IsLead="1" IsStd="1" Ver="1">841</PName>
<PName PID="530" CID="642" Value="CL" StdVal="CL" Lang="ro" Type="Short" IsLead="1" IsStd="1" Ver="1">842</PName>
<PName PID="531" CID="642" Value="Caraş-Severin" StdVal="CaraşSeverin" Lang="ro" Type="Full" IsLead="1" IsStd="1" Ver="1">843</PName>
<PName PID="531" CID="642" Value="CS" StdVal="CS" Lang="ro" Type="Short" IsLead="1" IsStd="1" Ver="1">844</PName>
<PName PID="532" CID="642" Value="CJ" StdVal="CJ" Lang="ro" Type="Short" IsLead="1" IsStd="1" Ver="1">845</PName>
<PName PID="532" CID="642" Value="Cluj" StdVal="Cluj" Lang="ro" Type="Full" IsLead="1" IsStd="1" Ver="1">846</PName>
<PName PID="533" CID="642" Value="Constanţa" StdVal="Constanţa" Lang="ro" Type="Full" IsLead="1" IsStd="1" Ver="1">847</PName>
<PName PID="533" CID="642" Value="CT" StdVal="CT" Lang="ro" Type="Short" IsLead="1" IsStd="1" Ver="1">848</PName>
<PName PID="534" CID="642" Value="Covasna" StdVal="Covasna" Lang="ro" Type="Full" IsLead="1" IsStd="1" Ver="1">849</PName>
<PName PID="534" CID="642" Value="CV" StdVal="CV" Lang="ro" Type="Short" IsLead="1" IsStd="1" Ver="1">850</PName>
<PName PID="535" CID="642" Value="Dâmboviţa" StdVal="Dâmboviţa" Lang="ro" Type="Full" IsLead="1" IsStd="1" Ver="1">851</PName>
<PName PID="535" CID="642" Value="DB" StdVal="DB" Lang="ro" Type="Short" IsLead="1" IsStd="1" Ver="1">852</PName>
<PName PID="536" CID="642" Value="DJ" StdVal="DJ" Lang="ro" Type="Short" IsLead="1" IsStd="1" Ver="1">853</PName>
<PName PID="536" CID="642" Value="Dolj" StdVal="Dolj" Lang="ro" Type="Full" IsLead="1" IsStd="1" Ver="1">854</PName>
<PName PID="537" CID="642" Value="Galaţi" StdVal="Galaţi" Lang="ro" Type="Full" IsLead="1" IsStd="1" Ver="1">855</PName>
<PName PID="537" CID="642" Value="GL" StdVal="GL" Lang="ro" Type="Short" IsLead="1" IsStd="1" Ver="1">856</PName>
<PName PID="538" CID="642" Value="Giurgiu" StdVal="Giurgiu" Lang="ro" Type="Full" IsLead="1" IsStd="1" Ver="1">857</PName>
<PName PID="538" CID="642" Value="GR" StdVal="GR" Lang="ro" Type="Short" IsLead="1" IsStd="1" Ver="1">858</PName>
<PName PID="539" CID="642" Value="GJ" StdVal="GJ" Lang="ro" Type="Short" IsLead="1" IsStd="1" Ver="1">859</PName>
<PName PID="539" CID="642" Value="Gorj" StdVal="Gorj" Lang="ro" Type="Full" IsLead="1" IsStd="1" Ver="1">860</PName>
<PName PID="540" CID="642" Value="Harghita" StdVal="Harghita" Lang="ro" Type="Full" IsLead="1" IsStd="1" Ver="1">861</PName>
<PName PID="540" CID="642" Value="HR" StdVal="HR" Lang="ro" Type="Short" IsLead="1" IsStd="1" Ver="1">862</PName>
<PName PID="541" CID="642" Value="HD" StdVal="HD" Lang="ro" Type="Short" IsLead="1" IsStd="1" Ver="1">863</PName>
<PName PID="541" CID="642" Value="Hunedoara" StdVal="Hunedoara" Lang="ro" Type="Full" IsLead="1" IsStd="1" Ver="1">864</PName>
<PName PID="542" CID="642" Value="Ialomiţa" StdVal="Ialomiţa" Lang="ro" Type="Full" IsLead="1" IsStd="1" Ver="1">865</PName>
<PName PID="542" CID="642" Value="IL" StdVal="IL" Lang="ro" Type="Short" IsLead="1" IsStd="1" Ver="1">866</PName>
<PName PID="543" CID="642" Value="Iaşi" StdVal="Iaşi" Lang="ro" Type="Full" IsLead="1" IsStd="1" Ver="1">867</PName>
<PName PID="543" CID="642" Value="IS" StdVal="IS" Lang="ro" Type="Short" IsLead="1" IsStd="1" Ver="1">868</PName>
<PName PID="544" CID="642" Value="Ilfov" StdVal="Ilfov" Lang="ro" Type="Full" IsLead="1" IsStd="1" Ver="1">869</PName>
<PName PID="545" CID="642" Value="Maramureş" StdVal="Maramureş" Lang="ro" Type="Full" IsLead="1" IsStd="1" Ver="1">870</PName>
<PName PID="545" CID="642" Value="MM" StdVal="MM" Lang="ro" Type="Short" IsLead="1" IsStd="1" Ver="1">871</PName>
<PName PID="546" CID="642" Value="Mehedinţi" StdVal="Mehedinţi" Lang="ro" Type="Full" IsLead="1" IsStd="1" Ver="1">872</PName>
<PName PID="546" CID="642" Value="MH" StdVal="MH" Lang="ro" Type="Short" IsLead="1" IsStd="1" Ver="1">873</PName>
<PName PID="547" CID="642" Value="MS" StdVal="MS" Lang="ro" Type="Short" IsLead="1" IsStd="1" Ver="1">874</PName>
<PName PID="547" CID="642" Value="Mureş" StdVal="Mureş" Lang="ro" Type="Full" IsLead="1" IsStd="1" Ver="1">875</PName>
<PName PID="548" CID="642" Value="Neamţ" StdVal="Neamţ" Lang="ro" Type="Full" IsLead="1" IsStd="1" Ver="1">876</PName>
<PName PID="548" CID="642" Value="NT" StdVal="NT" Lang="ro" Type="Short" IsLead="1" IsStd="1" Ver="1">877</PName>
<PName PID="549" CID="642" Value="Olt" StdVal="Olt" Lang="ro" Type="Full" IsLead="1" IsStd="1" Ver="1">878</PName>
<PName PID="549" CID="642" Value="OT" StdVal="OT" Lang="ro" Type="Short" IsLead="1" IsStd="1" Ver="1">879</PName>
<PName PID="550" CID="642" Value="PH" StdVal="PH" Lang="ro" Type="Short" IsLead="1" IsStd="1" Ver="1">880</PName>
<PName PID="550" CID="642" Value="Prahova" StdVal="Prahova" Lang="ro" Type="Full" IsLead="1" IsStd="1" Ver="1">881</PName>
<PName PID="551" CID="642" Value="Sălaj" StdVal="Sălaj" Lang="ro" Type="Full" IsLead="1" IsStd="1" Ver="1">882</PName>
<PName PID="551" CID="642" Value="SJ" StdVal="SJ" Lang="ro" Type="Short" IsLead="1" IsStd="1" Ver="1">883</PName>
<PName PID="552" CID="642" Value="Satu Mare" StdVal="SatuMare" Lang="ro" Type="Full" IsLead="1" IsStd="1" Ver="1">884</PName>
<PName PID="552" CID="642" Value="SM" StdVal="SM" Lang="ro" Type="Short" IsLead="1" IsStd="1" Ver="1">885</PName>
<PName PID="553" CID="642" Value="SB" StdVal="SB" Lang="ro" Type="Short" IsLead="1" IsStd="1" Ver="1">886</PName>
<PName PID="553" CID="642" Value="Sibiu" StdVal="Sibiu" Lang="ro" Type="Full" IsLead="1" IsStd="1" Ver="1">887</PName>
<PName PID="554" CID="642" Value="Suceava" StdVal="Suceava" Lang="ro" Type="Full" IsLead="1" IsStd="1" Ver="1">888</PName>
<PName PID="554" CID="642" Value="SV" StdVal="SV" Lang="ro" Type="Short" IsLead="1" IsStd="1" Ver="1">889</PName>
<PName PID="555" CID="642" Value="Teleorman" StdVal="Teleorman" Lang="ro" Type="Full" IsLead="1" IsStd="1" Ver="1">890</PName>
<PName PID="555" CID="642" Value="TR" StdVal="TR" Lang="ro" Type="Short" IsLead="1" IsStd="1" Ver="1">891</PName>
<PName PID="556" CID="642" Value="Timiş" StdVal="Timiş" Lang="ro" Type="Full" IsLead="1" IsStd="1" Ver="1">892</PName>
<PName PID="556" CID="642" Value="TM" StdVal="TM" Lang="ro" Type="Short" IsLead="1" IsStd="1" Ver="1">893</PName>
<PName PID="557" CID="642" Value="TL" StdVal="TL" Lang="ro" Type="Short" IsLead="1" IsStd="1" Ver="1">894</PName>
<PName PID="557" CID="642" Value="Tulcea" StdVal="Tulcea" Lang="ro" Type="Full" IsLead="1" IsStd="1" Ver="1">895</PName>
<PName PID="558" CID="642" Value="Vâlcea" StdVal="Vâlcea" Lang="ro" Type="Full" IsLead="1" IsStd="1" Ver="1">896</PName>
<PName PID="558" CID="642" Value="VL" StdVal="VL" Lang="ro" Type="Short" IsLead="1" IsStd="1" Ver="1">897</PName>
<PName PID="559" CID="642" Value="Vaslui" StdVal="Vaslui" Lang="ro" Type="Full" IsLead="1" IsStd="1" Ver="1">898</PName>
<PName PID="559" CID="642" Value="VS" StdVal="VS" Lang="ro" Type="Short" IsLead="1" IsStd="1" Ver="1">899</PName>
<PName PID="560" CID="642" Value="VN" StdVal="VN" Lang="ro" Type="Short" IsLead="1" IsStd="1" Ver="1">900</PName>
<PName PID="560" CID="642" Value="Vrancea" StdVal="Vrancea" Lang="ro" Type="Full" IsLead="1" IsStd="1" Ver="1">901</PName>
<PName PID="561" CID="643" Value="Amurskaya oblast'" StdVal="Amurskayaoblast" Lang="ru" Type="Full" IsLead="1" IsStd="1" Ver="1">903</PName>
<PName PID="562" CID="643" Value="Arkhangel'skaya obla" StdVal="Arkhangelskayaobla" Lang="ru" Type="Full" IsLead="1" IsStd="1" Ver="1">905</PName>
<PName PID="563" CID="643" Value="Astrakhanskaya oblas" StdVal="Astrakhanskayaoblas" Lang="ru" Type="Full" IsLead="1" IsStd="1" Ver="1">908</PName>
<PName PID="564" CID="643" Value="Belgorodskaya oblast" StdVal="Belgorodskayaoblast" Lang="ru" Type="Full" IsLead="1" IsStd="1" Ver="1">910</PName>
<PName PID="565" CID="643" Value="Bryanskaya oblast'" StdVal="Bryanskayaoblast" Lang="ru" Type="Full" IsLead="1" IsStd="1" Ver="1">913</PName>
<PName PID="566" CID="643" Value="Chelyabinskaya oblas" StdVal="Chelyabinskayaoblas" Lang="ru" Type="Full" IsLead="1" IsStd="1" Ver="1">916</PName>
<PName PID="567" CID="643" Value="Chitinskaya oblast'" StdVal="Chitinskayaoblast" Lang="ru" Type="Full" IsLead="1" IsStd="1" Ver="1">919</PName>
<PName PID="568" CID="643" Value="Irkutskaya oblast'" StdVal="Irkutskayaoblast" Lang="ru" Type="Full" IsLead="1" IsStd="1" Ver="1">921</PName>
<PName PID="569" CID="643" Value="Ivanovskaya oblast'" StdVal="Ivanovskayaoblast" Lang="ru" Type="Full" IsLead="1" IsStd="1" Ver="1">923</PName>
<PName PID="570" CID="643" Value="Kaliningradskaya obl" StdVal="Kaliningradskayaobl" Lang="ru" Type="Full" IsLead="1" IsStd="1" Ver="1">925</PName>
<PName PID="571" CID="643" Value="Kaluzhskaya oblast'" StdVal="Kaluzhskayaoblast" Lang="ru" Type="Full" IsLead="1" IsStd="1" Ver="1">928</PName>
<PName PID="572" CID="643" Value="Kemerovskaya oblast'" StdVal="Kemerovskayaoblast" Lang="ru" Type="Full" IsLead="1" IsStd="1" Ver="1">930</PName>
<PName PID="573" CID="643" Value="Kirovskaya oblast'" StdVal="Kirovskayaoblast" Lang="ru" Type="Full" IsLead="1" IsStd="1" Ver="1">932</PName>
<PName PID="574" CID="643" Value="Kostromskaya oblast'" StdVal="Kostromskayaoblast" Lang="ru" Type="Full" IsLead="1" IsStd="1" Ver="1">934</PName>
<PName PID="575" CID="643" Value="Kurganskaya oblast'" StdVal="Kurganskayaoblast" Lang="ru" Type="Full" IsLead="1" IsStd="1" Ver="1">936</PName>
<PName PID="576" CID="643" Value="Kurskaya oblast'" StdVal="Kurskayaoblast" Lang="ru" Type="Full" IsLead="1" IsStd="1" Ver="1">938</PName>
<PName PID="577" CID="643" Value="Leningradskaya oblas" StdVal="Leningradskayaoblas" Lang="ru" Type="Full" IsLead="1" IsStd="1" Ver="1">940</PName>
<PName PID="578" CID="643" Value="Lipetskaya oblast'" StdVal="Lipetskayaoblast" Lang="ru" Type="Full" IsLead="1" IsStd="1" Ver="1">942</PName>
<PName PID="579" CID="643" Value="Magadanskaya oblast'" StdVal="Magadanskayaoblast" Lang="ru" Type="Full" IsLead="1" IsStd="1" Ver="1">944</PName>
<PName PID="580" CID="643" Value="Moskovskaya oblast'" StdVal="Moskovskayaoblast" Lang="ru" Type="Full" IsLead="1" IsStd="1" Ver="1">947</PName>
<PName PID="581" CID="643" Value="Murmanskaya oblast'" StdVal="Murmanskayaoblast" Lang="ru" Type="Full" IsLead="1" IsStd="1" Ver="1">949</PName>
<PName PID="582" CID="643" Value="Nizhegorodskaya obla" StdVal="Nizhegorodskayaobla" Lang="ru" Type="Full" IsLead="1" IsStd="1" Ver="1">953</PName>
<PName PID="583" CID="643" Value="Novgorodskaya oblast" StdVal="Novgorodskayaoblast" Lang="ru" Type="Full" IsLead="1" IsStd="1" Ver="1">955</PName>
<PName PID="584" CID="643" Value="Novosibirskaya oblas" StdVal="Novosibirskayaoblas" Lang="ru" Type="Full" IsLead="1" IsStd="1" Ver="1">957</PName>
<PName PID="585" CID="643" Value="Omskaya oblast'" StdVal="Omskayaoblast" Lang="ru" Type="Full" IsLead="1" IsStd="1" Ver="1">959</PName>
<PName PID="586" CID="643" Value="Orenburgskaya oblast" StdVal="Orenburgskayaoblast" Lang="ru" Type="Full" IsLead="1" IsStd="1" Ver="1">962</PName>
<PName PID="587" CID="643" Value="Orlovskaya oblast'" StdVal="Orlovskayaoblast" Lang="ru" Type="Full" IsLead="1" IsStd="1" Ver="1">964</PName>
<PName PID="588" CID="643" Value="Penzenskaya oblast'" StdVal="Penzenskayaoblast" Lang="ru" Type="Full" IsLead="1" IsStd="1" Ver="1">967</PName>
<PName PID="589" CID="643" Value="Pskovskaya oblast'" StdVal="Pskovskayaoblast" Lang="ru" Type="Full" IsLead="1" IsStd="1" Ver="1">969</PName>
<PName PID="590" CID="643" Value="Rostovskaya oblast'" StdVal="Rostovskayaoblast" Lang="ru" Type="Full" IsLead="1" IsStd="1" Ver="1">971</PName>
<PName PID="591" CID="643" Value="Ryazanskaya oblast'" StdVal="Ryazanskayaoblast" Lang="ru" Type="Full" IsLead="1" IsStd="1" Ver="1">974</PName>
<PName PID="592" CID="643" Value="Sakhalinskaya oblast" StdVal="Sakhalinskayaoblast" Lang="ru" Type="Full" IsLead="1" IsStd="1" Ver="1">977</PName>
<PName PID="593" CID="643" Value="Samarskaya oblast'" StdVal="Samarskayaoblast" Lang="ru" Type="Full" IsLead="1" IsStd="1" Ver="1">979</PName>
<PName PID="594" CID="643" Value="Saratovskaya oblast'" StdVal="Saratovskayaoblast" Lang="ru" Type="Full" IsLead="1" IsStd="1" Ver="1">981</PName>
<PName PID="595" CID="643" Value="Smolenskaya oblast'" StdVal="Smolenskayaoblast" Lang="ru" Type="Full" IsLead="1" IsStd="1" Ver="1">983</PName>
<PName PID="596" CID="643" Value="Sverdlovskaya oblast" StdVal="Sverdlovskayaoblast" Lang="ru" Type="Full" IsLead="1" IsStd="1" Ver="1">985</PName>
<PName PID="597" CID="643" Value="Tambovskaya oblast'" StdVal="Tambovskayaoblast" Lang="ru" Type="Full" IsLead="1" IsStd="1" Ver="1">987</PName>
<PName PID="598" CID="643" Value="Tomskaya oblast'" StdVal="Tomskayaoblast" Lang="ru" Type="Full" IsLead="1" IsStd="1" Ver="1">989</PName>
<PName PID="599" CID="643" Value="Tul'skaya oblast'" StdVal="Tulskayaoblast" Lang="ru" Type="Full" IsLead="1" IsStd="1" Ver="1">991</PName>
<PName PID="600" CID="643" Value="Tverskaya oblast'" StdVal="Tverskayaoblast" Lang="ru" Type="Full" IsLead="1" IsStd="1" Ver="1">994</PName>
<PName PID="601" CID="643" Value="Tyumenskaya oblast'" StdVal="Tyumenskayaoblast" Lang="ru" Type="Full" IsLead="1" IsStd="1" Ver="1">996</PName>
<PName PID="602" CID="643" Value="Ul'yanovskaya oblast" StdVal="Ulyanovskayaoblast" Lang="ru" Type="Full" IsLead="1" IsStd="1" Ver="1">999</PName>
<PName PID="603" CID="643" Value="Vladimirskaya oblast" StdVal="Vladimirskayaoblast" Lang="ru" Type="Full" IsLead="1" IsStd="1" Ver="1">1001</PName>
<PName PID="604" CID="643" Value="Volgogradskaya oblas" StdVal="Volgogradskayaoblas" Lang="ru" Type="Full" IsLead="1" IsStd="1" Ver="1">1003</PName>
<PName PID="605" CID="643" Value="Vologodskaya oblast'" StdVal="Vologodskayaoblast" Lang="ru" Type="Full" IsLead="1" IsStd="1" Ver="1">1005</PName>
<PName PID="606" CID="643" Value="Voronezhskaya oblast" StdVal="Voronezhskayaoblast" Lang="ru" Type="Full" IsLead="1" IsStd="1" Ver="1">1008</PName>
<PName PID="607" CID="643" Value="Yaroslavskaya oblast" StdVal="Yaroslavskayaoblast" Lang="ru" Type="Full" IsLead="1" IsStd="1" Ver="1">1011</PName>
<PName PID="673" CID="705" Value="Capodistria" StdVal="Capodistria" Lang="it" Type="Full" IsLead="1" IsStd="1" Ver="1">1079</PName>
<PName PID="1044" CID="392" Value="Aiti" StdVal="Aiti" Lang="ja" Type="Full" IsLead="1" IsStd="1" Ver="1">1610</PName>
<PName PID="1045" CID="392" Value="Akita" StdVal="Akita" Lang="ja" Type="Full" IsLead="1" IsStd="1" Ver="1">1612</PName>
<PName PID="1046" CID="392" Value="Aomori" StdVal="Aomori" Lang="ja" Type="Full" IsLead="1" IsStd="1" Ver="1">1613</PName>
<PName PID="1047" CID="392" Value="Ehime" StdVal="Ehime" Lang="ja" Type="Full" IsLead="1" IsStd="1" Ver="1">1614</PName>
<PName PID="1048" CID="392" Value="Gihu" StdVal="Gihu" Lang="ja" Type="Full" IsLead="1" IsStd="1" Ver="1">1615</PName>
<PName PID="1049" CID="392" Value="Gunma" StdVal="Gunma" Lang="ja" Type="Full" IsLead="1" IsStd="1" Ver="1">1617</PName>
<PName PID="1050" CID="392" Value="Hirosima" StdVal="Hirosima" Lang="ja" Type="Full" IsLead="1" IsStd="1" Ver="1">1618</PName>
<PName PID="1051" CID="392" Value="Hokkaidô" StdVal="Hokkaidô" Lang="ja" Type="Full" IsLead="1" IsStd="1" Ver="1">1620</PName>
<PName PID="1052" CID="392" Value="Hukui" StdVal="Hukui" Lang="ja" Type="Full" IsLead="1" IsStd="1" Ver="1">1622</PName>
<PName PID="1053" CID="392" Value="Hukuoka" StdVal="Hukuoka" Lang="ja" Type="Full" IsLead="1" IsStd="1" Ver="1">1624</PName>
<PName PID="1054" CID="392" Value="Hukusima" StdVal="Hukusima" Lang="ja" Type="Full" IsLead="1" IsStd="1" Ver="1">1626</PName>
<PName PID="1055" CID="392" Value="Hyôgo" StdVal="Hyôgo" Lang="ja" Type="Full" IsLead="1" IsStd="1" Ver="1">1628</PName>
<PName PID="1056" CID="392" Value="Ibaraki" StdVal="Ibaraki" Lang="ja" Type="Full" IsLead="1" IsStd="1" Ver="1">1630</PName>
<PName PID="1057" CID="392" Value="Isikawa" StdVal="Isikawa" Lang="ja" Type="Full" IsLead="1" IsStd="1" Ver="1">1631</PName>
<PName PID="1058" CID="392" Value="Iwate" StdVal="Iwate" Lang="ja" Type="Full" IsLead="1" IsStd="1" Ver="1">1633</PName>
<PName PID="1059" CID="392" Value="Kagawa" StdVal="Kagawa" Lang="ja" Type="Full" IsLead="1" IsStd="1" Ver="1">1634</PName>
<PName PID="1060" CID="392" Value="Kagosima" StdVal="Kagosima" Lang="ja" Type="Full" IsLead="1" IsStd="1" Ver="1">1635</PName>
<PName PID="1061" CID="392" Value="Kanagawa" StdVal="Kanagawa" Lang="ja" Type="Full" IsLead="1" IsStd="1" Ver="1">1637</PName>
<PName PID="1062" CID="392" Value="Kôti" StdVal="Kôti" Lang="ja" Type="Full" IsLead="1" IsStd="1" Ver="1">1638</PName>
<PName PID="1063" CID="392" Value="Kumamoto" StdVal="Kumamoto" Lang="ja" Type="Full" IsLead="1" IsStd="1" Ver="1">1640</PName>
<PName PID="1064" CID="392" Value="Kyôto" StdVal="Kyôto" Lang="ja" Type="Full" IsLead="1" IsStd="1" Ver="1">1641</PName>
<PName PID="1065" CID="392" Value="Mie" StdVal="Mie" Lang="ja" Type="Full" IsLead="1" IsStd="1" Ver="1">1643</PName>
<PName PID="1066" CID="392" Value="Miyagi" StdVal="Miyagi" Lang="ja" Type="Full" IsLead="1" IsStd="1" Ver="1">1644</PName>
<PName PID="1067" CID="392" Value="Miyazaki" StdVal="Miyazaki" Lang="ja" Type="Full" IsLead="1" IsStd="1" Ver="1">1645</PName>
<PName PID="1068" CID="392" Value="Nagano" StdVal="Nagano" Lang="ja" Type="Full" IsLead="1" IsStd="1" Ver="1">1646</PName>
<PName PID="1069" CID="392" Value="Nagasaki" StdVal="Nagasaki" Lang="ja" Type="Full" IsLead="1" IsStd="1" Ver="1">1647</PName>
<PName PID="1070" CID="392" Value="Nara" StdVal="Nara" Lang="ja" Type="Full" IsLead="1" IsStd="1" Ver="1">1648</PName>
<PName PID="1071" CID="392" Value="Niigata" StdVal="Niigata" Lang="ja" Type="Full" IsLead="1" IsStd="1" Ver="1">1649</PName>
<PName PID="1072" CID="392" Value="Ôita" StdVal="Ôita" Lang="ja" Type="Full" IsLead="1" IsStd="1" Ver="1">1650</PName>
<PName PID="1073" CID="392" Value="Okayama" StdVal="Okayama" Lang="ja" Type="Full" IsLead="1" IsStd="1" Ver="1">1652</PName>
<PName PID="1074" CID="392" Value="Okinawa" StdVal="Okinawa" Lang="ja" Type="Full" IsLead="1" IsStd="1" Ver="1">1653</PName>
<PName PID="1075" CID="392" Value="Ôsaka" StdVal="Ôsaka" Lang="ja" Type="Full" IsLead="1" IsStd="1" Ver="1">1654</PName>
<PName PID="1076" CID="392" Value="Saga" StdVal="Saga" Lang="ja" Type="Full" IsLead="1" IsStd="1" Ver="1">1656</PName>
<PName PID="1077" CID="392" Value="Saitama" StdVal="Saitama" Lang="ja" Type="Full" IsLead="1" IsStd="1" Ver="1">1657</PName>
<PName PID="1078" CID="392" Value="Siga" StdVal="Siga" Lang="ja" Type="Full" IsLead="1" IsStd="1" Ver="1">1658</PName>
<PName PID="1079" CID="392" Value="Simane" StdVal="Simane" Lang="ja" Type="Full" IsLead="1" IsStd="1" Ver="1">1660</PName>
<PName PID="1080" CID="392" Value="Sizuoka" StdVal="Sizuoka" Lang="ja" Type="Full" IsLead="1" IsStd="1" Ver="1">1662</PName>
<PName PID="1081" CID="392" Value="Tiba" StdVal="Tiba" Lang="ja" Type="Full" IsLead="1" IsStd="1" Ver="1">1664</PName>
<PName PID="1082" CID="392" Value="Tokusima" StdVal="Tokusima" Lang="ja" Type="Full" IsLead="1" IsStd="1" Ver="1">1666</PName>
<PName PID="1083" CID="392" Value="Tôkyô" StdVal="Tôkyô" Lang="ja" Type="Full" IsLead="1" IsStd="1" Ver="1">1668</PName>
<PName PID="1084" CID="392" Value="Totigi" StdVal="Totigi" Lang="ja" Type="Full" IsLead="1" IsStd="1" Ver="1">1670</PName>
<PName PID="1085" CID="392" Value="Tottori" StdVal="Tottori" Lang="ja" Type="Full" IsLead="1" IsStd="1" Ver="1">1672</PName>
<PName PID="1086" CID="392" Value="Toyama" StdVal="Toyama" Lang="ja" Type="Full" IsLead="1" IsStd="1" Ver="1">1673</PName>
<PName PID="1087" CID="392" Value="Wakayama" StdVal="Wakayama" Lang="ja" Type="Full" IsLead="1" IsStd="1" Ver="1">1674</PName>
<PName PID="1088" CID="392" Value="Yamagata" StdVal="Yamagata" Lang="ja" Type="Full" IsLead="1" IsStd="1" Ver="1">1675</PName>
<PName PID="1089" CID="392" Value="Yamaguti" StdVal="Yamaguti" Lang="ja" Type="Full" IsLead="1" IsStd="1" Ver="1">1676</PName>
<PName PID="1090" CID="392" Value="Yamanasi" StdVal="Yamanasi" Lang="ja" Type="Full" IsLead="1" IsStd="1" Ver="1">1678</PName>
<PName PID="1134" CID="792" Value="Adana" StdVal="Adana" Lang="tr" Type="Full" IsLead="1" IsStd="1" Ver="1">1724</PName>
<PName PID="1135" CID="792" Value="Adıyaman" StdVal="Adıyaman" Lang="tr" Type="Full" IsLead="1" IsStd="1" Ver="1">1725</PName>
<PName PID="1136" CID="792" Value="Afyon" StdVal="Afyon" Lang="tr" Type="Full" IsLead="1" IsStd="1" Ver="1">1726</PName>
<PName PID="1137" CID="792" Value="Ağrı" StdVal="Ağrı" Lang="tr" Type="Full" IsLead="1" IsStd="1" Ver="1">1727</PName>
<PName PID="1138" CID="792" Value="Aksaray" StdVal="Aksaray" Lang="tr" Type="Full" IsLead="1" IsStd="1" Ver="1">1728</PName>
<PName PID="1139" CID="792" Value="Amasya" StdVal="Amasya" Lang="tr" Type="Full" IsLead="1" IsStd="1" Ver="1">1729</PName>
<PName PID="1140" CID="792" Value="Ankara" StdVal="Ankara" Lang="tr" Type="Full" IsLead="1" IsStd="1" Ver="1">1730</PName>
<PName PID="1141" CID="792" Value="Antalya" StdVal="Antalya" Lang="tr" Type="Full" IsLead="1" IsStd="1" Ver="1">1731</PName>
<PName PID="1142" CID="792" Value="Ardahan" StdVal="Ardahan" Lang="tr" Type="Full" IsLead="1" IsStd="1" Ver="1">1732</PName>
<PName PID="1143" CID="792" Value="Artvin" StdVal="Artvin" Lang="tr" Type="Full" IsLead="1" IsStd="1" Ver="1">1733</PName>
<PName PID="1144" CID="792" Value="Aydın" StdVal="Aydın" Lang="tr" Type="Full" IsLead="1" IsStd="1" Ver="1">1734</PName>
<PName PID="1145" CID="792" Value="Balıkesir" StdVal="Balıkesir" Lang="tr" Type="Full" IsLead="1" IsStd="1" Ver="1">1735</PName>
<PName PID="1146" CID="792" Value="Bartın" StdVal="Bartın" Lang="tr" Type="Full" IsLead="1" IsStd="1" Ver="1">1736</PName>
<PName PID="1147" CID="792" Value="Batman" StdVal="Batman" Lang="tr" Type="Full" IsLead="1" IsStd="1" Ver="1">1737</PName>
<PName PID="1148" CID="792" Value="Bayburt" StdVal="Bayburt" Lang="tr" Type="Full" IsLead="1" IsStd="1" Ver="1">1738</PName>
<PName PID="1149" CID="792" Value="Bilecik" StdVal="Bilecik" Lang="tr" Type="Full" IsLead="1" IsStd="1" Ver="1">1739</PName>
<PName PID="1150" CID="792" Value="Bingöl" StdVal="Bingöl" Lang="tr" Type="Full" IsLead="1" IsStd="1" Ver="1">1740</PName>
<PName PID="1151" CID="792" Value="Bitlis" StdVal="Bitlis" Lang="tr" Type="Full" IsLead="1" IsStd="1" Ver="1">1741</PName>
<PName PID="1152" CID="792" Value="Bolu" StdVal="Bolu" Lang="tr" Type="Full" IsLead="1" IsStd="1" Ver="1">1742</PName>
<PName PID="1153" CID="792" Value="Burdur" StdVal="Burdur" Lang="tr" Type="Full" IsLead="1" IsStd="1" Ver="1">1743</PName>
<PName PID="1154" CID="792" Value="Bursa" StdVal="Bursa" Lang="tr" Type="Full" IsLead="1" IsStd="1" Ver="1">1744</PName>
<PName PID="1155" CID="792" Value="Çanakkale" StdVal="Çanakkale" Lang="tr" Type="Full" IsLead="1" IsStd="1" Ver="1">1745</PName>
<PName PID="1156" CID="792" Value="Çankırı" StdVal="Çankırı" Lang="tr" Type="Full" IsLead="1" IsStd="1" Ver="1">1746</PName>
<PName PID="1157" CID="792" Value="Çorum" StdVal="Çorum" Lang="tr" Type="Full" IsLead="1" IsStd="1" Ver="1">1747</PName>
<PName PID="1158" CID="792" Value="Denizli" StdVal="Denizli" Lang="tr" Type="Full" IsLead="1" IsStd="1" Ver="1">1748</PName>
<PName PID="1159" CID="792" Value="Diyarbakır" StdVal="Diyarbakır" Lang="tr" Type="Full" IsLead="1" IsStd="1" Ver="1">1749</PName>
<PName PID="1160" CID="792" Value="Düzce" StdVal="Düzce" Lang="tr" Type="Full" IsLead="1" IsStd="1" Ver="1">1750</PName>
<PName PID="1161" CID="792" Value="Edirne" StdVal="Edirne" Lang="tr" Type="Full" IsLead="1" IsStd="1" Ver="1">1751</PName>
<PName PID="1162" CID="792" Value="Elazığ" StdVal="Elazığ" Lang="tr" Type="Full" IsLead="1" IsStd="1" Ver="1">1752</PName>
<PName PID="1163" CID="792" Value="Erzincan" StdVal="Erzincan" Lang="tr" Type="Full" IsLead="1" IsStd="1" Ver="1">1753</PName>
<PName PID="1164" CID="792" Value="Erzurum" StdVal="Erzurum" Lang="tr" Type="Full" IsLead="1" IsStd="1" Ver="1">1754</PName>
<PName PID="1165" CID="792" Value="Eskişehir" StdVal="Eskişehir" Lang="tr" Type="Full" IsLead="1" IsStd="1" Ver="1">1755</PName>
<PName PID="1166" CID="792" Value="Gaziantep" StdVal="Gaziantep" Lang="tr" Type="Full" IsLead="1" IsStd="1" Ver="1">1756</PName>
<PName PID="1167" CID="792" Value="Giresun" StdVal="Giresun" Lang="tr" Type="Full" IsLead="1" IsStd="1" Ver="1">1757</PName>
<PName PID="1168" CID="792" Value="Gümüşhane" StdVal="Gümüşhane" Lang="tr" Type="Full" IsLead="1" IsStd="1" Ver="1">1758</PName>
<PName PID="1169" CID="792" Value="Hakkâri" StdVal="Hakkâri" Lang="tr" Type="Full" IsLead="1" IsStd="1" Ver="1">1759</PName>
<PName PID="1170" CID="792" Value="Hatay" StdVal="Hatay" Lang="tr" Type="Full" IsLead="1" IsStd="1" Ver="1">1760</PName>
<PName PID="1171" CID="792" Value="İçel" StdVal="İçel" Lang="tr" Type="Full" IsLead="1" IsStd="1" Ver="1">1761</PName>
<PName PID="1172" CID="792" Value="Iğdır" StdVal="Iğdır" Lang="tr" Type="Full" IsLead="1" IsStd="1" Ver="1">1762</PName>
<PName PID="1173" CID="792" Value="Isparta" StdVal="Isparta" Lang="tr" Type="Full" IsLead="1" IsStd="1" Ver="1">1763</PName>
<PName PID="1174" CID="792" Value="İstanbul" StdVal="İstanbul" Lang="tr" Type="Full" IsLead="1" IsStd="1" Ver="1">1764</PName>
<PName PID="1175" CID="792" Value="İzmir" StdVal="İzmir" Lang="tr" Type="Full" IsLead="1" IsStd="1" Ver="1">1765</PName>
<PName PID="1176" CID="792" Value="Kahramanmaraş" StdVal="Kahramanmaraş" Lang="tr" Type="Full" IsLead="1" IsStd="1" Ver="1">1766</PName>
<PName PID="1177" CID="792" Value="Karabük" StdVal="Karabük" Lang="tr" Type="Full" IsLead="1" IsStd="1" Ver="1">1767</PName>
<PName PID="1178" CID="792" Value="Karaman" StdVal="Karaman" Lang="tr" Type="Full" IsLead="1" IsStd="1" Ver="1">1768</PName>
<PName PID="1179" CID="792" Value="Kars" StdVal="Kars" Lang="tr" Type="Full" IsLead="1" IsStd="1" Ver="1">1769</PName>
<PName PID="1180" CID="792" Value="Kastamonu" StdVal="Kastamonu" Lang="tr" Type="Full" IsLead="1" IsStd="1" Ver="1">1770</PName>
<PName PID="1181" CID="792" Value="Kayseri" StdVal="Kayseri" Lang="tr" Type="Full" IsLead="1" IsStd="1" Ver="1">1771</PName>
<PName PID="1182" CID="792" Value="Kilis" StdVal="Kilis" Lang="tr" Type="Full" IsLead="1" IsStd="1" Ver="1">1772</PName>
<PName PID="1183" CID="792" Value="Kırıkkale" StdVal="Kırıkkale" Lang="tr" Type="Full" IsLead="1" IsStd="1" Ver="1">1773</PName>
<PName PID="1184" CID="792" Value="Kırklareli" StdVal="Kırklareli" Lang="tr" Type="Full" IsLead="1" IsStd="1" Ver="1">1774</PName>
<PName PID="1185" CID="792" Value="Kırşehir" StdVal="Kırşehir" Lang="tr" Type="Full" IsLead="1" IsStd="1" Ver="1">1775</PName>
<PName PID="1186" CID="792" Value="Kocaeli" StdVal="Kocaeli" Lang="tr" Type="Full" IsLead="1" IsStd="1" Ver="1">1776</PName>
<PName PID="1187" CID="792" Value="Konya" StdVal="Konya" Lang="tr" Type="Full" IsLead="1" IsStd="1" Ver="1">1777</PName>
<PName PID="1188" CID="792" Value="Kütahya" StdVal="Kütahya" Lang="tr" Type="Full" IsLead="1" IsStd="1" Ver="1">1778</PName>
<PName PID="1189" CID="792" Value="Malatya" StdVal="Malatya" Lang="tr" Type="Full" IsLead="1" IsStd="1" Ver="1">1779</PName>
<PName PID="1190" CID="792" Value="Manisa" StdVal="Manisa" Lang="tr" Type="Full" IsLead="1" IsStd="1" Ver="1">1780</PName>
<PName PID="1191" CID="792" Value="Mardin" StdVal="Mardin" Lang="tr" Type="Full" IsLead="1" IsStd="1" Ver="1">1781</PName>
<PName PID="1192" CID="792" Value="Muğla" StdVal="Muğla" Lang="tr" Type="Full" IsLead="1" IsStd="1" Ver="1">1782</PName>
<PName PID="1193" CID="792" Value="Muş" StdVal="Muş" Lang="tr" Type="Full" IsLead="1" IsStd="1" Ver="1">1783</PName>
<PName PID="1194" CID="792" Value="Nevşehir" StdVal="Nevşehir" Lang="tr" Type="Full" IsLead="1" IsStd="1" Ver="1">1784</PName>
<PName PID="1195" CID="792" Value="Niğde" StdVal="Niğde" Lang="tr" Type="Full" IsLead="1" IsStd="1" Ver="1">1785</PName>
<PName PID="1196" CID="792" Value="Ordu" StdVal="Ordu" Lang="tr" Type="Full" IsLead="1" IsStd="1" Ver="1">1786</PName>
<PName PID="1197" CID="792" Value="Osmaniye" StdVal="Osmaniye" Lang="tr" Type="Full" IsLead="1" IsStd="1" Ver="1">1787</PName>
<PName PID="1198" CID="792" Value="Rize" StdVal="Rize" Lang="tr" Type="Full" IsLead="1" IsStd="1" Ver="1">1788</PName>
<PName PID="1199" CID="792" Value="Sakarya" StdVal="Sakarya" Lang="tr" Type="Full" IsLead="1" IsStd="1" Ver="1">1789</PName>
<PName PID="1200" CID="792" Value="Samsun" StdVal="Samsun" Lang="tr" Type="Full" IsLead="1" IsStd="1" Ver="1">1790</PName>
<PName PID="1201" CID="792" Value="Şanlıurfa" StdVal="Şanlıurfa" Lang="tr" Type="Full" IsLead="1" IsStd="1" Ver="1">1791</PName>
<PName PID="1202" CID="792" Value="Siirt" StdVal="Siirt" Lang="tr" Type="Full" IsLead="1" IsStd="1" Ver="1">1792</PName>
<PName PID="1203" CID="792" Value="Sinop" StdVal="Sinop" Lang="tr" Type="Full" IsLead="1" IsStd="1" Ver="1">1793</PName>
<PName PID="1204" CID="792" Value="Şırnak" StdVal="Şırnak" Lang="tr" Type="Full" IsLead="1" IsStd="1" Ver="1">1794</PName>
<PName PID="1205" CID="792" Value="Sivas" StdVal="Sivas" Lang="tr" Type="Full" IsLead="1" IsStd="1" Ver="1">1795</PName>
<PName PID="1206" CID="792" Value="Tekirdağ" StdVal="Tekirdağ" Lang="tr" Type="Full" IsLead="1" IsStd="1" Ver="1">1796</PName>
<PName PID="1207" CID="792" Value="Tokat" StdVal="Tokat" Lang="tr" Type="Full" IsLead="1" IsStd="1" Ver="1">1797</PName>
<PName PID="1208" CID="792" Value="Trabzon" StdVal="Trabzon" Lang="tr" Type="Full" IsLead="1" IsStd="1" Ver="1">1798</PName>
<PName PID="1209" CID="792" Value="Tunceli" StdVal="Tunceli" Lang="tr" Type="Full" IsLead="1" IsStd="1" Ver="1">1799</PName>
<PName PID="1210" CID="792" Value="Uşak" StdVal="Uşak" Lang="tr" Type="Full" IsLead="1" IsStd="1" Ver="1">1800</PName>
<PName PID="1211" CID="792" Value="Van" StdVal="Van" Lang="tr" Type="Full" IsLead="1" IsStd="1" Ver="1">1801</PName>
<PName PID="1212" CID="792" Value="Yalova" StdVal="Yalova" Lang="tr" Type="Full" IsLead="1" IsStd="1" Ver="1">1802</PName>
<PName PID="1213" CID="792" Value="Yozgat" StdVal="Yozgat" Lang="tr" Type="Full" IsLead="1" IsStd="1" Ver="1">1803</PName>
<PName PID="1214" CID="792" Value="Zonguldak" StdVal="Zonguldak" Lang="tr" Type="Full" IsLead="1" IsStd="1" Ver="1">1804</PName>
</PNameSets>
