<?xml version="1.0" encoding="UTF-8"?>
<CNameSets xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<CName Index="1" CID="004" Value="Afghānistān" StdVal="Afghānistān" Lang="ps" IsLead="1" IsStd="1" Ver="1">3</CName>
<CName Index="2" CID="008" Value="Shqipëria" StdVal="Shqipëria" Lang="sq" IsLead="0" IsStd="1" Ver="1">7</CName>
<CName Index="2" CID="008" Value="Shqipëri" StdVal="Shqipëri" Lang="sq" IsLead="1" IsStd="1" Ver="1">8</CName>
<CName Index="4" CID="012" Value="Al Jazā'ir" StdVal="AlJazāir" Lang="ar" IsLead="1" IsStd="1" Ver="1">13</CName>
<CName Index="9" CID="031" Value="Azәrbaycan" StdVal="Azәrbaycan" Lang="az" IsLead="1" IsStd="1" Ver="1">30</CName>
<CName Index="14" CID="048" Value="Al Baḩrayn" StdVal="AlBaḩrayn" Lang="ar" IsLead="1" IsStd="1" Ver="1">46</CName>
<CName Index="15" CID="050" Value="Bāṅlādesh" StdVal="Bāṅlādesh" Lang="bn" IsLead="1" IsStd="1" Ver="1">50</CName>
<CName Index="16" CID="051" Value="Hayastan" StdVal="Hayastan" Lang="hy" IsLead="1" IsStd="1" Ver="1">56</CName>
<CName Index="20" CID="064" Value="Druk-Yul" StdVal="DrukYul" Lang="dz" IsLead="1" IsStd="1" Ver="1">66</CName>
<CName Index="22" CID="070" Value="Bosna i Hercegovina" StdVal="BosnaiHercegovina" Lang="bs" IsLead="1" IsStd="1" Ver="1">73</CName>
<CName Index="24" CID="074" Value="Bouvetøya" StdVal="Bouvetøya" Lang="nb" IsLead="1" IsStd="1" Ver="1">81</CName>
<CName Index="31" CID="100" Value="Balgaria" StdVal="Balgaria" Lang="bg" IsLead="1" IsStd="1" Ver="1">106</CName>
<CName Index="32" CID="104" Value="Myanma" StdVal="Myanma" Lang="my" IsLead="1" IsStd="1" Ver="1">111</CName>
<CName Index="34" CID="112" Value="Bielarus'" StdVal="Bielarus" Lang="be" IsLead="1" IsStd="1" Ver="1">113</CName>
<CName Index="35" CID="116" Value="Kâmpŭchéa" StdVal="Kâmpŭchéa" Lang="km" IsLead="1" IsStd="1" Ver="1">121</CName>
<CName Index="41" CID="144" Value="Shrī Laṁkā" StdVal="ShrīLaṁkā" Lang="si" IsLead="1" IsStd="1" Ver="1">142</CName>
<CName Index="42" CID="148" Value="Tshād" StdVal="Tshād" Lang="ar" IsLead="1" IsStd="1" Ver="1">143</CName>
<CName Index="44" CID="156" Value="Zhongguo" StdVal="Zhongguo" Lang="zh" IsLead="1" IsStd="1" Ver="1">152</CName>
<CName Index="49" CID="174" Value="Al Qamar" StdVal="AlQamar" Lang="ar" IsLead="1" IsStd="1" Ver="1">169</CName>
<CName Index="55" CID="191" Value="Hrvatska" StdVal="Hrvatska" Lang="hr" IsLead="1" IsStd="1" Ver="1">191</CName>
<CName Index="57" CID="196" Value="Kýpros" StdVal="Kýpros" Lang="el" IsLead="1" IsStd="1" Ver="1">195</CName>
<CName Index="66" CID="231" Value="Ītyop'iya" StdVal="Ītyopiya" Lang="am" IsLead="1" IsStd="1" Ver="1">226</CName>
<CName Index="67" CID="232" Value="Irītrīyā" StdVal="Irītrīyā" Lang="ar" IsLead="1" IsStd="1" Ver="1">231</CName>
<CName Index="68" CID="233" Value="Eesti" StdVal="Eesti" Lang="et" IsLead="1" IsStd="1" Ver="1">236</CName>
<CName Index="79" CID="262" Value="Jībūtī" StdVal="Jībūtī" Lang="ar" IsLead="1" IsStd="1" Ver="1">282</CName>
<CName Index="81" CID="268" Value="Sak’art’velo" StdVal="Sak’art’velo" Lang="ka" IsLead="1" IsStd="1" Ver="1">292</CName>
<CName Index="83" CID="275" Value="Al arḍ al filasṭīniya al-muḥtalla" StdVal="Alarḍalfilasṭīniyaalmuḥtalla" Lang="ar" IsLead="1" IsStd="1" Ver="1">296</CName>
<CName Index="88" CID="300" Value="Elláda" StdVal="Elláda" Lang="el" IsLead="0" IsStd="1" Ver="1">306</CName>
<CName Index="88" CID="300" Value="Ellás" StdVal="Ellás" Lang="el" IsLead="1" IsStd="1" Ver="1">307</CName>
<CName Index="102" CID="352" Value="Ísland" StdVal="Ísland" Lang="is" IsLead="1" IsStd="1" Ver="1">351</CName>
<CName Index="105" CID="364" Value="Jomhūrī-ye Eslāmī-ye Īrān" StdVal="JomhūrīyeEslāmīyeĪrān" Lang="fa" IsLead="1" IsStd="1" Ver="1">360</CName>
<CName Index="106" CID="368" Value="Al ‘Irāq" StdVal="AlIrāq" Lang="ar" IsLead="1" IsStd="1" Ver="1">361</CName>
<CName Index="108" CID="376" Value="Isrā'īl" StdVal="Isrāīl" Lang="ar" IsLead="1" IsStd="1" Ver="1">369</CName>
<CName Index="113" CID="398" Value="Qazaqstan" StdVal="Qazaqstan" Lang="kk" IsLead="1" IsStd="1" Ver="1">391</CName>
<CName Index="114" CID="400" Value="Al Urdun" StdVal="AlUrdun" Lang="ar" IsLead="1" IsStd="1" Ver="1">392</CName>
<CName Index="118" CID="414" Value="Al Kuwayt" StdVal="AlKuwayt" Lang="ar" IsLead="1" IsStd="1" Ver="1">410</CName>
<CName Index="120" CID="418" Value="Sathalanalat Paxathipatai Paxaxôn Lao" StdVal="SathalanalatPaxathipataiPaxaxônLao" Lang="lo" IsLead="1" IsStd="1" Ver="1">419</CName>
<CName Index="121" CID="422" Value="Lubnān" StdVal="Lubnān" Lang="ar" IsLead="1" IsStd="1" Ver="1">420</CName>
<CName Index="123" CID="428" Value="Latvija" StdVal="Latvija" Lang="lv" IsLead="1" IsStd="1" Ver="1">430</CName>
<CName Index="125" CID="434" Value="Al Jamāhīrīyah al Άrabīyah al Lībīyah" StdVal="AlJamāhīrīyahalΆrabīyahalLībīyah" Lang="ar" IsLead="1" IsStd="1" Ver="1">433</CName>
<CName Index="127" CID="440" Value="Lietuva" StdVal="Lietuva" Lang="lt" IsLead="1" IsStd="1" Ver="1">443</CName>
<CName Index="133" CID="462" Value="Dhivehi Raajje" StdVal="DhivehiRaajje" Lang="dv" IsLead="1" IsStd="1" Ver="1">460</CName>
<CName Index="137" CID="478" Value="Mūrītāniyā" StdVal="Mūrītāniyā" Lang="ar" IsLead="1" IsStd="1" Ver="1">469</CName>
<CName Index="141" CID="496" Value="Mongol" StdVal="Mongol" Lang="mn" IsLead="1" IsStd="1" Ver="1">486</CName>
<CName Index="142" CID="498" Value="Republica Moldova" StdVal="RepublicaMoldova" Lang="mo" IsLead="1" IsStd="1" Ver="1">491</CName>
<CName Index="145" CID="504" Value="Al Maghrib" StdVal="AlMaghrib" Lang="ar" IsLead="1" IsStd="1" Ver="1">495</CName>
<CName Index="146" CID="508" Value="Moçambique" StdVal="Moçambique" Lang="pt" IsLead="1" IsStd="1" Ver="1">502</CName>
<CName Index="147" CID="512" Value="‘Umān" StdVal="Umān" Lang="ar" IsLead="1" IsStd="1" Ver="1">503</CName>
<CName Index="150" CID="524" Value="Nepāl" StdVal="Nepāl" Lang="ne" IsLead="1" IsStd="1" Ver="1">511</CName>
<CName Index="151" CID="528" Value="Nederland" StdVal="Nederland" Lang="nl" IsLead="1" IsStd="1" Ver="1">517</CName>
<CName Index="152" CID="530" Value="Nederlandse Antillen" StdVal="NederlandseAntillen" Lang="nl" IsLead="1" IsStd="1" Ver="1">522</CName>
<CName Index="162" CID="578" Value="Norge" StdVal="Norge" Lang="nb" IsLead="1" IsStd="1" Ver="1">549</CName>
<CName Index="177" CID="624" Value="Guiné-Bissau" StdVal="GuinéBissau" Lang="pt" IsLead="1" IsStd="1" Ver="1">597</CName>
<CName Index="180" CID="634" Value="Qaţar" StdVal="Qaţar" Lang="ar" IsLead="1" IsStd="1" Ver="1">604</CName>
<CName Index="194" CID="678" Value="São Tomé e Príncipe" StdVal="SãoToméePríncipe" Lang="pt" IsLead="1" IsStd="1" Ver="1">677</CName>
<CName Index="195" CID="682" Value="As Su‘ūdīyah" StdVal="AsSuūdīyah" Lang="ar" IsLead="1" IsStd="1" Ver="1">678</CName>
<CName Index="197" CID="688" Value="Srbija" StdVal="Srbija" Lang="sr" IsLead="1" IsStd="1" Ver="1">690</CName>
<CName Index="201" CID="703" Value="Slovensko" StdVal="Slovensko" Lang="sk" IsLead="1" IsStd="1" Ver="1">703</CName>
<CName Index="202" CID="704" Value="Việt Nam" StdVal="ViệtNam" Lang="vi" IsLead="1" IsStd="1" Ver="1">706</CName>
<CName Index="203" CID="705" Value="Slovenija" StdVal="Slovenija" Lang="sl" IsLead="1" IsStd="1" Ver="1">711</CName>
<CName Index="204" CID="706" Value="Aş Şūmāl" StdVal="AşŞūmāl" Lang="ar" IsLead="1" IsStd="1" Ver="1">712</CName>
<CName Index="205" CID="710" Value="Suid-Afrika" StdVal="SuidAfrika" Lang="af" IsLead="1" IsStd="1" Ver="1">715</CName>
<CName Index="208" CID="732" Value="Aş Şaḩra’ al Gharbīyah" StdVal="AşŞaḩra’alGharbīyah" Lang="ar" IsLead="1" IsStd="1" Ver="1">728</CName>
<CName Index="209" CID="736" Value="As Sūdān" StdVal="AsSūdān" Lang="ar" IsLead="1" IsStd="1" Ver="1">733</CName>
<CName Index="211" CID="744" Value="Svalbard og Jan Mayen" StdVal="SvalbardogJanMayen" Lang="nb" IsLead="1" IsStd="1" Ver="1">744</CName>
<CName Index="215" CID="760" Value="Al Jumhūrīyah al Άrabīyah as Sūrīyah" StdVal="AlJumhūrīyahalΆrabīyahasSūrīyah" Lang="ar" IsLead="1" IsStd="1" Ver="1">757</CName>
<CName Index="216" CID="762" Value="Tojikiston" StdVal="Tojikiston" Lang="tg" IsLead="1" IsStd="1" Ver="1">766</CName>
<CName Index="222" CID="784" Value="Al Imārāt" StdVal="AlImārāt" Lang="ar" IsLead="1" IsStd="1" Ver="1">780</CName>
<CName Index="223" CID="788" Value="Tūnus" StdVal="Tūnus" Lang="ar" IsLead="1" IsStd="1" Ver="1">785</CName>
<CName Index="225" CID="795" Value="Türkmenistan" StdVal="Türkmenistan" Lang="tk" IsLead="1" IsStd="1" Ver="1">797</CName>
<CName Index="229" CID="804" Value="Ukraina" StdVal="Ukraina" Lang="uk" IsLead="1" IsStd="1" Ver="1">807</CName>
<CName Index="230" CID="807" Value="Poranešna Jugoslovenska Republika Makedonija" StdVal="PoranešnaJugoslovenskaRepublikaMakedonija" Lang="mk" IsLead="1" IsStd="1" Ver="1">813</CName>
<CName Index="231" CID="818" Value="Mişr" StdVal="Mişr" Lang="ar" IsLead="1" IsStd="1" Ver="1">814</CName>
<CName Index="241" CID="860" Value="O‘zbekiston" StdVal="Ozbekiston" Lang="uz" IsLead="1" IsStd="1" Ver="1">861</CName>
<CName Index="245" CID="887" Value="Al Yaman" StdVal="AlYaman" Lang="ar" IsLead="1" IsStd="1" Ver="1">870</CName>
</CNameSets>
